### ISSUE TITLE
Support asynchronous disk writes

### ISSUE THREAD

**Issue by jpsim** [realm/realm-swift#1205]
Would be great for cases where writes can/should be coalesced (streaming data) and where eventual consistency is acceptable. See [this mailing list post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/realm-cocoa/nHP16ZyTeCk/mX2OhuzjeCcJ).

**Comment by tgoyne** [comment]
This was shipped in 10.26.0
