### ISSUE TITLE
Geospatial filtering/querying

### ISSUE THREAD

**Issue by mhergon** [realm/realm-swift#2569]
Hi,

Is there any way to do a geospatial filtering by distance?
I'm trying with geohash functions, but If there is a native alternative would be great!

Thanks!

**Comment by mrackwitz** [comment]
Realm doesn't bring such functionality built-in yet. But meanwhile there is a featured component [ABFRealmMapView](https://realm.io/news/building-an-ios-clustered-map-view-in-objective-c/), which brings not only [ABFLocationFetchRequest](https://github.com/bigfish24/ABFRealmMapView/blob/master/ABFRealmMapView/ABFLocationFetchRequest.h), but also integration with MapKit, if you're interested in that. The implementation of the mentioned class will be worthwhile to checkout.

**Comment by mhergon** [comment]
@mrackwitz @jpsim 

Is there a prevision to add this functionality in the near future?
A mobile database without this functionality loses much value.

Thank you!

**Comment by jpsim** [comment]
We absolutely want to add geo querying and sorting abilities to Realm in the future (see #2199 for some early work in progress too).

**Comment by mhergon** [comment]
@jpsim Ok, thanks!

**Comment by Zhuinden** [comment]
It is waiting for core in https://github.com/realm/realm-core/issues/1184

**Comment by mhergon** [comment]
Meanwhile https://github.com/mhergon/RealmGeoQueries

**Comment by austinzheng** [comment]
Just wanted to add another data point. http://stackoverflow.com/questions/41312433/how-to-do-geo-distance-sorting-on-realm-data-in-ios-objective-c/41351009

**Comment by ianpward** [comment]
Product for Realm & Device Sync here. I am interested in building this feature - I'd love to pick your bring on your use case if you're keen. If you could drop me a line at [ian.ward@mongodb.com](mailto:ian.ward@mongodb.com) we can set up a time to chat.

**Comment by dianaafanador3** [comment]
There is a new feature in the works which could help you with this https://github.com/realm/realm-swift/pull/8390
