### ISSUE TITLE
Ensure RLMSupport.swift's SequenceType additions iterate over an RLMResults snapshot

### ISSUE THREAD

**Issue by jpsim** [realm/realm-swift#3254]
A user reported that using Realm Objective-C from Swift doesn't iterate over a frozen TableView when SequenceType-enumerating an RLMResults:

``` swift
let realm = RLMRealm.defaultRealm()
let allItems = uncheckedItemsNoUpdate()

try! realm.transactionWithBlock({
  for itemObj in allItems {
    if let item = itemObj as? GroceryListItem {
      item.deleted = true
      item.syncStatus = SyncStatusNeedsUpdate
    }
  }
})
```

We should investigate if this is truly what's happening here, and if so mark this as a bug and fix this.

I was under the impression that `NSFastGenerator` on a collection with a custom enumerator would use the custom enumerator (where the `TableView` copy is done), but that wouldn't appear to be the case based on this report.

**Comment by reallyseth** [comment]
Just to jump in, I was the user JP is referring to. Let me know if I can help or provide more information about my particular situation. Thanks!

**Comment by dianaafanador3** [comment]
Closing this as it's already supported by `RLMSupport.swift` https://github.com/realm/realm-swift/blob/master/Realm/Swift/RLMSupport.swift, which extends `RLMResults` and makes it conform to `Sequence` which allows iteration over a RLMResults.
This test passes. 

``` swift
class TestObjectRLM: RLMObject {
    @objc dynamic var stringCol = ""
    @objc dynamic var boolCol = false
}

func testRLMResultsIterationFromSwift() throws {
        let realm = RLMRealm.default()
        realm.beginWriteTransaction()
        realm.createObject("TestObjectRLM", withValue: ["string A"])
        realm.createObject("TestObjectRLM", withValue: ["string B"])
        try realm.commitWriteTransaction()

        let allItems = realm.objects("TestObjectRLM", with: NSPredicate(format: "TRUEPREDICATE"))
        XCTAssertEqual(allItems.count, 2)

        try realm.transaction {
            for itemObj in allItems {
                if let item = itemObj as? TestObjectRLM {
                    item.boolCol = true
                    XCTAssertEqual(item.boolCol, true)
                }
            }
        }
}
```
