### ISSUE TITLE
Disable update notifications for specific properties or relationships

### ISSUE THREAD

**Issue by CraigSiemens** [realm/realm-swift#3704]
## Goals

I'd like to have a way to stop changes to certain properties or relationships from causing an object to be marked as updated in a notification.
## Expected Results

I have a `User` model with two properties, `name: String` and `retrievedAt: NSDate`. The UI is setup to only show the `name`. When a network request is done to get the users, `retrievedAt` will be updated and cause the UI to update even though nothing in the UI needs to change.
## Possible Solutions

Add a method to `Object` that can be overridden to provide properties that shouldn't cause an updated notification. This is the least flexible option since it would be set at the class level.

Add a property to `addNotificationBlock` that takes some kind of settings object that you can set properties that should be ignored.

Add a property to `RealmCollectionChange` or `Object` to find out what properties were changed to cause the update and allow the user to ignore them as needed.
## Current Workarounds

Create a new object `UserHousekeeping` that contains the `retrievedAt: NSDate` and a relationship to the `User`. `User` then needs to use a `LinkingObjects` to have a reference to the `UserHousekeeping` without having notifications be created for changes to the related object.

**Comment by tgoyne** [comment]
The initial design proposal for change notifications had something like `addNotificationBlock:watchingKeyPaths:` which would make it only report modifications for the specified keypaths. This turned out to be nontrivial to implement (currently the information about which property changed is discarded long before any of the per-notification-block logic), but I think it's still high on the list of things we'd like to add to change notifications.

**Comment by kunalsood** [comment]
+1

> I think it's still high on the list of things we'd like to add to change notifications.

Excellent!

> Add a method to Object that can be overridden to provide properties that shouldn't cause an updated notification. This is the least flexible option since it would be set at the class level.

Just my 2 cents: I would rather not have this feature at all, than have it implemented in this inflexible manner. I already have use cases where I need notifications for specific related object changes in one view controller, and not in another view controller.

Finally, I propose  that instead of telling it what keypaths to watch, we tell it what keypaths to ignore, so a method like:`addNotificationBlock:ignoringKeyPaths:`.

Hopefully this feedback is useful.

**Comment by aimobier** [comment]
need +1

**Comment by JAManfredi** [comment]
+1

**Comment by tomipu** [comment]
Any news on this one?

**Comment by jpsim** [comment]
We'll post any developments regarding this issue, in this issue.

**Comment by SureshSc** [comment]
+1

**Comment by marcocattai** [comment]
+1

**Comment by kevin-ponce** [comment]
+1

**Comment by tomaskraina** [comment]
+1

**Comment by samingle** [comment]
+1

**Comment by anysome** [comment]
+1111111111111

**Comment by GeorgeMagharious** [comment]
+1

**Comment by RetVal** [comment]
+1

**Comment by RetVal** [comment]
+1

**Comment by tomdaniel0x01** [comment]
+1

**Comment by dbmrq** [comment]
+1?

**Comment by amoshsueh** [comment]
I really need this!

**Comment by grangej** [comment]
Is there some kind of roadmap for what features will be worked on when? It seems like this has been open for 2 years? I too need this desperately !

**Comment by Bogsey** [comment]
+1

**Comment by dbmrq** [comment]
https://twitter.com/iamdevloper/status/1138792943794343936?s=21

**Comment by peterpaulis** [comment]
+1

**Comment by lukluca** [comment]
+1

**Comment by DominicFrei** [comment]
Good news: https://github.com/realm/realm-cocoa/pull/7249 (currently in review) will enable this.

**Comment by tgoyne** [comment]
Keypath filter was shipping in 10.12.0.

**Comment by Ataman11** [comment]
Hi @tgoyne, I see that key path filtering is out but could I do the opposite now - ask to not observe a particular key path instead?

**Comment by peterpaulis** [comment]
for anybody on this, to exclude a property you can do

```
            let schema = FItem().objectSchema
            var keyPaths = schema.properties.map { $0.name }
            keyPaths.removeAll(where: { $0 == "userActivated" })
            
            let t = Realm.defaultRealm().objects(FItem.self).observe(keyPaths: keyPaths, on: .main) { ... }
```

**Comment by lukaskollmer** [comment]
@peterpaulis keep in mind that this doesn't include _all_ properties (e.g., `LinkingObjects` are by default not included in the list of properties obtained through the `objectSchema`). Though I don't think a `LinkingObjects` property can cause a change notification to begin with...
