### ISSUE TITLE
Write documentation for relevant protocol methods

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-swift#3813]
Protocol members like `count`, `isEmpty`, etc that would reasonably be of interest to a user should be documented explicitly. This is so they show up directly in our Jazzy docs.

**Comment by austinzheng** [comment]
Context:

> I think we have to look at it from the users perspective. When I go to the doc with the intention to find out how I get the length of the List, I don’t want to have to explore a labyrinth of protocols, I just want to know what to call. (Alexander Stigsen)

There are a couple of members (like `count`) that are defined in a superclass marked as `:nodoc:`, which means that Jazzy won't generate documentation for them. I will probably end up moving those methods into the public API subclass so that we can generate documentation for them. (@jpsim)

**Comment by jpsim** [comment]
Relevant jazzy issue: #190
