### ISSUE TITLE
Request: Support NSIndexSet in RLMResults

### ISSUE THREAD

**Issue by dhiraj** [realm/realm-swift#3861]
## Goals

One of the coolest ways to dice up an NSArray into sections for usage in UITableview is to have an accompanying array of NSIndexSet objects that list the indices of the items in the single items array.

It would be _awesome_ if RLMResults could support this.
## Expected Results

 RLMResults supports `objectAtIndex:(NSUInteger)index` but not `objectsAtIndexes:(NSIndexSet *)indexSet` which means I have to pull out all objects into an NSArray before I can use it.

**Comment by TimOliver** [comment]
Hi @dhiraj! 

Cool! Thanks for that! That's a great idea! I've added the appropriate labels to this issue so the other engineers can review this request and see what they think.

To anyone else reading this: if you would like to see this feature implemented, please add a :+1: reaction to this issue.

Thanks!

**Comment by bmunkholm** [comment]
Closing as we don't intend to do this.
