### ISSUE TITLE
List<Object>.addNotificationBlock is behaving strangely

### ISSUE THREAD

**Issue by anlaital** [realm/realm-swift#3996]
## Goals

Observe changes in a `List<Object>`.
## Expected Results

`.Initial` is received first in `addNotificationBlock` closure.
## Actual Results

`.Update` is received first, where both `deletions` and `insertions` have index `0`. 

Suppose an `Object` subclass that contains `let children = List<SomeObject>`.  Prior to this change notification, calling `object.valueForKeyPath("children")` results correctly in `List<SomeObject>`. After this update notification is received, behavior is changed so that `RLMArray` is returned instead.

The documentation states the following: `Notifications can't be delivered as long as the run loop is blocked by other activity. When notifications can't be delivered instantly, multiple notifications may be coalesced into a single notification. This can include the notification with the initial list.`

However, no insertions or deletions should've been made to the `List` in question.
## Steps to Reproduce

N/A
## Code Sample

N/A
## Version of Realm and Tooling

Realm version: 1.0.2

Xcode version: 7.3.1

iOS/OSX version: 9.x

Dependency manager + version: CocoaPods 1.0.1

**Comment by jpsim** [comment]
To be clear, there are two issues here?

One is that, under certain circumstances that you've yet to pin down, `List.addNotificationBlock` triggers an invalid `.Update` notification instead of an `.Initial` notification?

The other is that `object.valueForKeyPath("children")` correctly returns a `List` if invoked before the first notification is received, then incorrectly returns an `RLMArray` afterwards?

**Comment by anlaital** [comment]
That's correct. I don't know if the former causes the latter or if both have their own (or shared) root causes. :)

**Comment by anlaital** [comment]
Also, is the documentation for `addNotificationBlock` in v1.0.2 incorrect when it states that `This can include the notification with the initial list.` if this scenario should not be happening anymore?

**Comment by jpsim** [comment]
No, that documentation is still accurate, the `.Initial` notification should always be delivered.
