### ISSUE TITLE
Fix installation examples for Swift 3.0.1

### ISSUE THREAD

**Issue by jpsim** [realm/realm-swift#4266]
Swift 3.0.1 installation examples were symlinked to the 3.0 ones in #4265, which means they're incorrect when using prebuilt binaries. This causes the `Cocoa Installation Examples` Jenkins job to fail ([example](https://ci.realm.io/job/Cocoa%20Installation%20Examples/448/)).

![image](https://cloud.githubusercontent.com/assets/474794/19783755/fb07f216-9c47-11e6-965e-d0428fac261c.png)

**Comment by Ravi2712** [comment]
@jpsim I'm not able to read examples.. Read Permission Denied..

**Comment by jpsim** [comment]
> I'm not able to read examples.. Read Permission Denied..

The link points to our internal CI system, only Realm employees have access.
