### ISSUE TITLE
'Unsupported operator', reason: 'Multi-level object equality link queries are not supported.'

### ISSUE THREAD

**Issue by asjesset** [realm/realm-swift#4282]
Realm 2.0.3

I am doing a query like (Person is a RLMObject class, redThread is a RLMObject instance):
```
[Person objectsWhere:"ANY clothes.buttons.thread == %@", redThread];
```

Sometimes (!?) it blows up with:
2016-11-01 14:16:52.610 CRM-CT-Pro[88780:1625835] *** Terminating app due to uncaught exception 'Unsupported operator', reason: 'Multi-level object equality link queries are not supported.'

Here's the stacktrace i could get:
```
	1   libobjc.A.dylib                     0x00000001082f121e objc_exception_throw + 48
	2   Realm                               0x0000000106e63f09 _ZL15RLMPreconditionbP8NSStringS0_z + 320
	3   Realm                               0x0000000106eac95e _ZN12_GLOBAL__N_112QueryBuilder14add_constraintINS_15ColumnReferenceEU8__strongP11objc_objectEEv15RLMPropertyType23NSPredicateOperatorTypemT_T0_ + 410
	4   Realm                               0x0000000106e6792e _ZN12_GLOBAL__N_112QueryBuilder22apply_value_expressionEP15RLMObjectSchemaP8NSStringP11objc_objectP21NSComparisonPredicate + 2646
	5   Realm                               0x0000000106e64c40 _ZN12_GLOBAL__N_112QueryBuilder15apply_predicateEP11NSPredicateP15RLMObjectSchema + 2782
	6   Realm                               0x0000000106e64857 _ZN12_GLOBAL__N_112QueryBuilder15apply_predicateEP11NSPredicateP15RLMObjectSchema + 1781
	7   Realm                               0x0000000106e63fd2 _Z19RLMPredicateToQueryP11NSPredicateP15RLMObjectSchemaP9RLMSchemaRN5realm5GroupE + 154
	8   Realm                               0x0000000106e5b56d RLMGetObjects + 221
	9   Realm                               0x0000000106e51669 +[RLMObject objectsWithPredicate:] + 101
```

Is this legal? Why is it only sometimes working? If it's illegal what are my options?

I did not observe this in 2.0.2. Theorizing a regression or updated policy.

**Comment by jpsim** [comment]
I don't have much time to look into this now, but I think your query can be expressed in other ways that may work:

```
[Person objectsWhere:"clothes.buttons.thread == %@", redThread];
```

or

```
[Person objectsWhere:"SUBQUERY(clothes, $garment, ANY $garment.buttons.thread == %@).@count > 0", redThread];
```

or

```
[Person objectsWhere:"SUBQUERY(clothes, $garment, $garment.buttons.thread == %@).@count > 0", redThread];
```

Although I'm very surprised you're saying your query used to work on 2.0.2 but not on 2.0.3.

Does it consistently fail with that exception, or only occasionally?

**Comment by bdash** [comment]
I think [we don't allow for multi-level object equality link queries that compare against null](https://github.com/realm/realm-cocoa/blob/17769afd241dc2a094873c526fd2be91b298b8d3/Realm/RLMQueryUtil.mm#L677-L680). It's not immediately obvious to me if this is simply an oversight, or if we're missing support from the query engine. I suspect it's the former.

**Comment by bdash** [comment]
[It's the latter](https://github.com/realm/realm-core/blob/e6ac817a4fbb40276f483670ba268f924ccfbe25/src/realm/query_expression.hpp#L2225-L2231). It's not 100% clear what semantics we want for a comparison against null when one of the intermediate links is itself null.
