### ISSUE TITLE
Explore convenience API designs for upcoming thread-safe references feature

### ISSUE THREAD

**Issue by jpsim** [realm/realm-swift#4477]
In an effort to avoid holding back thread-safe references any longer (#4114), I'd like to consider convenience APIs as a separate matter, to be done after the main API is merged. Though possibly before it ships.

To start off, here's a sample use case with the current full/flexible ("inconvenient") API:

```swift
let ref = ThreadSafeReference(to: obj)
DispatchQueue(label: "io.realm.realm.background").async {
    let realm = try! Realm()
    guard let obj = realm.resolve(ref) else { return }
    try! realm.write {
        // do something with obj
    }
}
```

Some of the advantages of this API, from a usage and cognitive load standpoint, are:

1. **Reuse familiar GCD APIs.** These were recently given a facelift in Swift 3 and are quite concise.
2. **Flexibility of your own concurrency APIs:** You want to use GCD with a specific queue? Easy. You want to use your own GCD convenience methods, NSOperations, Promises, 3rd party concurrency frameworks/wrappers? Easy.
3. **Minimal Realm API surface area duplication:** This adds 1 new type, with one initializer and a single `resolve` method. You can reuse the same APIs you already use today: constructors, writing, canceling, error handling, etc.

The biggest disadvantage is that it requires that some potentially very common boilerplate be written.

For example, you'll almost always want the Realm and the resolved object in the async block. You'll also often want to start a write transaction. You'll also often want to reuse the same dispatch queue.

The best convenience API that comes to mind is the following:

```swift
extension DispatchQueue {
    public static let realmBackgroundQueue = DispatchQueue(label: "io.realm.realm.background")
}
extension ThreadSafeReference {
    func async(write: Bool = false, queue: DispatchQueue = .realmBackgroundQueue,
               errorHandler: ((Realm.Error) -> Void)? = nil,
               block: @escaping (Realm, Confined) -> Void) {
        queue.async {
            do {
                let realm = try Realm()
                if let obj = realm.resolve(self) {
                    if write { realm.beginWrite() }
                    block(realm, obj)
                    if write { try realm.commitWrite() }
                } else {
                    // throw "object deleted" error
                }
            } catch {
                errorHandler?(error as! Realm.Error)
            }
        }
    }
}
```

where the example above becomes:

```swift
ThreadSafeReference(to: obj).async(write: true) { realm, obj in
    // do something with obj
}
```

and due to a number of defaulted arguments, there are a few customization points:

```swift
// Simplest case (read transaction)
ThreadSafeReference(to: obj).async { realm, obj in }
// Pass back to main thread
ThreadSafeReference(to: obj).async(queue: .main) { realm, obj in }
// Handle errors (creating the Realm, committing the transaction, performing the handover or invalid object)
ThreadSafeReference(to: obj).async(errorHandler: { e in print(e) }) { realm, obj in }
```

This would have the disadvantage of not being able to resolve other objects in the block if `write: true` is passed as an argument. Unless we lifted the current requirement that an object cannot be resolved into a Realm in a write transaction.

This is easy to do, but could be confusing to users, as you'd only be able to resolve references if the target Realm is at the same or later version than the source Realm, because the target Realm won't be able to advance if the source Realm is at a later version.

**Alternatives Considered**

1. The async block could take an optional `Confined?` argument, but then using the convenience API takes almost the same number of lines as the full/inconvenient one. So in that case, just use the full API.
2. No error handling block. I don't really see the point of doing that when we can simply have a default argument, which looks the same at the call site if you don't use it.
3. Instead of `ThreadSafeReference.async`, we could have `Realm.async` or `Realm.resolveAsync`, but since the Realm can be inferred from a thread-confined object, but not the other way around, this would be slightly less convenient, and if we're discussing convenience APIs, that defeats the purpose.
4. What about Objective-C? I haven't thought of what a convenience API in ObjC would look like just yet. With our Swift usage growing much faster than Objective-C, that's less of a pressing need. But I'm certainly open to it.

**Comment by astigsen** [comment]
Wouldn't it be more natural to have it as a variation of `Realm.write()`. My intuitive expectation would be something like:

```swift
realm.writeAsync(with: obj) { realm, obj in
    // do something with obj
}
```

**Comment by jpsim** [comment]
That's point 3 in the "alternatives considered" above.

**Comment by astigsen** [comment]
> That's point 3 in the "alternatives considered" above.

I saw that. I am not sure I understand the argument for it being less convenient. Could you detail that a bit more?

My point was also more on the discoverability side. If you are thinking about a how to make your write transaction async, it would be nice to have the answer show up in the autocomplete :-)

**Comment by jpsim** [comment]
> The Realm can be inferred from a thread-confined object, but not the other way around...

My point was that you need to pass two things if the API is on `Realm` (realm+obj), rather than just one (obj) if it's on `ThreadSafeReference`:

```swift
realm.writeAsync(with: obj) { realm, obj in }
// vs
obj.writeAsync { realm, obj in }
```

Come to think of it, it might make sense for the API to be on `ThreadConfined` rather than on `ThreadSafeReference` to eliminate a bit more boilerplate, with no difference in supported functionality:

```swift
extension ThreadConfined {
    func async(write: Bool = false, queue: DispatchQueue = .realmBackgroundQueue,
               errorHandler: ((Realm.Error) -> Void)? = nil,
               block: @escaping (Realm, Self) -> Void)
}

e.g. cut out the middle type.

**Comment by jpsim** [comment]
The argument of the API being more discoverable in auto-complete on `Realm` than if it's on `ThreadConfined` doesn't really stick. Essentially it depends what a user is thinking.

If you're thinking "I have this object, how do I pass it to another thread" the API will be more discoverable on the object (`ThreadConfined`).

If you're thinking "I have this thread-safe reference to an object, how do I pass it to another thread", the API will be more discoverable on the reference (`ThreadSafeReference`).

There's more of a symmetry argument to putting `asyncWrite()` on `Realm` since that's where `write()` is already located. But I think `async(write:)` is more flexible since it's the same API for both reads and writes, and there's no real symmetry argument there on `Realm` since there's no read API, it's implicit.

**Comment by astigsen** [comment]
I can see how `obj.writeAsync { realm, obj in }` is a bit more succinct, but I do think that it breaks the current expectation that transactions are done on the Realm.

I would also expect a `writeAsync` method to eventually support passing in more than one object, in which case it could get pretty complex having it on the objects itself (requiring a separate type for groups of objects).

**Comment by jpsim** [comment]
> I would also expect a `writeAsync` method to eventually support passing in more than one object, in which case it could get pretty complex having it on the objects itself (requiring a separate type for groups of objects).

Actually, passing more than one object becomes problematic at the type system level, as showcased by the force casts necessary with the earlier/abandoned API approach of #3946.

```swift
let package = realm.exportThreadHandover(containing: [stringObject, intObject])
dispatchAsyncAndWait {
    let (realm, objects) = try! package.importOnCurrentThread()
    let (stringObject, intObject) = (objects[0] as! SwiftStringObject, objects[1] as! SwiftIntObject)
    try! realm.write {
        stringObject.stringCol = "the meaning of life"
        intObject.intCol = 42
    }
}
```

From https://github.com/realm/realm-cocoa/blob/10508de51c1ef77860d6c8ce3528e757cbf882a2/RealmSwift/Tests/RealmTests.swift#L879-L902

**Comment by astigsen** [comment]
I remember that. Hence "eventually" ;-)

I think my push for the optimizing for the write transaction case is colored by that being the case I have run into personally, and which I have had several users asking me for (basically just wanting to do all the writes on background thread). So I would like for that one use case to be extremely simple and discoverable.

For the more complex use cases where you want to start with read transactions, use specific queues and so on, I am fine with the generic interface.

**Comment by allsome** [comment]
Still not work, when write objects just fetch from network and have not yet been managed by realm. It's a Infinite loop: need realm write objects in background thread for blocking main thread, but these new objects can't be **ThreadSafeReferenced**, because realm has not saved them.

**Comment by nirinchev** [comment]
@allsome unmanaged objects are intrinsically safe to pass between threads. So when you fetch an object, you don't need to create a thread safe reference for it, simply pass it to your background thread as it is.

**Comment by jpsim** [comment]
@allsome I don't understand what you're saying. Could you please open a new issue taking care to fill out the issue template? Thanks!
