### ISSUE TITLE
Improve error message when "Bad syntax in input message" occurs

### ISSUE THREAD

**Issue by ivanschuetz** [realm/realm-swift#4601]
## Explanation

Without knowing, the user was trying to sync objects using an older version of the object server (while they were using the latest version of Realm/Swift. (Modified by @istx25).

## Actual Results

Sync doesn't work. There's a message

> Sync: Bad syntax in input message 'download 1 2 2 2 8070488485324680466 2 0 0 0

in the app's log. Complete log:

> 2017-01-28 23:13:00.008803 TestProject[2865:1268507] Sync: Connection[1]: Session[1]: Starting session for '/var/mobile/Containers/Data/Application/190510CD-A314-41D3-88C1-4FF9628F0ED4/Documents/realm-object-server/c4c5e243ebe4e1bdc1d9542eee6d9b2c/realm%3A%2F%2F192.168.0.11%3A9080%2F%7E%2Ftest'
> 2017-01-28 23:13:00.009093 TestProject[2865:1268507] Sync: Connection[1]: Resolving '192.168.0.11:9080'
> 2017-01-28 23:13:00.010963 TestProject[2865:1268507] Sync: Connection[1]: Connecting to endpoint '192.168.0.11:9080' (1/1)
> 2017-01-28 23:13:00.015017 TestProject[2865:1268507] Sync: Connection[1]: Connected to endpoint '192.168.0.11:9080' (from '192.168.0.13:54220')
> 2017-01-28 23:13:00.021734 TestProject[2865:1268507] Sync: Connection[1]: Session[1]: Sending: BIND(server_path='/c4c5e243ebe4e1bdc1d9542eee6d9b2c/test', signed_user_token_size=621, need_file_ident_pair=1)
> 2017-01-28 23:13:00.040850 TestProject[2865:1268507] Sync: Connection[1]: Session[1]: Received: ALLOC(server_file_ident=7420913103191721957, client_file_ident=1, client_file_ident_secret=8459691314699173015)
> 2017-01-28 23:13:00.044016 TestProject[2865:1268507] Sync: Connection[1]: Session[1]: Sending: IDENT(server_file_ident=7420913103191721957, client_file_ident=1, client_file_ident_secret=8459691314699173015, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)
> 2017-01-28 23:13:00.057166 TestProject[2865:1268507] Sync: Bad syntax in input message 'download 1 2 2 2 8070488485324680466 2 0 0 0
> '
> 2017-01-28 23:13:00.057427 TestProject[2865:1268507] Sync: Connection[1]: Connection closed due to error
> 2017-01-28 23:13:00.057939 TestProject[2865:1268507] Sync: Closing Realm file: /var/mobile/Containers/Data/Application/190510CD-A314-41D3-88C1-4FF9628F0ED4/Documents/realm-object-server/c4c5e243ebe4e1bdc1d9542eee6d9b2c/realm%3A%2F%2F192.168.0.11%3A9080%2F%7E%2Ftest

After I re-started the device and logged in again, I got the same error but with some numbers incremented:

> 2017-01-28 23:22:14.937873 TestProject[2868:1269571] Sync: Bad syntax in input message 'download 1 3 3 3 8070488485324680466 3 0 0 0

More restarts continue showing the same message / numbers.

The server log doesn't display any errors:

> 2017-01-28T22:12:59.551Z - info: sync-server: Connection[4]: Connection from 127.0.0.1:52236
> 2017-01-28T22:12:59.555Z - info: sync-server: Connection[4]: Session[1]: Session initiated (session_ident=1).
> 2017-01-28T22:12:59.555Z - info: sync-server: Connection[4]: Session[1]: Received: BIND(server_path=/c4c5e243ebe4e1bdc1d9542eee6d9b2c/test, signed_user_token='...jEg25vGcZCnQhIllwiV5i8uO141A==', need_file_ident_pair=1)
> 2017-01-28T22:12:59.570Z - info: sync-server: Connection[4]: Session[1]: Sending: ALLOC(server_file_ident=7420913103191721957, client_file_ident=1, client_file_ident_secret=8459691314699173015)
> 2017-01-28T22:12:59.577Z - info: sync-server: Connection[4]: Session[1]: Received: IDENT(server_file_ident=7420913103191721957, client_file_ident=1, client_file_ident_secret=8459691314699173015, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)
> 2017-01-28T22:12:59.591Z - info: sync-server: Connection[4]: Session[1]: Session terminated (session_ident=1).
> 2017-01-28T22:12:59.592Z - info: sync-server: Connection[4]: Connection closed by client: End of input

## Steps to Reproduce

It's happening during a call of `SyncUser.logIn(with: credentials)` with a device, after upgrading Realm. Happens with new installation as well as with already installed app. It's a bit difficult to extract the code but I can do this if the error message isn't informative enough.

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

/Applications/Xcode.app/Contents/Developer
Xcode 8.2.1
Build version 8C1002

/usr/local/bin/pod
1.1.1
Realm (2.4.1)
RealmSwift (2.4.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.18.1
(not in use here)

/usr/bin/git
git version 2.10.1 (Apple Git-78)
```

**Comment by i-schuetz** [comment]
I forgot to upgrade also the object server. I did it now and it works. Letting this open because the error message could be improved.

**Comment by istx25** [comment]
Hiya @i-schuetz! Thanks for filing this. I'm going to edit your issue to reflect your last comment (more of an enhancement than a bug) and have someone look into it. Cheers.

**Comment by joshuapinter** [comment]
I am getting this on the Realm-JS platform as well. Both the Realm package and the Realm Object Server are up-to-date. I logged an issue over here: https://github.com/realm/realm-js/issues/859

In case they are related.
