### ISSUE TITLE
when build on Simulator with this error

### ISSUE THREAD

**Issue by GesanTung** [realm/realm-swift#5498]
This script strip-framework.sh with error lipo -remove
maybe Building for simulator, no need to thin frameworks.
if [[ "${TARGET_BUILD_DIR}" == *"iphonesimulator" ]]; then
    echo "Building for simulator, no need to thin frameworks."
    exit 0
fi

**Comment by austinzheng** [comment]
Sorry, it's not clear what you're asking. What is the error you are seeing? What you've posted is a snippet of bash code. Have you tampered with any of the scripts? Can you please fill out the rest of the information in the issue template?

**Comment by GesanTung** [comment]
when Installation realm  with dynamic framework，https://realm.io/docs/swift/latest/
Download the latest release of Realm and extract the zip.
Go to your Xcode project’s “General” settings. Drag RealmSwift.framework and Realm.framework from the appropriate Swift-versioned directory for your project in ios/, osx/, tvos/ or watchos/ directory to the “Embedded Binaries” section. Make sure Copy items if needed is selected (except if using Realm on multiple platforms in your project) and click Finish.
In your unit test target’s “Build Settings”, add the parent path to RealmSwift.framework in the “Framework Search Paths” section.
If using Realm in an iOS, tvOS or watchOS project, create a new “Run Script Phase” in your app’s target’s “Build Phases” and paste the following snippet in the script text field:

Copy to clipboardbash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh"
This step is required to work around an App Store submission bug when archiving universal binaries.

Building for simulator with script strip-framework.sh error

**Comment by Incorporalis** [comment]
The same problem here

I assume @GesanTung supposed to edit `strip-frameworks.sh` file for building with simulators

If you use Realm as prebuilt framework, it can bring a problem with building on simulator.

If we add these lines of code to the script at the beginning, what could be broken?

```
if [ "$PLATFORM_NAME" = iphonesimulator ]; then
  echo "No need to strip frameworks for simulator."
  exit(0)
fi
