### ISSUE TITLE
Hard-coded cast breaks access to List<String>, List<Int>, etc. during migrations

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-swift#5633]
## Goals
Update a `List<String>` property during migration.

## Expected Results
To be able to

## Actual Results
`DynamicObject` has a hard-coded cast here:
https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Object.swift#L364

so `List<String>` is being cast to `List<DynamicObject>` during a migration.

## Steps to Reproduce
Add a new value to a `List<String>` property during a migration.

## Version of Realm and Tooling
Realm framework version: 3.1.1

Xcode version: 9.2

iOS/OSX version: 11

Dependency manager + version: CP

**Comment by santaasus** [comment]
In the latest versions, realm return List<DynamicObject> instead of for example List<Primitive Type>. Resolve please cast for elementary types: Int, Float, String...
