### ISSUE TITLE
Migration crashes when using enum case

### ISSUE THREAD

**Issue by hermanolsson** [realm/realm-swift#5711]
I'm not sure if this fits as a question or bug report, but I have run into an issue where trying to use an enum type in a migration block. When using objc enums for regular Realm Objects in Swift, Realm helps transforming an NSInteger backed enum to a Realm Object property, but in a migration block, that is lost due to the intermediary migration object and the `rawValue` must be used for the migration to work.

Some background: We went from a `Bool` to an `Enum` which required this migration.

I cannot find anything in the documentation regarding this, though, so I guess this issue can be treated as a request for more clear docs regarding the use of enums as properties in Realm Objects. In hindsight this is pretty clear, but since the compiler does not complain, it's pretty hard to spot.

## Goals
Set value to a enum type property in a migration block

## Expected Results
The migration succeeds with a correct value set on the enum

## Actual Results
The migration fails with an exception.

```
Invalid property value '__C.ProductEntitlementType' for property 'entitlementType' of class 'Download'
```

## Code Sample

```objectivec
// Objective C NSInteger backed Enum
typedef NS_ENUM(NSInteger, ProductEntitlementType) {
    ProductEntitlementTypeNone,
    ProductEntitlementTypePurchased,
    ProductEntitlementTypeRented
};
```

```swift
class Download: Object {
  // Version 0
  // @objc dynamic var isPurchased: Bool = false

  // Version 1
  @objc dynamic var entitlementType: ProductEntitlementType = .none
}
```

```swift
// Compiles, but crashes
if oldSchemaVersion < 1 {
  migration.enumerateObjects(ofType: Download.className(), { oldDownloadObject, newDownloadObject in
    newDownloadObject?["entitlementType"] = ProductEntitlementType.purchased
  })
}
```

```swift
// Works (note the rawValue)
if oldSchemaVersion < 1 {
  migration.enumerateObjects(ofType: Download.className(), { oldDownloadObject, newDownloadObject in
    newDownloadObject?["entitlementType"] = ProductEntitlementType.purchased.rawValue
  })
}
```

## Steps to Reproduce
1. Create a Realm Object subclass
2. Add an enum property
3. Set a value in a migration block
4. Bump realm version to trigger a migration

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: -

Xcode version: 9.2

iOS/OSX version: iOS 11.3

Dependency manager + version: Carthage 0.28.0

**Comment by bmunkholm** [comment]
Yeah we don't really support enums. The supported types are listed here: https://realm.io/docs/swift/latest/#property-cheatsheet.
Perhaps we should specifcally say we don't support enums.
I'll put that in the backlog. Thanks for reporting this!
