### ISSUE TITLE
Feature Request: Commit without Notification with No Token Required

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-swift#5760]
At present, you can do a Realm write and forego the notification like this:

```
let realm = try! Realm()
realm.beginWrite()
//...
try! realm.commitWrite(withoutNotifying: [token])
```

But for any moderately complex app, it can be a real pain to keep track of your `token` (especially if you have several of them). It'd be nice to just be able to say, _"Don't notify anything, anywhere."_ 

Something like this:
```
//...
try! realm.commitWrite(sendNotification: false)
```
...and it simply wouldn't create a notification anywhere.

Thanks! :)

**Comment by NikKovIos** [comment]
That's really better, than send token through over the app.

**Comment by NikKovIos** [comment]
Up

**Comment by NikKovIos** [comment]
Another one point to transfer to CoreData.
