### ISSUE TITLE
Support new features from Xcode 10

### ISSUE THREAD

**Issue by tgoyne** [realm/realm-swift#5798]
Basic functionality:

* [x] Build obj-c
* [x] Obj-c tests passing
* [x] Build Swift
* [x] Swift tests passing
* [x] Fix new warnings and static analyzer things
* [x] CocoaPods build
* [ ] Write/recycle blog post about using Realm with Xcode betas

New features:

* [ ] Codable enhancements
* [x] Property names starting with `new`
* [ ] Parallel testing
* [x] @inlinable?

**Comment by wilmarvh** [comment]
Compiling branch `tg/xcode-10` with `Xcode Version 10.0 beta (10L176w)` results in the following build errors:

<img width="269" alt="screen shot 2018-06-05 at 10 22 22" src="https://user-images.githubusercontent.com/238580/40992008-5ec82692-68aa-11e8-8b2a-7369e98362dc.png">

**Comment by tgoyne** [comment]
Building as Swift 4 now works for me, and all of our tests pass. We'll be making an unrelated release tomorrow, and then after that I'll work on merging the xcode 10 branch to master and looking into if there's any new things we can take advantage of.

**Comment by JALsnipe** [comment]
@tgoyne How can we play around with your branch?

I'm trying to use it in my podfile like so:

    pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :branch => 'tg/xcode-10', submodules: true

But I'm still getting compile time errors like `Value of type 'RLMSyncConfiguration' has no member 'fullSynchronization'`, `Cannot invoke initializer for type 'RLMSyncConfiguration' with an argument list of type '(user: SyncUser, realmURL: URL, isPartial: Bool, urlPrefix: String?, stopPolicy: RLMSyncStopPolicy, enableSSLValidation: Bool)'`, etc.

**Comment by tgoyne** [comment]
You need to explicitly add the Realm pod as well (with the branch specified) or it'll try to use the latest release.

**Comment by grangej** [comment]
@tgoyne I would also be interested in trying this out as this seems to be the only dependency not working in Xcode 10, I tried the above line but received other errors after recompiling. If you have a few mins would love a quick way to get this up and running? :)

**Comment by grangej** [comment]
@NeriusB That will teach me to read before coffee ☕️

**Comment by uson1x** [comment]
Has `tg/xcode-10` branch been removed or it's not in this repository?

**Comment by uson1x** [comment]
Seems like the `tg/xcode-10` branch has been merged into master, so I guess now we can just target master branch. https://github.com/realm/realm-cocoa/pull/5801

**Comment by tgoyne** [comment]
You should now be able to update to v3.7.1 and not have to do anything special.

**Comment by haithngn** [comment]
Version 10.0 beta (10L176w) cannot build via carthage :(

**Comment by waner11** [comment]
I'm having trouble on XCode 10.0 beta 5 (10L221o) with 3.7.6 and Swift 4.2, I'm getting these errors and more.

![screen shot 2018-08-11 at 2 41 50 pm](https://user-images.githubusercontent.com/22116259/43995029-b9d5d38c-9d74-11e8-9b2a-1268c4c8fd04.png)

**Comment by rjchatfield** [comment]
Just sharing that I can't compile RealmSwift using Carthage 0.30.1 and today's Xcode 10 beta 6. Running carthage a second time (with no changes to any projects) compiles successfully.

**Comment by LuAndreCast** [comment]
is there a time frame Xcode 10 support? 🙏

**Comment by bmunkholm** [comment]
@LuAndreCast It is supported. But we could utilize some of the new features better.

**Comment by LuAndreCast** [comment]
@bmunkholm how can I start testing realm with Xcode 10?  any docs available?
your help is greatly appreciated :)

**Comment by bmunkholm** [comment]
@LuAndreCast Following our docs on the website (https://realm.io/docs/swift/latest/) should do. Otherwise let us know. It's outside the scope of this issue, which now tracks utilizing new features from XCode 10. So if you have trouble installing, our Forum or SO likely gives better responses. Thanks!

**Comment by Syed-Sahab** [comment]
> pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa', :branch => 'tg/xcode-10', submodules: true
> pod 'Realm', :git => 'https://github.com/realm/realm-cocoa', :branch => 'tg/xcode-10', submodules: true

I am using these lines but it give error in terminal that 
[!] Error installing Realm
[!] Failed to download 'Realm'.

what should I do.
Thanks
