### ISSUE TITLE
Support for NSURL

### ISSUE THREAD

**Issue by alejandro-isaza** [realm/realm-swift#599]
RLMObject should support NSURL properties.

**Comment by Entalpi** [comment]
So, one year later. How does things look with the NSURL support? :)

**Comment by istx25** [comment]
What's the status on this?

**Comment by jpsim** [comment]
This isn't being actively worked on at the moment.

**Comment by istx25** [comment]
@jpsim: :disappointed: Okay.

**Comment by antiero** [comment]
What is the recommended way for storing NSURLs? Just write them as Strings then convert back to NSURL when retrieving the data?

**Comment by istx25** [comment]
@antiero: Yes. Saving the absolute string of the URL in your model is the best work around. Though I wish Realm would do that conversion for us!

**Comment by yanke-guo** [comment]
Any progress on NSCoding support? I wish Realm could support any NSCoding class by backing up with NSData.

**Comment by jpsim** [comment]
No progress to report.

**Comment by yanke-guo** [comment]
@jpsim 

I made a quick and dirty workaround to support NSCoding by using NSData as underlaying persistence format.

You can find the diff it here.

https://github.com/YMXian/YMFoundation/commit/50b3878404fee8582f2918b7589173cef4067a6f

It's basically the original version of Realm 0.98.2, I just kept iOS static framework stuffs only.

I need your advice. Thanks.

**Comment by yanke-guo** [comment]
@jpsim 

For now, Read/Write, Auto-Updating works, I wonder will this modification crash other things.

**Comment by jpsim** [comment]
I'm sorry I don't have much time at this point to review external projects.

**Comment by yanke-guo** [comment]
@jpsim 

That will be fine, I will do tests and create a pull request once it's proofed as matured.

**Comment by jpmcglone** [comment]
+1

**Comment by mitchdrew** [comment]
bump

**Comment by alibasta** [comment]
+1

**Comment by Isuru-Nanayakkara** [comment]
+1

**Comment by jVirus** [comment]
+1

**Comment by ppamorim** [comment]
Two years feature... Very tasty.

**Comment by jonchui** [comment]
+1 - any news on this? thanks!

**Comment by thbaja** [comment]
+1

**Comment by onmyway133** [comment]
A workaround is to to use a computed property

```swift
class Product: Object, Mappable {
  dynamic var id: Int = 0
  dynamic var image: String = ""

  override static func primaryKey() -> String? {
    return "id"
  }

  required convenience init(_ map: [String : Any]) {
    self.init()

    self.id <- map.property("id")
    self.image <- map.property("image")
  }

  var imageUrl: URL? {
    return URL(string: image)
  }
}
```

**Comment by markcdb** [comment]
+1

**Comment by d-srd** [comment]
+5

**Comment by Zeta611** [comment]
+1

**Comment by umurgdk** [comment]
@jsflax any updates on `FailableCustomPersistable`?

**Comment by jsflax** [comment]
@umurgdk : @tgoyne is filing a series of PRs to enable the custom types spoken about above. Expect more news in the coming weeks.

**Comment by tgoyne** [comment]
The custom type adaptor feature is now released, and we don't plan to add native URL support.

**Comment by aehlke** [comment]
This is necessary to add:
```
    public static func _rlmDefaultValue() -> Self {
        .init(string: "about:blank")!
    }
```

**Comment by aehlke** [comment]
And a custom property seems unsupported in a swifty query? I get `Cannot compare value 'about:blank' of type 'NSURL' to property 'sourceURL' of type 'string'` for using .where on a URL primaryKey
