### ISSUE TITLE
[Xcode 11] swift package generate-xcodeproj with RealmSwift dependency does not build.

### ISSUE THREAD

**Issue by marc-medley** [realm/realm-swift#6345]
**Bug: An Xcode 11 project which is generated from an executable-type Swift Package which has RealmSwift as a dependency does not build.**

## Goals
The goal is to have an Xcode 11 project which is generated from an executable-type Swift Package which has RealmSwift as a dependency that can successfully build and run.

## Expected Results
What Swift Package that builds from the command line is also expected to build in an Xcode 11 project generated from the same package.

## Actual Results
Build fails as show below in the steps to reproduced.

## Steps to Reproduce
1. Setup an executable type Swift Package with RealmSwift as a dependency.
  * Example [Package.swift](https://github.com/marc-medley/RealmSPMXcode/blob/master/Package.swift)
  * GitHub repository [`marc-medley/RealmSPMXcode` is an example Swift Package with RealmSwift as a dependency](https://github.com/marc-medley/RealmSPMXcode).
1. Verify build from the command line on has only a few warnings.

```sh
swift build

# RealmSPMXcode/.build/checkouts/realm-cocoa/Realm/RLMRealm.mm:135:17: 
# warning: method definition for 'privilegesForRealm' not found [-Wincomplete-implementation]
# @implementation RLMRealm {

# RealmSPMXcode/.build/checkouts/realm-cocoa/include/Realm/RLMRealm.h:658:1: 
# note: method 'privilegesForRealm' declared here
# - (struct RLMRealmPrivileges)privilegesForRealm;

## ... snip ...

# warnings generated.
# [139/139] Linking RealmSPMXcode
```

1. Generate an Xcode 11 project from the Swift Package.

```sh
swift package generate-xcodeproj 
# generated: ./RealmSPMXcode.xcodeproj
open RealmSPMXcode.xcodeproj/
```

1. Build in Xcode with "My Mac" as the target.

![Xcode](https://user-images.githubusercontent.com/15098151/68745086-d2f3e580-05aa-11ea-844e-67c86af7171c.png)UNITO-UNDERSCORE!Errors!UNITO-UNDERSCORE!01!

![Xcode](https://user-images.githubusercontent.com/15098151/68745144-f3bc3b00-05aa-11ea-9871-ef773650681b.png)UNITO-UNDERSCORE!Errors!UNITO-UNDERSCORE!02!

![Xcode](https://user-images.githubusercontent.com/15098151/68745156-f9198580-05aa-11ea-8e5d-eb59c0acbdc4.png)UNITO-UNDERSCORE!Errors!UNITO-UNDERSCORE!03!

![Xcode](https://user-images.githubusercontent.com/15098151/68745163-fe76d000-05aa-11ea-8ed6-6a59b4f29894.png)UNITO-UNDERSCORE!Errors!UNITO-UNDERSCORE!04!

_Workaround: Edit RealmCore 5.23.5/realm/util/terminate.cpp to remove the `REALM_VER_CHUNK` expansion related error:_

```cpp
REALM_NORETURN void terminate(const char* message, const char* file, long line) noexcept
{
    std::stringstream ss;
    // ss << file << ":" << line << ": " REALM_VER_CHUNK " " << message << '\n'; // :BEFORE:
    ss << file << ":" << line << ": [realm-core-5.23.5] " << message << '\n';    // :AFTER:
    terminate_internal(ss);
}
```

After the about workaround more errors occur:

![Xcode](https://user-images.githubusercontent.com/15098151/68745188-0afb2880-05ab-11ea-8ad4-fb5d99baf003.png)UNITO-UNDERSCORE!Errors!UNITO-UNDERSCORE!05!

Notice that .build/checkouts/realm-cocoa/Realm/ObjectStore/src/impl/results_notifier.hpp
and .build/checkouts/realm-cocoa/Realm/ObjectStore/src/impl/results_notifier.cpp are in the same directly.

Next attempted workaround ...

```cpp
// #include "impl/results_notifier.hpp"
#include "results_notifier.hpp"
```

... leads to yet more errors:

![Xcode](https://user-images.githubusercontent.com/15098151/68745213-15b5bd80-05ab-11ea-8443-b8119617567c.png)UNITO-UNDERSCORE!Errors!UNITO-UNDERSCORE!06!

## Code Sample
* Example [Package.swift](https://github.com/marc-medley/RealmSPMXcode/blob/master/Package.swift)
* GitHub repository [`marc-medley/RealmSPMXcode` is an example Swift Package with RealmSwift as a dependency](https://github.com/marc-medley/RealmSPMXcode).

## Version of Realm and Tooling
Realm framework version: REALM_COCOA_VERSION 3.21.0

Realm Object Server version: REALM_VERSION 5.23.5

Xcode version: 11.2

iOS/OSX version: macOS Mojave 10.14.6 (18G1012)

Dependency manager + version: swift-tools-version 5.1

**Comment by tgoyne** [comment]
`swift build` and `swift generate-xcodeproj` do significantly different things and AFAICT it isn't possible to support both of them at the same time.

**Comment by marc-medley** [comment]
I have several projects which build and run with both in the Swift Package Manager CLI `swift build` environment and as an Xcode project created by `swift generate-xcodeproj`. Both can work. 

It's acutally a more rigorous process to test with both because sometimes one environment identifies weaknesses which the other environment does not. I've been using this multi-environment approach for _almost 2 years on multi-environment Linux/iOS/macOS C/Swift headless libraries_. 

The version auto-generated for the Xcode environment by SPM has certain GUI debugging conveniences. However, a package library which builds and runs warning-free across all three environment (`swift build` macOS, `swift generate-xcodeproj` and `swift build` Linux) is pretty solid.

So, at least in my experience, this multi-enviroment approach can work; and, it can also help provide higher quality code.

**Comment by tgoyne** [comment]
Well, if you can figure out a way to deal with the problems I'd certainly be interested in them, but I couldn't. The `REALM_VER_CHUNK` error is because `.define("REALM_VERSION_STRING", to: "\"\(coreVersionStr)\"")` results in `-DREALM_VERSION_STRING="5.23.6"` being passed to the compiler with `swift build`, but `-DREALM_VERSION_STRING=5.23.6` with the generated xcode project (note how it has stripped the quotes). The header inclusion failures are because the generated xcode project ignores `.headerSearchPath("Realm/ObjectStore/src")`.

**Comment by marc-medley** [comment]
@tgoyne Thank you for the clarifying information. It's apparent that there are some upstream Package Manager issues to be addressed for a `swift package generate-xcodeproj` with RealmSwift dependency to build successfully.

The following issues have now been [reported as SwiftPM bugs](https://github.com/apple/swift-package-manager/blob/master/Documentation/Resources.md#reporting-a-swiftpm-bug):

* [SR-11789: `generate-xcodeproj` does not preserve quotes in `.define(...)`](https://bugs.swift.org/browse/SR-11789)
* [SR-11790: `generate-xcodeproj` fails to provide `.headerSearchPath(…)` includes](https://bugs.swift.org/browse/SR-11790)

**Comment by AdieOlami** [comment]
Hi, any update on this please.

**Comment by dianaafanador3** [comment]
Closing this as we don't need to generate an `xcodeproj` to be able to open a Package project as the warning mentions when running `swift package generate-xcodeproj`
`Xcode can open and build Swift Packages directly. 'generate-xcodeproj' is no longer needed and will be deprecated soon.`
If this is needed for other uses case, @AdieOlami @marc-medley please reopen the issue.
