### ISSUE TITLE
Realm sdk version info

### ISSUE THREAD

**Issue by Jaycyn** [realm/realm-swift#6608]
**Feature Request**

## Goals
Have easier access to the currently installed Realm SDK **version**

## Expected Results
I may be overlooking a simple way to get the installed sdk version but as of now, it's several lines of code to derive the currently installed Realm version. It's really handy during development to know which version of Realm sdk is installed - especially when there are several projects in concurrent production.

What we'd like to see is

`print(Realm.sdkVersion)`

instead of the current way (Swift)

```
    func showRealmVersion() {
        let pathOfThisFile = #file
        var path = URL(fileURLWithPath: pathOfThisFile)
        path.deleteLastPathComponent() //remove the enclosing folder name
        path.deleteLastPathComponent() //and then remove the next up folder, leaving the project folder
        let podPath = path.appendingPathComponent("Pods")
        let finalPathUrl = podPath.appendingPathComponent("Target Support Files/Realm/")

        if let realmBundle = Bundle(url: finalPathUrl) {
            if let infoFileDict = realmBundle.infoDictionary {
                if let sdkVersion = infoFileDict["CFBundleShortVersionString"] {
                    print("Realm version: \(sdkVersion)")
                } else {
                    print("realm CFBundleShortVersionString key not found in info.plist")
                }
            } else {
                print("infoDictionary not found")
            }

        } else {
            print("path to info.plist not found")
        }
    }
```

**Comment by tgoyne** [comment]
You should be able to get the Realm bundle with just `Bundle(for: RealmSwift.Object.self)` rather than fiddling around with the filesystem.

**Comment by visdyn** [comment]
@tgoyne You would think so, huh. Unfortunately that doesn't work as getting the bundle that way output the base version only and not the point releases. For example, suppose we have 5.0.3 installed and we get the info from the Bundle as you suggest

let realmBundle = Bundle(for: RealmSwift.Object.self)
if let infoFileDict = realmBundle.infoDictionary {
    if let sdkVersion = infoFileDict["CFBundleShortVersionString"] {
        print("Realm version: \(sdkVersion)")
    } else {
        print("realm CFBundleShortVersionString key not found in info.plist")
    }
} else {
    print("infoDictionary not found")
}

The output (compared to getting it from the file system is as follows

```
Realm version: 5.0.3 //from filesystem
Realm version: 5.0.0 //from bundle via the above code
```

Likewise, if we have 5.1.0 installed the output is

```
Realm version: 5.1.0 //from filesystem
Realm version: 5.0.0 //from bundle via the above code
```

**Comment by visdyn** [comment]
As an update. It seems from 10.x forward. getting the bundle per my above code does appear to now reflect the currently installed Realm version including point releases.

**Comment by jsflax** [comment]
🎉 Great to hear it. Can you close out this issue if that is confirmed?

**Comment by tgoyne** [comment]
This was probably fixed by the shift to defining RealmSwift.Object in obj-c, so now you're getting the Realm bundle and the version from that. Not sure why that would work and getting it from the RealmSwift bundle didn't.

**Comment by Jaycyn** [comment]
I am closing this after 4 years. Would still really like to see a simple way to get the current running Realm SDK version like this

`print(Realm.sdkVersion)`

however, the following code suffices

```
func showRealmVersion() {
    let realmBundle = Bundle(for: RealmSwift.Object.self)
    if let infoFileDict = realmBundle.infoDictionary {
        if let sdkVersion = infoFileDict["CFBundleShortVersionString"] {
            print("Realm version: \(sdkVersion)")
        } else {
            print("realm CFBundleShortVersionString key not found in info.plist")
        }
    } else {
        print("infoDictionary not found")
    }
}
```
