### ISSUE TITLE
Realm Results<Object>  to conform ObervableObject

### ISSUE THREAD

**Issue by jovanpreet** [realm/realm-swift#6635]
**Goals:**
Realm Results<Object> to conform to ObservableObject so we can use it with Lists in SwiftUI. Currently Results are of type struct and only class can conform to ObservableObject protocol. I don't know if this is feasible.

**ExpectedResults:**
Any updation on Results to reflect on Lists.

**Comment by tgoyne** [comment]
Currently you'll need a wrapper class. Something like the following should work (but I haven't tested it):

```swift
class ObservableResults<Element: RealmCollectionValue>: ObservableObject {
    public let results: Results<Element>
    public var objectWillChange: RealmSwift.Publishers.WillChange<Results<Element>> {
        results.objectWillChange
    }
    public init(results: Results<Element>) {
        self.results = results
    }
}
```

**Comment by jovanpreet** [comment]
Hi @tgoyne this works thanks. But still do you have any plans to do so? Because you make RealmSwift.List and Object conform to ObservableObject and not Results. 

Also you use publisher to update which gets called anytime the collection change, will there be any performance difference when using publisher compared to your own Notification.

One last question can publisher tell which rows are added or removed(detailed changes)?

Sorry for asking so many questions but there are no documents what so ever and just one blog on MongoDB which basically covers frozen objects only.

Thanks 🙂

**Comment by jovanpreet** [comment]
Hi @tgoyne could you help on above questions?
