### ISSUE TITLE
Crash in realm::Cluster::init(realm::MemRef)

### ISSUE THREAD

**Issue by igrechuhin** [realm/realm-swift#7009]
!!! MANDATORY TO FILL OUT !!!

## Goals

No crash

## Expected Results

No crash

## Actual Results

Crash

## Steps for others to Reproduce

Unknown.
It's not stable.
We enumerate flatMap collection on List(s) to get single array of distinct elements.

## Code Sample

```
#0	(null) in __pthread_kill ()
#1	(null) in pthread_kill ()
#2	(null) in __abort ()
#3	(null) in abort ()
#4	0x0000000100fb0c68 in please_report_this_error_to_help_at_realm_dot_io ()
#5	0x0000000100fb0f58 in _hidden#13626_ ()
#6	0x0000000100fb10d4 in realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) ()
#7	0x0000000100e47898 in __hidden#3446_ ()
#8	0x0000000100e47898 in realm::Cluster::init(realm::MemRef) ()
#9	0x0000000100e53a80 in __hidden#3603_ ()
#10	0x0000000100e53a80 in realm::ClusterNodeInner::try_get(realm::ObjKey, realm::ClusterNode::State&) const ()
#11	0x0000000100e4758c in realm::ClusterNode::get(realm::ObjKey, realm::ClusterNode::State&) const ()
#12	0x0000000100bd59ec in _hidden#256_ ()
#13	0x0000000100bd9100 in _hidden#385_ ()
#14	0x0000000100ef9834 in realm::Query::find_all(realm::ConstTableView&, unsigned long, unsigned long, unsigned long) const ()
#15	0x0000000100f93f4c in realm::ConstTableView::do_sync() ()
#16	0x0000000100ef9b1c in realm::Query::find_all(unsigned long, unsigned long, unsigned long) ()
#17	0x0000000100d2405c in realm::Results::do_evaluate_query_if_needed(bool) ()
#18	0x0000000100d30408 in realm::Results::snapshot() && ()
#19	0x0000000100d10168 in realm::List::snapshot() const ()
#20	0x0000000100bed4f8 in _hidden#2331_ ()
#21	0x0000000100bfab6c in __hidden#154_ ()
#22	0x0000000100bfab6c in __hidden#2957_ ()
#23	0x0000000100bfab6c in _hidden#2869_ ()
#24	0x0000000100bedad4 in RLMFastEnumerate(NSFastEnumerationState*, unsigned long, id<RLMFastEnumerable>) ()
#25	(null) in NSFastEnumerationIterator.next() ()
#26	0x0000000100ccd4b4 in RLMIterator.next() ()
```

## Version of Realm and Tooling

Realm framework version: 10.5.0

Realm Object Server version: No

Xcode version: 12.3

iOS/OSX version: iOS 14.2

Dependency manager + version: Swift package manager

**Comment by leemaguire** [comment]
Hi @igrechuhin Could you please send us a code sample that reproduces the crash?

Thanks

**Comment by igrechuhin** [comment]
It's not possible. This happens in complex project at random (as it seems to us) moments. Realm just crashes unexpectedly at our users. We do not have stable steps to reproduce it. However it makes millions of crashes at our users.

**Comment by leemaguire** [comment]
@finnschiermer @jedelbo does the above stack trace point to any issues in core?

**Comment by leemaguire** [comment]
@igrechuhin could you not achieve retrieving the distinct elements by using `List.value(for key)`? If you could show us the code where you are performing `flatMap` we may be able to help diagnose further.

**Comment by bmunkholm** [comment]
@igrechuhin Is this still an issue? We can't get further without a repro, unfortunately. If you still see this please help with a repro and we will be happy to look into this again. Thanks!
