### ISSUE TITLE
Failed to consume XCFramework built for distribution

### ISSUE THREAD

**Issue by dcacenabes** [realm/realm-swift#7313]
## Goals
I am trying to build Realm as an XCFramework with ABI stability and use it in our app. For that, I am setting `REALM_BUILD_LIBRARY_FOR_DISTRIBUTION = YES;` in RealmSwift.xcconfig file and then building an xcframework with Xcode 12.5. After successfully generating the frameworks (Realm and RealmSwift), I am then importing them into my project and building the app with Xcode 13 beta.

## Expected Results
My application successfully builds with a different version of the swift compiler.

## Actual Results
We get errors:
Failed to build module 'RealmSwift'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.19.104 clang-1300.0.18.4)'). Please select a toolchain which matches the SDK.

## Steps for others to Reproduce
- Make sure Xcode 12.5 toolchain is selected for the command line build.
- Set REALM_BUILD_LIBRARY_FOR_DISTRIBUTION to YES in RealmSwift.xcconfig file
- Run script: `./build.sh xcframework ios`
- From the build/ folder, grab both Realm and RealmSwift xcframework files and drag them into the sample project
- Build the app with Xcode 13

## Code Sample
Sample project can be found at
https://github.com/dcacenabes/ABIDemo

## Version of Realm and Tooling

Realm framework version: 10.8.0

Xcode version: 12.5 and 13.0 beta

iOS/OSX version: ios 14 and 15

Dependency manager + version: Tried both with Cocoapods and manually adding the framework to the project. Same result.

**Comment by ericjordanmossman** [comment]
If you're building the xcframeowrk with Xcode 12.5, which is using Swift 5.4 tools, is your xcframework building in an app using Xcode 12.5?
Are you able to build the xcframework with 13.0 beta so that it's built with Swift 5.5?

Sorry if I'm misunderstanding something.

**Comment by dcacenabes** [comment]
> If you're building the xcframeowrk with Xcode 12.5, which is using Swift 5.4 tools, is your xcframework building in an app using Xcode 12.5?
> Are you able to build the xcframework with 13.0 beta so that it's built with Swift 5.5?
> 
> Sorry if I'm misunderstanding something.

That is exactly what happens, I build XCFramework with Xcode 12.5 with Swift 5.4.
I can use the framework in an app building with Xcode 12.5 and Swift 5.4

If I try to build the same App using Xcode 13 beta (Swift 5.5) I get the error mentioned above:

Failed to build module 'RealmSwift'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.19.104 clang-1300.0.18.4)'). Please select a toolchain which matches the SDK.

I am setting REALM_BUILD_LIBRARY_FOR_DISTRIBUTION to YES, so the XCFramework should be compatible with other versions of the swift compiler.

As stated in this comment, Realm supports library evolution:
https://github.com/realm/realm-cocoa/issues/7258#issuecomment-843925170

**Comment by ravikirankhareedi** [comment]
I am facing the same issue. Did you find any solution for this problem?

**Comment by dcacenabes** [comment]
> I am facing the same issue. Did you find any solution for this problem?

Unfortunately not

**Comment by leemaguire** [comment]
@dcacenabes Does this issue happen for you with the latest Xcode beta?

**Comment by dcacenabes** [comment]
> @dcacenabes Does this issue happen for you with the latest Xcode beta?

Do you mean building the Realm SDK with BUILD_LIBRARY_FOR_DISTRIBUTION enabled or build the app that uses the library built in an older Xcode version ?

**Comment by dianaafanador3** [comment]
@dcacenabes I think what @leemaguire is trying to ask is if you have tried to built the XCFramework with the REALM_BUILD_LIBRARY_FOR_DISTRIBUTION flag with the latest Xcode release (Xcode 13 as today).

**Comment by leemaguire** [comment]
I think I've found the root cause of the issue. In my investigation I found myself getting these errors (in the below image) along with '`Failed to build module 'RealmSwift'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2`'
<img width="1186" alt="Screenshot 2022-04-20 at 09 50 53" src="https://user-images.githubusercontent.com/17234962/164190159-a31fd5af-6b39-4127-b0f8-c11f04e49efd.png">

I then removed all occurrences of `Realm.` before the obj-c types present in the swiftinterface file. After a clean and build it succeeded and ran on Xcode 13.3.1 with an XCFramework built on Xcode 12.5.1.

The next step is to figure out a way to avoid the name collision when building with older versions of Xcode. Ideally we could use `-Xfrontend -module-interface-preserve-types-as-written` but that will strip out all module names before types and we don't want that.

**Comment by amirthytejeshwar-sc** [comment]
Hey @leemaguire 
Thank you so much for all your contributions. 
I'm just trying to use the library evolution on my local setup. 
So I'm downloading the xcframework from the assets here [v10.28.0](https://github.com/realm/realm-swift/releases/tag/v10.28.0), but getting the same error
`Module compiled with Swift x.x.x cannot be imported by Swift x.x.x`
Am I missing something. Can you point me in right way if possible?
