### ISSUE TITLE
Database Contains Control Control Characters "AAAA\x11" 

### ISSUE THREAD

**Issue by Baumchen** [realm/realm-swift#7330]
## Goals
Solution to remove control characters `"AAAA\x11"`  from database so that database contents are readable and thus don't return `NSNull` when requesting data in Swift.

Is there any way to do a "full-text-search" of the database (over all entities and attributes) to find objects with those characters, so that we can to a on-device cleanup of the database?

## Expected Results
Control Characters `"AAAA\x11"` should never be written to the database (or be exposed to the database user).

## Actual Results
Control Characters `"AAAA\x11"` are written to the database. When reading a `String` typed object containing this data `NSNull` is returned for a non-optional property. This will crash any Swift application having a database model with a non-optional `String` property.

## Steps for others to Reproduce
Sadly there's no way to reproduce. However in https://github.com/realm/realm-cocoa/issues/7111 we already described that the database migration fails because of those control characters being part of the string. That bug has been fixed in https://github.com/realm/realm-core/pull/4443 . However it's only fixed in case of a migration. The bug should be fixed for databases which are not being migrated, too.

## More Detailed Explanation
We have a couple of users using our app on their devices, thus we don't have access to the database directly. The app crashes when accessing property `myString` from an object `MyObject` with returning an `NSNull` exception for non-nullable property `myString`. Looking into the database the content of that `myString` object starts with `"AAAA\x11"`. As mentioned by @jedelbo (https://github.com/realm/realm-cocoa/issues/7111#issuecomment-780394878) these are header information which should not be exposed to the database user. 

```
class MyObject: Object {
    @objc open dynamic var myString: String = ""
}
```

What we're looking for is a way to cleanup the database as this information could be in any attribute of any model object. 

Thank you for any help here.

## Version of Realm and Tooling
Realm framework version: 10.7.2 

Xcode version: 12.4

iOS/OSX version: iOS 12+

Dependency manager + version: Cocoapods 1.10.0

**Comment by pavel-ship-it** [comment]
Hi @Baumchen 
Is it happened on the newer version of Realm after the migration?

**Comment by Baumchen** [comment]
Hi @pavel-ship-it :)

> Is it happened on the newer version of Realm after the migration?

We haven't updated the Realm File Version lately (we're still using 10.7.2 with v20).
It is likely though that the data within the database was added to the database by Realm (or realm-core or realm-java) in a previous version. That's nothing we can't say, because we have no way of accessing the database right now.

**Comment by pavel-ship-it** [comment]
@Baumchen 
It is hard to say how to reproduce the issue without an actual realm. file. Is it possible to have it somehow?

**Comment by Baumchen** [comment]
@pavel-ship-it 
Right now we can't provide such a database.. All we know by now is that it seems that Realm seems to write that faulty data into the database on Java side. The user installed a backup from Android to iOS. However Realm Cocoa seems to not be expecting that data either. 

From what I know looking at the crash is that `RLMStringDataToNSString` is returning nil - very likely because `[[NSString alloc] initWithBytes: ...` is returning nil.

```
// String conversion utilities
static inline NSString * RLMStringDataToNSString(realm::StringData stringData) {
    static_assert(sizeof(NSUInteger) >= sizeof(size_t),
                  "Need runtime overflow check for size_t to NSUInteger conversion");
    if (stringData.is_null()) {
        return nil;
    }
    else {
        return [[NSString alloc] initWithBytes:stringData.data()
                                        length:stringData.size()
                                      encoding:NSUTF8StringEncoding];
    }
}
```

This results in the `RLMAccessorContext` to return `NSNull.null` in the box method:

```
id box(realm::StringData v) { return RLMStringDataToNSString(v) ?: NSNull.null; }
```

This again results in the crash resulting from that faulty data, when Realm Cocoa is trying to convert `NSNull` to a `Swift.String`:

```
NSInvalidArgumentException
-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x202a05c00
```

**Comment by jedelbo** [comment]
Perhaps the StringData variable contains a stale pointer. It points to "AAAA" which is what every data frame in the database starts with. So the pointer could have been obtained in a transaction that is no longer existing and the database could have been modified since.

**Comment by dianaafanador3** [comment]
@Baumchen Any updates on this issue?, Did you take a look at the comment below, it may explain why the issue is happening.

**Comment by molind** [comment]
Similar crash has been reported by one of our users.

**Comment by molind** [comment]
That's was a corrupted database. Waiting for explanation from user when it's happened. In our app we updated realm-swift from 10.28.2 to 10.30.0. Don't know if it's related.
