### ISSUE TITLE
Crash On Delete When LinkingObjects Refer To Same Type

### ISSUE THREAD

**Issue by bdkjones** [realm/realm-swift#7347]
## Expected Results
Realm should not crash when deleting objects of type `T` that contain `LinkingObjects(fromType: T.self, property:"someProp")` properties.

## Actual Results
When deleting objects that link to each other, Realm crashes in a way that's VERY difficult to figure out. The output is:

```
libc++abi: terminating with uncaught exception of type realm::KeyNotFound: No such object
MyApp(65686,0x107297d40) malloc: *** error for object 0x16d381c00: pointer being freed was not allocated
MyApp(65686,0x107297d40) malloc: *** set a breakpoint in malloc_error_break to debug
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
terminating with uncaught exception of type realm::KeyNotFound: No such object
MyApp(65686,0x107297d40) malloc: *** error for object 0x16d381c00: pointer being freed was not allocated
```

## Context

Consider this class:

```
final class Foo: Object
{
   ObjC dynamic var timecode: Int = 0

    let duplicateFoos: MutableSet<Foo> = MutableSet()
    let primeFoos: LinkingObjects<Foo> = LinkingObjects(fromType: Foo.self, property: "duplicateFoos")           // There should only ever be one, but Realm does not provide singular LinkingObjects
    var primeFoo: Foo? {
        return primeFoos.first
    }
}
```

## Steps for others to Reproduce

1. Given the context above, create a database that contains `Foo` objects that link to each other.
2. In a write block, delete these `Foo` objects.
3. Observe that Realm crashes with the stacktrace above.
4. To prevent the crash, BEFORE deleting the `Foo` objects, on EACH object to be deleted, call: `someFoo.duplicateFoos.removeAll()`

## Best Guess

Realm is attempting to delete the same `Foo` object twice, producing the crash. This is based on some other bug reports with a similar stack trace. Perhaps no consideration was given to the edge case where `LinkingObjects` would refer to objects of the same type?

## Version of Realm and Tooling

Realm framework version: 10.10.0

Xcode version: 13.0 Beta 3

iOS/OSX version: 11.4

Dependency manager + version: SPM

**Comment by leemaguire** [comment]
Hi @bdkjones 

All properties in your `Foo` class must use `@Persisted`. You cannot mix it with the old syntax for collections and Linking Objects.

**Comment by bdkjones** [comment]
Yea, that's not the cause of this problem. I just typed that example from memory. I'll change it to use the old syntax. Either one will cause the crash.

**Comment by bdkjones** [comment]
@leemaguire I originally thought the crash was related to the new property wrapper syntax, so I rolled my project back to a commit before I switched to @Persisted. The same crash occurred on delete. I did test the case where everything (including the set and linkingObjects) adopted @Persisted and the result was the same.

**Comment by leemaguire** [comment]
I see what you mean, you might also be able to achieve the singular linking object like so:

```
class Bar: Object {
    @Persisted var timecode: Int = 0
    @Persisted var duplicateBar: Bar?
    @Persisted(originProperty: "duplicateBar") private var primeBar: LinkingObjects<Bar>
    var bar: Bar? {
        return primeBar.first
    }
}

let bar1 = Bar()
bar1.timecode = 123
let bar2 = Bar()
bar2.timecode = 456

bar1.duplicateBar = bar2
bar2.duplicateBar = bar1
```

I can delete `bar1` and `bar2` with no issue

**Comment by bdkjones** [comment]
@leemaguire I assume you're adding the objects to a Realm before deleting them?

In further testing, it appears this issue manifests only once a substantial number of objects are being deleted. In my case, it's about 800.

There are several old issues on other Realm repos that jive with that: the crash doesn't happen for trivial deletes.

**Comment by leemaguire** [comment]
Hi @bdkjones to help us get to the root of the issue quickly, could you provide us with a sandbox app that replicates the crash? Thanks

**Comment by pavel-ship-it** [comment]
@bdkjones any luck with the resolution? Could you provide us with a sandbox app that replicates the crash?

**Comment by bdkjones** [comment]
I can try, once I get some free time. 

This crash occurred in an app I built for a client and their data scaled to millions of relationships. If I recall correctly, it was necessary to have a sizable number of items in the LinkingObjects relationship before the crash manifests.
