### ISSUE TITLE
iOS 11 min target requirement for Swift Package Manager libraries

### ISSUE THREAD

**Issue by alexmx** [realm/realm-swift#7409]
### Problem
I'm trying to migrate a project from CocoaPods to Swift Package Manager and one of the blockers I encountered is that Realm requires iOS 11 min deployment target for Swift PM libraries.

My project uses iOS 10 as min version at the moment and I use CocoaPods to integrate Realm. CocoaPods version supports iOS 9 min target.

Is there a reason why CocoaPods version requires iOS 9 min version but Swift Package Manger one requires iOS 11?

### Solution
Decrease the min deployment target for Swift Package Manger version of the library to iOS 9/10 to be in line with the CocoaPods version.

### How important is this improvement for you?
Dealbreaker

**Comment by jsflax** [comment]
Hey @alexmx, this commit explains the "why": https://github.com/realm/realm-cocoa/commit/a701f6cc069055eec0503a8777eb44104238c32e.

Building as c++17 for iOS <11 requires passing a extra compiler flag to disable
aligned allocations, which SPM does not support.

**Comment by alexmx** [comment]
> Hey @alexmx, this commit explains the "why": [a701f6c](https://github.com/realm/realm-cocoa/commit/a701f6cc069055eec0503a8777eb44104238c32e).
> 
> Building as c++17 for iOS <11 requires passing a extra compiler flag to disable
> aligned allocations, which SPM does not support.

@jsflax will the addition of [Package Manager Extensible Build Tools](https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md) to SPM help workaround this limitation and allow you to drop min target below 11?

**Comment by jsflax** [comment]
We might be able to do something creative with that in how we compile core? But it doesn't change the simpler issue that the flags we need to provide through the standard SPM mechanism are considered "unsafe".

I'm curious, why do you need iOS9 still? iOS9 seems to have an infinitesimal amount of users at this point: https://david-smith.org/iosversionstats/

**Comment by alexmx** [comment]
@jsflax I don't need iOS 9, but I do need iOS 10. The project I'm trying to migrate is a financial app which can't that simply drop support for older OS versions even though the number of users is low.

**Comment by tgoyne** [comment]
Now that Xcode 14 is required and that doesn't support iOS <11 at all this is no longer applicable.
