### ISSUE TITLE
Started experiencing SIGKILL crashes very frequently after iOS 15 launch

### ISSUE THREAD

**Issue by romanrudyy** [realm/realm-swift#7466]
### How frequently does the bug occur?

Sometimes

### Description

We're having a ton of crash reports appearing after iOS 15 release that have not been present before. All of them are SIGKILL crashes and stack traces have nothing nut realm activity. Is this something that is a known issue?

### Stacktrace & log output

```shell
Multiple different stack traces
```

### Can you reproduce the bug?

Yes, sometimes

### Reproduction Steps

The iOS will kill the app eventually

### Version

10.7.6

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS 15

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by romanrudyy** [comment]
Could that be due to us using the ancient 10.7.6 version?

**Comment by romanrudyy** [comment]
Thanks for responding  @leemaguire ! We have updated to 10.16, but the crashes seem to keep happening. I'm not fully sure the crashing is caused by Realm, but it seems like a suspect! Thanks!

[Riot  07.10.2021, 23-04.crash.zip](https://github.com/realm/realm-cocoa/files/7307632/Riot.07.10.2021.23-04.crash.zip)

[Riot  07.10.2021, 17-23.crash.zip](https://github.com/realm/realm-cocoa/files/7307633/Riot.07.10.2021.17-23.crash.zip)

[Riot  07.10.2021, 16-08.crash.zip](https://github.com/realm/realm-cocoa/files/7307634/Riot.07.10.2021.16-08.crash.zip)

**Comment by laGrave** [comment]
Also faced with same issue. I've found that in my case crashes happens on obj-c apps, but not happens on swift apps.

**Comment by rjvir** [comment]
To anyone else seeing this issue - I *think* moving the Realm file to the main document directory rather than the app group container fixed the issue. (Not fully confirmed, but anecdotally have been seeing fewer background crashes in the last ~3 days since attempting it). 

Essentially, before initializing Realm on app launch, I perform a 1 time move operation of the Realm file to the main document directory, kind of like this:

```swift
let containerDirectory = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: Constants.sharedContainerIdentifier)

let documentsDirectory = try? FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)

if let oldContainerRealmURL = containerDirectory?.appendingPathComponent("app.realm") &&
    let realmUrl = directory?.appendingPathComponent("app.realm") &&
    FileManager.default.fileExists(atPath: oldContainerRealmURL.path) {
        try? FileManager.default.moveItem(atPath: oldContainerRealmURL.path, toPath: newPath)
}

// Initialize realm with the new realm URL here
```

**Comment by laGrave** [comment]
I have a very basic default setup, not storing Realm in app group container and still facing those crashes
```
RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.schemaVersion = 5;
    config.migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {
        if (oldSchemaVersion < 5)
        {}
    };
    [RLMRealmConfiguration setDefaultConfiguration:config];
    [RLMRealm defaultRealm];
```

**Comment by JituDeore** [comment]
Same we also have Realm file in main Document directory still our app is crashing.

**Comment by SebC99** [comment]
Same here, as reported here: https://developer.apple.com/forums/thread/693623
Due to lock on the realm file in the shared container
Just as in the old #6671

**Comment by vj1988** [comment]
Not the same problem, @JituDeore is talking about crash on launch and not about crash on background.

**Comment by vj1988** [comment]
To simply put - When realm is upgraded from 4.* to 10.*, there is a format change in realm. Due to this the realm file is copies to the new format and this takes time on launch. Time out occurs and app crashes for a lot of users. What can we do to avoid this long delay ?

**Comment by pavel-ship-it** [comment]
Hi all,
I made some experiments on this matter and I was able to reproduce it.
I have 2 cases:
```<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<com.py.Compact>:6743 exhausted real (wall clock) time allowance of 10.00 seconds
ProcessVisibility: Background
```
and
```<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-create watchdog transgression: application<com.py.Compact>:6130 exhausted real (wall clock) time allowance of 19.86 seconds
ProcessVisibility: Foreground
```

How to:
1. Choose 'Edit scheme' in Xcode menu
2. Set 'Run' -> 'Build Configuration' to 'Release'
3. Install the app on the iOS device (just build and run on the device)
4. Now stop the app (You need to launch it without the debugger)
5. Manually run it on your device and do what you need
>> do something to reproduce the issue.

The crashlog could be found in XCode's Devices and Simulators window.

Pleae let me know if that works for you.

**Comment by pavel-ship-it** [comment]
@romanrudyy hi. any news on the issue? Can you reproduce the issue using the approach from my previous message?

**Comment by laGrave** [comment]
Hi all. Is there any information? Still facing hundreds of crashes every day. Can't see them in firebase, but they are visible in AppStoreConnect dashboard and XCode organizer

**Comment by bb-git** [comment]
We contacted Apple about the iOS 15 issues. What we were told, is that starting from iOS 15 the lifecycle methods do not necessarily need to be called in the order expected from previous iOS version. We found out, that `applicationWillTerminate` was called without `applicationDidFinishLaunching` being called. One object wasn't initalized and the app crashed. Also the crash tracker wasn't loaded, so no reports. Hope it helps!

**Comment by PetrBodnar** [comment]
May be related to https://developer.apple.com/forums/thread/693623 general problem?

**Comment by pavel-ship-it** [comment]
@bb-git thank you for information. Can you confirm you were able to fix that?

@PetrBodnar thank you. It seems Apple have a fix for better crash reports on EXC_CRASH (SIGKILL). Maybe anyone can share fresh crashlogs?

@romanrudyy does anything from above helps you to fix the issue?

**Comment by IAmMichellis** [comment]
Hi @pavel-ship-it , I'm working on the same codebase / issue as @romanrudyy was working on in October.

I found this thread and I believe this to be our issue: we are storing our Realm db in a shared container and accessing it from the app and from a notification extension: https://githubhot.com/repo/realm/realm-swift/issues/7649

Can you speak to what we can do about iOS 15 killing our app because of Realm access in the shared container while in the background?

It sounds to me as though if we prevent all Realm access when the app becomes suspended, then Realm access via the notification extension shouldn't cause crashes (because there will be no file lock). Does that sound right to you?

This is quite an undertaking to fix on my side so I'd love any insight you have - I see you commented in that other thread as well :)

**Comment by bmunkholm** [comment]
Looks like this has been resolved. If anyone see this issue again, please create another issue referencing this one. Thanks!
