### ISSUE TITLE
SwiftUI.swift file showing StateObject error in macOS app.

### ISSUE THREAD

**Issue by m-afham** [realm/realm-swift#7484]
### How frequently does the bug occur?

All the time

### Description

![image](https://user-images.githubusercontent.com/35783310/137532176-f8ab68a0-850c-4eaa-82d7-778b3cc2889f.png)

### Can you reproduce the bug?

Yes, always

### Version

Realm 10.17

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS BigSur Beta Ver 11.5

### Build environment

Xcode version: 12.5.1
Dependency manager and version: COCOAPODS: 1.10.1 & SPM

**Comment by m-afham** [comment]
@leemaguire I'm using these pods: 
 
```
  pod 'MagicalRecord/Shorthand'
  pod 'SDWebImage'
  pod 'PocketSVG'
  pod 'Localize-Swift', '~> 2.0'
  pod 'ReachabilitySwift'
  pod 'Zip', '~> 1.1'
  pod 'AppCenter'
  pod 'Alamofire', '~> 5.2'
  pod 'CocoaLumberjack/Swift'
  pod 'SwiftGen', '~> 6.0'
  pod 'RealmSwift'
```

**Comment by pavel-ship-it** [comment]
@m-afham could you try the fix from the message above?

**Comment by azhm** [comment]
@IPrototypeI 
I just encountered this problem. 
Update to the latest version. 
It has been fixed. 
Thanks

**Comment by dianaafanador3** [comment]
@m-afham were you able to fix this after upgrading from Big Sur beta?
