### ISSUE TITLE
LinkingObject property doesn't notify correctly

### ISSUE THREAD

**Issue by ericjordanmossman** [realm/realm-swift#7493]
### How frequently does the bug occur?
All the time

### Description
~~It appears that a linkingObject property doesn't notify properly when the origin property is on the same class~~
Write transactions where only a backlink property is changed does not notify.

This happens even without a keyPath parameter.

![Screen Shot 2021-10-20 at 4 25 02 PM](https://user-images.githubusercontent.com/25092858/138166791-a80dd9e2-9d18-4f32-b6d5-570b0970fcc3.png)

Expected behavior is to receive a notification on a linkingObject property. Similar to how [testBacklinkPropertyKeyPathNotifications4](https://github.com/realm/realm-cocoa/blob/em/backlink-notification/RealmSwift/Tests/ObjectTests.swift#L1344) behaves.

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
Example reproduction [code](https://github.com/realm/realm-cocoa/blob/em/backlink-notification/RealmSwift/Tests/ObjectTests.swift#L1383)

### Version
10.17

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
All

### Build environment
Xcode version: 13.0
Dependency manager and version: SPM

**Comment by Zanchee** [comment]
I've attached an example that uses valuePublisher that shows a short example of this issue happening. Hopefully it helps.

[Example.zip](https://github.com/realm/realm-swift/files/7877466/Example.zip)

**Comment by Zanchee** [comment]
Any updates on this issue?

**Comment by Zanchee** [comment]
@pavel-ship-it any updates on this bug being addressed?

**Comment by aehlke** [comment]
Would be nice to have a scary disclaimer about this in the docs for LinkingObject if this is going to remain an issue
