### ISSUE TITLE
libsystem_kernel.dylib __pthread_kill

### ISSUE THREAD

**Issue by RahulRawat-95** [realm/realm-swift#7499]
#### SDK and version
SDK : RealmSwift
Version: 10.15.0

#### Observations
* How frequent do the crash occur?
Happened only once
* Does it happen in production or during dev/test?
Happened in testing
* Can the crash be reproduced by you?
No
* Can you provide instructions for how we can reproduce it?
No

#### Crash log / stacktrace
libsystem_kernel.dylib
__pthread_kill
libsystem_c.dylib
abort
Realm
please_report_this_issue_in_github_realm_realm_core
Realm
realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)
Realm
realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&)
Realm
void realm::util::terminate<unsigned long long, unsigned long long>(char const*, char const*, long, unsigned long long, unsigned long long) terminate.hpp:45
Realm
realm::Array::set(unsigned long, long long)
Realm
realm::Obj& realm::Obj::set<long long>(realm::ColKey, long long, bool)
Realm
void (anonymous namespace)::kvoSetValue<long long, long long>(RLMObjectBase*, unsigned long, long long) RLMAccessor.mm:120
-----Redacted stacktrace for privacy------
CoreBluetooth
-[CBPeripheral handleAttributeEvent:args:attributeSelector:delegateSelector:delegateFlag:]

#### Steps & Code to Reproduce
Can't share the steps since I don't know myself. Can share the code either. The stack trace said to report the issue so reporting it. Will help as much as I can while redacting some info.

**Comment by pavel-ship-it** [comment]
@RahulRawat-95 
Can you show how you using the Realm?
Realm configuration, creation of object and object model related to the crash?
Is it happened in the main thread?
