### ISSUE TITLE
Expose RLMArray constructor for creating Primitive type Array using Swift with realm-objective C

### ISSUE THREAD

**Issue by tusharmutreja300** [realm/realm-swift#7536]
### How frequently does the bug occur?

All the time

### Description

Hey, I am working on the project that has the combination of both objective-c and Swift. While working with realm-coca, using the swift language in same project , i found that below mentioned constructor is not exposed in `RLMArray.h` file to create the primitive type Array.  
`- (instancetype)initWithObjectType:(RLMPropertyType)type optional:(BOOL)optional; `

Only `- (instancetype)initWithObjectClassName:(NSString *)objectClassName;` is exposed to create the array of RLMObject.

As With the requirement of project ,we require this constructor to be exposed . 

### Can you reproduce the bug?

Yes, always

### Version

10.19

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MAC OS big sur (11.5.1)

### Build environment

Xcode version: 12.5.1
Dependency manager and version: cocapods (1.10.1)

**Comment by pavel-ship-it** [comment]
Hi @tusharmutreja200 you don't need to import anything else in Objective-С.
To create a Realm array of primitives you can define it like following:
```
@interface PrimitiveArray : RLMObject
@property RLMArray<RLMInt> *intObj;
@end
```
Please refer to example in our tests 
[declaration](https://github.com/realm/realm-cocoa/blob/f630b28cc3d056f784d568569e671e32b9eacb6c/Realm/TestUtils/include/RLMTestObjects.h#L211)
[initialization](https://github.com/realm/realm-cocoa/blob/f630b28cc3d056f784d568569e671e32b9eacb6c/Realm/Tests/ObjectCreationTests.mm#L811)

You can find more in the Realm [documentation](https://docs.mongodb.com/realm/sdk/ios/)

**Comment by tusharmutreja300** [comment]
@pavel-ship-it I understand if we are writing using objective-c language then there is no need. But what if we need create an  array of primitive array using swift language.

please refer to this comment of @jsflax   https://github.com/realm/realm-cocoa/issues/7517#issuecomment-963067

As I found the solution for this too , And also created the PR for the same.

PR link: https://github.com/realm/realm-cocoa/pull/7537

please look into it once, As this issue is blocking our development.

**Comment by pavel-ship-it** [comment]
Can you explain the use case a bit more please?

You can have array of primitives in both ways.
```
// obj c
@import Realm;

@interface PrimitiveArrayObjC: RLMObject
@property RLMArray<RLMInt> *intObj;
@end

RLMRealm *realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[realm addObject: [PrimitiveArray new]];
[realm addObject: [PrimitiveArrayObjC new]];
[realm commitWriteTransaction];
```

```
// swift
import Realm
import Realm.Private

class PrimitiveArray: RLMObject {
    @objc dynamic var intObj = RLMArray<NSNumber>(objectType: RLMPropertyType.int, optional: true)
}

let realm = RLMRealm.default()
realm.beginWriteTransaction()
realm.add(PrimitiveArray())
realm.add(PrimitiveArrayObjC())
try! realm.commitWriteTransaction()
```

**Comment by tusharmutreja300** [comment]
Hey @pavel-ship-it, I have a use case in which I need to create Realm array of primitive types in Swift file. And configuration of the project like this 

- Base of the the project is in Objective-c and mix of Swift files too
- Using realm-objective c as a library
- But using Swift language to create the realm Schema via bridging 

Problem : We are not able to access the` - (instancetype)initWithObjectType:(RLMPropertyType)type optional:(BOOL)optional` this constructor in our swift file to create an array of primitive type.

And based on my analysis I found that **initWithObjectType** is not exposed from the file RLMArray.h file like  **initWithObjectClassName** , thats y we are not able to access in our swift file.

As you can check in PR: https://github.com/realm/realm-cocoa/pull/7537 too that I just added this constructor and everything works, I think it might be a miss.

And also I have tried your solution in swift file, but it gives an error as we are importing realm from bridging header file.

<img width="967" alt="Screenshot 2021-11-17 at 8 02 10 PM" src="https://user-images.githubusercontent.com/63159707/142220255-911876cf-1b01-4e54-9b0c-a3e95e575253.png">



**Error after applying  above solution** 

<img width="1009" alt="Screenshot 2021-11-17 at 8 02 23 PM" src="https://user-images.githubusercontent.com/63159707/142220357-87d2d12f-b752-4e48-9186-cee19bcd7c3e.png">


**Error after not applying  above solution** 


<img width="1000" alt="Screenshot 2021-11-17 at 8 07 42 PM" src="https://user-images.githubusercontent.com/63159707/142220975-abb5562c-7afa-4fdd-91b9-d5f096268348.png">

And it goes away if we add `initWithObjectType` in RLMArray.h file. And it doesn"t 
requires to import anything in swift file

<img width="1007" alt="Screenshot 2021-11-17 at 8 09 50 PM" src="https://user-images.githubusercontent.com/63159707/142221441-c4a658b1-aea3-4b77-9eab-40d2357414f2.png">

please have a look into PR and let me know if you have any pointers

**Comment by pavel-ship-it** [comment]
The code above should work without the fix you're added in the PR.
Is there a reason to import Realm in bridging header?

fyi - after adding `@objcMembers` you can remove `@objc` from properties.

**Comment by tusharmutreja300** [comment]
@pavel-ship-it thanks for the update.
We are importing realm in bringing header, so that we can use  realm properties in swift files.

You can test this scenario at your end too.
Just need to create objective-c project and install pod realm 10.19 and try to create the schema in swift file.
You will face this issue.

**Comment by pavel-ship-it** [comment]
>You can test this scenario at your end too.

That case is working good for me. Probably there is the issue with a project?
Can you try this project on your environment? https://github.com/pavel-ship-it/support-realm-cocoa-7536

**Comment by tusharmutreja200** [comment]
@pavel-ship-it I understand the scenario that why it works fine at your end because you are using the dynamic framework as I have checked in your project you didn't comment the ` use_frameworks!` in Podfile, but in our project, we have limitations that we can't use dynamic framework and we have commented `use_frameworks!` in Podfile while installing the pods.

Please suggest a way that we can use the same functionality via Static framework of realm

**Comment by pavel-ship-it** [comment]
@tusharmutreja200 
Yes, you can use Realm as a static library. Please refer to the documentation [here](https://docs.mongodb.com/realm-legacy/docs/objc/latest/index.html)

**Comment by tusharmutreja300** [comment]
Thanks, @pavel-ship-it for the update. This issue does"t  exist when we use the Static IOS framework via Drag-drop way eg. by dragging `Realm.xcframework` into the project.
But this issue exists when we install a realm static framework via Pods. For now, I can use the drag-drop way, please check once why this issue exists when we use realm static framework via Cocoapods.

**Comment by tusharmutreja200** [comment]
@pavel-ship-it Any update on it, Can we merge that pull request.

**Comment by dianaafanador3** [comment]
@tusharmutreja200 have you tried adding use_modular_headers! to your Podfile

**Comment by tusharmutreja200** [comment]
@leemaguire  yes, it works perfectly fine with it.

**Comment by leemaguire** [comment]
@tusharmutreja200 good to hear! On that note I will close this issue.

**Comment by tusharmutreja200** [comment]
@leemaguire But we have to fix this for CocoaPods too

**Comment by leemaguire** [comment]
I will bring the PR to the teams attention. In the meantime you can declare a category in your project and building with Cocoapods will work. 

```swift
@interface RLMArray (SwiftExtensions)
- (instancetype)initWithObjectType:(RLMPropertyType)type optional:(BOOL)optional;
@end
```

I declared this in the bridging header just for test purposes and it allowed the project to build & run normally.
