### ISSUE TITLE
Cannot import in Swift Playground (iPadOS)

### ISSUE THREAD

**Issue by Astrian** [realm/realm-swift#7574]
### How frequently does the bug occur?

All the time

### Description

Related to issue #7117 

Apple updated Swift Playground app in iPadOS today and can create a real iPad app program inside the app. There is a package manager function, however, it cannot import Realm-cocoa with error `this software package has no version tags` (translated from simp chinese)

![IMG_0848](https://user-images.githubusercontent.com/4896770/146374330-d64c9bfc-15ee-407b-8163-7198f9b056db.PNG)

### Can you reproduce the bug?

Yes, always

### Version

10.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iPadOS 15.2

### Build environment

The latest version of Swift Playground

**Comment by dianaafanador3** [comment]
Hi @Astrian Thanks for letting us know about this, we are testing this at the moment and let you know any updates

**Comment by Astrian** [comment]
![image](https://user-images.githubusercontent.com/4896770/146628482-5b718527-c340-4dc1-8cda-61c02967dd3d.jpeg)

Just found that Realm-Cocoa cannot be implemented in Swift Playgrounds, for Realm-cocoa used C++ code and cannot be compiled in iPad.

Closing this issue for Realm-cocoa not be supported in the environment.

**Comment by jsflax** [comment]
@Astrian where are you able to see those warnings? We're experimenting with ways to get Realm working on Playgrounds and I haven't encountered those warnings yet.

**Comment by Astrian** [comment]
@jsflax Repeat the warning steps:

- Create app project in Swift Playgrounds on iPad
- Wait the new project upload to iCloud Drive
- Upgrade Xcode to version 13.2 on Mac
- Open project package on Mac with Xcode
- Add Realm-cocoa dependency and compile the project with Command-R 
- See the warning
