### ISSUE TITLE
Can’t import Realm to the Newest Swift Playgrounds 4

### ISSUE THREAD

**Issue by cobeo2004** [realm/realm-swift#7579]
So I’m trying to create an app, but when it comes to importing Realm, it said that “Packages does not have version tags”. So could anyone help me ?
![41A917F8-AA20-4F3C-A819-3FE10BA76477](https://user-images.githubusercontent.com/80842534/146625893-5e8e66b0-5357-49d0-acf4-586ec99162bd.png)

**Comment by moflo** [comment]
Hi - Apple SPM does not support version suffix “v” for release tags, so you would need to update Realm releases to be tagged as “10.20.1” and not “v10.20.1”

But, fatally, Swift Playgrounds does not support Objective-C so you would have to rewrite Realm as a pure Swift library… which seems unlikely

**Comment by leemaguire** [comment]
Realm is not compatible with Swift Playgrounds on iPad at this time.

**Comment by cobeo2004** [comment]
I see the point now, thanks for letting me know !
