### ISSUE TITLE
Upon updating Realm Sync rules/schema, mobile clients don't sync anymore

### ISSUE THREAD

**Issue by Kalzem** [realm/realm-swift#7580]
### How frequently does the bug occur?

All the time

### Description

Using Realm sync on Atlas v4.x and iOS SDK 10.20.0, when I update the Realm Sync schema by adding a new field to a document or a new collection using the Realm Sync Dashboard, I realized that the "living" mobile client doesn't sync anymore (I'm talking about clients that open a sync stream before and during the schema update). Realm would then only work locally, and a restart of the app is required in order send the fresh data to the servers.

How can I keep the clients synced when I update the server schema?

### Can you reproduce the bug?

Yes, always

### Version

10.20.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS 15.1

### Build environment

Xcode version: 13.2
Dependency manager and version: SPM

**Comment by leemaguire** [comment]
Hi @Kalzem,

I will take a look into this issue.

**Comment by leemaguire** [comment]
Hi @Kalzem ,

I tried to reproduce this and it first it looked like a bug. I done an additive change to the Realm Sync schema and then modified some documents in Atlas. At first it looked like they were not syncing, but after about 2-3 minutes I received a sync changeset and all objects synced correctly. 

Could you also check and see if your objects sync after a certain amount of time?

**Comment by Kalzem** [comment]
Hello @leemaguire 

Thank you for answering and sorry for the very late delay.
I confirm your observation: Client side re-syncs after 2-3 minutes (or at next launch if the user killed the app before).

Is there a way to make it happen sooner - to control it from the client SDK?

On a final note, I believe that it can be helpful for others to have this behaviour documented.

**Comment by leemaguire** [comment]
@Kalzem I spoke with the team and this is the expected behaviour, there is no way to speed up the changes. I will note your suggestion to add this to the documentation.
