### ISSUE TITLE
Impact of Generate Debug Symbols is set to NO for Realm iOS static

### ISSUE THREAD

**Issue by dwirandyh** [realm/realm-swift#7583]
Hello there, i would like to ask a question related xcode build confinguration.

So i have build a Realm static framework on my local machine, because of the .framework file is large, i want to generate Realm.framework but with Generate Debug Symbols is NO, and the result Realm.framework size is reduced

The question is there any negative impact that will happen to my app that use Realm.framework?

**Comment by leemaguire** [comment]
Hi @dwirandyh,

Not generating debug symbols will not have any impact on your app. Debug symbols will be stripped automatically if you build Realm in release mode.
