### ISSUE TITLE
library not found for -lrealm-monorepo

### ISSUE THREAD

**Issue by mmdHussain** [realm/realm-swift#7585]
### How frequently does the bug occur?

All the time

### Description

When Compiling with realm im getting these error.

Xcode Version - 13.1
iOS 15

Im installing the realm like these
```
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
```

Ld /Users/mac/Library/Developer/Xcode/DerivedData/Project-bmdqhsllekeuaygqupexvoaluawt/Build/Products/Debug-iphoneos/Realm/Realm.framework/Realm normal (in target 'Realm' from project 'Pods')
    cd /Users/mac/Documents/Study/Project/ios-app\ 3/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk -L/Users/mac/Library/Developer/Xcode/DerivedData/Project-bmdqhsllekeuaygqupexvoaluawt/Build/Products/Debug-iphoneos/Realm -L/Users/mac/Library/Developer/Xcode/DerivedData/Project-bmdqhsllekeuaygqupexvoaluawt/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/Realm -F/Users/mac/Library/Developer/Xcode/DerivedData/Project-bmdqhsllekeuaygqupexvoaluawt/Build/Products/Debug-iphoneos/Realm -F/Users/mac/Documents/Study/Project/ios-app\ 3/Pods/Realm/core -filelist /Users/mac/Library/Developer/Xcode/DerivedData/Project-bmdqhsllekeuaygqupexvoaluawt/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Realm.build/Objects-normal/arm64/Realm.LinkFileList -install_name @rpath/Realm.framework/Realm -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Project-bmdqhsllekeuaygqupexvoaluawt/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Realm.build/Objects-normal/arm64/Realm_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -fapplication-extension -lc++ -lrealm-monorepo -lz -framework Security -framework Foundation -framework Security -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Project-bmdqhsllekeuaygqupexvoaluawt/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Realm.build/Objects-normal/arm64/Realm_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/Project-bmdqhsllekeuaygqupexvoaluawt/Build/Products/Debug-iphoneos/Realm/Realm.framework/Realm

ld: library not found for -lrealm-monorepo
```


### Can you reproduce the bug?

Yes, always

### Reproduction Steps

When Compiling with realm im getting these error.

Im installing the realm like these
```
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
```

<img width="943" alt="Screenshot 2021-12-22 at 11 18 15 AM" src="https://user-images.githubusercontent.com/17882197/147042435-07c73053-5f95-4b75-95c6-8a38364fc5fb.png">


### Version

Xcode 13.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Xcode 13.1,iOS 15

### Build environment

Xcode version: 13.1
Dependency manager and version: ...
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true

**Comment by leemaguire** [comment]
Hi @mmdHussain,

I cannot reproduce your issue. Could you clean the build + delete all derived data and try again. Could you also show us your full pod file?

**Comment by mmdHussain** [comment]
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

# PhoneNumber Lib
pod 'PhoneNumberKit'
pod 'PhoneCountryCodePicker'
pod 'libPhoneNumber-iOS', '~> 0.8'

# Realm Swift
#pod 'RealmSwift'

pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true


# Date
pod 'SwiftDate', '~> 6.2'

# Reactive Components
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'RxTheme', '~> 4.0'
pod 'RxSwiftExt', '~> 5'
pod 'RxDataSources', '~> 4.0'
pod "RxGesture"
pod 'RxBinding'
pod 'RxOptional'
pod 'RxKingfisher'
pod 'RxKeyboard'

pod 'RxAlamofire'

# Tools
pod 'KeychainSwift', '~> 19.0'

# UI
pod 'SnapKit', '~> 5.0.0'
pod 'lottie-ios'
pod 'Hero'
pod 'SideMenu'
pod 'FittedSheets'
pod "Popover"
pod 'youtube-ios-player-helper', '~> 1.0.3'
pod 'SwiftMessages'
pod "PagingKit"
pod 'SwiftCake', :git => 'https://github.com/Rovalx/SwiftCake.git', :branch => 'master'
pod 'SwiftyJSON'


# GZIP
pod 'GzipSwift'

# Tus for Image Upload
pod "TUSKit", '~> 1.4.2'


pod 'Branch', '~>1.38.0' 


pod 'SwiftyAttributes'

pod 'iOSDropDown'
pod 'IQKeyboardManagerSwift'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

**Comment by mmdHussain** [comment]
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

# PhoneNumber Lib
pod 'PhoneNumberKit'
pod 'PhoneCountryCodePicker'
pod 'libPhoneNumber-iOS', '~> 0.8'

# Realm Swift
#pod 'RealmSwift'

pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true


# Date
pod 'SwiftDate', '~> 6.2'

# Reactive Components
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'RxTheme', '~> 4.0'
pod 'RxSwiftExt', '~> 5'
pod 'RxDataSources', '~> 4.0'
pod "RxGesture"
pod 'RxBinding'
pod 'RxOptional'
pod 'RxKingfisher'
pod 'RxKeyboard'

pod 'RxAlamofire'

# Tools
pod 'KeychainSwift', '~> 19.0'

# UI
pod 'SnapKit', '~> 5.0.0'
pod 'lottie-ios'
pod 'Hero'
pod 'SideMenu'
pod 'FittedSheets'
pod "Popover"
pod 'youtube-ios-player-helper', '~> 1.0.3'
pod 'SwiftMessages'
pod "PagingKit"
pod 'SwiftCake', :git => 'https://github.com/Rovalx/SwiftCake.git', :branch => 'master'
pod 'SwiftyJSON'


# GZIP
pod 'GzipSwift'

# Tus for Image Upload
pod "TUSKit", '~> 1.4.2'


pod 'Branch', '~>1.38.0' 


pod 'SwiftyAttributes'

pod 'iOSDropDown'
pod 'IQKeyboardManagerSwift'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

**Comment by leemaguire** [comment]
@mmdHussain I cannot reproduce your issue with the above pod file. Can you clean your build and delete your derived data to see if that helps?

**Comment by owenzhao** [comment]
Can you test this?

1. Create a new project and added realm. 
2. Build with Xcode. Don't apply the yellow optimization options that are provided by Xcode.
3. If 2 will be built with success. Click and see the yellow optimization with Xcode.

If you see the yellow optimizations are code-signing with "-", just don't apply them. Uncheck the box and press done. The options will never be shown again. 

If you apply the options, build will be successful but when running, the app will crash. 

The issue I described was happened to me for some projects, not all. I don't know why it seemed like random.

**Comment by jberkel** [comment]
Maybe this is useful to someone else: it looks like with CocoaPods, the `[CP] Copy XCFrameworks` build phase sometimes does not get executed, which results in the library not being present during linking.

 It seems related to the "Run script based on dependency analysis" setting in the build phase configuration. When unchecked, the project always builds.

<img width="517" alt="Captura de pantalla 2022-03-10 a les 11 02 54" src="https://user-images.githubusercontent.com/18891/157638585-122930cc-7639-4d78-9354-706ecc1396b5.png">

**Comment by taurusdev567** [comment]
This will be helpful someone who are using different pod with realm dependency.

Please add below directly to pod

  pod 'Realm', '10.18.0'
  pod 'RealmSwift', '10.18.0'

it will help.
