### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by devZant** [realm/realm-swift#7587]
Hello,

My App crashes on launch with following error on RealmSwift 10.5.1 although all properties are marked as @objc dynamic var.

'RLMException', reason: 'No properties are defined for 'ReflectableObject'. Did you remember to mark them with '@objc' in your model?'

On this line:
s_sharedSchemaState = SharedSchemaState::Uninitialized;

**Comment by leemaguire** [comment]
Hi @devZant, Can you show us what your Realm models look like?

**Comment by devZant** [comment]
class ReflectableObject: Object {
	func convertObjectToMirrorChildren() -> Mirror.Children {
		return Mirror(reflecting: self).children
	}
}

class Child: ReflectableObject {
	@objc dynamic var name = String()
	@objc dynamic var birthDate = Date()
	@objc dynamic var profilePhotoData = NSData()
	@objc dynamic var gender = String()
	@objc dynamic var lengthUnit = Int()
	@objc dynamic var weightUnit = Int()
	@objc dynamic var amountUnit = Int()
	@objc dynamic var uniqueString = NSUUID().uuidString
	let feedings = List<Feeding>()
	let pumpings = List<Pumping>()
	let diapers = List<Diaper>()
	let sleepings = List<Sleeping>()
	let shoppings = List<Shopping>()
	let growths = List<Growth>()
	let immunizations = List<Immunization>()
	let medications = List<Medication>()
	let sicknesses = List<Sickness>()
	let memories = List<Memory>()
	let medicationNames = List<MedicationName>()
}

class Feeding: ReflectableObject {
	@objc dynamic var startTime = Date()
	@objc dynamic var type = String()
	@objc dynamic var bottleType = String()
	@objc dynamic var amount = Double()
	@objc dynamic var leftDuration = TimeInterval()
	@objc dynamic var rightDuration = TimeInterval()
	@objc dynamic var pauseDuration = TimeInterval()
	@objc dynamic var comments = String()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Pumping: ReflectableObject {
	@objc dynamic var startTime = Date()
	@objc dynamic var side = String()
	@objc dynamic var amount = Double()
	@objc dynamic var duration = TimeInterval()
	@objc dynamic var comments = String()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Diaper: ReflectableObject {
	@objc dynamic var changeDate = Date()
	@objc dynamic var comments = String()
	@objc dynamic var type = String()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Sleeping: ReflectableObject {
	@objc dynamic var startTime = Date()
	@objc dynamic var duration = TimeInterval()
	@objc dynamic var comments = String()
	@objc dynamic var pastMidnight = false
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Shopping: ReflectableObject {
	@objc dynamic var itemTitle = String()
	@objc dynamic var isCompleted = Bool()
	@objc dynamic var dueDate = Date()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Growth: ReflectableObject {
	@objc dynamic var date = Date()
	@objc dynamic var height = Double()
	@objc dynamic var weight = Double()
	@objc dynamic var headSize = Double()
	@objc dynamic var details = String()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Immunization: ReflectableObject {
	@objc dynamic var date = Date()
	@objc dynamic var index = Int()
	@objc dynamic var name: String? = nil
	@objc dynamic var details = String()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Medication: ReflectableObject {
	@objc dynamic var date = Date()
	@objc dynamic var name = String()
	@objc dynamic var details = String()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Sickness: ReflectableObject {
	@objc dynamic var date = Date()
	@objc dynamic var name = String()
	@objc dynamic var details = String()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class Memory: ReflectableObject {
	@objc dynamic var date = Date()
	@objc dynamic var titleIndex = Int()
	@objc dynamic var titleString: String?
	@objc dynamic var photoData = NSData()
	@objc dynamic var comments = String()
	@objc dynamic var uniqueString = NSUUID().uuidString
}

class MedicationName: ReflectableObject {
	@objc dynamic var name = String()
}

**Comment by leemaguire** [comment]
Your `ReflectableObject` is missing a property. You need at least one property in each Realm `Object` class.

**Comment by devZant** [comment]
Oh OK :), thanks a lot.
