### ISSUE TITLE
SwiftUI TextFields do not accept typed in characters in preview mode.

### ISSUE THREAD

**Issue by alan16R** [realm/realm-swift#7595]
### How frequently does the bug occur?

All the time

### Description

I'm using SwiftUI and Realm with the @ObservedRealmObject property type. 

I'm using TextField objects to input text. Although the binding to an Object subclass String property appears to work properly for cases like Cut, Paste etc, typing at the keyboard does not work.However, running in a simulator does work.

### Stacktrace & log output

```shell
None.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Create a default XCode SwiftUI App.
2. Use SPM to add the RealmSwift package
3. Copy/paste the code below into the ContentView.swift
4. Run the preview and attempt to type into the TextField - cursor will be in the field but not respond
  4.A - you can, however, select words and delete/paste etc. The Text View below shows that the binding is updating properly.
5. Run the App in the simulator. Now the field can be edited.

The problem occurs in every Realm project that I've tried it in, including the current ListSwiftUI example in the release.

```
import SwiftUI
import RealmSwift

class MyObject: Object, ObjectKeyIdentifiable {
    
    @Persisted(primaryKey: true) var _id: ObjectId = ObjectId.generate()
    @Persisted var greeting: String
   
    override init() {
        super.init()
    }
    
    convenience init(greet: String) {
        self.init()
        self.greeting = greet
        
    }
}

struct ObjectView: View {
    @ObservedRealmObject var object: MyObject
    var body: some View {
        VStack(alignment: .leading) {
            Text("\(object._id)")
            TextField("greeting", text: $object.greeting)
            Text("Greeting is: \(object.greeting)")
        }.padding()
    }
}


struct ContentView: View {
    @StateRealmObject private var theObject: MyObject = MyObject(greet: "Hello There")
    var body: some View {
        ObjectView(object: theObject)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

### Version

10.20.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

ProductName:	macOS ProductVersion:	11.6.1 BuildVersion:	20G224

### Build environment

/Applications/Xcode.app/Contents/Developer
Xcode 13.2.1
Build version 13C100

/usr/local/bin/pod
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

carthage not found
(not in use here)

/usr/local/bin/git
git version 2.24.0

**Comment by leemaguire** [comment]
This looks like an Xcode bug https://developer.apple.com/forums/thread/650365
