### ISSUE TITLE
Swift Playgrounds 4/iPad: "Package has no version tags"

### ISSUE THREAD

**Issue by TheMojoMan** [realm/realm-swift#7597]
### How frequently does the bug occur?

All the time

### Description

I tried to import the package using Swift Playgrounds 4 on my iPad and always get "Package has no version tags" error.

### Can you reproduce the bug?

Yes, always

### Version

Swift Playgrounds 4

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iPadOS 15.2

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by jsflax** [comment]
@TheMojoMan apologies but we cannot support Playgrounds in its current state. Our library is built on top of ObjC/C++ so until they allow non-Swift (or binary) dependencies, we cannot support Playgrounds.
