### ISSUE TITLE
Make Swift Concurrency Realm enhancements available for iOS 13+

### ISSUE THREAD

**Issue by gabrielnica** [realm/realm-swift#7599]
### Problem

Currently all the structured concurrency enhancements such as 
```
@MainActor
    public init(configuration: Realm.Configuration = .defaultConfiguration,
                downloadBeforeOpen: OpenBehavior = .never) async throws 
``` 
etc. are marked with 

```
@available(iOS 15.0)
```

Is it possible to add availability for iOS 13 as well? At a first glance it doesn't look like there's any blocker for this change

### Solution

Change `@available(iOS 15.0)` to `@available(iOS 13.0)` for Concurrency enhancements

### How important is this improvement for you?

Dealbreaker

**Comment by tgoyne** [comment]
Swift concurrency backdeployment currently has some issues (the Mac App Store rejects apps using it, and it bundles the rather large libswift_Concurrency.dylib even if the app itself never calls any of the async functions) which we need to find workarounds for before we can reasonably enable it.

**Comment by tfe** [comment]
Looks like there is a [report here](https://forums.swift.org/t/app-store-connect-does-not-accept-back-deploy-concurrency-macos-app-that-build-by-xcode-13-2-rc/53913/22) of a macOS app with Swift concurrency back-deployment being accepted as of two days ago.

**Comment by tgoyne** [comment]
If I understand https://forums.swift.org/t/async-await-crash-on-ios14-with-xcode-13-2-1/54541 correctly then enabling back-deployment will also sometimes result in iOS 14 crashes even if the app isn't using concurrency, so we probably need to wait for 13.2.2.

**Comment by onelogapp** [comment]
Update: Xcode 13.3 beta fixes this issue

**Comment by gabrielnica** [comment]
@tgoyne Now that Xcode 13.3 is out, possible to look at this again? Xcode 13.3 fixes the back deployment issue. Thanks
