### ISSUE TITLE
Only crash on iOS 12.x, image not found (libswift_Concurrency.dylib)

### ISSUE THREAD

**Issue by shiami** [realm/realm-swift#7601]
### How frequently does the bug occur?

All the time

### Description

Upgrade to newer version of RealmSwift, crash happens only on iOS 12.x.

Environment:
- Xcode `13.2.1`
- iOS Deployment Target 9.0
- RealmSwift `10.20.1`
- CocoaPods `1.11.2`

Run my app on iPhone 8 Simulators (iOS 11.4, 12.1, 15.2).
Crash only happens on iOS `12.1`.

Same thing happens on real devices (iOS `12.x`).

After downgrade to RealmSwift `10.14.0`, the crash has gone.

### Stacktrace & log output

```shell
dyld: Library not loaded: /usr/lib/swift/libswiftCore.dylib
Referenced from: /Users/hebi/Library/Developer/CoreSimulator/Devices/XXX/data/Containers/Bundle/Application/XXX/XXX.app/Frameworks/libswift_Concurrency.dylib
Reason: image not found
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Upgrade to newer version of RealmSwift, from `10.14.0` to `10.20.1`.

### Version

10.20.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 12.x

### Build environment

Xcode version: 13.2.1
Dependency manager and version: CocoaPods 1.11.2

**Comment by shiami** [comment]
Possible related to https://github.com/realm/realm-swift/issues/7562

**Comment by ericjordanmossman** [comment]
Hi shiami - it does look similar to 7562. The async and the concurrency has presented some issues. But let's keep this issue open too for now, in case it's unrelated.

**Comment by igorvoytovich** [comment]
https://forums.swift.org/t/async-await-crash-on-ios14-with-xcode-13-2-1/54541/81

discussion on this topic

**Comment by dianaafanador3** [comment]
@shiami Can you check if this is still happening on the new Xcode version 13.3. I tested this on my side with iOS version 12.4 on a Simulator and it is not crashing.

**Comment by dianaafanador3** [comment]
Hi @shiami Xcode 13.3 was recently released and I just tested this out on a Simulator iOS 12.4 and seems like is working fine. Can you check on your side and let me know if you are still having issues.
