### ISSUE TITLE
Our App is using Realm. After storing data, the memory cannot be lowered. Is there any way to lower the memory

### ISSUE THREAD

**Issue by liDengHong** [realm/realm-swift#7603]
### How frequently does the bug occur?

All the time

### Description

I wrote a simple demo to verify that memory can't be reduced

> model

```
class TestModel: Object {
    @objc dynamic var text: String = "text"
    @objc dynamic var cid: String = ""
    @objc dynamic var id: String = ""
    @objc dynamic var width: Double = 300
    @objc dynamic var height: Double = 300
    @objc dynamic var totalCount: Int = 300
    @objc dynamic var totalPage: Int = 300
    @objc dynamic var count: Int = 300
    @objc dynamic var offset: Int = 300
    @objc dynamic var date: NSDate = NSDate()
    override static func primaryKey() -> String? {
        return "id"
    }
}
```

> action

```
 func saveData() {
        for index in 0..<10000 {
            autoreleasepool {
                let model = TestModel()
                model.id = "\(index + 130)"
                let realm = try? Realm()
                try? realm?.write({
                    realm?.add(model, update: .all)
                })
            }
        }
    }
```

> Memory comparison before and after using  Realm
![image](https://user-images.githubusercontent.com/16500164/148901520-51eda9cc-7fbe-4fac-ad90-4c393d1a19df.png)
![image](https://user-images.githubusercontent.com/16500164/148901598-e35b6497-d8f8-4d2f-b9ac-11455aa1723f.png)

### Can you reproduce the bug?

Yes, always

### Version

v10.20.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

 iPhone

### Build environment

Xcode version: Version 13.1 
Dependency manager and version:  CocoaPods

**Comment by ericjordanmossman** [comment]
In this loop: 
```
 func saveData() {
        for index in 0..<10000 {
            autoreleasepool {
                let model = TestModel()
                model.id = "\(index + 130)"
                let realm = try? Realm()
                try? realm?.write({
                    realm?.add(model, update: .all)
                })
            }
        }
    }
```

You're starting a write 1000 times. This isn't necessarily an inexpensive action to run. You 'll want to start a single write, then loop within that. ex)
```
realm.write {
         for index in 0..<10000 {
                    realm?.add(model, update: .all)
         }
}
```

**Comment by liDengHong** [comment]
> ```swift
> model
> ```

Hi, thanks for replying to me, but it doesn't reduce memory

**Comment by liDengHong** [comment]
> In this loop:
> 
> ```swift
>  func saveData() {
>         for index in 0..<10000 {
>             autoreleasepool {
>                 let model = TestModel()
>                 model.id = "\(index + 130)"
>                 let realm = try? Realm()
>                 try? realm?.write({
>                     realm?.add(model, update: .all)
>                 })
>             }
>         }
>     }
> ```
> 
> You're starting a write 1000 times. This isn't necessarily an inexpensive action to run. You 'll want to start a single write, then loop within that. ex)
> 
> ```swift
> realm.write {
>          for index in 0..<10000 {
>                     let model = TestModel()
>                     model.id = "\(index + 130)"
>                     realm?.add(model, update: .all)
>          }
> }
> ```

Hi, thanks for replying to me, but it doesn't reduce memory

**Comment by jsflax** [comment]
I think we'd need more info about what else you're doing to help you out. Naturally, using our memory mapped database is going to increase memory usage– what kind of app are you trying to build?

**Comment by liDengHong** [comment]
We use realm for the App Extension. The system allocates very little memory. On iPhone 8, only 53M memory will be allocated.  after initializing realm, the memory will increase by 8~10M

> I think we'd need more info about what else you're doing to help you out. Naturally, using our memory mapped database is going to increase memory usage– what kind of app are you trying to build?

**Comment by jsflax** [comment]
The best recommendations we can give you would be to 1) partition your data in a way that prevents exposing the extension to a large realm and 2) compaction.

**Comment by liDengHong** [comment]
> The best recommendations we can give you would be to 1) partition your data in a way that prevents exposing the extension to a large realm and 2) compaction.

Ok, thank you very much
