### ISSUE TITLE
Decimal128 initializers works differently depending on the input 

### ISSUE THREAD

**Issue by gorkemkarahan** [realm/realm-swift#7608]
### How frequently does the bug occur?

All the time

### Description

We were using double for currencies on our old project and now we have migrated to Decimals.
When we were trying to initialize Decimal128 on the decoder side we saw that the end of the numbers are all zero when the number is big enough. When tested against initializers, only string initializer seems to be working correctly for big numbers.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Value: 1159336.05

`Decimal128(string: "1159336.05") // Result is 1159336.05`

`Decimal128(value: 1159336.05) // Result is 1.15934E6`

`Decimal128(floatLiteral: 1159336.05) // Result is 1.15934E6`

`try container.decodeIfPresent(Decimal128.self, forKey: .amount)  // Result is 1.15934E6`

I was able to track the issue until util::to_string function it receives correct value of "1159336.05" but returns the "1.15934e+06" value whereas the string initializer directly uses data of the string directly and works correctly.

```
template <class T>
std::string to_string(const T& v)
{
    return Printable(v).str();
}
```

### Version

10.21

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 13+

### Build environment

Xcode version: 13.2
Dependency manager and version: Swift Package Manager

**Comment by ericjordanmossman** [comment]
Yeah, this is definitely a bug. Interestingly I got this opposite with strings:
![Screen Shot 2022-01-12 at 12 35 28 PM](https://user-images.githubusercontent.com/25092858/149192798-58f3c046-e376-4847-9301-d9da408e60d2.png)

**Comment by ericjordanmossman** [comment]
I'm having some trouble with the reproduction with the encoder/decoder. Could you share snippet of how the container is encoded?

**Comment by gorkemkarahan** [comment]
Hello @ericjordanmossman I mentioned the encoder issue because I noticed it there and check the initializers. The example code block shows a simple double parsing for the json server data. I will try to mock this up and add an example.

**Comment by gorkemkarahan** [comment]
@ericjordanmossman I tried to create a quick demo 

```
class D128ReproductionTests: XCTestCase {

    override func setUpWithError() throws {
        // Put setup code here. This method is called before the invocation of each test method in the class.
    }

    override func tearDownWithError() throws {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }

    func testInitializers() throws {
        let floatLiteralInit = Decimal128(floatLiteral: 1159336.05)
        let valueInit = Decimal128(value: 1159336.05)
        let stringInit = try! Decimal128(string: "1159336.05")
        XCTAssertEqual(floatLiteralInit, valueInit)
        XCTAssertEqual(floatLiteralInit, stringInit)
        XCTAssertEqual(stringInit, valueInit)
    }

    func testDecoding() throws {
        let string = "{\"amount\": 1159336.05}"
        let data = string.data(using: .utf8)!
        do {
            let value = try JSONDecoder().decode(Account.self, from: data)
            XCTAssertEqual(value.amount, try! Decimal128(string: "1159336.05"))
        } catch (let err) {}
    }

    func testEncoding() throws {
        let string = "{\"amount\": 1159336.05}"
        let account = Account(amount: 1159336.05)
        let acountData = try! JSONEncoder().encode(account)
        XCTAssertEqual(String(data: acountData, encoding: .utf8)!, string)
    }

    class Account: Decodable, Encodable {
        var amount: Decimal128

        enum CodingKeys: String, CodingKey {
            case amount
        }

        required init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.amount =  (try container.decodeIfPresent(Decimal128.self, forKey: .amount) ?? 0)
        }

        init(amount: Decimal128) {
            self.amount = amount
        }
    }
}
```

**Comment by jedelbo** [comment]
Fixed at the core level

**Comment by leemaguire** [comment]
Will be closed via https://github.com/realm/realm-swift/pull/7675
