### ISSUE TITLE
Loss of automatic Codable conformance when using @Persisted property wrapper?

### ISSUE THREAD

**Issue by tfe** [realm/realm-swift#7616]
### How frequently does the bug occur?

All the time

### Description

I was excited to change all of my properties to use the new `@Persisted` property declaration syntax, however when I finished I found Realm objects that were previously encodable are now throwing errors at runtime: "Only unmanaged Realm objects can be encoded using automatic Codable synthesis. You must explicitly define encode(to:) on your model class to support managed Realm objects."

Is the loss of automatic Codable synthesis expected when using the new property wrapper? I feel like I'm missing something because that feels like a big feature to give up to get the new syntax.

If so, that's fine and I'll work around it. I just want to make sure I'm not missing something first.

### Stacktrace & log output

```shell
Swift.EncodingError.invalidValue(RealmSwift.Persisted<Swift.String>(storage: RealmSwift.(unknown context at $10d2a3778).PropertyStorage<Swift.String>.managed(key: 0)), Swift.EncodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "uuid", intValue: nil)], debugDescription: "Only unmanaged Realm objects can be encoded using automatic Codable synthesis. You must explicitly define encode(to:) on your model class to support managed Realm objects.", underlyingError: nil))
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```swift
class MyObject: Object {
  @Persisted var uuid: String
}

// Create and add myObject to Realm, query for it and get a `myResults` object containing it. Then the following line will throw the error from PersistedProperty.swift.

myResults.encode(to: JSONEncoder())
```

### Version

10.21.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS 15.2

### Build environment

Xcode version: 13.2
Dependency manager and version: CocoaPods

**Comment by haroun-hajem** [comment]
I have the same problem and I'm not using any encryption. If that matters.

**Comment by leemaguire** [comment]
Hi @tfe You will need to explicitly declare `encode(to:)` of the use case of converting the results to json. You can use the following example:
```swift
class MyObject: Object, Codable {
   @Persisted var uuid: String

    enum CodingKeys: String, CodingKey {
        case uuid
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
    }
}


let realm = try! Realm()
try! realm.write {
        let obj = MyObject()
        obj.uuid = UUID().uuidString
        realm.add(obj)
}
let myResults = realm.objects(MyObject.self)

let encoder = JSONEncoder()
let jsonString = try! String(data: encoder.encode(myResults), encoding: .utf8)!
```
