### ISSUE TITLE
Decryption fails and Realm crashes after restoring Mac using TimeMachine

### ISSUE THREAD

**Issue by LukasGram** [realm/realm-swift#7618]
### How frequently does the bug occur?

Sometimes

### Description

Some of our users reported that they couldn't access their database anymore after they restored their Mac using a TimeMachine backup. Some other users reported the same problem after transferring their data from their old Mac to a new one using Apple's data migration tool.

The Realm file is encrypted with a key derived using a password the user entered and is not stored in the keychain. The user enters the password each time he wants to unlock the app.

We regularly create encrypted backups for the user using Realm's `writeCopy` method. Users with the issue mentioned above were able to restore such backups. So it seems only the main database file is corrupted.

### Stacktrace & log output

```shell
terminating with uncaught exception of type realm::util::DecryptionFailed: Decryption failed


0x000000010bb0623a realm::util::DecryptionFailed::DecryptionFailed() (in MyApp) + 90
0x000000010baedb8f realm::util::AESCryptor::read(int, long long, char*, unsigned long) (in MyApp) + 527
0x000000010baee77e realm::util::EncryptedFileMapping::refresh_page(unsigned long) (in MyApp) + 110
0x000000010baef13c realm::util::EncryptedFileMapping::read_barrier(void const*, unsigned long, unsigned long (*)(char const*)) (in MyApp) + 124
0x000000010b9b4984 realm::util::do_encryption_read_barrier(void const*, unsigned long, unsigned long (*)(char const*), realm::util::EncryptedFileMapping*) (in MyApp) + 68
0x0000000109fc07f2 realm::Array::init_from_ref(unsigned long) (in MyApp) (array.hpp:194)
0x000000010bab229a realm::Table::get_key_direct(realm::Allocator&, unsigned long) (in MyApp) + 90
0x000000010b9bc7bc realm::Group::key2ndx_checked(realm::TableKey) const (in MyApp) + 172
0x000000010bab08ef realm::Table::get_opposite_table(realm::ColKey) const (in MyApp) + 95
0x000000010babd8a9 realm::Table::get_link_target(realm::ColKey) (in MyApp) + 9
0x000000010bbb465a realm::ObjectSchema::ObjectSchema(realm::Group const&, realm::StringData, realm::TableKey) (in MyApp) + 1146
0x000000010bbbe55b realm::ObjectStore::schema_from_group(realm::Group const&) (in MyApp) + 123
0x000000010bc23e4b realm::Realm::read_schema_from_group_if_needed() (in MyApp) + 187
0x000000010bc23bfc realm::Realm::Realm(realm::Realm::Config, realm::util::Optional<realm::VersionID>, std::__1::shared_ptr<realm::_impl::RealmCoordinator>, realm::Realm::MakeSharedTag) (in MyApp) + 428
0x000000010bc48289 realm::Realm::make_shared_realm(realm::Realm::Config, realm::util::Optional<realm::VersionID>, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) (in MyApp) + 201
0x000000010bc4742a realm::_impl::RealmCoordinator::do_get_realm(realm::Realm::Config, std::__1::shared_ptr<realm::Realm>&, realm::util::Optional<realm::VersionID>, realm::util::CheckedUniqueLock&) (in MyApp) + 522
0x000000010bc47079 realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config, realm::util::Optional<realm::VersionID>) (in MyApp) + 489
0x000000010bc24697 realm::Realm::get_shared_realm(realm::Realm::Config) (in MyApp) + 135
0x000000010a0e46a7 +[RLMRealm realmWithConfiguration:queue:error:] (in MyApp) (RLMRealm.mm:476)
0x000000010a1686d1 Realm.__allocating_init(configuration:queue:) (in MyApp) (Realm.swift:92)
```

### Can you reproduce the bug?

Not yet

### Version

10.16.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

macOS

### Build environment

Xcode version: Xcode 13.2
Dependency manager and version: CocoaPods 1.11.2

**Comment by leemaguire** [comment]
Hi @LukasGram could you tell us what version of Realm created the main database before it was restored from Time Machine? cc @finnschiermer

**Comment by LukasGram** [comment]
@leemaguire Since we are using Realm several years now and had several updates during that time there is no way to find out which version was used to create the database unfortunately.

**Comment by leemaguire** [comment]
@LukasGram would you be able to send us the Realm file to realm-help@mongodb.com so we can help diagnose the issue?

**Comment by LukasGram** [comment]
@leemaguire unfortunately we don't have access to any Realm file with the mentioned issue. We only see the crash logs users sent to use when the described their problem.

**Comment by tgoyne** [comment]
Is it possible that the crashes are all when migrating from Intel macs to apple silicon macs? We've had portability issues with encrypted Realm files before so possibly the files aren't portable between the architectures. Similarly, is it possible that the key derived from the user's password is accidentally dependent on macOS version or architecture?

The other major possibility is that this is pointing at a crash-safety bug in encrypted Realms which time machine is incidentally exposing. The data on disk is supposed to always be in a valid state so that if you get a kernel panic or power failure at any point in the writing process no data is lost other than possibly the data you were in the process of writing. If encrypted Realms are failing to guarantee that, then time machine might be happening to back up a file while it's in an intermediate invalid state. This would explain why files produced by writeCopy() work correctly, as those are written in one shot rather than being a file that's incrementally updated.

**Comment by LukasGram** [comment]
> Is it possible that the crashes are all when migrating from Intel macs to apple silicon Macs?
Many users who reported the issue were indeed migrating to Apple Silicon Macs. However according to our crash logs it also occurs on Intel Macs which contradicts the assumption. But none of those users reached out to our support. So I'm not sure if those crashes are caused by the backup/migration issue as well.

> Similarly, is it possible that the key derived from the user's password is accidentally dependent on macOS version or architecture?
Since we have an iOS app as well we would run into problems if using the same data on an iOS device. As we have no reports about this we can rule that out. Also I double checked the code and didn't find any dependencies.

**Comment by dianaafanador3** [comment]
Hi @LukasGram just checking if you have any update about this. Are you still getting decryption crashes reports from users restoring with TimeMachine, given your last comment we can start to discard some possible causes, but it will be helpful if we ask this users if they had some issues during the restoring or with the database before the restoring.

**Comment by leemaguire** [comment]
@LukasGram do you have any updates on this?

**Comment by LukasGram** [comment]
@leemaguire sry for the late answer. The crashes still show up in our crash logs. Unfortunately no user reached out to our support lately about that. So I have no further information on this.

**Comment by dianaafanador3** [comment]
Hi @LukasGram just checking again if you have any update about this. Are you still getting decryption crashes from users restoring with TimeMachine. We continuously release fixes with each version of our SDK, please update to our latest version and get back to us if you are still getting this issue.
