### ISSUE TITLE
Realm Swift version not updating above 4.4.0 when update pods. I checked on github its 10.21.0. 

### ISSUE THREAD

**Issue by shirishbankar1** [realm/realm-swift#7619]
### How frequently does the bug occur?

All the time

### Description

I am trying to update RealM swift pod version to latest. But it wont update above 4.4.0. I havent mentioned any version in pod file. But it still show installing RealMSwift 4.4.0. As I saw on github RealMSwift releases 10.21.0 is latest (ref : https://github.com/realm/realm-swift/releases/tag/v10.21.1 ). 
I am I referring wrong release version or any other issue ?
Below is line which I add in pod file to install latest pod. 
pod 'RealmSwift'

### Can you reproduce the bug?

Yes, always

### Version

4.4.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOs Big sur 11.5.2

### Build environment

Xcode version: 13.2
Dependency manager and version: Cocoapods  1.11.2

**Comment by leemaguire** [comment]
you need to do `pod repo update`.

**Comment by shirishbankar1** [comment]
In iOS pod file if we dont specify the version then it should take the latest by default. Still I have already tried what you said. mentioning 1.21.1. It didnt work. It gave error no such version available, while pod install and pod update.

**Comment by leemaguire** [comment]
You need to update your local repo of pods for it to know there is a new version available. For that do `pod repo update` and then `pod update / pod install`

**Comment by shirishbankar1** [comment]
Thanks, did following steps and worked :

1) pod repo update
2) pod install
3) pod update
