### ISSUE TITLE
Include dSYMs in prebuilt binaries for release zips

### ISSUE THREAD

**Issue by sarpsolakoglu** [realm/realm-swift#7620]
### Problem

The dSYMs are not included in the release xcframeworks, I've ran the `build.sh` to generate the xcframeworks myself as well and this also results in no dSYMs in the xcframeworks.

### Solution

Update the `build.sh` script to also include `dSYMs` in the created `xcframeworks`.

### How important is this improvement for you?

Would be a major improvement

**Comment by dianaafanador3** [comment]
Hi @sarpsolakoglu dSYMs are intended for debit purposes and we are not planning to add them to our release, you can build them yourself replacing the following lines
```
        find build/DerivedData/Realm/Build/Products -name 'Realm.framework' \
            | grep -v '\-static' \
            | sed 's/.*/-framework &/' \
            | xargs xcodebuild -create-xcframework -allow-internal-distribution -output build/Realm.xcframework
        find build/DerivedData/Realm/Build/Products -name 'RealmSwift.framework' \
            | sed 's/.*/-framework &/' \
            | xargs xcodebuild -create-xcframework -allow-internal-distribution -output build/RealmSwift.xcframework
```
with this (remember to replace your current path
       ```
 find build/DerivedData/Realm/Build/Products -name 'Realm.framework' \
            | grep -v '\-static' \
            | sed 's|.*|-framework & -debug-symbols <current-path>/&.dSYM|' \
            | xargs xcodebuild -create-xcframework -allow-internal-distribution -output build/Realm.xcframework
        find build/DerivedData/Realm/Build/Products -name 'RealmSwift.framework' \
            | sed 's|.*|-framework & -debug-symbols <current-path>/&.dSYM|' \
            | xargs xcodebuild -create-xcframework -allow-internal-distribution -output build/RealmSwift.xcframework
```

**Comment by hisaac** [comment]
Would it be reasonable to add a `--include-dsyms` flag to this script for those of us that need them? I'd be willing to do the work of adding the flag to `build.sh` if there's a chance it would be accepted.
