### ISSUE TITLE
Does @ObservedResults async-open Realm?

### ISSUE THREAD

**Issue by ksiwei** [realm/realm-swift#7622]
### How frequently does the bug occur?

Sometimes

### Description

During the initial sync after user logins, the app sometimes crashes after 10~20 seconds due to `terminating with uncaught exception of type realm::AddressSpaceExhausted: mmap() failed: Cannot allocate memory size: 26279936 offset: 134217728`

I removed all the occurrences of realm() that are opened synchronously after seeing this issue: https://github.com/realm/realm-swift/issues/7040 3 but still couldn’t avoid it.

I use @ObservableResults in many places, I wonder if they are causing the crash.

### Can you reproduce the bug?

Yes, sometimes

### Version

10.16.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS14

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by leemaguire** [comment]
Hi @ksiwei. `@ObservedResults` does not open the Realm asynchronously. How much storage is available on the test device you are using? Could you also post some code showing how you are using Realm?

**Comment by pavel-ship-it** [comment]
Hi @ksiwei 
Is it possible to run the app with Instruments utility to see how many memory takes the app for the images?
Depending on what and how the app does to image data it could explain the lack of free space. Let's say image file will take only several MBytes as NSData but the same image can take tenths of MBytes as UIImage. The solution can be to sync the images one by one and/or to check the free space before opening next photo. Any way you can get more info from Instruments Allocations tool.

**Comment by leemaguire** [comment]
@ksiwei the memory bloating you are encountering looks related to the use of writes inside the for loops. I would suggest:

```swift
        let fifteenMB = 15 * 1024 * 1024
        let imageChunks = images.chunked(into: 5)
try ! realm.write {
        for chunk in imageChunks {
            let totalBytesForImages = chunk.reduce(0) { acc, p in
                return acc + (p.imageData?.count ?? 0)
            }
            if totalBytesForImages < fifteenMB {
                    realm.add(chunk)
            } else {
                for image in imageChunk {
                     realm.add(image)
                }
            }
        }
}
```
