### ISSUE TITLE
One of Realm's best Swift talks has been set to "private"

### ISSUE THREAD

**Issue by cellularmitosis** [realm/realm-swift#7627]
### How frequently does the bug occur?

All the time

### Description

Realm hosted a fantastic talk by Andy Matuschak about how to leverage the power of Swift's value types to write better code: https://academy.realm.io/posts/andy-matuschak-controlling-complexity/

Unfortunately, that youtube video has been marked "private" and is no longer viewable.

I've tried reaching out via other channels and this is my last resort.  Is there any hope that this video can be restored?  Help me Obi Wan, you're my only hope! 🙏

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Open https://academy.realm.io/posts/andy-matuschak-controlling-complexity/ in a web browser.

### Version

All

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

All

### Build environment

Any web browser.

**Comment by cellularmitosis** [comment]
![Screen Shot 2022-01-22 at 4 06 13 PM](https://user-images.githubusercontent.com/223396/150656965-16e570d4-a176-46f8-ba36-42d50294c366.png)

**Comment by pavel-ship-it** [comment]
Hi @cellularmitosis ,
Sorry for inconvenience. At the moment we're moving the older Realm Academy posts/videos to a new home.
I'll try to find a solution.

**Comment by pavel-ship-it** [comment]
Hi @cellularmitosis, sorry to say that, I cannot get the video. Maybe you can reach Andy Matuschak, the author of this talk, ask for copy?

**Comment by pepas-everly** [comment]
Hi, I just wanted to ping about this issue again.  Can you get in touch with however manages the YouTube account and set this video back to "public"?  The video is still there, it just needs to be configured correctly.  Thanks!
