### ISSUE TITLE
Random crashes with encrypted realm.

### ISSUE THREAD

**Issue by TheHmmka** [realm/realm-swift#7629]
### How frequently does the bug occur?

All the time

### Description

Application constantly crashes in random transactions.

### Stacktrace & log output

```shell
uncaught exception in notifier thread: N5realm5_impl17TransactLogParser14BadTransactLogE: Bad transaction log
2022-01-24 18:16:38.391094+0300 Walken[15692:3232033] uncaught exception in notifier thread: N5realm5_impl17TransactLogParser14BadTransactLogE: Bad transaction log
libc++abi: terminating with uncaught exception of type realm::_impl::TransactLogParser::BadTransactLog: Bad transaction log
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
terminating with uncaught exception of type realm::_impl::TransactLogParser::BadTransactLog: Bad transaction log
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

-

### Version

10.21.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS 15

### Build environment

Xcode version: 13.2.1
Dependency manager and version: CocoaPods 1.11.2

**Comment by TheHmmka** [comment]
I found next description in the Doc, may be it's a reason:
```
If multiple processes need to access a realm simultaneously, use an unencrypted realm. Encrypted realms cannot be accessed by multiple processes at the same time.
As an alternative, you can store data that you want to encrypt as NSData properties on realm objects. Then, you can encrypt and decrypt individual fields.
```

**Comment by dianaafanador3** [comment]
Hi @TheHmmka I see you can reproduce the issue, maybe you can share a repo or a code snippet so we can reproduce it in our side.
The warning on our documentation refers to trying to access a shared realm from different processes, for example a realm stored on a shared group which is used by different apps at the same time?, if this the case that may be the cause of the crash.

**Comment by TheHmmka** [comment]
> Hi @TheHmmka I see you can reproduce the issue, maybe you can share a repo or a code snippet so we can reproduce it in our side.
> The warning on our documentation refers to trying to access a shared realm from different processes, for example a realm stored on a shared group which is used by different apps at the same time?, if this the case that may be the cause of the crash.

Nope, this is not my case.

Sorry, I can't share production code. I'll try to create demo project and catch this issue.

**Comment by tfe** [comment]
I've started getting these too, possibly concurrently with starting to use Realm Notifications, or starting to use async/await, all of which happened around the same time.

I am not accessing the Realm from different processes in my case.

**Comment by dianaafanador3** [comment]
HI @tfe would you mind sharing your stack trace and/or the code where you het the crash, with a little more info we may be able to reproduce the issue.

**Comment by tfe** [comment]
@dianaafanador3 I haven't seen it do it in development... all I have is the exception report via Sentry, and it doesn't give very much (unless I'm not looking in the right place?):

```
libsystem_kernel    0x1b8efab2c  __workq_kernreturn
libsystem_pthread   0x1f25fe13c  _pthread_wqthread
```

However from their breadcrumbs I can see that it's likely happening during the same operation I mentioned and shared code for over in #7641. It makes sense that that operation would surface issues since it's the most extensive exercise the database receives in the lifecycle of this app.

**Comment by sainttail** [comment]
@TheHmmka Got this error when upgrading from realm 10.20.0 to 10.21.1 on iOS 15 both simulator and real device.

Have you try going back to use 10.20.2? 
It does not crash for me.

**Comment by TheHmmka** [comment]
> @TheHmmka Got this error when upgrading from realm 10.20.0 to 10.21.1 on iOS 15 both simulator and real device.
> 
> Have you try going back to use 10.20.2? It does not crash for me.

I'll try, thank you!

**Comment by Saul-Liang** [comment]
We're also seeing this crash on 10.22.0. Downgrading to 10.20.2 seems to fix the issue for us - thanks @sainttail 🙏

**Comment by bfichter** [comment]
We're also experiencing this sporadically after upgrading to 10.21.1 with encryption enabled.

**Comment by leemaguire** [comment]
@bfichter @Saul-Liang  can you attach any stack traces?

**Comment by dianaafanador3** [comment]
This issue may be related to this https://github.com/realm/realm-core/issues/5174

**Comment by driq** [comment]
This crash looks indeed identical to https://github.com/realm/realm-js/issues/4428

**Comment by driq** [comment]
Realm-core was upgraded from `11.6.1` to `11.8.0` in Realm-swift `v10.21.1`.  Realm-swift `v10.21.0` contains Realm-core `11.6.1`.

If the issue was introduced by a regression in Realm core 11.7 or 11.8, this would mean that downgrading Realm-swift to `v10.21.0` should fix it. Perhaps that's worth a shot?

PS. I would not expect such relatively major changes in patch releases, especially considering that Realm core 11.8.0 contains breaking changes according to it's own changelog. Is there any reason not to adhere to [semver](https://semver.org/)?

**Comment by finnschiermer** [comment]
Although these reports mention encryption, there are no relevant changes to the encryption machinery in the versions mentioned.

**Comment by TheHmmka** [comment]
Now encryption works as expected.
