### ISSUE TITLE
Make Realm object sendable

### ISSUE THREAD

**Issue by underthestars-zhy** [realm/realm-swift#7642]
### How frequently does the bug occur?

All the time

### Description

Xcode13.3 beta need realm object conform `Sendable`.

### Can you reproduce the bug?

Yes, always

### Version

10.20.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.4

### Build environment

Xcode version: 13.3
Dependency manager and version: 10.20.2

**Comment by dianaafanador3** [comment]
Hi @underthestars-zhy you might be interested in checking our new feature (from v10.17.0) `[@ThreadSafe](https://docs.mongodb.com/realm/sdk/swift/advanced-guides/threading/#use-the--threadsafe-wrapper)` wrapper which allow you to pass thread-confined instances to another thread and it is `Sendable`.

**Comment by jsflax** [comment]
The reason being, our Objects cannot cross thread boundaries, so by definition they aren't sendable. Marking an object @ThreadSafe like Diana mentioned will make them so, however.

**Comment by underthestars-zhy** [comment]
However, In the xcode13.3 I need to add a extension like this `extension RealmSwift.Realm: @unchecked Sendable {}` Otherwise, `try await Realm()` warns.

**Comment by underthestars-zhy** [comment]
I cannot use `@ThreadSafe ` on `try await Realm()`

**Comment by dianaafanador3** [comment]
Hi you cannot use `@ThreadSafe` with Realm you can use it on an instance of an Object, for example
```
let realm = try await Realm()
let results = realm.objects(Card.self)
@ThreadSafe var threadSafeObject = results.first
```
This `threadSafeObject` instance can be passed and used on a different thread.

**Comment by underthestars-zhy** [comment]
How ever, if you run this code (`let realm = try await Realm()`) in Xcode 13.3 beta, it will warn you, like: Realm is not Sendable, Realm.config... is not Sendable, etc

**Comment by dianaafanador3** [comment]
HI @underthestars-zhy you get this warning because we use [@MainActor](https://developer.apple.com/documentation/swift/mainactor) annotation in our Realm `async await` constructor.
You add this annotation to your function to force running it on the main thread and remove the warning-
```
@MainActor
func test() async throws {
        let realm = try await Realm()
        let results = realm.objects(Card.self)
        @ThreadSafe var swiftStringObject = results.first
}
```
If you are using Realm only as a local database I would recommend to use `let realm = try Realm()`, which will execute synchronously same as `await Realm()` for local databases, and will not force you to run this on the main thread.

**Comment by tgoyne** [comment]
Yes, frozen objects are conceptually Sendable but we can't mark them as such because they're not a distinct type, so that's an appropriate use of `@unchecked Sendable`.
