### ISSUE TITLE
Error in linking phase when using Realm as SPM dependency for sub-target

### ISSUE THREAD

**Issue by aleyooop** [realm/realm-swift#7645]
### How frequently does the bug occur?

All the time

### Description

Actual result:
1. Try to archive project with a sub-target that has realm-cocoa as SPM dependency.
2. Get errors as described here ([#7526](https://github.com/realm/realm-cocoa/issues/7526))
3. Apply proposed fix to realm-core
4. Receive another linking error

Expected result:
Archive process succeeds

### Stacktrace & log output

```shell
Undefined symbols for architecture arm64
Symbol: realm::ObjKey realm::Table::find_first<realm::StringData>(realm::ColKey, realm::StringData) const
Referenced from: realm::ObjKey realm::Object::get_for_primary_key_in_migration<objc_object* __strong, RLMAccessorContext>(RLMAccessorContext&, realm::Table const&, realm::Property const&, objc_object* __strong&&) in RLMAccessor.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

In description

### Version

v10.22.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Any iOS Device (arm64)

### Build environment

Xcode version: 13.2
Dependency manager and version: SPM

**Comment by pavel-ship-it** [comment]
@aleyooop I try to reproduce it locally without any luck.
Can you share some details on what library you are using in your project?
Could you try to clear derived data and/or reset package cache?

**Comment by aleyooop** [comment]
@pavel-ship-it This can be easily reproduced with the same reference project in this related issue ([#7526](https://github.com/realm/realm-swift/issues/7526))

1. Build project and get issue with Security framework
2. Change Realm swift package dependency with fork+applied fixes -> Build fixed
3. Try to archive

Derived data cleaning and/or resetting package cache aren't helping.

**Comment by vladyslavpopovych** [comment]
Same issue with missing symbols

**Comment by dianaafanador3** [comment]
It seems like linking a sub-dependency is not possible with the current configuration of the Sample project provided. You need to add them as Package.swift modules so it links correctly any sub-dependency (In this case is RealmCore).
I updated the [Sample project](https://github.com/dianaafanador3/RealmModulesProjectsPlaygorunds/tree/master) which I used to test archiving the App, and it is working.
The missing Security framework should be fixed by this [PR](https://github.com/realm/realm-core/pull/5254).
Let me know if you have any question.

**Comment by emrekarasahin** [comment]
Hi, 

Same issues here.

I have some internal framework which is dependent to Realm. I added Realm and RealmSwift from SPM. No issues on building but have an error on archive side.

Undefined symbols for architecture arm64:
  "realm::ObjKey realm::Table::find_first<realm::StringData>(realm::ColKey, realm::StringData) const", referenced from:
      realm::ObjKey realm::Object::get_for_primary_key_in_migration<objc_object* __strong, RLMAccessorContext>(RLMAccessorContext&, realm::Table const&, realm::Property const&, objc_object* __strong&&) in RLMAccessor.o
ld: symbol(s) not found for architecture arm64

**Comment by nojoDOTse** [comment]
Hello, we are also having the same issue.

@emrekarasahin You can apply the changes found in [PR5204](https://github.com/realm/realm-core/pull/5204/files#diff-e752b38a6d72eb50c7ab147fe48749dee382b2c4153c01364db035c2843f1519) in realm-core to ```SourcePackages/checkouts/realm-core/src/realm/table.cpp``` (located in your DerivedData folder for your project) as a work around until that PR is merged.

**Comment by igrechuhin** [comment]
Hello, is there any update in this?

**Comment by RustamKhisamov** [comment]
Any suggestions?
