### ISSUE TITLE
SwiftUI / TextField - Typing too fast with an ObservedRealmObject bound value causes memory leak

### ISSUE THREAD

**Issue by briannadoubt** [realm/realm-swift#7655]
#### Expected results
Type text into a `SwiftUI.TextField` very quickly and move on with my day 🤪

#### Actual Results
A memory leak and frozen UI

#### Steps & Code to Reproduce
1. Clone project at https://github.com/briannadoubt/Tofu
2. Build and run app with a debug session
3. Focus cursor on any text field (they are all bound to their own @ObservedRealmObject key value)
4. Observe that typing at a semi reasonable rate will not produce a memory leak and frozen UI
5. Type very fast (mash the keyboard)
6. Observe that the UI is frozen and the 'Memory' section of the debug session is leaking

#### Core version
Core version: 11.9.0

**Comment by 6eyu** [comment]
same here, when the app becomes complex,  and TextField is trying to edit a property of `@ObservedRealmObject` fast, it will throw the error of `Binding<String> action tried to update multiple times per frame.` and crash the app.

**Comment by aehlke** [comment]
Any workarounds discovered? This is a scary open issue to see walking into the project!

**Comment by wipnick** [comment]
@aehlke my current workaround is using a temporary binding and saving to realm only on submit. I implemented something like this to use the convenience of realm auto-write with swiftUI:
```
class Person: Object {
    @Persisted var firstName: String
    @Persisted var lastName: String
}
```

```
struct TestView: View {
    
    @ObservedRealmObject var person: Person
    
    var body: some View {
        TextFieldRealm(title: title, text: $person.firstName)
        TextFieldRealm(title: title, text: $person.lastName)
    }
}
```

```
struct TextFieldRealm: View {
    var title: String
    @Binding var text: String
    @State private var tempText: String = ""

    var body: some View {
        TextField(title, text: $tempText, onEditingChanged: { editing in
            if !editing {
                $text.wrappedValue = tempText
            }
        })
        .onAppear {
            tempText = text
        }
    }
}
```

**Comment by briannadoubt** [comment]
Is it possible to implement some form of debouncing into the setter of the ObservedRealmObject [here](https://github.com/realm/realm-swift/blob/df3eda1cbd32844a9a444bfd948ed52336b47d2b/RealmSwift/SwiftUI.swift#L1041)?

**Comment by aehlke** [comment]
I'm now using https://github.com/Tunous/DebouncedOnChange
