### ISSUE TITLE
EXC_BREAKPOINT at _Persistable._rlmGetProperty(_:_:)

### ISSUE THREAD

**Issue by juanj** [realm/realm-swift#7664]
### How frequently does the bug occur?

Sometimes

### Description

I have updated from version 10.7.2 to 10.22.0 and migrate the models to use the new `@Persisted` property wrapper syntax.

After pushing the update to production, I started seeing a bunch of crashed that point to `_Persistable._rlmGetProperty(_:_:)`.
I'm unable to reproduce it, but it appears to happen pretty frequently.

### Stacktrace & log output

```shell
Crashed: DataSource
0  RealmSwift                     0xcf48 protocol witness for static _Persistable._rlmGetProperty(_:_:) in conformance Int32 + 40 (<compiler-generated>:40)
1  RealmSwift                     0x56150 Persisted.get(_:) + 182 (PersistedProperty.swift:182)
2  RealmSwift                     0x55e98 static Persisted.subscript.getter + 126 (PersistedProperty.swift:126)
```

### Can you reproduce the bug?

Not yet

### Version

10.22.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.3.0, iOS 15.3.1

### Build environment

Xcode version: Version 13.1 (13A1030d)
Dependency manager and version: Cocoapods 1.10.1

**Comment by ericjordanmossman** [comment]
@juanj 
Can you provide more context and logs? Or a reproduction project?
Right now I don't think there's a enough information to diagnose the problem.

**Comment by ericjordanmossman** [comment]
Thanks. Looks like this'll need to be investigated some more.

**Comment by juanj** [comment]
Some more info I can add:
1. It doesn't seem to be Related with Realm migrating the db file. The app keeps crashing with a fresh install.
2. Almost all of the changes to Realm are done using `dynamicCreate`.

**Comment by juanj** [comment]
I found the cause of the crash.
`Fatal error: Not enough bits to represent the passed value`

This was happening when accessing an object that was created with `dynamicCreate` and one of the int properties didn't fit inside the property type.

This error is totally on my side, but just wanted to point out that the way Realm handled it changed. Before updating, instead of crashing it returned a value. I'm not sure how this value was calculated, but it returned a value.
Before updating, accessing `3551372657` as an Int32 returned `-743594639`
