### ISSUE TITLE
dyld: Library not loaded: /usr/lib/swift/libswiftCore.dylib

### ISSUE THREAD

**Issue by qibaozhen** [realm/realm-swift#7665]
### How frequently does the bug occur?

All the time

### Description

我从xcode13升级到xcode13.2.1之后，realm 也升级到10.22.0 ，运行在iOS12系统上会crash

dyld: Library not loaded: /usr/lib/swift/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/FBB8FCFA-xxx-xx-xxx-4B1D040443D6/xxxx.app/Frameworks/libswift_Concurrency.dylib
  Reason: image not found
(lldb) 

### Can you reproduce the bug?

Yes, always

### Version

10.22.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS12

### Build environment

xcode 13.2.1

**Comment by dianaafanador3** [comment]
Hi @qibaozhen which dependency manager are you using to import Realm?

**Comment by tgoyne** [comment]
Xcode 13.2 has a bug in the concurrency back-deployment that makes it not support iOS 12. You need to use 13.1 or 13.3.
