### ISSUE TITLE
Encrypted Interprocess sharing is unsupported error on app launch

### ISSUE THREAD

**Issue by natalia-osa** [realm/realm-swift#7668]
### How frequently does the bug occur?

All the time

### Description

I receive an error on app launch saying:

> A database initialization failed: Error Domain=io.realm Code=1 "/Users/.../Library/Developer/CoreSimulator/Devices/.../Documents/deafult.realm:: Encrypted interprocess sharing is currently unsupported. DB has been opened by pid: 70682. Current pid is 94960.

I migrated from Realm 5.x to 10.x last week. Was able to reproduce this issue just on this one simulator, on other devices it's working correctly and I can't make this error appear. However, it doesn't look like it's connected with the fact it's a simulator not device, so I'd prefer to fix it before shipping to the clients. We've been using Realm for 3+ years and I've never earlier seen this error.

I listed all of the PIDs via running `xcrun simctl spawn booted launchctl print system`. 
Process of my app is properly listed there:
`94960      - 	UIKitApplication:com.mycompany.myapp.myscheme[e097][rb-legacy]`
However there is **no process with pid 70682**. What's worth to note, is that if I select in the simulator `Device->Restart` Realm still claims PID 70682 is using it. What is more, I killed all background apps (including mine) and when I relaunch app, I can still see the same error. My app doesn't have any notification widget or other running instances and is run only once in full screen.

BTW: I think it may be connected with: https://github.com/realm/realm-java/issues/1477#issuecomment-989990828

### Can you reproduce the bug?

Yes, always

### Version

Realm 10.22.0, RealmCore 11.9.0 (Installed via SPM)

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS 15.2

### Build environment

```
ProductName:	macOS
ProductVersion:	12.2
BuildVersion:	21D49

/Applications/Xcode.app/Contents/Developer
Xcode 13.2.1
Build version 13C100

/usr/local/bin/pod
1.11.2
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

/opt/homebrew/bin/carthage
0.38.0
(not in use here)

/usr/bin/git
git version 2.32.0 (Apple Git-132)
```

**Comment by dianaafanador3** [comment]
This error indicates that the current database session was initiated by other process and then you are trying to open the same database with other process, which is not allowed with an encryption enabled database. 
Are you storing your database in a shared group?
If this only happened once with a particular simulator, this may be an issue with a corrupted pid on your simulator or pid changes on a simulator session, or a hanging process in your computer.
This should not be an issue on production.

**Comment by natalia-osa** [comment]
@dianaafanador3 Thanks for your reply, that's what I expected. I do not have any shared group. I'm 100% certain no other instance of my apps is using (nor even have access) to this database. The app is full-screen, and you cannot run 2 instances of this app at the same time. So nothing else could have access to the database.

As for now, it happened once in a particular simulator. However, it's been only a week since the migration and the app wasn't run so often in the meantime, so it's hard to say how often will this happen.

Is it popular to happen on simulators..? Maybe a problem is M1 Rosetta simulator..? I've never faced this issue. In this case, I'll ignore this case and test on the devices. If the issue reappears on any device, I will reopen the thread. As for now, we can close it.
