### ISSUE TITLE
NavigationLink create a duplicated realm object

### ISSUE THREAD

**Issue by 6eyu** [realm/realm-swift#7671]
### How frequently does the bug occur?

All the time

### Description

Hi, I am testing [the example code](https://docs.mongodb.com/realm/sdk/swift/swiftui/#authenticate-users-with-mongodb-realm). I found that after adding a new item, it creates 2 objects in memory
<img width="589" alt="Screen Shot 2022-02-21 at 4 48 40 pm" src="https://user-images.githubusercontent.com/46993604/154896735-e7e49909-774e-4eff-8345-7f5652e5caca.png">
and it only happens when using  `NavigationLink`.

I have tested the `NavigationLink` with `@StateObject` and `@ObservedObject`, the issue doesn't appear.

 

### Can you reproduce the bug?

Yes, always

### Version

10.22.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.2

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by leemaguire** [comment]
@6eyu I cannot reproduce the issue with the sample code. Can you please send us a sample project that reproduces the issue.

**Comment by 6eyu** [comment]
@leemaguire https://docs.mongodb.com/realm/sdk/swift/swiftui/#without-sync
exactly the same as the sample code.

It wouldn't cause any error (I will close this issue), 
but I am wondering why after adding a new item to the list, the app memory (enable debug memory graph in XCode) has 2 objects.

see the picture below, there are 2 items in the list, but the memory graph shows 4 objects.
<img width="603" alt="Screen Shot 2022-02-21 at 9 50 33 pm" src="https://user-images.githubusercontent.com/46993604/154940863-10e90f5b-d421-46ae-9fe0-0b48a0c0a8a9.png">

**Comment by leemaguire** [comment]
It looks like the accompanying allocation is specific to the internals of SwiftUI. Realm is not creating duplicate heap or stack allocations.
