### ISSUE TITLE
filter("'some const string' contains field")

### ISSUE THREAD

**Issue by free-znet** [realm/realm-swift#7676]
### Problem

When I query from this 
```
filter("'some const string' contains field")
```
realm throws an exception:
```
Operator 'CONTAINS' requires a keypath on the left side.
```

### Solution

My model value is:
```
model 1:
id = 1
value = 'test'

model 2:
id = 2
value = 'text'
```

I have a string.

if string is `this is text string`, I want found model 2.
if string is `this is test string`, I want found model 1.

when I use `filter("'some const string' contains field")`, it not work.

Such my need is not common. So I can't found solution from document and google.

**Comment by pavel-ship-it** [comment]
This error message just informs you should place a field name on the left part of query.
Let's say you define your model like this:
```
    class TextObject: Object {
        @Persisted(primaryKey: true) public var _id: ObjectId = ObjectId.generate()
        @Persisted public var storedText: String
    }
```
Then you can query like that:
```
    let realm = try! Realm()
    try! realm.write {
        realm.create(TextObject.self, value: [ObjectId.generate(), "this is matching text string"])
        realm.create(TextObject.self, value: [ObjectId.generate(), "this is not matching text string"])
    }
    let texts = realm.objects(TextObject.self).filter("storedText contains 'is matching'")
```
`texts` will contain first object.

**Comment by free-znet** [comment]
@pavel-ship-it Hi, I just want filter `'const string'` contains`field`.

if use sql it maybe like this:
sqlite3: `SELECT * FROM table where 'const string' GLOB field`
mysql: `SELECT * FROM table where instr('const string', field) > 0`

Does realm have a similar function?

**Comment by pavel-ship-it** [comment]
@free-znet, yes, you can achieve this behaviour with Realm. Please refer the documentation on filtering - https://docs.mongodb.com/realm/sdk/swift/examples/filter-data/#std-label-ios-filter-data

In the example above
```
    let texts = realm.objects(TextObject.self).filter("storedText contains 'is matching'")
```
`realm` - data base
`TextObject` - table name
`storedText` - field name
`'is matching'` - search string

**Comment by free-znet** [comment]
@pavel-ship-it 
`realm` - data base
`TextObject` - table name
`storedText` - field name (value is string: `'is matching'`)
`'this is matching string'` - will be search

then:
`let texts = realm.objects(TextObject.self).filter("storedText contains 'this is matching string'")`

can't get the object which value is `is matching`.

I want to filter which `'const string'` contains field(`storedText`).

not field(`storedText`) contains `'const string'`.

**Comment by pavel-ship-it** [comment]
You can try [Realm Swift query API](https://docs.mongodb.com/realm-sdks/swift/latest/Structs/Query.html)
