### ISSUE TITLE
Slow loading times when navigating views

### ISSUE THREAD

**Issue by davidkessler-ch** [realm/realm-swift#7679]
### How frequently does the bug occur?

All the time

### Description

When trying to navigate between views in SwiftUI the view freezes if there is an realm being passed:
```swift
.environment(\.realmConfiguration, app.currentUser!.configuration(partitionValue: "example")) 
```
The more elements received in
```swift
@ObservedResults(Example.self) var = examples
```
the longer until it then slides to the actual child view (already a few full seconds for more than 20 elements). There are also other things where the app lags for some time. Looking at the console output, that mostly occurs when there is a Disconnection and Reconnection for no apparent reason:
```
2022-02-27 18:23:00.413438+0100 RChat[10194:2895762] Sync: Connection[3]: Disconnected
2022-02-27 18:23:01.012754+0100 RChat[10194:2895762] Sync: Connection[4]: Session[4]: client_reset_config = false, Realm exists = true, client reset = false
2022-02-27 18:23:01.039700+0100 RChat[10194:2895762] Sync: Connected to endpoint 'xxxxx:443' (from 'xxxxx:49665')
```

A similar issue is described in [this post on the community forum](https://www.mongodb.com/community/forums/t/swiftui-slow-loading-views/147346/8).

Leaving the code exactly the same but rolling back to the RealmSwift version 10.21.0 solves the issue and makes the navigation instantaneous again.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Using
```swift
.environment(\.realmConfiguration, app.currentUser!.configuration(partitionValue: "example")) 
```
with
```swift
@ObservedResults(Example.self) var = examples
```

### Version

starting from 10.21.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

ios 14.0 and above

### Build environment

Xcode version: 12.5
Dependency manager and version: SPM SwiftRealm version 10.21.1

**Comment by pavel-ship-it** [comment]
We are working on fix for this issue. You can follow up [here](https://github.com/realm/realm-swift/pull/7667)

I'll close this ticket as a duplicate.

**Comment by ismyhc** [comment]
@pavel-ship-it did this performance issue fix ever get pushed into a release?

**Comment by pavel-ship-it** [comment]
Hi @ismyhc, better ask someone else.
@leemaguire , @dianaafanador3
