### ISSUE TITLE
Compile Error on Xcode 13.2.1

### ISSUE THREAD

**Issue by angelmic** [realm/realm-swift#7681]
### How frequently does the bug occur?

All the time

### Description

I using cocoapod to install realm 10.22, and I got many compile error from realm-swift.

### Stacktrace & log output

```shell
Intermediates.noindex/Pods.build/Debug-iphoneos/RealmSwift-iOS.build/Objects-normal/arm64/Aliases.dia:1:1: warning: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'RealmSwift-iOS' from project 'Pods')
Command CompileSwift failed with a nonzero exit code

===
public enum override final func isEmbedded() -> Bool {  //<-- show error: Expected '{' in enum

===
try await withCheckedThrowingContinuation { continuation in  //<-- show error: Generic parameter 'T' could not be inferred

many many. 

```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. add pod 'RealmSwift', '~>10' to Podfile
2. pod install
3. build project from xcode.

### Version

10.22

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15, iOS 14

### Build environment

Xcode version: 13.2.1
Dependency manager and version: Cocoapods 1.10.2

**Comment by pavel-ship-it** [comment]
I cannot reproduce it.
There are several typical options to try:
- pod deintegrate, pod install
- clean the build folder
- remove derived data
- restart Xcode

**Comment by tgoyne** [comment]
"public enum override final func" is not a string of text that appears in any of our files, so I think you have some sort of wacky file corruption.

**Comment by angelmic** [comment]
@tgoyne I saw it on my Pods/RealmSwift/EmbeddedObject.swift `isEmbedded()`

**Comment by tgoyne** [comment]
[The word enum there is class in our repository](https://github.com/realm/realm-swift/blob/master/RealmSwift/EmbeddedObject.swift#L61). I suspect you accidentally modified that file.

**Comment by angelmic** [comment]
> [The word enum there is class in our repository](https://github.com/realm/realm-swift/blob/master/RealmSwift/EmbeddedObject.swift#L61). I suspect you accidentally modified that file.

Thanks @tgoyne I found that's my fault. I use swiftformat and forgot to set Pods to be excluded. Thank for your help.

**Comment by pavel-ship-it** [comment]
It seems it's fixed, so I close the ticket. Please get back if you need help with this or another issue
