### ISSUE TITLE
download-core.sh script doesn't work on non interactive shells

### ISSUE THREAD

**Issue by tosbaha** [realm/realm-swift#7688]
### How frequently does the bug occur?

All the time

### Description

Your download-core.sh script has the following lines

```bash
set -euo pipefail
```
which indicates that this script should fail if there's an undefined variable. However, below code causes a failure on non-interactive shells.

https://github.com/realm/realm-swift/blob/c6d8ff61221f2ef8a4cdc53a36f44e700c61b286/scripts/download-core.sh#L57-L59
On macOS, this TMDIR is sandboxed so it is created per user.
Even though your script covers the scenario of undefined `TMPDIR` variable, because of the first line, this script fails. There are two ways to fix this issue.

1. You can remove the `u` part from t`set -euo pipefail`. 
2. You can put https://github.com/realm/realm-swift/blob/c6d8ff61221f2ef8a4cdc53a36f44e700c61b286/scripts/download-core.sh#L57-L59 at the beginning of the script before the 
```bash
set -euo pipefail
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Run the pod install step with non interactive shells or undefined the TMPDIR

### Version

10.23.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Monterey 

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by pavel-ship-it** [comment]
Hi @tosbaha 
Can you share more details on your environment and how you running the scripts to help us reproduce the issue?

**Comment by tosbaha** [comment]
We are running the `pod install` step in a non-interactive shell, meaning `TMPDIR` is not set. TMPDIR environment variable is only set for interactive bash shell and it's different for every user. 

You can emulate this environment by unsettling `TMPDIR` environment variable. As in your script, it is POSSIBLE for users to not have that environment variable set. You're already covering that scenario. It's just your `set -euo pipefail` prevents setting `TMPDIR` environment variable to `/tmp` directory if it doesn't exist.

**Comment by pavel-ship-it** [comment]
Thank you @tosbaha 
Fixed in #7690
