### ISSUE TITLE
Linker command failed

### ISSUE THREAD

**Issue by guramijobava** [realm/realm-swift#7691]
### How frequently does the bug occur?

All the time

### Description

This issue is connected to #7526. Since the issue was closed, I wanted to reopen it because I'm experiencing one more error while building. You can see the log output below.

Anyone experiencing the same error?

### Stacktrace & log output

```shell
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in RealmCore.o
      ___llvm_profile_runtime_user in Bid.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```


### Can you reproduce the bug?

Yes, always

### Reproduction Steps

_No response_

### Version

10.24.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.3.1

### Build environment

Xcode version: Xcode version: 13.2.1

**Comment by shusta-patreon** [comment]
+1 also seeing this with this latest version. I can build successfully if I remove code coverage generation from all targets, but re-enabling it then re-introduces the linker error. Various invocations of cleaning builds or cleaning derived data doesn't seem to help, alas.

**Comment by guramijobava** [comment]
I agree that turning off the code coverage generation works. For temporary solution, we can have it that way. However, this needs to be addressed and fixed, since we want to have code coverage enabled.

**Comment by tgoyne** [comment]
You should report this to Apple, as it's an Xcode bug.

**Comment by guramijobava** [comment]
@tgoyne It's being reported already: https://bugs.swift.org/browse/SR-14788
Unfortunately, no updates. If we all try to vote for the issue, they might fix it

**Comment by leemaguire** [comment]
Closing as this is not related to Realm.
