### ISSUE TITLE
Stuck on Cocoapods Realm

### ISSUE THREAD

**Issue by manimaustudios** [realm/realm-swift#7696]
### How frequently does the bug occur?

Seen once

### Description

Cocoapods gets stuck on pod install at realm pod

`Running prepare command
   $ /bin/bash -c  set -e sh scripts/setup-cocoapods.sh
   Downloading dependency: 11.9.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.9.0.tar.xz
`

trying to delete the entire pod and tried to run pod install -verbose. Stuck for good 20 minutes now with no progress.

### Can you reproduce the bug?

Yes, sometimes

### Version

11.9.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Mac OS 11.6

### Build environment

Xcode version: ...13.0
Dependency manager and version: ...

**Comment by dianaafanador3** [comment]
Hi @manimaustudios, It was just once or it something that happens occasionally?. This issue may be related to the server been down temporally on our side or a poor internet connection on your side.
