### ISSUE TITLE
Reading data on the main queue after writing data on the background queue does not produce expected results

### ISSUE THREAD

**Issue by srstanic** [realm/realm-swift#7700]
### How frequently does the bug occur?

Sometimes

### Description

After writing data to the Realm database on the background queue, reading the same data on the main queue sometimes results with a success and sometimes results with an empty result. There is a [report](https://github.com/realm/realm-swift/issues/7625) already that looks like the same underlying issue. 

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Create a new empty iOS app project with a unit tests target
2. Install RealmSwift v10.24.1 with CocoaPods (`pod 'RealmSwift', '~> 10.24.1'`)
3. Copy paste the following unit test code into the unit test file: https://gist.github.com/srstanic/5b0a3cb5225c1b9fb95d4bdd2f296ff5 
4. Run the test 5 to 10 times in a row manually and the test will fail at least a couple of times
5. If by any chance this has not produced a failed test, [run the test repeatedly automatically](https://www.avanderlee.com/debugging/flaky-tests-test-repetitions/#reproducing-a-flaky-test-locally-using-test-repetitions) and it will fail on the 2nd or 3rd repetition

The expected result would be that the test never fails, even if it runs 100 times in a row.

### Version

10.24.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.4

### Build environment

ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52

Xcode 13.3 Build version 13E113

Cocoapods 1.11.2
Realm (10.24.1)
RealmSwift (10.24.1)
RealmSwift (~> 10.24.1)

/bin/bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

carthage not found
(not in use here)

/usr/bin/git
git version 2.32.0 (Apple Git-132)

**Comment by dianaafanador3** [comment]
Hi @srstanic An In-Memory realm is deallocated from memory when you lose the reference to the realm. So every time you are getting a new realm (function `getRealm`), it is creating a new in memory realm, which will not contain the data stored to the previous ones.

**Comment by srstanic** [comment]
@dianaafanador3 Thank you for looking into it! The explanation makes perfect sense. When I switched to the file based Realm, the test was green even with 100 attempts. Though, I wonder why the in-memory version failed only sometimes and not always? Anyway, not that important. Sorry for the false alarm!
