### ISSUE TITLE
memory leak ios

### ISSUE THREAD

**Issue by rajatdhasmana1234** [realm/realm-swift#7708]
### How frequently does the bug occur?

All the time

### Description

I was working on an iOS project where Realm sdk was used. When I checked the leaks instrument of Xcode, it kept on giving me memory leaks on creation of Realm instance. Then I created a very simple demo app using swiftui and Realm. I looked into memory leaks again and I see the leaks again. I want to know is there a way to get rid of these leaks cuz I checked on internet but there is no such solution.

<img width="1396" alt="Screenshot 2022-03-17 at 11 51 37 AM" src="https://user-images.githubusercontent.com/96765608/159169083-79b1258d-f0f3-4714-b76d-e799f00bc833.png">

### Can you reproduce the bug?

Yes, always

### Version

  pod 'RealmSwift', '~>10'

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOs Monterey 12.1 and xcode 13.2.1

### Build environment

Xcode version: ...13.2.1
Dependency manager and version: ...

**Comment by leemaguire** [comment]
Hi @rajatdhasmana1234 can you give us the code sample that reproduces the issue?

**Comment by rajatdhasmana1234** [comment]
> Hi @rajatdhasmana1234 can you give us the code sample that reproduces the issue?

View to show names list:

     import SwiftUI
      import RealmSwift

      struct NameListView: View {
          @ObservedResults(NameModel.self) var nameList

          var body: some View {
    
              List(nameList) { nameObj in
             Text(nameObj.name)
              }
          }
      }``


Name model:

      class NameModel: Object, ObjectKeyIdentifiable {

          @Persisted(primaryKey: true) var id: Int
          @Persisted var name: String
      }


View to add names to Realm

      struct AddNameView: View {

          @State private var name: String = ""
          @ObservedResults(NameModel.self) var nameList

          var body: some View {
    
              HStack {
                  TextField("Enter name here...", text: $name)
                      .textFieldStyle(.roundedBorder)

                  Button {
                      let obj = NameModel()
                      obj.name = name
                     obj.id = nameList.count
                      $nameList.append(obj)
                  } label: {
                      Text("Add")
                          .padding()
                  }
              }
              .padding()
          }
      }


And this is my Home view

      struct HomeView: View {
          var body: some View {
    
              VStack{
                  NameListView()
                      .padding(.bottom, 5)
                  AddNameView()
                      .frame(height: 50)
              }
          }
      }


The screen looks like this

<img width="487" alt="Screenshot 2022-03-19 at 1 33 59 PM" src="https://user-images.githubusercontent.com/96765608/159482917-50de0570-784e-4fb5-87f6-1279f197f94c.png">


And the leaks instrument shows this plus as I add values sometimes more leaks shows up.

<img width="1396" alt="Screenshot 2022-03-17 at 11 51 37 AM" src="https://user-images.githubusercontent.com/96765608/159483034-171ab8dc-ad3d-44a7-b6ce-5b91724c7737.png">

**Comment by dianaafanador3** [comment]
@rajatdhasmana1234 Can you please point which exact version of Realm-Swift are you getting this memory leaks, because I can't reproduce it with your sample code. You can check this on your Podfile.lock file.

**Comment by rajatdhasmana1234** [comment]
> @rajatdhasmana1234 Can you please point which exact version of Realm-Swift are you getting this memory leaks, because I can't reproduce it with your sample code. You can check this on your Podfile.lock file.

  pod 'RealmSwift', '10.15.1'

**Comment by dianaafanador3** [comment]
@rajatdhasmana1234 Can you please update to our latest version (v10.24.2) and check if you still get the memory leak?

**Comment by rajatdhasmana1234** [comment]
Did update to 10.24.0, but still getting the leak.

**Comment by pavel-ship-it** [comment]
@rajatdhasmana1234 can you share the trace file for leaks?

**Comment by rajatdhasmana1234** [comment]
stack trace is there on the screenshot

**Comment by pavel-ship-it** [comment]
@rajatdhasmana1234 can you record trace with the leak and save it? It contains much more data than a stack trace on the screenshot. It will help a lot. Thank you

**Comment by horatiu1921** [comment]
I can reproduce the memory leak using both Instruments and memory graph debugger. In my case, is caused by the fileURL of the configuration. See the attached images.

![Screenshot 2022-07-05 at 19 26 20](https://user-images.githubusercontent.com/27273880/177374639-dade4085-5e14-4553-b53e-f063b22a1d8d.png)
![Screenshot 2022-07-05 at 19 27 01](https://user-images.githubusercontent.com/27273880/177374655-92f2b7e2-56fb-4c79-86ac-860b8ae507ae.png)

**Comment by rajatdhasmana1234** [comment]
Okay but as I can see in my sample project, I am using the default Realm configuration and still getting the leak.

**Comment by dianaafanador3** [comment]
This may be related to this fix https://github.com/realm/realm-swift/pull/7857

**Comment by kaeferfreund** [comment]
Any Updates on this?

**Comment by leemaguire** [comment]
@rajatdhasmana1234 @kaeferfreund has the latest version of Realm solved this issue for you? https://github.com/realm/realm-swift/pull/7857 should address it.
