### ISSUE TITLE
`@ObservedResults` inside a ViewModel (`ObservableObject`)

### ISSUE THREAD

**Issue by flowbe** [realm/realm-swift#7712]
### How frequently does the bug occur?

All the time

### Description

I would like to put my `@ObservedResults` variable in my view model (which is an `ObservableObject`) instead of putting it directly inside the SwiftUI view. When I do this, my variable is correctly populated but the view is not updated anymore.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Put the `@ObservedResults` inside a view model instead of the view directly:
```swift
@MainActor class ViewModel: ObservableObject {
    // Implicitly use the default realm's objects(Group.self)
    @ObservedResults(Group.self) var groups
}

/// The main content view if not using Sync.
struct LocalOnlyContentView: View {
    // My view model
    @ObservedObject var viewModel = ViewModel()
    
    var body: some View {
        if let group = viewModel.groups.first {
            // Pass the Group objects to a view further
            // down the hierarchy
            ItemsView(group: group)
        } else {
            // For this small app, we only want one group in the realm.
            // You can expand this app to support multiple groups.
            // For now, if there is no group, add one here.
            ProgressView().onAppear {
                viewModel.$groups.append(Group())
            }
        }
    }
}
```

You will see that the view is not updating anymore.

### Version

10.24.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iPhone 13 - iOS 15.4 - Simulator

### Build environment

Xcode version: 13.3
Dependency manager and version: SPM

**Comment by leemaguire** [comment]
`@ObservedResults` is only intended to be used on a SwiftUI View.

**Comment by flowbe** [comment]
Do you think it would be possible to add an equivalent to `ObservableObject` for Realm to mimic the behavior in Combine?

**Comment by jsflax** [comment]
You should just be able to do:
```swift
@MainActor class ViewModel: ObservableObject {
    @Published var groups: Results<Group>
}
```
And create your view model with the realm's results.

**Comment by flowbe** [comment]
@jsflax I just tried it and the view doesn't seem to be updating when there is an update to the results

**Comment by leemaguire** [comment]
Closing this as it has gone off topic. `@ObservedResults` was created for the purpose of being used on SwiftUI Views. To use it in a ViewModel you'll need to make the ViewModel a struct like the example above. Otherwise you will need to notify your View the traditional way by setting up a change listener on the Realm.

**Comment by patrickmenendez29** [comment]
> `@ObservedResults` is only intended to be used on a SwiftUI View.

It would be nice to write that under documentation. The description is currently ambiguous.
