### ISSUE TITLE
Uncaught exception 'RLMException', reason: 'Index 3 is out of bounds (must be less than 2).'. Use of dropFirst

### ISSUE THREAD

**Issue by axmav** [realm/realm-swift#7713]
### How frequently does the bug occur?

All the time

### Description

When I use .dropFirst operator on the collection of realm entries and then I want to delete them inside of a transaction I get the error: Uncaught exception 'RLMException', reason: 'Index 3 is out of bounds (must be less than 2).'. 
```
let realm = try Realm(configuration: config)
let entries = realm.objects(MyObject.self)
let toDelete = entries.dropFirst()
try realm.write {
      realm.delete(toDelete)
}
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Please try my code above

### Version

10.20.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.2

### Build environment

Xcode version: 13.2.1
Dependency manager and version: SPM 10.20.1

**Comment by tgoyne** [comment]
`dropFirst()` returns a lazy view that wraps the input `Results`, and `Results` live-updates as you delete objects. Together, these mean that `toDelete` changes in length as each object is deleted from it. The simplest thing to do is to create an array of objects to delete (i.e. `let toDelete = Array(entries.dropFirst())`) so that it does not update during the deletion.

**Comment by axmav** [comment]
thank you @tgoyne for the explanation. I did the same thing basically. But the thing is, that this interface does exists and is not overwritten. As I did this, I was looking in my code almost everywhere to find what actually goes wrong. I would suggest to resolve this possibility or to delete the function.

**Comment by leemaguire** [comment]
Closing this issue as solution provided and `.dropFirst()` is part of Swift's API, not Realm's

**Comment by axmav** [comment]
But it is not supported in Realm and can cause unexpected bugs, @leemaguire
