### ISSUE TITLE
realm.add nils unspecified fields with .modified upsert

### ISSUE THREAD

**Issue by visdyn** [realm/realm-swift#7723]
### How frequently does the bug occur?

All the time

### Description

When [upserting](https://www.mongodb.com/docs/realm/sdk/swift/examples/read-and-write-data/#upsert-an-object) an existing object using .add and .modified, the fields that are not specified are nil'd

Here's an object using the classic @objc dynamic syntax (this issue occurs using @Persisted as well)

```
class Person: Object {
    @objc dynamic var id = 0
    @objc dynamic var name = ""
    @objc dynamic var test = ""
    @objc dynamic var testtest = ""
    
    override static func primaryKey() -> String? {
        return "id"
    }
}
```

a person is created with primary key of 1234

```
let person1 = Person(value: ["id": 1234, "name": "Jones", "test": "test", "testtest": "testtest"])

try! realm.write {
    realm.add(person1, update: .modified) //add a new person since one does not exist
}
```

and then according to the documentation, the person should be able to be upserted by referencing the same primary key

```
let person2 = Person(value: ["id": 1234, "name": "Bowie"])
// Judging by the ID, it's the same person, just with a
// different name. When `update` is:
// - .modified: update the fields that have changed.
try! realm.write {
    realm.add(person2, update: .modified)
}
```

What's happening is all of the other fields (test and testtest) are being nil'd with the upsert while the name is updated correctly.

Note that `realm.create` has the correct behavior and does not nil the other fields

```
try! realm.write {
    realm.create(Person.self, value: ["id": "1234", "name": "Thorpe"], update: .modified)
}
```

If .add with .modified has the intended behavior of nilling all other fields, the docs should be updated accordingly.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Reproduce by using the above code, which closely matches the code in the documentation.

### Version

10.24.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 12.3

### Build environment

Xcode version: 13.3
Dependency manager and version: -

**Comment by pavel-ship-it** [comment]
Hi @visdyn,
That looks exactly like #7335
Please follow up the mentioned ticket (you may want to +1 there to give it a kick)
I close this ticket as duplicate.

**Comment by visdyn** [comment]
@pavel-ship-it 

Thanks for taking a look. I am not sure it's exactly the same thing. That's a feature request to allow skipping of fields to update.

My bug report is that Realm should already *not* be modifying fields that are not specified. More specifically, while the specified field is updated, the rest of the fields are erased.

Is the intended function of `.add. with `.modified` to update only the specified field(s) and erase the others? If so, cool. Can the documentation be updated to reflect that?
