### ISSUE TITLE
set encryptionKey crash

### ISSUE THREAD

**Issue by suddenly1990** [realm/realm-swift#7732]
### How frequently does the bug occur?

All the time

### Description

I used the realm object-c database before, but did not set the encryptionKey. Now I need to set the encryptionKey to the previous database, how should I migrate. I do the encryption like the following code, but the app will crash。I am did find what should I do or it not support this migrate？.
![281648812189_ pic_hd](https://user-images.githubusercontent.com/13513828/161254145-fb3ef233-bec7-4dc1-ab9a-3e469a65900e.jpg)

### Can you reproduce the bug?

Yes, always

### Version

Realm (10.10.0):

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.1

### Build environment

Xcode version: ...Version 13.2.1 (13C100)

**Comment by pavel-ship-it** [comment]
Hi @suddenly1990,
To enable the encryption you want to use `writeCopyToURL:encryptionKey:error:`
```
        [realm writeCopyToURL:newRealmURL encryptionKey:newRealmEncryptionKey error:nil];
```
Here `realm` is your existing unencrypted Realm.

**Comment by suddenly1990** [comment]
thanks a lot **@pavel-ship-it**
I know your means. I have another questions. when 
I called `+ (instancetype)realmWithURL:(NSURL *)fileURL `and realm crash. 

the crash message is:
`Error Domain=io.realm Code=1 "Provided schema version 0 is less than last set version 17." UserInfo={NSLocalizedDescription=Provided schema version 0 is less than last set version 17., Error Code=1}`

**my questions:**
**1  I need know it that assure get user correct schemaVersion，how I know my current schemaVersion(I migrate realm many times so maybe the user have schemaVersion 17 maybe have schemaVersion 16, maybe have schemaVersion 13，......) 
2  if I can‘t know it what should I do（why realm know my schemaVersion）.**

> when I check the realm source code, in the + (instancetype)realmWithURL:(NSURL *)fileURL fucntions  it use [RLMRealmConfiguration defaultConfiguration],but the default configuration the schemaVersion is 0.

thank you.

**### the pictures is my code and the crash messag**:
code:
![Snip20220402_1](https://user-images.githubusercontent.com/13513828/161365830-13bc4c31-1998-4640-9333-24d3d5d14823.png)
crash:
![Snip20220402_3](https://user-images.githubusercontent.com/13513828/161365875-318d7f18-22c1-4da9-85e6-4a311701805c.png)
message:
![Snip20220402_2](https://user-images.githubusercontent.com/13513828/161365901-c435e71a-7a16-4332-a39f-98ab0bcbf8fb.png)

**Comment by suddenly1990** [comment]
> Hi @suddenly1990, To enable the encryption you want to use `writeCopyToURL:encryptionKey:error:`
> 
> ```
>         [realm writeCopyToURL:newRealmURL encryptionKey:newRealmEncryptionKey error:nil];
> ```
> 
> Here `realm` is your existing unencrypted Realm.

**Comment by suddenly1990** [comment]
thanks a lot
