### ISSUE TITLE
Injecting partition for @AsyncOpen while passing @ObservedRealmObject

### ISSUE THREAD

**Issue by davidkessler-ch** [realm/realm-swift#7733]
### How frequently does the bug occur?

All the time

### Description

Not sure if I implemented this just wrong, but I checked with the guidelines with SwiftUI and can really not find anything that's off. While passing a @ObservedRealmObject I can no longer inject a partition for @AsyncOpen I try to open in the subview.
The problem is quite complex, so below code should illustrate what I am trying to do. With a similar setup to the one below, the app crashes (see output below)

edit:
Sorry, should have been more precise: A realm with a **different** partition is already injected into View1 from its parent, so View1 receives Objects [Example] from which it needs one to set the partition value of the Realm of View2, but also pass along the according object from the Realm of View1. The new realm needs to have a new partition but when passing the object from the Realm of View1, it probably tries to inject the partition into both realms, while it should only inject it into the newly created real. If that makes sense.

```Swift
struct View1: View {
    
    @ObservedResults(Example.self) var examples
    
    var someImportantVariable = "123"
    
    var body: some View {
        NavigationView {
            NavigationLink(
                destination:
                    View2(importantExample: examples.first)
                        .environment(\.partitionValue, "session=\(someImportantVariable)"), // realm being opened async, just injecting partition...
                label: {
                    Text("go")
                })
        }
    }
}

struct View2: View {
    
    @ObservedRealmObject var importantExample: Example
    
    @AsyncOpen(appId: "HIDDEN", partitionValue: "", timeout: 4000) var asyncOpen // partition value injected from parent view
    
    var body: some View {
        Text("handling the async open...")
    }
}

struct ContentView: View {
    var body: some View {
        View1()
           .environment(\.realmConfiguration, user.configuration(partitionValue: "somePartition"))
    }
}
```

### Stacktrace & log output

```shell
terminating with uncaught exception of type realm::MismatchedConfigException: Realm at path '/Users/HIDDEN/Library/Developer/CoreSimulator/Devices/HIDDEN-2B56-40D4-B085-39BEC872E347/data/Containers/Data/Application/HIDDEN-623E-4999-AA78-116468126CF5/Documents/mongodb-realm/HIDDEN-HIDDEN/HIDDEN/%22PARTITION%22.realm' already opened with different partition value.
CoreSimulator 757.5 - Device: iPhone 11 (HIDDEN-2B56-40D4-B085-39BEC872E347) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 11
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```SWIFT

struct View1: View {
    
    @ObservedResults(Example.self) var examples
    
    var someImportantVariable = "123"
    
    var body: some View {
        NavigationView {
            NavigationLink(
                destination:
                    View2(importantExample: examples.first)
                        .environment(\.partitionValue, "session=\(someImportantVariable)"), // realm being opened async, just injecting partition...
                label: {
                    Text("go")
                })
        }
    }
}

struct View2: View {
    
    @ObservedRealmObject var importantExample: Example
    
    @AsyncOpen(appId: "HIDDEN", partitionValue: "", timeout: 4000) var asyncOpen // partition value injected from parent view
    
    var body: some View {
        Text("handling the async open...")
    }
}
```

### Version

10.25.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

CoreSimulator 757.5 - Device: iPhone 11 (HIDDEN-2B56-40D4-B085-39BEC872E347) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 11

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by pavel-ship-it** [comment]
Hi @davidkessler-ch ,
You getting this error because you're successfully passing the partition value. Problem here - you're trying to open realm file that is already opened. Solution is to inject a new file url:
```
                    View2(importantExample: examples.first)
                        .environment(\.partitionValue, "session=\(someImportantVariable)"),
                        .environment(\.realmConfiguration.fileURL, **nonDefaultURL**),
```
In fact it is better to prepare the whole configuration for the second Realm partition and pass it to the second view instead of passing only a different file URL - `.environment(\.realmConfiguration, **anotherConfig**),`

**Comment by davidkessler-ch** [comment]
Thanks for your response @pavel-ship-it . If I do pass the entire configuration as you suggested, the realm somehow no longer opens asynchronously, but it also opens if there is no internet connection, with a local realm. So this is unfortunately not an option. Is there a way to have it open asynchronously while also passing in the required parameters?
