### ISSUE TITLE
Pod install stuck on -> Installing Realm (10.25.1)

### ISSUE THREAD

**Issue by Akshaytule09** [realm/realm-swift#7772]
### How frequently does the bug occur?

All the time

### Description

I am trying to Install Realm (10.25.1) but it is taking forever and finally I have to abort it after 3-4 hours. I have tries updating cocoapods. Tried updating pod repo and also tried pod deintegrate and removing podlock file. Results are the same and pod install gets stuck.

### Stacktrace & log output

```shell
-> Installing Realm (10.25.1)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-swift.git /var/folders/zc/lnhqdkvx28x8dtkjk21f0gnm0000gp/T/d20220427-1776-16azmoi --template= --single-branch --depth 1 --branch v10.25.1
     Cloning into '/var/folders/zc/lnhqdkvx28x8dtkjk21f0gnm0000gp/T/d20220427-1776-16azmoi'...
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

run pod install for 10.25.1 version.

### Version

10.25.1 

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS Monterey 12.3.1

### Build environment

Xcode version: ... 
Dependency manager and version: ... cocoapods-1.11.3

**Comment by ericjordanmossman** [comment]
@Akshaytule09 Are you still seeing this today? I'm able to download in a reasonable time.
Did this happen before 10.25.1? Are you using a mirror to download?

**Comment by abingeorgev** [comment]
Am also facing the same issue.

-> Installing Realm (10.25.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-swift.git
     /var/folders/lr/vnvgc0694c314bzv1mbnkh300000gn/T/d20220502-81653-p1rykl --template= --single-branch --depth 1
     --branch v10.25.0
     Cloning into '/var/folders/lr/vnvgc0694c314bzv1mbnkh300000gn/T/d20220502-81653-p1rykl'...
     Note: switching to 'f9400ca044844701ea32491a4c6c4b06d74ab24d'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false

**Comment by abingeorgev** [comment]
-> Installing Realm (10.22.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-swift.git
     /var/folders/lr/vnvgc0694c314bzv1mbnkh300000gn/T/d20220502-88195-brpxqi --template= --single-branch --depth 1
     --branch v10.22.0
     Cloning into '/var/folders/lr/vnvgc0694c314bzv1mbnkh300000gn/T/d20220502-88195-brpxqi'...

**Comment by dianaafanador3** [comment]
Hi @abingeorgev, @Akshaytule09 I don't seem to have any issues downloading latest version `10.25.2` or `10.22.0`, have you tried any other GitHub repository?, this may be a GitHub issue. If you are still experiencing this issue, can you please run `pod install --verbose` and paste the log in here.

**Comment by abingeorgev** [comment]
> Am also facing the same issue.
> 
> -> Installing Realm (10.25.0)
> 
> > Git download
> > Git download
> > $ /usr/bin/git clone https://github.com/realm/realm-swift.git
> > /var/folders/lr/vnvgc0694c314bzv1mbnkh300000gn/T/d20220502-81653-p1rykl --template= --single-branch --depth 1
> > --branch v10.25.0
> > Cloning into '/var/folders/lr/vnvgc0694c314bzv1mbnkh300000gn/T/d20220502-81653-p1rykl'...
> > Note: switching to 'f9400ca044844701ea32491a4c6c4b06d74ab24d'.
> 
> ```
>  You are in 'detached HEAD' state. You can look around, make experimental
>  changes and commit them, and you can discard any commits you make in this
>  state without impacting any branches by switching back to a branch.
>  
>  If you want to create a new branch to retain commits you create, you may
>  do so (now or later) by using -c with the switch command. Example:
>  
>    git switch -c <new-branch-name>
>  
>  Or undo this operation with:
>  
>    git switch -
>  
>  Turn off this advice by setting config variable advice.detachedHead to false
> ```
> 
> The same is happening with 10.25.1 & 10.25.2

So I got these logs after running pod install --verbose. There were 8 other pods which all got installed real quick. Only got stuck with these.Not sure why.

**Comment by dianaafanador3** [comment]
Can you please paste the log here from `pod install --verbose`? @abingeorgev

**Comment by ankits1626** [comment]
@dianaafanador3 
-```
> Installing RealmSwift (3.17.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-cocoa.git
     /var/folders/mm/1mpnnks110g0txm6l6fj1pqm0000gn/T/d20220505-44279-fxprb2
     --template= --single-branch --depth 1 --branch v3.17.0
     Cloning into '/var/folders/mm/1mpnnks110g0txm6l6fj1pqm0000gn/T/d20220505-44279-fxprb2'...
     Note: switching to '55ccdf065a762a7bf41f429efd1591e5cf1e55b6'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false
     
     $ /usr/bin/git -C
     /var/folders/mm/1mpnnks110g0txm6l6fj1pqm0000gn/T/d20220505-44279-fxprb2
     submodule update --init --recursive
     Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
     Cloning into '/private/var/folders/mm/1mpnnks110g0txm6l6fj1pqm0000gn/T/d20220505-44279-fxprb2/Realm/ObjectStore'...
     Submodule path 'Realm/ObjectStore': checked out '13adc3afe177fb67afc8d3f63e0b2775df0a95b1'
     Submodule 'external/catch' (https://github.com/catchorg/Catch2) registered for path 'Realm/ObjectStore/external/catch'
     Cloning into '/private/var/folders/mm/1mpnnks110g0txm6l6fj1pqm0000gn/T/d20220505-44279-fxprb2/Realm/ObjectStore/external/catch'...
     Submodule path 'Realm/ObjectStore/external/catch': checked out '6860c8def0ba7559bf077515b7a7ff63ad3444f8'
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup swift
   core is not a symlink. Deleting...
   Downloading dependency: sync 4.6.1 from https://static.realm.io/downloads/sync/realm-sync-cocoa-4.6.1.tar.xz


```

**Comment by dianaafanador3** [comment]
Hi @ankits1626 seems like your having issues connecting to `[https://static.realm.io/](https://static.realm.io/downloads/sync/realm-sync-cocoa-4.6.1.tar.xz)` in your location. 
Can you test `curl https://static.realm.io/downloads/sync/realm-sync-cocoa-4.6.1.tar.xz --output realm-sync-cocoa-4.6.1.tar.xz` and check if you can download the file, so we can be sure that's the issue.
I'll suggest to migrate your `RealmSwift` installation SPM, have in mind that you can have a mixed project, using both Cocoapods and SPM.

**Comment by Akshaytule09** [comment]
The issue is resolved for me. I was using terminal for maintaining git repo. I switched to Sourcetree. Took pull using Sourcetree and tried to install the pods again. The pods got installed successfully. Still not sure what was the root cause of the issue.

**Comment by pavel-ship-it** [comment]
I close the issue as the original problem was solved.

**Comment by AkashBelekar2428** [comment]
anybody can tell me about which version is latest of Realm Pod ?
pod 'RealmSwift' (?)
Xcode version ?

**Comment by dianaafanador3** [comment]
@AkashBelekar2428 v10.38.0
