### ISSUE TITLE
Realm Object isEqual(_:) override

### ISSUE THREAD

**Issue by igorvoytovich** [realm/realm-swift#7781]
Hello,

Could you please tell if it is safe to override:

`func isEqual(_ object: Any?) -> Bool { ... }`

for Realm Objects?

I heard that Realm objects with **primaryKey** override it by default, but we use **detached** objects in several cases and need to be able to compare them too.

For example, if we have:

```
class Item: Object {
    @Persisted var id: String
    @Persisted var field: String

    override class func primaryKey() -> String? {
          return "id"
    }
}
```

If we add:
```
func isEqual(_ object: Any?) -> Bool {
    guard let c = object as? Item else { return false }
    return id == c.id
}

```
to this class,

Can something break or go wrong? Could this lead to some unexpected behavior in production or is it completely safe?

Thanks.

P.S.
Or maybe you can tell how to correctly implement objects comparison so that it works for detached objects as well? Maybe something related to Hashable and hashValue would be more correct?

**Comment by dianaafanador3** [comment]
Hi @igorvoytovich you should be able to compare between two detached (frozen) objects without overriding the `isEqual` function. How are you deataching your objects?, Can you give a little bit more context so I can help you.

**Comment by igorvoytovich** [comment]
> Hi @igorvoytovich you should be able to compare between two detached (frozen) objects without overriding the `isEqual` function. How are you deataching your objects?, Can you give a little bit more context so I can help you.

Hi @dianaafanador3,

Thank your for your response.

We use this code: https://github.com/realm/realm-swift/issues/5578#issuecomment-364475728

We can not use Realm's frozen objects due to their implementation nuances.

**Comment by dianaafanador3** [comment]
ok I understand. Regarding overriding `isEqual` for that particularly Object Type there is no issue, as we don't use this internally, and you will be overriding it for just this Object Type. Have in mind that for comparing managed objects you will have to use `public func isSameObject(as object: Object?) -> Bool` if you want deep comparison.

**Comment by igorvoytovich** [comment]
Thanks @dianaafanador3 ,

This is exactly what we wanted to know. There were fears that this function can be used somewhere inside the Realm internal logic, for example, when updating objects with a primary key, in order to check for the presence of an object in database or something like that. Now it's all clear.

Thanks again! We can close this case now.
Have a nice day!

**Comment by xingheng** [comment]
> ok I understand. Regarding overriding `isEqual` for that particularly Object Type there is no issue, as we don't use this internally, and you will be overriding it for just this Object Type. Have in mind that for comparing managed objects you will have to use `public func isSameObject(as object: Object?) -> Bool` if you want deep comparison.

So can we just override that `isSameObject` function to add additional compare logic?
