### ISSUE TITLE
Class Projections with `ObservedResults` and `where(_:)`

### ISSUE THREAD

**Issue by Cheezzhead** [realm/realm-swift#7782]
**Goals**
Use class projections with the `ObservedResults` property wrapper. Related to this I would also want to query the results collection with the `where(_:)` method. 

The [documentation](https://www.mongodb.com/docs/realm/sdk/swift/examples/define-and-use-class-projections/#use-a-class-projection-in-a-swiftui-view) for class projections specifically mention that they can be used with the ObservedResults property wrapper, but this does not seem to be the case, at least not without conforming to additional protocols.

**Expected Results**
```
class TestItem: Object, ObjectKeyIdentifiable {
    @Persisted(primaryKey: true) var guid = UUID()
    @Persisted var name: String
    @Persisted var service: ItemService!
}

class ItemProjection: Projection<TestItem> {
    @Projected(\TestItem.name) var name
    @Projected(\TestItem.service.id) var serviceNumber
}

class ItemService: Object, ObjectKeyIdentifiable {
    @Persisted(primaryKey: true) var guid = UUID()
    @Persisted var id: Int
}

struct ProjectionTest: View {
    // With projections
    @ObservedResults(ItemProjection.self) var itemProjections
    /* ERROR: Referencing initializer 'init(_:configuration:filter:keyPaths:sortDescriptor:)' on 'ObservedResults' requires that 'ItemProjection' conform to 'Identifiable' */
    var serviceSelection: Int
    
    var body: some View {
        let items = itemProjections.where { $0.serviceNumber == serviceSelection }
        /* ERROR: Subscript 'subscript(dynamicMember:)' requires that 'ItemProjection' inherit from 'RLMObjectBase' */
        List(items) { item in
            Text(item.name)
        }
    }
}

struct ProjectionTest2: View {
    // With objects
    @ObservedResults(TestItem.self) var allItems
    var serviceSelection: ItemService
    
    var body: some View {
        let items = allItems.where { $0.service == serviceSelection }
        List(items) { item in
            Text(item.name)
        }
    }
}
```

The ProjectionTest view shows an attempt at using a projection class with the intended goals. The expected result should be the same as the ProjectionTest2 view (which does not use the projected class).

**Actual Results**
The errors are commented in the code snippet above, but for clarity:

- Attempting to initialize a property with the `ObservedResults` property wrapper and a class projection as ResultType runs into: `Referencing initializer 'init(_:configuration:filter:keyPaths:sortDescriptor:)' on 'ObservedResults' requires that 'ItemProjection' conform to 'Identifiable'`. While this can be solved (by conforming to `ObjectKeyIdentifiable`, for example), this does not seem consistent with the way the documentation is phrased. As in, the way I read it is that `ObservedResults` and class projections should work out of the box. But this is clearly not the case.
- Attempting to filter a realm collection of class projections (such as `Results<..>`, `List<..>`) runs into: `Subscript 'subscript(dynamicMember:)' requires that 'ItemProjection' inherit from 'RLMObjectBase'`. I do not see a clear way to solve this.

**Version of Realm / Xcode / macOS**
Realm: 10.25.1 (RealmDatabase: 11.14.0)
XCode: 13.3.1 (13E500a)
macOS: 12.0.1 (21A559)

**Comment by dianaafanador3** [comment]
Hi @Cheezzhead, as the compilation error suggest, any `ObservedResults` result type (Objects, Projection Objects) needs to conform to Identifiable (Or `ObjectKeyIdentifiable` which defines a default identity for the object), allowing it to be used in `SwiftUI` elements like for example `ForEach`. 
You mentioned the documentation doesn't mention conforming to Identifiable, which documentation are you using as a reference? our docstrings or any other documentation, so we can add extra information about this conformance.
Concerning filtering the Projection results, I'll recommend for now changing the filter to
`let items = allItems.wrappedValue.filter { $0.service == serviceSelection } `, while we check if we can incorporate this into our `ObservedResults` API.

**Comment by Cheezzhead** [comment]
> You mentioned the documentation doesn't mention conforming to Identifiable, which documentation are you using as a reference? our docstrings or any other documentation, so we can add extra information about this conformance.

I don't see it mentioned anywhere, specifically [here](https://www.mongodb.com/docs/realm/sdk/swift/examples/define-and-use-class-projections/#use-a-class-projection-in-a-swiftui-view) (Section 'Use a Class Projection in a SwiftUI View').

I should mention that the documentation isn't factually 'incorrect', per se. It's just that, with the absence of this necessary protocol conformance being mentioned in the docs, users might interpret the compiler error as something unexpected happening, and infer from that something going wrong elsewhere in the code.

> Concerning filtering the Projection results, I'll recommend for now changing the filter to
`let items = allItems.wrappedValue.filter { $0.service == serviceSelection }` , while we check if we can incorporate this into our ObservedResults API.

Thank you very much, this does what I wanted.

**Comment by aehlke** [comment]
was this ever improved in the API or filed elsewhere?

**Comment by dianaafanador3** [comment]
This was just something missing on the docstring not an API or implementation issue
