### ISSUE TITLE
EXC_BREAKPOINT

### ISSUE THREAD

**Issue by ICloud0114** [realm/realm-swift#7784]
### How frequently does the bug occur?

Sometimes

### Description

EXC_BREAKPOINT: arrayByAddingObjectsFromArray: > init > propertiesForClass:isSwift:

### Can you reproduce the bug?

Yes, sometimes

### Version

10.25.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

15.4.1

### Build environment

Xcode version: ...
Dependency manager and version: ...
Version 13.1

**Comment by dianaafanador3** [comment]
Hi @ICloud0114, this seems to indicate an issue while reading the schema, can you please add a more detailed stacktrace so we can better diagnose this.

**Comment by pavel-ship-it** [comment]
Hi @ICloud0114, this seems to indicate an issue while reading the schema, can you please add a more detailed stacktrace so we can better diagnose this.

**Comment by leemaguire** [comment]
Closing this issue as no detailed information provided.
