### ISSUE TITLE
Async versions of login(credentials:) and linkUser(credentials:) are not visible to the compiler

### ISSUE THREAD

**Issue by kachalo** [realm/realm-swift#7791]
### How frequently does the bug occur?

All the time

### Description

The async versions of `login(credentials:)` and `linkUser(credentials:)` are not visible to the compiler because the extensions they are defined are not declared public.

When using:
```
let _ = try await app.login(credentials: credentials)
```

I get the following compiler warnings:
```
No 'async' operations occur within 'await' expression
No calls to throwing functions occur within 'try' expression
```

### Stacktrace & log output

```shell
No 'async' operations occur within 'await' expression
No calls to throwing functions occur within 'try' expression
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Try to use async version of `login(credentials:)`:

```
let _ = try await app.login(credentials: credentials)
```

or `linkUser(credentials:)`:

```
let _ = try await anonymousUser.linkUser(credentials: credentials)
```

### Version

Realm 10.25.2 and RealmDatabase 11.15.0 for Swift

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.2

### Build environment

Xcode version: 13.2.1 (13C100)

**Comment by jsflax** [comment]
The methods on the extensions are exposed publicly. Can you show us the method you are calling them from? Also, are there other compiler errors that you're saying?

**Comment by kachalo** [comment]
Here are our methods that invokes async methods:
```
public func login(credentials: Credentials = .anonymous) async throws
{
   shouldIndicateActivity = true
        
   let _ = try await app.login(credentials: credentials)
        
   shouldIndicateActivity = false
   updateState()
}
```

and

```
public func registerNewAccount(credentials: Credentials) async throws
{
   guard let anonymousUser = currentUser, anonymousUser.isAnonymous else { return }
        
   if case let .emailPassword(email, password) = credentials
   {
       shouldIndicateActivity = true
            
       try await app.emailPasswordAuth.registerUser(email: email, password: password)

       _ = try await anonymousUser.linkUser(credentials: credentials)
            
       shouldIndicateActivity = false
            
       updateState()
   }
}
```

**Comment by ericjordanmossman** [comment]
Should be addressed by: https://github.com/realm/realm-swift/pull/7792/files, I think.
