### ISSUE TITLE
Collection Change Listener - Crash

### ISSUE THREAD

**Issue by igorvoytovich** [realm/realm-swift#7798]
### How frequently does the bug occur?

Sometimes

### Description

Hello,

We use Realm collection changes listener code from docs (https://www.mongodb.com/docs/realm/sdk/swift/examples/react-to-changes/#register-a-collection-change-listener) to update a table view in the app.

Sometimes, during very intensive work with Realm, we get a crash on the tableview when it tries to insert a new cell into the table.

I'm attaching a test piece of code that reproduces this issue 10% of the time.

[AppDelegate.swift.zip](https://github.com/realm/realm-swift/files/8710081/AppDelegate.swift.zip)

[](url)

Or in text: https://gist.github.com/igorvoytovich/01eabf6760e207b8fb0ee1bc248885ef

There is a complete application code. When the application starts, endless loop with random Realm work starts (writes, updates, deletions). When opening ViewController2, we start the Realm Change Listener, and in some of cases we have a crash on start on the tableView _performBatchUpdates_ here.

Crash reason looks like this:

> "Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (85) must be equal to the number of rows contained in that section before the update (85), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

It seems to be something similar to some kind of "race condition", due to the fact that all Realm transactions occur in the background thread, and the listener is attached on the main thread. Maybe if the code of the listener attaching is executed when Realm is in the middle of transaction on our write thread, idk... This is the first thing that comes to mind.

Kindly let me know if you need more information.

Thanks.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Code example attached.

### Version

10.25.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15

### Build environment

Xcode version: 13.3.1
Dependency manager and version: CocoaPods

**Comment by igorvoytovich** [comment]
Hi @pavel-ship-it ,

Thanks for your response.

This crash is not reproducable in 100% cases. To reproduce it, open/close ViewController2 some number of times.
Sometimes it crashes the first times, sometimes you need to repeat it 20-50-60 times. Completely random, but it can definitely be caught.

**Comment by pavel-ship-it** [comment]
@igorvoytovich thank you for the update. I've got the crash with the original sample. Let me see in to that

**Comment by igorvoytovich** [comment]
@pavel-ship-it 

Thanks!

Kindly let me know if you need any additional information from me.

On a production project, we see this crash in 0.3-0.4% of users.

BTW:
Our practical case - we have a realtime feed in our app, we save feed posts in the background, and on some screen we show them using UITableView using a collection change listener as in the example above.

**Comment by igorvoytovich** [comment]
Hi @pavel-ship-it ,

Thank you so much for getting back to me!

I will definitely try to do that now and will let you know about the results.

Could you please tell more when we need explicitly pass `queue` parameter to Realm's init? I thought that the Realm is "attached" to a specific thread in which it was created. 

And it's also interesting about `.observe(keyPaths: nil, on: DispatchQueue.main)`, that is, when we need to specify the queue parameter explicitly.

I would be very grateful if you can tell about this in more detail, I think understanding this will help to avoid similar mistakes in the future.

**Comment by igorvoytovich** [comment]
@pavel-ship-it 

I added the code for automatically attaching/reattaching listener and tested several cases with different configurations.

I see that passing `queue` parameter to the Realm like `Realm(configuration: configuration, queue: queue)` has **no** effect, I mean it is not related to this crash.

But adding queue parameter to this function `.observe(keyPaths: nil, on: DispatchQueue.main)` seems like helps. It stops crashing. If we pass `DispatchQueue.main` here - it won't crash, not depending on how we constructed Realm before (with or without queue).

But now things have gotten even more confusing. That is, we specify the main queue for the listener, which is already on the main queue. Should we always do this with all listeners? 

To be honest, the situation is strange, and I can not find any information in the documentation or on the forums.

**Comment by pavel-ship-it** [comment]
@igorvoytovich ,
passing the queue parameter to the Realm like `Realm(configuration: configuration, queue: queue)` has no effect _so far_. As soon as you leaving the main queue, you should configure this parameter. It is not a problem in your case tho, just overall  recommendation.

Regarding the thread confining on the main thread it's actually something new to me. It should work without passing the queue. Looks like machine gun notification speed needs a special treatment where the queueing the updates gives a hand.  maybe @tgoyne can tell more.

Anyway, as soon as problem solved I close the ticket. If it still present please open a new ticket.

**Comment by igorvoytovich** [comment]
Hi @pavel-ship-it ,

Thanks for the explanation.

I have one question left - that is, every time we use Realm in a custom DispatchQueue, should we pass this queue to the Realm's initializer? Even if we don't access Realm from different blocks ( `.sync {}, .async {}` ) of this queue?

As far as I understand, this parameter is needed in order to be able to do the following:

```
let queue = DispatchQueue(...)
let realm = try Realm(queue: queue)

queue.async {
    try! realm.write { ... }
}

queue.async {
    try! realm.write { ... } // here will be the crash without passing queue to the init
}
```

If we don't do that in our code, should we still init Realm with the `queue` parameter? In our cases we always create **new** Realm instance in every `.async {}` block of a custom serial DispatchQueue always within `autoreleasepool {}`, so I'm wondering if it's really good practice in our case.
I wonder what it affects, can somehow affect the performance?

Thanks!
