### ISSUE TITLE
Pod install stuck on -> Installing Realm (10.19.0)

### ISSUE THREAD

**Issue by Maling1255** [realm/realm-swift#7809]
### How frequently does the bug occur?

All the time

### Description

Cocoapods gets stuck on pod install at realm pod

I am trying to Install Realm (10.19.0) but it is taking forever and finally I have to abort it after 8 hours. I have tries updating cocoapods. Tried updating pod repo and also tried pod deintegrate and removing podlock file. Results are the same and pod install gets stuck.

### Stacktrace & log output

```shell
-> Installing Realm (10.19.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/m4/jw6lg3ps0zj1rr5mflxhwhn40000gn/T/d20220524-44775-9etcdr
     --template= --single-branch --depth 1 --branch v10.19.0
     Cloning into '/var/folders/m4/jw6lg3ps0zj1rr5mflxhwhn40000gn/T/d20220524-44775-9etcdr'...
     Note: switching to '328425bfc372ce77ec1f4f2701f61ececbb97d84'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false
     
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   Downloading dependency: 11.6.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.6.0.tar.xz
```

### Can you reproduce the bug?

Yes, always

### Version

10.19.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

11.5.2

### Build environment

Xcode version: v13.2.1
Dependency manager and version: ...

**Comment by pavel-ship-it** [comment]
Hi @Maling1255,
Can you show the Podfile?
Did you try `pod repo update`?

**Comment by KamilStanuszek** [comment]
I have the same problem

**Comment by kasa-ailleron** [comment]
I have the same problem

**Comment by pavel-ship-it** [comment]
@Maling1255, 
   Downloading dependency: 11.6.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.6.0.tar.xz
can you try to run `curl https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.6.0.tar.xz --output realm-monorepo-xcframework-v11.6.0.tar.xz`?

@kasa-ailleron,
can you try to run `curl https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.0.0.tar.xz --output realm-monorepo-xcframework-v12.0.0.tar.xz`?

**Comment by 342261733** [comment]
I tried call ' pod install ' several times, but it doesn't work, any other solution? how big is the 'realm-monorepo-xcframework'? Can you put it in your pod library?

**Comment by 342261733** [comment]
@dianaafanador3  I think It should be the network problem. I tried again several times and succeeded
