### ISSUE TITLE
Exception with error: "Cannot schedule async transaction. Make sure you are running from inside a run loop."

### ISSUE THREAD

**Issue by theoks** [realm/realm-swift#7812]
### Problem

When trying to perform an async write from within a thread without a run-loop, which is a common situation when performing an async write in a Task, an exception happens with the following error:

`Cannot schedule async transaction. Make sure you are running from inside a run loop.
`
1. This is missing from the documentation
2. Is this limitation going to be lifted in the future?

### How important is this improvement for you?

Would be a major improvement

**Comment by pavel-ship-it** [comment]
Hi @theoks,
Thank you for the input. I'll discuss that with the team

**Comment by LilaQ** [comment]
Any news on this? This is blocking me too right now

**Comment by natario1** [comment]
Any news?

**Comment by Dhaval3110** [comment]
Any update?

**Comment by dianaafanador3** [comment]
Hi @Dhaval3110 we are working on a better experience with async/await operations, I'll post any updates to this issue, or follow our release notes to check for changes.

**Comment by Dhaval3110** [comment]
@dianaafanador3  thank you for update

**Comment by AdieOlami** [comment]
Any update on this please?

**Comment by nerzh** [comment]
🥺

**Comment by nerzh** [comment]
🙄

**Comment by reinosutisno** [comment]
Any update?

**Comment by Heafy** [comment]
Any update?

**Comment by dianaafanador3** [comment]
This is an ongoing project at the moment, we've been improving concurrency support in our last releases, but there some things which are still on the works. We'll let you know when this is working correctly.

**Comment by samuelowino** [comment]
Looking forward to this

**Comment by nerzh** [comment]
🙄

**Comment by EdwinXiang** [comment]
any update?

**Comment by EdwinXiang** [comment]
any update?

**Comment by nerzh** [comment]
🙄

**Comment by jsflax** [comment]
Current update is that we are enabling Actor confined Realm's in the near future. I know it is not exactly what is being asked for here, but technically accomplishes the same end result. Once a Realm is confined to the Actor, you will be able to do `asyncWrite`s on it, and we/the swift concurrency runtime will handle the rest.

**Comment by ericjordanmossman** [comment]
Actor confined realms released [here](https://github.com/realm/realm-swift/releases/tag/v10.39.0). As mentioned [above](https://github.com/realm/realm-swift/issues/7812#issuecomment-1475360105), this should handle the original issue.
