### ISSUE TITLE
Crash on the first access to the realm database

### ISSUE THREAD

**Issue by PavelKandratsyeu** [realm/realm-swift#7815]
### How frequently does the bug occur?

Sometimes

### Description

The app crashes on the first realm initialisation with the configuration passed as the parameter.

### Stacktrace & log output

```shell
0 libsystem_pthread.dylib pthread_mutex_lock + 102
1 libc++.1.dylib std::__1::mutex::lock() + 16
2 Realm RLMGetThreadLocalCachedRealmForPath(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, void*) + 44
3 Realm +[RLMRealm realmWithConfiguration:queue:error:] + 244
4. RealmSwift $s10RealmSwift0A0V13configuration5queueA2C13ConfigurationV_So012OS_dispatch_D0CSgtKcfC + 92
5 OurAppName RealmUtil.swift - Line 147 specialized static RealmUtil.read(realm:configuration:readingClosure:) + 147
```

### Can you reproduce the bug?

Not yet

### Reproduction Steps

Call the realm initialiser passing a configuration as a parameter for the 1st time. Since the database didn't exist before, no migration occurs at this moment. No other calls to realms with the same config are made concurrently. Happens on both main and non-main threads. Not reproduced on iOS/iPad OS 15.

### Version

10.27.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14, iPadOS 14

### Build environment

Xcode version: 13.3
Dependency manager and version: cocoapods 1.11.3

**Comment by pavel-ship-it** [comment]
Hi @PavelKandratsyeu, thanks for the info. Could you please give more info on Realm configuration and how you instantiating the Realm?

Can be related to #7741

**Comment by PavelKandratsyeu** [comment]
The issue isn't reproduced with the legacy build system.
