### ISSUE TITLE
EXC_BAD_ACCESS Crash on unit test when using List<Object>

### ISSUE THREAD

**Issue by ssjtin** [realm/realm-swift#7822]
### How frequently does the bug occur?

All the time

### Description

I have two objects, one contains a List<> of the other like this

```
class Template: Object {
    
    @Persisted(primaryKey: true) var id: String
    @Persisted var name: String?
    @Persisted var body: String?
```

```
class ConversationTemplatesObject: Object {

    @Persisted(primaryKey: true) var id: String
    @Persisted var templates: List<Template>     *** This line gets 1Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)1 ***
    @Persisted var postStayReviewScheduled: Bool = false
    @Persisted var expiryDate: Date
```

So this works fine in normal debug and prod.  But when trying to do anything in Unit Test, I get a crash at the List property indicated above.  This includes trying to fetch objects of a type, or even creating a new object unrelated to that class.

```
    func testCreateTemplateObject() {
        let inMemoryRealm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "MyInMemoryRealm"))
        
        let singleTemplate = Template(id: "12345", name: "My template", body: "This is a test template")
        do {
            try inMemoryRealm.write {
                inMemoryRealm.create(Template.self, value: singleTemplate, update: .modified)
            }
        } catch let error {
            print(error)
        }
    }
```
This gets a crash, even though I'm not doing anything related to the `ConversationTemplatesObject`, it still registers a crash at that exact line.

### Stacktrace & log output

```shell
#0	0x00007fff30ca86b4 in swift::TargetMetadata<swift::InProcess>::isCanonicalStaticallySpecializedGenericMetadata() const ()
#1	0x00007fff30cb3f8c in swift::MetadataResponse performOnMetadataCache<swift::MetadataResponse, swift_checkMetadataState::CheckStateCallbacks>(swift::TargetMetadata<swift::InProcess> const*, swift_checkMetadataState::CheckStateCallbacks&&) ()
#2	0x00007fff30cb3f5b in swift_checkMetadataState ()
#3	0x0000000131b5df57 in type metadata completion function for PropertyStorage ()
#4	0x00007fff30cb73ed in swift::MetadataCacheEntryBase<(anonymous namespace)::GenericCacheEntry, void const*>::doInitialization(swift::MetadataWaitQueue::Worker&, swift::MetadataRequest) ()
#5	0x00007fff30ca9bb8 in _swift_getGenericMetadata(swift::MetadataRequest, void const* const*, swift::TargetTypeContextDescriptor<swift::InProcess> const*) ()
#6	0x0000000131ae2dba in __swift_instantiateGenericMetadata ()
#7	0x0000000131b5640d in type metadata accessor for PropertyStorage ()
#8	0x0000000131b56b40 in Persisted.init() ()
#9	0x000000012e92d98c in ConversationTemplatesObject.init() at /Users/holuong/Desktop/epcmobile-ios/epcmobile-ios/Messages/ConversationsModels.swift:61
```

### Can you reproduce the bug?

Yes, always

### Version

10.27.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Xcode 13.4 Simulator iPhone 13

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by ericjordanmossman** [comment]
Are you using cocoapods? 

Reading the stack trace I get a little lost after initializing the persisted and property storage. But I found some other swift metadata crashes in other libraries that look similar to this (and also only occur in unit testing). This might be related to how your targets are organized in cocoapods. 
See [here](https://github.com/ReactiveX/RxSwift/issues/2107) for more.

If it's _not_ could you share a .zip reproduction?

**Comment by leemaguire** [comment]
@ssjtin did you manage to solve the issue? I cannot reproduce on my end.

**Comment by sssuourabh** [comment]
hi @ssjtin i am still facing issue? how you have solved this.

**Comment by sssuourabh** [comment]
Thank you everyone i solved the issue - after reading this 
Test Targets
Don't link the Realm framework directly to your test target. This can cause your tests to fail with an exception message "Object type 'YourObject' is not managed by the Realm." Unlinking Realm from your test target should resolve this issue.

Compile your model class files in your application or framework targets; don't add them to your unit test targets. Otherwise, those classes are duplicated when testing, which can lead to difficult-to-debug issues.
[LINK](https://www.mongodb.com/docs/realm/sdk/swift/test-and-debug/)
<img width="931" alt="Screenshot 2023-10-23 at 1 36 37 AM" src="https://github.com/realm/realm-swift/assets/2918573/574b1169-fb8d-4cca-b6c8-a69d43377641">
