### ISSUE TITLE
Failed to install Realm with cocoapods

### ISSUE THREAD

**Issue by jvuong** [realm/realm-swift#7824]
### How frequently does the bug occur?

All the time

### Description

Realm is failing to install due to an invalid certificate

### Stacktrace & log output

```shell
> $ pod install                                                                                                                                                                                                    ⬡ system [±master ●]
Auto-linking React Native module for target `AIOApp`: ReactNativeNavigation
Analyzing dependencies
Downloading dependencies
Installing Realm (10.7.7)
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

Downloading dependency: 10.7.2 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v10.7.2.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v10.7.2.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Run `pod install` to reproduce the issue.

### Version

10.7.7

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS builds

### Build environment

Xcode version: 13.3.1
CocoaPods version: 1.10.1

**Comment by studiogaram** [comment]
It is probably an incident caused by the expiration of the SSL certification of the domain that provides pods. It seems that the confirmation of the operator is needed.

![image](https://user-images.githubusercontent.com/3108770/171982630-bdf53eac-806b-410d-a26c-3d4b6f6d0555.png)

**Comment by jvuong** [comment]
@studiogaram Yes, I should have been clearer in my report that the installation failure is due to an expired certificate.  I hope this is the right place to open the issue to get this resolved.

**Comment by jvuong** [comment]
The certificate expiration seems to be resolved now.
