### ISSUE TITLE
static.realm.io SSL certificate expired

### ISSUE THREAD

**Issue by zykis** [realm/realm-swift#7825]
### How frequently does the bug occur?

All the time

### Description

Could you please update static.realm.io certificate, so tuist/carthage would be able to build my project?

### Stacktrace & log output

```shell
Downloading dependency: 11.14.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.14.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.14.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
```
```


### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Try to build a tuist project with realm-swift as external dependency

`.github(path: "realm/realm-swift", requirement: .exact("10.25.1")),`

### Version

10.25.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by nirinchev** [comment]
Hey zykis, apologies for that. We're having the SRE team look into it.

**Comment by zykis** [comment]
Is there any information considering the issue or is there a way to connect the SRE team?

**Comment by nirinchev** [comment]
The SRE team is looking at updating the certificate but it'll likely be a couple of hours before they resolve the issue.

**Comment by zykis** [comment]
Thank you :)

**Comment by stephengilroy-grx** [comment]
Ah looks like we are having this issue as well. Any updates on a fix?

```
Downloading dependency: 11.3.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.3.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.3.0.tar.xz
	curl: (35) error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure
command failed, error: pod install failed: exit status 1
```

**Comment by dimkagithub** [comment]
Hi!
The same problem.

`[!] /bin/bash -c 
set -e
sh scripts/setup-cocoapods.sh

Downloading dependency: 12.1.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.1.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.1.0.tar.xz
	curl: (35) error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure

`

**Comment by nirinchev** [comment]
Hey folks, apologies again for the disruption. It should all be good. I'm closing the issue, but if anyone continues to experience problems downloading the binaries, feel free to comment/reopen.

**Comment by dimkagithub** [comment]
Great! It upgrades now!

**Comment by Asifnewaz** [comment]
Issue is not solved yet, I'm facing same issue

**Comment by chanhdatng** [comment]
Me too, I'm facing same issue 
```
[!] /bin/bash -c
set -e
sh scripts/setup-cocoapods.sh

Downloading dependency: 12.11.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.11.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.11.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by hawflakes** [comment]
@nirinchev can you get someone to cycle the cert?

**Comment by huihuang82** [comment]
hit this too

```
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

Downloading dependency: 11.3.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.3.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.3.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
```

**Comment by muhamadakoum** [comment]
> The SRE team is looking at updating the certificate but it'll likely be a couple of hours before they resolve the issue.

Failing again

**Comment by IanTaehoonYoo** [comment]
Me too
`Downloading dependency: 12.11.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.11.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.11.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.`

**Comment by liuduoios** [comment]
It fails now.

```
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

Downloading dependency: 11.6.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.6.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.6.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html`
```

**Comment by SPHthabib** [comment]
I am also facing the same issue

```
Installing Realm (10.32.3)

[!] /bin/bash -c 
set -e
sh scripts/setup-cocoapods.sh

Downloading dependency: 12.11.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.11.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.11.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by bmunkholm** [comment]
We are very sorry about this and are looking into fixing this asap.

**Comment by royherma** [comment]
Hey, please re-open this issue / add an alert to save the panic that many devs will encounter in the meantime 🙏🏻❤️

**Comment by mehul2013** [comment]
@royherma You can another thread here: https://github.com/realm/realm-swift/issues/8092

**Comment by shirishbankar1** [comment]
Getting same error on M1 Mac. 
<img width="931" alt="Screenshot 2023-01-09 at 3 12 29 PM" src="https://user-images.githubusercontent.com/22815097/211281581-f1cf68fb-3795-44eb-986a-55304ecb4867.png">

**Comment by drmas** [comment]
A workaround for React Native apps is to disable node certificate check using:
NODE_TLS_REJECT_UNAUTHORIZED=0 yarn or NODE_TLS_REJECT_UNAUTHORIZED=0 npm install
