### ISSUE TITLE
Xcode 14Beta Build Failed

### ISSUE THREAD

**Issue by hdcola** [realm/realm-swift#7828]
### How frequently does the bug occur?

All the time

### Description

When I build project,  RealmSwift/SwiftUI.swift has some error

### Stacktrace & log output

```shell
Type 'V' does not conform to protocol 'RealmCollectionValue'
Reference to member 'remove' cannot be resolved without a contextual type
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

use Xcode 14Beta building

### Version

10.27.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS 12.4

### Build environment

Xcode version: 14.0Beta

**Comment by tgoyne** [comment]
This is listed as a known issue in the Xcode 14 release notes.

**Comment by aheze** [comment]
Quoting from the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes):
> Due to a bug in the new generics implementation in Swift 5.7, the Realm Swift project fails to build with a type check error “type ‘V’ does not conform to protocol ‘RealmCollectionValue’.” (91594361)

> Workaround: Disable the new generics implementation by adding `OTHER_SWIFT_FLAGS='-Xfrontend -requirement-machine-inferred-signatures=off'` to the library’s build settings. Note that this workaround disables bug fixes and performance improvements in the new generics implementation; therefore, only use it when needed to work around this Swift generics bug.

> If using Swift Package Manager, add Realm as a local package. Then in Realm’s `Package.swift` file, add the following parameter to “RealmSwift” target: `swiftSettings: [.unsafeFlags(["-Xfrontend", "-requirement-machine-inferred-signatures=off"])]`

**Comment by aheze** [comment]
All the errors seem to come from `RealmSwift/SwiftUI.swift`... so in my fork I deleted the file and it works.
Until this gets fixed, feel free to use my fork. Package URL:

```
https://github.com/aheze/realm-swift
```
![Screen Shot 2022-06-06 at 8 48 23 PM](https://user-images.githubusercontent.com/49819455/172291847-09d2b9ff-f56a-440b-812b-69daeae51a88.png)

*Build Succeeded!*

**Comment by gongzhang** [comment]
The workaround above works, but still fail to build when targeting to _watchOS_.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/4470629/172313832-58edcee6-d3da-47f5-8c66-23cae92e17ca.png">

 I found now there are three architectures for Apple Watch. It might be related to this.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/4470629/172313179-14018081-5631-48cb-8c2a-3b314f99adcd.png">

**Comment by cemonet** [comment]
Pour les podfile:
```
disableGenerics = ['RealmSwift']

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if disableGenerics.include?(target.name)
                config.build_settings['OTHER_SWIFT_FLAGS'] = '-Xfrontend -requirement-machine-inferred-signatures=off'
            end
        end
    end
end
```

**Comment by developerfromjokela** [comment]
I just forked and added swiftsettings:
https://github.com/developerfromjokela/realm-swift

Just add this repo as dependency instead of realm's repo
