### ISSUE TITLE
Allow for Collection Grouping in 'Flexible Sync' - by not requiring all 'queryable fields' in each collection

### ISSUE THREAD

**Issue by reveelapp** [realm/realm-swift#7830]
### Problem

Currently each provided ‘`queryable field`’ must be in each and every class in 'Flexible Sync'. This forces a developer to create generic names to fit the 10 max limit (e.g., in larger products or complex ones). With that, this causes extra fields not needed in each class that are there for 'Flexible Sync'. Further, these properties will end up handling values differently for data based on usage to satisfy 'Flexible Sync' requirements rather than actual product's usage requirements.

### Solution

Regardless, of the limit or product size, it is more ideal to sync only those that include a matching  ‘`queryable field`’. This way developers can group their data structures with specific ‘queryable fields’ that apply to their needs. Take for example an app that does online gambling. They could divide their code for Users, Bets,  Game, States, etc. Each set would need its own 3-7 (est.) ‘queryable fields’. If a role defined in Sync Permissions comes across a Collection that does not have (all) such ‘`queryable field`’ then that Collection is ignored for that Permission’s role. [usage error case] If a developer uses default roles (i.e., non-Collection based) and misses a '`queryable field`', shame on them for the mistake, they will then just need to add that in, on the cloud-side's Sync Permission's JSON.

Yes - this way the '`queryable field`' design is a bit more, but it would also reduce data being queried in a session.

Now the question about how many ‘queryable fields’ to then allow can be handled too … here are some ideas. 
Some ideas (prioritized):
A)	have developers use a declaration attribute (e.g., in Swift) and limit 7 per collection (I personally only need 1-3 per collection). This way the declaration of 'queryable fields' are not handled on cloud-side. They could be pushed while in “DEV mode” or manually added in Schema to match the Collection. Maybe something similar to how Document relationships are manually added.
B)	allow 10 per group, which means each group has its own Sync Permissions to define and would mean to create a new section called groups.
C)	Increase the limit from 10 to some bigger number - as a generic way.

### How important is this improvement for you?

Dealbreaker

**Comment by dianaafanador3** [comment]
@reveelapp Flexible Sync doesn't force you to have every queryable fields within all the Object classes of your schema, you only need to list all the queryable field you are using in your `QuerySubscription` queries.
For example if you add the following subscriptions to your realm, you would need to add the firstName and age to your queryable fields. 
```
subscriptions.update {
            subscriptions.append(
                QuerySubscription<Person> {
                    $0.firstName == "Alex"
                })
            subscriptions.append(QuerySubscription<User> {
                $0.age > 0
            })
        }
```
The limitation for the number of queryable fields is 10 max at the moment, but you can add a queryable field which is used in different Objects classes. For example you can add one queryable field for the following subscriptions
```
subscriptions.update {
            subscriptions.append(
                QuerySubscription<SwiftPerson> {
                    $0.firstName == "Alex"
                })
            subscriptions.append(QuerySubscription<SwiftTypesSyncObject> {
                $0.firstName.contains("Alex")
            })
        }
```
This is what you mean?

**Comment by reveelapp** [comment]
@dianaafanador3 - I forgot to mention after trying to add the new backend collections. If I updated the Sync Permission JSON,  I would also get this preventative-error message in the Sync page too, as follows:
"_default roles can't be used for table "ActiveUsers": invalid permissions for 'read': invalid match expression: key "userID" is not a queryable field_"

The error message provides the first missing '`queryable field`' in the list of 10.

**Comment by reveelapp** [comment]
@ianpward 

Are you basically saying that in the Sync Permission's JSON, there MUST be a permission 'role' that affects each Collection when the "default" role will NOT cover them all?  Then within that collection's 'role' you do not have to use any '`queryable field'`,  rather that it needs to be covered as a 'role'? -I thought I tested that too, but will do it again .. If that works, that make more functional sense. 

Please let me know if I am on the right track with my question above and then I can test it out. Thank you!

**Comment by reveelapp** [comment]
@ianpward & @dianaafanador3 

OK - retested by applying roles on the collections that did not have all 'queryable fields'. This way when the '`defaultRoles`' cannot cover all collections (due to missing a '`queryable field`'), it is now handled by covering those through collection-based 'roles' (via '`rules`' for those collections). There is now no error.

I'd like to recommend to update the [documentation on this page](https://www.mongodb.com/docs/atlas/app-services/sync/data-access-patterns/flexible-sync-permissions-guide/#about-these-examples), to replace "you can override" to "you need to apply". Here is the _current_ full text that I am referring to: 
"In particular, if a rule in the defaultRoles uses a "queryable field" that doesn't exist on objects in a certain collection, **_you can override_** the rules for that collection by providing a collection-specific role. See [Flexible Sync Session Roles and Rules](https://www.mongodb.com/docs/atlas/app-services/sync/data-access-patterns/permissions/#std-label-flexible-sync-roles)."
