### ISSUE TITLE
RLMProgressNotificationToken released without unregistering a notification. You must hold on to the RLMProgressNotificationToken and call -[RLMProgressNotificationToken invalidate] when you no longer wish to receive progress update notifications.

### ISSUE THREAD

**Issue by anton-plebanovich** [realm/realm-swift#7831]
### Description

The error is falsely produced when a session is released before `invalidate` for a token is called causing an inability to reset the `_token` value and so producing a misleading error message. On the screenshot is the proposed solution but I don't know the Realm source base good enough so it's up to you.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/10807812/172525067-eae60bdf-6a7b-41da-b697-f17630ac3cf1.png">

### Version

10.27.0

**Comment by anton-plebanovich** [comment]
> Do you know what's causing the session to be released that makes you think the error falsely produced? That may be the issue. I think never having a progress_notifier exist whose token was released is intentional.

Well, I did what the warning says, I hold the token and then called `invalidate` when I no longer need it but still received the warning on the `dealloc` so I assumed it is missleading because I spent some time to investigate my logic while it was working fine.

This is happening on the `App` switch during ongoing load and overall is minor since there are no other issues.

**Comment by ericjordanmossman** [comment]
What is the "`App` switch"? How are you storing the token? 
It sounds like you're able to reproduce reliably -- could you share a .zip so the team can check it out?

That'd be super helpful.

**Comment by anton-plebanovich** [comment]
Please check the reproduction example here https://github.com/anton-plebanovich/SingleView/tree/realm/notification-token-bug
