### ISSUE TITLE
Filter using object property called 'size' results in exception

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-swift#7855]
### How frequently does the bug occur?

All the time

### Description

Using Filter() with a property name of 'size' causes a crash.

See ViewController below for full example (tested with RealmSwift v10.27.0)

```
class TestObject: Object {
    @objc dynamic var _id = UUID().uuidString
    @objc dynamic var tstamp: Date = Date()
    @objc dynamic var code: String = ""
    @objc dynamic var name: String = ""

/// The unhappy 'size' property
    @objc dynamic var size: String = ""
    
    override static func primaryKey() -> String? {
        return "_id"
    }
}

// this work fine
let filtered = realm.objects(TestObject.self).filter("code contains[c] %@", "2")

// The following line throws an exception
// "Predicate expressions must compare a keypath and another keypath or a constant value"
// It seems it does not like using a proper name of 'size'

let filtered = realm.objects(TestObject.self).filter("size contains[c] %@", "2")


// This code works fine

let filtered = objects.filter("%K contains[c] %@", "size", "2")

```

### Stacktrace & log output

```shell
"Predicate expressions must compare a keypath and another keypath or a constant value"
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```
//
//  ViewController.swift
//  RealmTest
//
//  Created by Duncan Groenewald on 21/6/2022.
//

import Cocoa
import RealmSwift

class ViewController: NSViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        
        test()
    }

    override var representedObject: Any? {
        didSet {
        // Update the view, if already loaded.
        }
    }

    var realm: Realm? {
        do {
            let realm = try Realm()
            return realm
        } catch {
            return nil
        }
    }
    
    func test() {
        
        guard let realm = self.realm else {
            print("Error opening realm")
            return
        }
        
        let objects = realm.objects
        
        if objects.isEmpty {
            realm.createObjects()
        }
        
        let filtered1 = objects.filter("name contains[c] %@", "2")
        
        for obj in filtered1 {
            print("\(obj.code), \(obj.name), \(obj.size)")
        }
        
        // The following line will crash with the following error
        // 'Predicate expressions must compare a keypath and another keypath or a constant value'
        // It seems 'size' is not allowed as a property name ??
        
        let filtered = objects.filter("size contains[c] %@", "2")
            
        
        for obj in filtered {
            print("\(obj.code), \(obj.name), \(obj.size)")
        }
        
    }

    
}


class TestObject: Object {
    @objc dynamic var _id = UUID().uuidString
    @objc dynamic var tstamp: Date = Date()
    @objc dynamic var code: String = ""
    @objc dynamic var name: String = ""
    @objc dynamic var size: String = ""
    
    override static func primaryKey() -> String? {
        return "_id"
    }
}


extension Realm {
    var objects: Results<TestObject> {
        self.objects(TestObject.self)
    }
    func createObjects(){
        
        self.beginWrite()
        
        for i in 1...100 {
            let obj = TestObject()
            obj.code = "\(i)"
            obj.name = "Name_\(i)"
            obj.size = "Size_\(i)"
            
            self.add(obj)
        }
        
        do {
            try self.commitWrite()
        } catch {
            print("Error: \(error.localizedDescription)")
        }
    }
    
}
```

### Version

RealmSwift v 10.27.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 12.4

### Build environment

Xcode version: 13.4.1
Dependency manager and version: SPM

**Comment by duncangroenewald** [comment]
Formatted test code

/```
/
//  ViewController.swift
//  RealmTest
//
//  Created by Duncan Groenewald on 21/6/2022.
//

import Cocoa
import RealmSwift

class ViewController: NSViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        
        test()
    }

    override var representedObject: Any? {
        didSet {
        // Update the view, if already loaded.
        }
    }

    var realm: Realm? {
        do {
            let realm = try Realm()
            return realm
        } catch {
            return nil
        }
    }
    
    func test() {
        
        guard let realm = self.realm else {
            print("Error opening realm")
            return
        }
        
        let objects = realm.objects
        
        if objects.isEmpty {
            realm.createObjects()
        }
        
        let filtered1 = objects.filter("name contains[c] %@", "2")
        
        for obj in filtered1 {
            print("\(obj.code), \(obj.name), \(obj.size)")
        }
        
        // The following line will crash with the following error
        // 'Predicate expressions must compare a keypath and another keypath or a constant value'
        // It seems 'size' is not allowed as a property name ??
        
        let filtered = objects.filter("size contains[c] %@", "2")
            
        
        for obj in filtered {
            print("\(obj.code), \(obj.name), \(obj.size)")
        }
        
    }

    
}


class TestObject: Object {
    @objc dynamic var _id = UUID().uuidString
    @objc dynamic var tstamp: Date = Date()
    @objc dynamic var code: String = ""
    @objc dynamic var name: String = ""
    @objc dynamic var size: String = ""
    
    override static func primaryKey() -> String? {
        return "_id"
    }
}


extension Realm {
    var objects: Results<TestObject> {
        self.objects(TestObject.self)
    }
    func createObjects(){
        
        self.beginWrite()
        
        for i in 1...100 {
            let obj = TestObject()
            obj.code = "\(i)"
            obj.name = "Name_\(i)"
            obj.size = "Size_\(i)"
            
            self.add(obj)
        }
        
        do {
            try self.commitWrite()
        } catch {
            print("Error: \(error.localizedDescription)")
        }
    }
    
}

```

**Comment by duncangroenewald** [comment]
Hmm - any tips for ensuring correctly formatted source code ??

**Comment by dianaafanador3** [comment]
HI @duncangroenewald we use Apple's framework `NSExpression` API to determine the expressionType of the NSPredicate, the returned expression type is not been parsed to a key path expression because size is a reserved word in the foundation framework.
You can use instead #size if you want to, or use any of the alternatives you proposed in the post above.
`let filtered = realm.objects(TestObject.self).filter("#size contains[c] %@", "2")`

**Comment by duncangroenewald** [comment]
@dianaafanador3 thanks - thanks, sorry I was a bit lazy, I should have checked that.
