### ISSUE TITLE
Potential Bug: Nested '`Object`' and '`List<Object>`' won't download to client (if 'false' on SyncPermission)

### ISSUE THREAD

**Issue by reveelapp** [realm/realm-swift#7858]
### How frequently does the bug occur?

All the time

### Description

I’d like to confirm what I am seeing in my testing… that a related ‘`Object`’ or ‘`List<Object>`’ will be prevented to download to a client-app... for a ‘Flexible Sync’ query if it has nested relationships that do not meet the conditions in Sync Permission’s (JSON) rules (set on cloud-side). 

Therefore, we must ensure that all nested relationships also meet conditions (just like the top-level does) for the complete results to be available. For example, if a ‘`Person`’ object has a ‘`List<Dogs>`’, but one of the dog objects does not meet the rules’ conditions, then that one dog object **_is not supposed_** to show up in that query (while other dog objects meeting conditions will), correct? **- I want to make sure that is the intended behavior in Flexible Sync, or a bug.**

### Can you reproduce the bug?

Yes, always

### Version

SWift SDK 10.28.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS

### Build environment

Xcode version: 13.3
Dependency manager and version: ...

**Comment by reveelapp** [comment]
Hi @kachalo, 

The subscriptions are there for this test. This is about the Sync Permissions (JSON) that are set on the cloud-side. Currently, they also seem the need to be satisfied. Which can complicate things, but not impossible. Personally, if the top-level is OK to allow syncing, then we (developers) can handle the rest on the client-side via subscriptions... that would be a better policy. 

... so still would like to know if this is intended behavior or is a bug - thank you!

**Comment by ericjordanmossman** [comment]
The behavior that @kachalo quoted is intended behavior. The client device would need permission for the linked objects.

If you want a top-level parent object to confer permission on children objects, then you could use embedded objects. Embedded objects don't have permissions independent of their parent. This might be what you're looking for.

**Comment by reveelapp** [comment]
Expected behavior was that Server's Sync Permissions would pull all related/nested objects (if top-level satisfied), _unless_ specific (Collection-based) rules are declared in Server's Sync Permission that affect the nested-object's. Thereby _then_ making those unsatisfactory to sync.

**Comment by kachalo** [comment]
I understand and share your concern, @reveelapp. We've got two independent mechanisms to filter data for a specific client: the subscription predicates and Sync Permissions JSON. It is a possibility they may go out of sync or be inconsistent. And it is an excellent question to be answered: whether it is intended behavior or a potential source of bugs?

**Comment by kachalo** [comment]
I have an addition, though. It is tempting to stick just for Sync Permissions JSON and set up the realm subscriptions to query all objects of a given entity. If business logic allows, we can avoid having to manage two sets of filtering rules.
However, I didn't find any mentions or recommendations that it is an acceptable way to go. Maybe @ericjordanmossman can clarify?

**Comment by reveelapp** [comment]
Hey @kachalo - thanks for commenting. I can share some of my own thoughts regarding all this. These are simply my assumptions... I feel the Realm Team will evolve all this and will give us more flexibility with subscriptions and queries over time. Currently, they want us to do the heavy-conditioning on the client-side - since that is where we can provide more code to do it, versus the cloud-side's JSON.

Yeah, I agree, let's see what they come back with. As I mentioned above in the "Expected behavior" post, that chopping-off (i.e., preventing) related '`Object`' data that are structurally part of an object's data purpose (since top-level passes) does not seem to be (IMHO) an intended behavior 🤷‍♂️.

**Comment by dianaafanador3** [comment]
Hi @reveelapp as mentioned before this is the intended behaviour, for now if you want to have more control on the client side, keeps this rules simple and use subscriptions to handle which data you want to be downloaded.
Thanks for the feedback, what we want is to make sure the developer has the best experience using our product
@ianpward this feedback is interesting regarding flexible sync.

**Comment by reveelapp** [comment]
Hi @dianaafanador3 - thanks for getting back to me!

Understood. I hope to see this change. It is not a huge issue and usually won't be a problem with most setups; though it just seems odd - that is all.

Thank you and have a great weekend!
