### ISSUE TITLE
Realm data access throws EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by E2-karthickperumal** [realm/realm-swift#7866]
### How frequently does the bug occur?

Sometimes

### Description

We face EXC_BAD_ACCESS exception while try to access the Realm data in tvOS.

### Stacktrace & log output

```shell
https://drive.google.com/file/d/1XkjuAjkklQe6_5WlYW3Dvy1PwhPBsOFJ/view?usp=sharing
```

### Can you reproduce the bug?

Not yet

### Version

RealmSwift 10.28.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

tvOS 14.0 above

### Build environment

Xcode version: 13.4
Dependency manager and version: cocoapods 1.11.3

**Comment by dianaafanador3** [comment]
Hi @E2-karthickperumal Is this related to this issue https://github.com/realm/realm-swift/issues/7865? Or this are two separate issues? Please attach a readable stack trace so we can diagnose the issue

**Comment by E2-karthickperumal** [comment]
> Hi @E2-karthickperumal Is this related to this issue #7865? Or this are two separate issues? Please attach a readable stack trace so we can diagnose the issue

Two separate issues. Here when I try to access realm objects it throws EXC_BAD_ACCESS exception in the RealmSwift pod file.

**Comment by dianaafanador3** [comment]
@E2-karthickperumal we need more information in order to diagnose the issue. Please attach the stack trace (the drive file is not available), also if you can reproduce the issue a sample project or code so we can do it in our side

**Comment by E2-karthickperumal** [comment]
> @E2-karthickperumal we need more information in order to diagnose the issue. Please attach the stack trace (the drive file is not available), also if you can reproduce the issue a sample project or code so we can do it in our side

 We can't reproduce the issue. The drive file is available now. It includes the stack trace.

**Comment by pavel-ship-it** [comment]
@E2-karthickperumal ,
Can you share the Realm schema and configuration and code snippet of how do you accessing Realm?

**Comment by E2-karthickperumal** [comment]
> @E2-karthickperumal , Can you share the Realm schema and configuration and code snippet of how do you accessing Realm?

Realm Configuration - https://drive.google.com/file/d/17GmvmEdYgDZJEWy8WBX3yoE3CXYfO-1k/view?usp=sharing
Realm Data Access - https://drive.google.com/file/d/1l7D484c5o6rjpr0hlEG-YcH2AyDbKrYv/view?usp=sharing

**Comment by E2-karthickperumal** [comment]
> @E2-karthickperumal, Thank you for the update. On the original screenshot I see you're added some changes to the code of `RLMBinaryDataToNSData` Is there any actual change or is it just your experiments remaining? Could you tell me also the error code for `EXC_BAD_ACCESS`?

No changes were added to the code of 'RLMBinaryDataToNSData' at the exception occurred time. The error code was ' EXC_BAD_ACCESS (code=1, address=0x10ff70000)'

**Comment by pavel-ship-it** [comment]
Can you narrow down the steps to reproduce the issue?

**Comment by E2-karthickperumal** [comment]
We can't reproduce the crash. As of the analysis, sudden power failure triggered the App crash. The sample project contains the Realm data access operation which was the crash triggering part from our observation.
Sample Project Link : https://github.com/E2-karthickperumal/RealmDB_Crash_Analysis

**Comment by leemaguire** [comment]
There are no references to any properties using `Data`/`NSData` in the sample app. @E2-karthickperumal if possible can you share the realm file which causes the issue?

**Comment by E2-karthickperumal** [comment]
@leemaguire 
 Realm file link : https://drive.google.com/file/d/1kvh4sh6piU3D4HFCBuAbbtV3lH2XE0-v/view?usp=sharing

**Comment by leemaguire** [comment]
Might be related to https://github.com/realm/realm-swift/issues/7896
