### ISSUE TITLE
Old version os realm-core links are broken

### ISSUE THREAD

**Issue by ttuygun** [realm/realm-swift#7884]
### How frequently does the bug occur?

All the time

### Description

I got the following error when I build the project 
`The specified key does not exist.` for the link of `https://static.realm.io/downloads/core/realm-core-5.23.8.tar.xz`

### Stacktrace & log output

```shell
grep: core/release_notes.txt: No such file or directory
Downloading dependency: core 5.23.8 from https://static.realm.io/downloads/core/realm-core-5.23.8.tar.xz
mv: rename core to core-5.23.8: No such file or directory
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```
git clone https://github.com/realm/realm-swift
cd realm-swift
git checkout v4.4.1
./build.sh download-core
```

### Version

4.4.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS

**Comment by tgoyne** [comment]
Why are you trying to run `download-core` on that version? That version requires the core+sync package to build, and `download-sync` does work.
