### ISSUE TITLE
The v10.28.2 release does not contain an Xcode 14 build asset despite claiming compatibility in the notes

### ISSUE THREAD

**Issue by daltonclaybrook** [realm/realm-swift#7886]
### How frequently does the bug occur?

All the time

### Description

The release notes for [v10.28.2](https://github.com/realm/realm-swift/releases/tag/v10.28.2) claim that the release is compatible with Xcode 14 beta 2, but the `realm-swift-10.28.2.zip` asset does not contain an XCFramework that is compatible with Xcode 14.

### Can you reproduce the bug?

Yes, always

### Version

v10.28.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS, tvOS, watchOS

### Build environment

Xcode 14 beta 2 (and beta 3)

**Comment by pavel-ship-it** [comment]
Hi @daltonclaybrook,
You can build XCFramework for beta version from the source code using `build.sh`. You can find the script in the `realm-swift` root.

**Comment by daltonclaybrook** [comment]
@pavel-ship-it Unfortunately, it looks like the Realm target does not build for watchOS device on Xcode 14. It seems to build fine for watch simulator, but building for device reports many linker errors like:
```
Undefined symbol: realm::ArrayMixed::init_from_mem(realm::MemRef)
Undefined symbol: realm::ArrayMixed::move(realm::ArrayMixed&, unsigned long)
Undefined symbol: realm::ArrayMixed::create()
Undefined symbol: realm::ArrayMixed::ArrayMixed(realm::Allocator&)
Undefined symbol: realm::ArrayMixed::ArrayMixed(realm::Allocator&)
Undefined symbol: realm::Decimal128::is_valid_str(realm::StringData)
```
etc

**Comment by daltonclaybrook** [comment]
Digging in, it looks like `realm-monorepo.xcframework` does not contain an `arm64` slice for watchos. Just `armv7k` and `arm64_32`.

**Comment by pavel-ship-it** [comment]
Thank's for the update @daltonclaybrook. I'll look into that

**Comment by gongzhang** [comment]
Still waiting for the next version of realm-core. I did not succeed in building the realm-core myself. 😢
