### ISSUE TITLE
Xcode 14.0 beta 3 "Based on Dependency Analysis" Compile Warning

### ISSUE THREAD

**Issue by dgpratt4** [realm/realm-swift#7891]
### How frequently does the bug occur?

All the time

### Description

I am getting the following warning in my project in Xcode 14.0 beta 3 after installing RealmSwift 10.28.2 through pods. The warning appears to specifically live on the 'Create Symlinks to Header Folders' build phase.

"warning build: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase."

<img width="582" alt="Screen Shot 2022-07-21 at 11 40 03 AM" src="https://user-images.githubusercontent.com/3002573/180261804-c596d8c3-2724-41f7-ba34-3b684afdab2c.png">

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Install RealmSwift v10.28.2 via Pods v1.11.3 to a client project and attempt to run the project in Xcode 14.0 beta 3.

### Version

10.28.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 16, MacOS 12.4

### Build environment

Xcode version: Xcode 14 beta 3
Dependency manager and version: Pods 1.11.3

**Comment by pavel-ship-it** [comment]
Hi @dgpratt4,
No worries, this is produced by cocoapods. It's working the same way in the Xcode 13 just without warning. You can continue use Realm.
Here is a ticket against cocoapods for that matter https://github.com/CocoaPods/CocoaPods/issues/11477
