### ISSUE TITLE
Collection Change Listener - Crash.

### ISSUE THREAD

**Issue by igorvoytovich** [realm/realm-swift#7892]
### How frequently does the bug occur?

All the time

### Description

Hello,

We use Realm collection changes listener code from docs (https://www.mongodb.com/docs/realm/sdk/swift/examples/react-to-changes/#register-a-collection-change-listener) to update a table view in the app.

Sometimes, during very intensive work with Realm, we get a crash on the tableview when it tries to insert a new cell into the table.

I already opened an issue related to this before (https://github.com/realm/realm-swift/issues/7798), which helped to fix one of the cases of reproducing this crash, but we found another one.

Here is the code to reproduce: https://gist.github.com/igorvoytovich/01eabf6760e207b8fb0ee1bc248885ef 
Just run this app and leave it running for a while, you will see the crash. 

Kindly let me know if you need more information.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Please find the code attached.

### Version

'10.25.2'

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14, iOS 15. Both simulators and devices.

### Build environment

Xcode version: 13.1
Dependency manager and version: CocoaPods

**Comment by pavel-ship-it** [comment]
Hi @igorvoytovich ,
What is the actual exception reason?

**Comment by igorvoytovich** [comment]
Hi @pavel-ship-it ,

Here is the crash:
<img width="1160" alt="Screen Shot 2022-07-25 at 17 09 28" src="https://user-images.githubusercontent.com/47663430/180797671-27fd1788-7585-4f79-b46f-83b88948b0ab.png">

**Comment by pavel-ship-it** [comment]
Yep, I can reproduce it. Thanks. I'll look into this

**Comment by pavel-ship-it** [comment]
At the moment I wouldn't say this is a bug in Realm, rather it's a synchronisation issue.
I can't say for sure the difference between `UITableView` `reloadData` and `performBatchUpdates`, but obviously the processes aren't same and the vital difference - call to `reloadData` will dismiss all the unfinished updates, which it's not the case for `performBatchUpdates`.
In terms of the sample app it means you need to maintain the state of the results during `performBatchUpdates` or use some kind of `debounce` as in reactive programming to reduce the updates rate. Or you can create an intermediate layer between Realm and UITableView which will handle that.

**Comment by igorvoytovich** [comment]
Hi @pavel-ship-it ,

Thanks for getting back to me.

Do you mean to reduce the frequency of Realm transactions? If you are talking about the frequency of table updates, then to be honest, I can’t even imagine how this can be done, given that updates are directly tied to changes in Results.

**Comment by pavel-ship-it** [comment]
@igorvoytovich I'm talking about the frequency of table updates.
Unfortunately batch updates are incapable to handle the flow. While reload data can maintain the flow it will be bad at presenting the smooth updates. If you need both - you need a custom solution. From the available open source solutions I can think of [RxRealmDataSources](https://github.com/RxSwiftCommunity/RxRealmDataSources)

**Comment by igorvoytovich** [comment]
@pavel-ship-it 

Seems like moving from:

```
self.tableView.performBatchUpdates({
        self.tableView.deleteRows(at: deletions.map({ IndexPath(row: $0, section: 0)}), with: .automatic)
        self.tableView.insertRows(at: insertions.map({ IndexPath(row: $0, section: 0)}), with: .automatic)
        self.tableView.reloadRows(at: modifications.map({ IndexPath(row: $0, section: 0)}), with: .automatic)
}, completion: nil)
```

to:
```
self.tableView.beginUpdates()
self.tableView.deleteRows(at: deletions.map({ IndexPath(row: $0, section: 0)}), with: .automatic)
self.tableView.insertRows(at: insertions.map({ IndexPath(row: $0, section: 0)}), with: .automatic)
self.tableView.reloadRows(at: modifications.map({ IndexPath(row: $0, section: 0)}), with: .automatic)
self.tableView.endUpdates()
```

Removes the crash. That is very weird and I can't explain it, because Apple in their docs recommend to use `performBatchUpdates`. Kinda ridiculous.

I will monitor for some time if I could catch th
<img width="477" alt="Screen Shot 2022-07-26 at 14 19 18" src="https://user-images.githubusercontent.com/47663430/180993992-164c6715-4e9b-45e5-8899-c17b1f01ab7f.png">
is crash.

**Comment by igorvoytovich** [comment]
@pavel-ship-it 

Yeah, seems like the core problem is `performBatchUpdates`, this function just can't handle a lot of updates, so buggy.

Moving to `beginUpdates()` and `endUpdates()` fixes the problem. And, by the way, we don't even need to implicitly specify the queue in listener code `observe(on: ...)` as you suggested in https://github.com/realm/realm-swift/issues/7798 . It works and does not crash even without specifying this param. Could you please advise if we should leave the `queue` explicit just in case? Does it affect anything? Maybe performance. 
What is the best practice?  Should we use just `observe { ... }` or `observe(on: .main) { ... }` when adding change listener on the main queue (from VC's viewDidLoad() for example) ?

Also perhaps it makes sense to update the documentation?

**Comment by pavel-ship-it** [comment]
@igorvoytovich 
Here you created everything on the main thread. Observe will call changes notification on current thread by default. In this case it's main so it will be same.
Passing the thread/queue would make sense when the observer created on another thread.
