### ISSUE TITLE
Optional values are Synced as null which breaks validation down the line

### ISSUE THREAD

**Issue by georgesjamous** [realm/realm-swift#7923]
### How frequently does the bug occur?

All the time

### Description

I am not sure if this is an issue with the **iOS Realm Sync in the Package** or it is the Realm App Server issue.
However, I will create it hoping for some guidance. 
Also this relates to an [existing report I filed here](https://www.mongodb.com/community/forums/t/bug-null-values-do-no-pass-validation/181896).

Basically objects with optional parameters are saved as `null` in the Database (after Sync), where they should be simply non-existent.

```swift
class MyObject: RealmObject {
   var name: String = "Hello"
   var file: FileObject?
}
class FileObject: EmbeddedObject {
   var url: String?
}

Case A:
let object = MyObject()
// object.file = null or setting the file to null if I am clearing a value

Case B:
let object = MyObject()
object.file = FileObject()
```

Database result after Sync with Realm
```json
// Case A
{ 
   "name": "Hello",
   "file": null
}
// Case B
{ 
   "name": "Hello",
   "file": {
      "url": null 
   }
}
```

The Null values are expected to be Non-Existent and not set to Null.
Why?? Because later in a cloud function update `collection.update` of name to "Hello1" the validation fails on the exiting Null Value, claiming it does not validate the schema. (Although it is Optional)

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Just save an object with some optional params, and check the database JSON value.
Then you can try to edit it using a cloud function, or even just validate it using Atlas Realm Schema

### Version

10.19.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

teste on 15.5

### Build environment

Xcode version: 13.4.1 (13F100)

**Comment by tgoyne** [comment]
This is working as intended. "Optional" in Realm means that it can be null, not that it's allowed to be missing.

**Comment by georgesjamous** [comment]
Yes, however, the validation from MongoDb Realm side is failing.

--
 
Lets say I save the object
```swift
class MyObject: RealmObject {
   var name: String = "Hello"
   var file: FileObject?
}
```

then the schema would be like so
```
{
    "properties": {
        ...
        "name": {
          "bsonType": "string"
        },
       file: { "bsonType": "object", ....},
   },
   "required": [_id, _partition],
   "title": "MyObject"
}
```

and the object in the Database will be
```
{
   _id: "1234", (type ObjectId)
  _partition: "", (type String)
  name: "Hello", (type String)
  "file": Null (type Null)
}
```

Then if in a cloud function I do:
```js
collection.update({ _id: 1234}, {name: "World"})
```

it fails due to: `could not validate document 'ObjectID("123")' for update`
and if I run the schema validator in Atlas I get this error `InvalidTypeError`

if I delete the Null key (file), the save succeeds. 

--

So either Nulls should be avoided and the key should simply not exist, 
or Null should pass validation in some way from Atlas Realm App Side.

**Comment by ianpward** [comment]
@georgesjamous Please see this thread and my response here, this should solve your issue - 
https://www.mongodb.com/community/forums/t/missing-mandatory-realm-fields-in-atlas/98801/27?u=ian_ward

I believe this should fix your issue

**Comment by georgesjamous** [comment]
Thank you, i did not know about this option. I will give it a try.
