### ISSUE TITLE
RealmSwift does not specify a Swift version

### ISSUE THREAD

**Issue by edison0951** [realm/realm-swift#7936]
### How frequently does the bug occur?

All the time

### Description

I use cocoapods-xcframework to build xcframework. But I receive a report like this:

[!] Unable to determine Swift version for the following pods:

- `RealmSwift` does not specify a Swift version and none of the targets (`SwiftDatabase-ios`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Can we add swift_version in the podspec?

### Stacktrace & log output

```shell
[!] Unable to determine Swift version for the following pods:

- `RealmSwift` does not specify a Swift version and none of the targets (`SwiftDatabase-ios`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:597:in `validate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:163:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-xcframework-0.2.4/lib/cocoapods-framework/util/pod_util.rb:78:in `installation_root'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-xcframework-0.2.4/lib/cocoapods-framework/frameworker.rb:35:in `build_in_sandbox'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-xcframework-0.2.4/lib/cocoapods-framework/frameworker.rb:27:in `build_framework'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-xcframework-0.2.4/lib/cocoapods-framework/frameworker.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-xcframework-0.2.4/lib/cocoapods-framework/command/framework.rb:62:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. gem install cocoapods-xcframework
2. pod framework RealmSwift.podspec

### Version

10.28.6

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

OSX

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by leemaguire** [comment]
`cocoapods-xcframework` is not a supported method of installation, only the traditional `cocoapods` is

**Comment by edison0951** [comment]
The realm-swift is support swift. Why can't we add swift_version in the podfile?
