### ISSUE TITLE
Warning about use of private API when uploading app with Xcode 14

### ISSUE THREAD

**Issue by SergejLogis** [realm/realm-swift#7945]
### How frequently does the bug occur?

All the time

### Description

After uploading app to App Store (or rather TestFlight, since it's BETA version of Xcode 14) I'm getting warning:
`The app references non-public selectors in Payload/MyApp.app/Frameworks/Realm.framework/Realm: authenticationDidCompleteWithError:`. 
I was using version 10.20.1 of Realm because of the performance issue. I have updated it to the most recent version 10.28.7. However, the warning is still displayed after the upload is finished.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Build app and upload it to App Store using Xcode Organizer.

### Version

10.20.1, 10.28.7

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15/16

### Build environment

Xcode version: Xcode 14 RC
CocoaPods 1.11.2

**Comment by tgoyne** [comment]
Are you using Game Center in your app? It appears that a [private Game Center framework happens to use the same method name as us](https://github.com/nst/iOS-Runtime-Headers/blob/master/PrivateFrameworks/GameCenterFoundation.framework/GKLocalPlayer.h). If you aren't and it's warning anyway then this seems like a bug in iTC that you should report to Apple.

Even if you are, it's pretty obnoxious that Apple just declares some method names forbidden in unrelated code and doesn't publish a list of them...

**Comment by SergejLogis** [comment]
Hello, @tgoyne! Thanks for the quick reply!

No, we don't use Game Center. 

It's probably worth mentioning, that our recent 2 releases were rejected by Apple for a similar reason - the use of private API. We didn't update anything significant in that recent versions and most definitely didn't introduce any private API usage. Both releases were approved after the appeal. We are using Realm 10.20.1 for a few months already and never had such issues before.

**Comment by tgoyne** [comment]
We added that method in v10.0.0, so the thing that changed is probably that Apple just recently added a new check.

**Comment by SergejLogis** [comment]
Yeah, I have come to the same assumption... Any suggestions on what should we do? I'm afraid Apple won't allow us to App Store and we are planning to release as soon as the final version of Xcode 14 will be available.
Thank you.

**Comment by tgoyne** [comment]
Please try building your app with https://github.com/realm/realm-swift/pull/7951 and submitting it. I'm pretty sure it'll work around the problem, but it'd be good to have confirmation. With CocoaPods, you can do this with:

```
pod 'Realm', git: 'https://github.com/realm/realm-swift.git', branch: 'tg/rename-sel'
pod 'RealmSwift', git: 'https://github.com/realm/realm-swift.git', branch: 'tg/rename-sel'
```

Note that you do need to explicitly mention the Realm pod when targeting a specific branch even if you don't normally include it.

**Comment by shimastripe** [comment]
I submitted this branch version via Swift Package Manager using Xcode 14.
And I passed Apple's review!

**Comment by SergejLogis** [comment]
We've been approved by Apple with RealmSwift 10.28.7. So this warning doesn't lead to rejection, at least for now. Looking forward for updated RealmSwift with the fix included 🤓

**Comment by kachalo** [comment]
We have the same issue when submitting builds for TestFlights from Xcode 14 RC.

**Comment by alexeydemidovkz** [comment]
I got same warning today with App Store version of Xcode.

**Comment by alexeydemidovkz** [comment]
I have (manually, as I need older version of Relam as dependency for another package) changed code according to [#7951](https://github.com/realm/realm-swift/pull/7951)
I still have this warning but it changed from:
```
App Store Connect Operation Error
The app references non-public selectors in Payload/myapp.app/Frameworks/
RealmSwift.framework/RealmSwift:get:

App Store Connect Operation Error
The app references non-public selectors in Payload/myapp.app/Frameworks/
Realm.framework/Realm: authenticationDidCompleteWithError:, get:
```

to:

```
The following issues occurred while distributing your application.

App Store Connect Operation Error
The app references non-public selectors in Payload/myapp.app/Frameworks/
Realm.framework/Realm: get:

App Store Connect Operation Error
The app references non-public selectors in Payload/myapp.app/Frameworks/
RealmSwift.framework/RealmSwift:get:
```
Not sure what does this mean?

**Comment by Infinity-James** [comment]
Tried fixing it by changing my Podfile like so:
`pod 'RealmSwift', :git => 'https://github.com/realm/realm-swift.git', :branch => 'tg/rename-sel'`
It doesn't even build because Xcode `Cannot find RLMCreateAsymmetricObjectInRealm is scope.`

**Comment by dianaafanador3** [comment]
@Infinity-James we just need to te rebase the branch from this PR https://github.com/realm/realm-swift/pull/7951, we'll try to make a release as soon as possible with the fix as well.

**Comment by Infinity-James** [comment]
I fixed this by unlocking `RLMApp.h` and `RLMApp.mm` and changing all instances of
`authenticationDiCompleteWithError`
to
`authenticationDidFailWithError`

My app is successfully uploaded. Hope that helps anybody else who needs a short-term fix.

**Comment by alexeydemidovkz** [comment]
> authenticationDidCompleteWithError

You don’t have any warnings? I have done the same but still have warnings, just without mention of “authenticationDidCompleteWithError”.

**Comment by eegrok** [comment]
I'm getting the same warning deploying using XCode 14 to TestFlight -- the deploy works, but gives a warning.

**Comment by alexeydemidovkz** [comment]
I submited the app with warnings to review and got approved
