### ISSUE TITLE
Strange rare crash while addingobjects

### ISSUE THREAD

**Issue by byljbdh** [realm/realm-swift#7952]
### How frequently does the bug occur?

Sometimes

### Description

Crashlytics catchs a lot of crash, it happens when I try to save array objects in realm. But I can't reproduce the bug.

The background is that, I have a buffer_queue, to create realm object(about app event) to array.  when the array is big enough, I save the objects to realm in a write_queue.

And I also has a timer, to upload those relam object to server, when the upload finished, I delete the realm objects. 
Thanks.

`  
 func saveToBuffer(with name: String, parameters: [String: Any]?) {
        bufferQueue.async {
            let obj = TDAnalyticsRmObj()
            obj.name = name
            if self.semaphore.wait(timeout: .distantFuture) == .success {
                self.buffer.append(obj)
                self.semaphore.signal()
            }
            if self.buffer.count >= self.bufferCount2Realm {
                self.saveAllBufferToRealm()
            }
        }
    }
`

`func saveAllBufferToRealm() {
        bufferQueue.async {
            if self.semaphore.wait(timeout: .distantFuture) == .success {
                let array = self.buffer
                self.buffer.removeAll()
                self.semaphore.signal()
                guard array.count > 0 else {
                    return
                }
                self.writeQueue.async {
                    autoreleasepool {
                        guard let realm = TDAnalyticsRmDB.shared.client() else {
                            return
                        }
                        do {
                            realm.beginWriteTransaction()
                            iLog("rlmBeginWrite", msg: "beginWriteTransaction ++")
                            realm.addObjects(array as NSFastEnumeration)
                            try realm.commitWriteTransaction()
                        } catch {
                            eLog(Self.LogModule, msg: "db error \(error)")
                        }
                    }
                }
            }
        }
    }`

### Stacktrace & log output

```shell
Crashed: TDAnalyticsSyncManager_write_realm
0  libobjc.A.dylib                0x2d20 objc_release + 16
1  Tide                           0x3d85f4 @objc TDAnalyticsRmObj.__ivar_destroyer (TDAnalyticsSyncManager.swift)
2  libobjc.A.dylib                0x77d0 object_cxxDestructFromClass(objc_object*, objc_class*) + 112
3  libobjc.A.dylib                0x4858 objc_destructInstance + 88
4  libobjc.A.dylib                0xd7d4 _objc_rootDealloc + 52
5  Tide                           0xf44614 -[RLMObjectBase dealloc] + 93 (RLMObjectBase.mm:93)
6  libswiftCore.dylib             0x2e4a60 swift_arrayDestroy + 68
7  libswiftCore.dylib             0x7cf3c _ContiguousArrayStorage.__deallocating_deinit + 44
8  libswiftCore.dylib             0x2efc20 _swift_release_dealloc + 28
9  Tide                           0x3dd5fc _swift_stdlib_malloc_size + 106 (LibcShims.h:106)
10 libswiftCore.dylib             0x2efc20 _swift_release_dealloc + 28
11 libsystem_blocks.dylib         0x1840 _Block_release + 184
12 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
13 libdispatch.dylib              0x3f4a4 _dispatch_lane_serial_drain$VARIANT$armv81 + 600
14 libdispatch.dylib              0x3ff44 _dispatch_lane_invoke$VARIANT$armv81 + 388
15 libdispatch.dylib              0x498e0 _dispatch_workloop_worker_thread + 608
16 libsystem_pthread.dylib        0x1e10 _pthread_wqthread + 284
17 libsystem_pthread.dylib        0x193c start_wqthread + 8
```

### Can you reproduce the bug?

Not yet

### Reproduction Steps

It is reported by automatically from users.
The RAM seems ok, crashs happens from 100MB to 700MB RAM.
I wasn't able to reproduce it by myself.

### Version

10.28.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 16,15, 14, iPad os 15. It seems has nothing to do with versions.

### Build environment

Xcode version: 14, 13
Realm framework version: 10.28.1
iOS/OSX version: 16,15,14
Dependency manager + version: Cocoapods 1.11.3

**Comment by byljbdh** [comment]
here's another stacktrace;
```shell
Crashed: TDAnalyticsSyncManager_write_realm
0  libobjc.A.dylib                0x2d20 objc_release
1  Tide                           0x3e68d8 @objc TDAnalyticsRmObj.__ivar_destroyer (TDAnalyticsSyncManager.swift)
2  libobjc.A.dylib                0x77d0 object_cxxDestructFromClass(objc_object*, objc_class*)
3  libobjc.A.dylib                0x4858 objc_destructInstance
4  libobjc.A.dylib                0xd7d4 _objc_rootDealloc
5  Tide                           0xf6a004 -[RLMObjectBase dealloc] + 93 (RLMObjectBase.mm:93)
6  libswiftCore.dylib             0x2e4a60 swift_arrayDestroy
7  libswiftCore.dylib             0x7cf3c _ContiguousArrayStorage.__deallocating_deinit
8  libswiftCore.dylib             0x2efc20 _swift_release_dealloc
9  Tide                           0x3ead94 partial apply for closure #1 in TDAnalyticsSyncManager.saveAllBufferToRealm() (<compiler-generated>)
10 libswiftCore.dylib             0x2efc20 _swift_release_dealloc
11 libsystem_blocks.dylib         0x1840 _Block_release
12 libdispatch.dylib              0x64094 _dispatch_client_callout
13 libdispatch.dylib              0x3f4a4 _dispatch_lane_serial_drain$VARIANT$armv81
14 libdispatch.dylib              0x3ff44 _dispatch_lane_invoke$VARIANT$armv81
15 libdispatch.dylib              0x498e0 _dispatch_workloop_worker_thread
16 libsystem_pthread.dylib        0x1e10 _pthread_wqthread
17 libsystem_pthread.dylib        0x193c start_wqthread
```

**Comment by dianaafanador3** [comment]
Hi @byljbdh I tried a similar code to yours on version `v10.28.1` and against our latest version, and I'm not able to reproduce your crash. 
What kind of dispatch queue are you using for the `bufferQueue` and the `writeQueue`?, What kind of buffer are you using to store the data to be written?

The issue seems to be related to the deallocation of the Objects that are saved in the realm, it looks like you are over-releasing the objects, this mean that an object is deallocated when it is still required, it may happen in cases where the  object may have been inadvertently set to nil or perhaps it was never initiated in the first place. 
Can you check if that's the case?

**Comment by byljbdh** [comment]
Sorry for replying so late.
What kind of dispatch queue are you using for the bufferQueue and the writeQueue?, What kind of buffer are you using to store the data to be written?
The code is:
`    

    private var buffer: [TDAnalyticsRmObj] = []
    private var semaphore: DispatchSemaphore = DispatchSemaphore(value: 1)
    private var bufferQueue: DispatchQueue = DispatchQueue(label: "TDAnalyticsSyncManager")
    private var writeQueue: DispatchQueue = DispatchQueue(label: "TDAnalyticsSyncManager_write_realm")`

Which is quite simple.
I'll check the overrealeaing sooner.  But anything from you would be more helpful. Thanks again.

**Comment by dianaafanador3** [comment]
With ARC this over-releasing should not be happening. May want to migrate your code to use the RealmSwift API instead of the Objective-C one, even though Objective-C use ARC as well, this may help. Even in pure Swift this may still be happening, due to compiler bugs.

**Comment by byljbdh** [comment]
Thanks. I'll try migrate it to RealmSwift.
