### ISSUE TITLE
Is there a way for flexible sync to query on a list field? This is a necessary feature

### ISSUE THREAD

**Issue by archidvignesh** [realm/realm-swift#7953]
### Problem

Say you have a chat application. It can have one - one chats as well as group chats. Now I need to display the inbox screen which will contain an overview of one-one chats and group chats just like Whatsapp and it has to work real time so flexible sync is an awesome option. But

The best data model for this would be to have an array of participants aka **participants_field** in mongoDB and whoever is the currentUser in the app can just query the **ChatRoom** collection where **participants_field** contains **currentUserId**

Is there a way to create a flexible sync subscription that does the above? As far as I know, this is not possible in flexible sync or am I wrong?

### Solution

`		guard let currentUid = Auth.auth().currentUser?.uid else {return}
		realmUser = try await app.login(credentials: Credentials.anonymous)
		
		self.configuration = realmUser?.flexibleSyncConfiguration(initialSubscriptions: { subs in
			if subs.first(named: ChatRoom.rawString) == nil {

				subs.append(QuerySubscription<ChatRoom>(name: ChatRoom.rawString, query: { chatRoom in
					chatRoom.participants.contains(currentUid)
				}))
			}
				
		}, rerunOnOpen: true)
				
		realm = try! await Realm(configuration: configuration!, downloadBeforeOpen: .always)`

### How important is this improvement for you?

Dealbreaker

**Comment by dianaafanador3** [comment]
Hi @archidvignesh adding a subscription with a query like the one in you example it is possible. 
For example, for the following model 
```
public class Contact: Object {
    @Persisted(primaryKey: true) public var _id: ObjectId = ObjectId.generate()
    @Persisted public var name: String = ""
    @Persisted public var phoneNumbers: RealmSwift.List<String> = RealmSwift.List<String>()

    public convenience init(name: String) {
        self.init()
        self.name = name
    }
}
```
If you add a subscription like the following one
```
let config = user.flexibleSyncConfiguration(initialSubscriptions: { subs in
            subs.append(QuerySubscription<Contact>(name: "name", query: {
                $0.phoneNumbers.contains("000000000")
            }))
        })
```
This should work as expected and will only sync the `Contact`s that includes in the phoneNumbers array the string in the query subscription.

Did you set up the queryable field in the Device Sync configuration in Atlas.
If the model doesn't correspond to the sample below, please attach a code sample of the model.

**Comment by archidvignesh** [comment]
Hi @dianaafanador3 . I actually did not try this out as I was going through the documentation to see if this is possible. It says in the documentation that fields in **embedded objects** and also fields of the **List** type cannot be queried in flexible sync. Can you confirm this?

Here is the article. Please look for the heading **Flexible Sync RQL Limitations**:

[https://www.mongodb.com/docs/realm/realm-query-language/#std-label-flexible-sync-rql-limitations]

**Comment by archidvignesh** [comment]
Ok I just tested this out. Works as expected. Maybe the documentation needs some clarity on this cuz it says List fields cannot be added as a query
