### ISSUE TITLE
App Store Connect Operation Error: app references non-public selector authenticationDidCompleteWithError

### ISSUE THREAD

**Issue by marcolabreu** [realm/realm-swift#7954]
### How frequently does the bug occur?

All the time

### Description

After choosing Product / Archive in the just released Xcode 14, any attempt to upload the app in the Organizer will fail with **App Store Connect Operation Error**, The app references non-public selectors in Payload/(...): authenticationDidCompleteWithError:.

This reference is in Realm [RLMASLoginDelegate](https://www.mongodb.com/docs/realm-legacy/docs/objc/latest/api/Protocols/RLMASLoginDelegate.html).

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Using Xcode 14

1. Archive app
2. Choose Distribute App in the Organizer

### Version

Realm 10.29.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS Monterrey 12.6

### Build environment

Xcode version: 14.0
Dependency manager and version: Swift Package Manager

**Comment by dianaafanador3** [comment]
This is a duplicate from this https://github.com/realm/realm-swift/issues/7945, and a fix is an already on the making.
You can follow the instructions from [this comment](https://github.com/realm/realm-swift/issues/7945#issuecomment-1242172957) if you are in a hurry.
