### ISSUE TITLE
Xcode 14.0 'Create Symlinks to Header Folders' warning

### ISSUE THREAD

**Issue by anton-plebanovich** [realm/realm-swift#7957]
### How frequently does the bug occur?

All the time

### Description

When build an app with Xcode 14.0 it produces a warning:
```
Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
```
<img width="393" alt="image" src="https://user-images.githubusercontent.com/10807812/190491340-78c78e28-7e30-4d64-a981-4996f04b3ef5.png">

For our run script build phases it was an easy fix we just had to remove `Based on dependency analysis` checkmar from `Run script` configuration. Not sure how it is done for cocoapods though.
<img width="714" alt="Screenshot 2022-09-15 at 22 22 14" src="https://user-images.githubusercontent.com/10807812/190491458-2a88c955-fa47-43d3-9ca1-5ccf3775fd84.png">

### Stacktrace & log output

```shell
-
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Build a project with Realm

### Version

10.29.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS 12.5.1

### Build environment

Xcode version: 14.0
Dependency manager and version: Cocoapods 1.11.3

**Comment by tgoyne** [comment]
This is not something we have any control over; you'll need to report it to CocoaPods.

**Comment by anton-plebanovich** [comment]
Thanks @tgoyne you are right, there is already an issue for that
https://github.com/CocoaPods/CocoaPods/issues/11477

Hence, closing this one

**Comment by anton-plebanovich** [comment]
Workaround for now:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Realm'
      create_symlink_phase = target.shell_script_build_phases.find { |x| x.name == 'Create Symlinks to Header Folders' }
      create_symlink_phase.always_out_of_date = "1"
    end
  end
end
```
