### ISSUE TITLE
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by visdyn** [realm/realm-swift#7958]
### How frequently does the bug occur?

All the time

### Description

This code will not allow XCode to compile the project and throws the error in the title. There is another bug report with the same title but the cause/issue appears to be different.

```
let realm = try! Realm()
let results = realm.objects(ProductClass.self).where { $0.product_type == "" && $0.family == "" && $0.processor == "" && $0.gpu == "" && $0.ram == "" && $0.storage == "" && $0.color = "" }
```

There is nothing else in the project.

However, this code compiles fine. Remove the last and statement `&& $0.color = ""`

```
let realm = try! Realm()
let results = realm.objects(ProductClass.self).where { $0.product_type == "" && $0.family == "" && $0.processor == "" && $0.gpu == "" && $0.ram == "" && $0.storage == "" }
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Reproduce: Create a new project, add Realm either via SPM or Cocoapods. Add import RealmSwift and in the main viewController viewDidLoad, copy and paste those lines. 

### Version

10.29.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 12.5.1

### Build environment

Xcode version: ...
Dependency manager and version: ...

XCode Version 14.0 (14A309)

**Comment by visdyn** [comment]
Well, I found the issue but I don't know *why* it's an issue.

Using a property name `color` on a Realm object is the cause

The ProductClass looked like this

class ProductClass1: Object {
    @Persisted var product_type = ""
    @Persisted var family = ""
    @Persisted var processor = ""
    @Persisted var gpu = ""
    @Persisted var ram = ""
    @Persisted var storage = ""
    @Persisted var color = ""
}

and then I changed it to this

class ProductClass1: Object {
    @Persisted var product_type = ""
    @Persisted var family = ""
    @Persisted var processor = ""
    @Persisted var gpu = ""
    @Persisted var ram = ""
    @Persisted var storage = ""
    @Persisted var product_color = ""    //change
}

**Comment by dianaafanador3** [comment]
@visdyn I tested your code and at first I got a compilation error bit after many attempts I was able to build successfully, then I added a `color` property like you mentioned in your last comment and it is working as well. 
You probably have to wait for the type checker to slowly process your natural code and the type checker issue to be fixed.

**Comment by dianaafanador3** [comment]
Another reason for this to happen is if you have an error within the expression, because we use dynamic lookup it means you can use any property name which may not be declared in the object.

**Comment by visdyn** [comment]
Thanks for looking into it. I am not sure I am clear on your process. Keeping in mind I'm duplicating it across 4 different Macs all with the same result.

Are you saying that to get around it, you have to keep building the app over and over until the message clears?

If so, that's not working for me. I can compile it 20 times and it thows the same error - even being patient between builds.

A bit more info. The color vs product_color may have been a fluke. Here's why. I change the model to this

```
class ProductClass2: Object {
    @Persisted var a = ""
    @Persisted var b = ""
    @Persisted var c = ""
    @Persisted var d = ""
    @Persisted var e = ""
    @Persisted var f = ""
    @Persisted var g = ""
}
```

and then this code type-checks every time, builds and runs

`let results = realm.objects(ProductClass2.self).where { $0.a == "" && $0.b == "" && $0.c == "" && $0.d == "" }`

but this code will not type check on any device I try it on

`let results = realm.objects(ProductClass2.self).where { $0.a == "" && $0.b == "" && $0.c == "" && $0.d == "" && $0.e = "" }`

It seems like more then 4 && clauses cause the issue (just guessing at this point)

**Comment by visdyn** [comment]
I just took a brand new Mac out of the box, installed XCode and all current updates. Then created a brand new XCode project shown here in it's entirety

```
import Cocoa
import RealmSwift

class ProductClass2: Object {
    @Persisted var a = ""
    @Persisted var b = ""
    @Persisted var c = ""
    @Persisted var d = ""
    @Persisted var e = ""
    @Persisted var f = ""
    @Persisted var g = ""
}

class ViewController: NSViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let realm = try! Realm()
        let results = realm.objects(ProductClass2.self).where { $0.a == "" && $0.b == "" && $0.c == "" && $0.d == "" && $0.e = "" }
    }
}
```

and here's the result

<img width="1954" alt="Realm Type Check Test" src="https://user-images.githubusercontent.com/19558530/190708782-acb28d47-e177-434d-a3f3-d2b06585724d.png">


Removing the last `&& $0.e = "" ` allows it to work correctly.

**Comment by dianaafanador3** [comment]
In your last comment you have an issue in the expression
Instead of `&& $0.e = ""` it should be `&& $0.e == ""`
I know the error message should be more explicit, but because like mentioned before we use dynamic lookup we cannot control this.

**Comment by visdyn** [comment]
That is a really really good catch and a really really poor error message!

I understand why that happened but making Realm 'type safe' is great but not when it allows other errors, like a simple typo, to not be caught.

Thanks for your time 'debugging'. That seems to have corrected the issue. Will circle back if not.

**Comment by visdyn** [comment]
That is a really really good catch and a really really poor error message!

I understand why that happened but making Realm 'type safe' is great but not when it allows other errors, like a simple typo, to not be caught.

Thanks for your time 'debugging'. That seems to have corrected the issue. Will circle back if not.
