### ISSUE TITLE
It does not respect `&&` operator when filtering a list of embedded objects

### ISSUE THREAD

**Issue by robsontenorio** [realm/realm-swift#7961]
### How frequently does the bug occur?

All the time

### Description

It does not respect `&&` operator when filtering a list of embedded objects. 

In this specific case it filter correctly `key == "rooms"` but second statement `value == 4 ` seems to be ignored , once results brings rows with values different from `4`.

```swift
class Property: Object, ObjectKeyIdentifiable {
    @Persisted(primaryKey: true) var _id: ObjectId
    @Persisted var name: String
    @Persisted var specs: List<PropertySpec>

     // ...
}


class PropertySpec: EmbeddedObject, ObjectKeyIdentifiable {
    @Persisted var key: String
    @Persisted var value: Double?

    //  ...
}


struct SearchResultView: View {
    @ObservedResults(Property.self) var properties
   
     var filteredProperties: Slice<Results<Property>> {
        var results = properties
            .where {
              // It ignores && operator
              // Actually it seems to consider any value == 4, not only "rooms"
                $0.specs.key == "rooms" && $0.specs.value == 4     
            }

         return results.prefix(50)
     }

}
```

### Stacktrace & log output

```shell
There is no.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

- Create some `Property`s
- Foreach `Property` add random `key/value`  
- Assure at least one of them contains `key = room / value = 4`    
- In `SearchResultView ` it will list properties when "rooms" different from "4"

**I am suspecting it will consider any `spec.value` with `4`.**

Sample Data:

- Property 1
   - specs: 
       - rooms = 4
       - bathrooms = 3

- Property 2
   - specs: 
       - rooms = 3
       - bathrooms = 8

- Property 3
   - specs: 
       - rooms = 6
       - bathrooms = 4       // <---- suspect here!

### Version

10.29.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Mac OS 13 beta (22A5342f)

### Build environment

Xcode version: Version 14.0 (14A309)

<img width="191" alt="image" src="https://user-images.githubusercontent.com/118955/190650888-6868afc4-f628-4728-b9a0-46451c2ace4d.png">

**Comment by robsontenorio** [comment]
I also tried but it does not work, the list will be empty.

```swift
.where {
    $0.specs.contains(PropertySpec(key: "rooms", value: 4))
}
```

**Comment by dianaafanador3** [comment]
@robsontenorio I think the issue is the data model and not an issue with the query, correct me if I'm wrong but looking at your model
The following query
`$0.specs.key == "rooms" && $0.specs.value == 4`
translates to this
`((ANY specs.key == 'rooms') && (ANY specs.value == 4.0))`
and would return true in case of any spec has a key == "rooms" and any value to be == 4, in the specs array.

The second query which you tested 
`$0.specs.contains(PropertySpec(key: "rooms", value: 4))`
which translates to this 
`(%@ IN specs), where %@ is [PropertySpec(key: "rooms", value: 4)]`
 and I would have to get back to you if this is allowed even if it doesn't throw any error.
 
If you a bounded list of specs why not create a model that just contains the number of the element, but I guess you may want something more dynamic.

**Comment by robsontenorio** [comment]
@dianaafanador3 I am looking for something dynamic. 

Because each `Property` can have different `Specifications`. In that case there is a dozen of specs to be chosen when creating a new `Property`

So customers can look for : What `Property`s has `4 rooms`  and `1 pool` ?

**Comment by dianaafanador3** [comment]
@robsontenorio I think I found a solution for this.
Can you try the following query
`{ ($0.specs.key == "rooms" && $0.specs.val == 4.0).count > 0 }`
which translates to 
`(SUBQUERY(specs, $specs, (($specs.key == %@) && ($specs.val == %@))).@count > %@)`
You can get info about Subqueries in here
https://www.mongodb.com/docs/realm/realm-query-language/#subqueries

**Comment by robsontenorio** [comment]
@dianaafanador3 

Although I don’t think it is intuitive, I have mentioned that solution on my previous comment. 

Anyway , thanks !
