### ISSUE TITLE
RealmProperty<SomeClass?> does not automatically get added during migration

### ISSUE THREAD

**Issue by BlueCobold** [realm/realm-swift#7968]
### How frequently does the bug occur?

All the time

### Description

I have added some new optional fields to some of my realm objects and while I can easily add these as optional Float or Boolean fields in Java during a migration, I don't see any way to add them in a Swift migration block. They also do not automatically get added like @Persistet properties do. I thus cannot migrate the file on iOS, which stops me from releasing new versions on both platforms, because users can switch devices via export/import feature.

```
class MyRealmDTO: Object, ... {
    
    @Persisted var count: Int = 0
    @Persisted var stage: CollectionStageDO? = nil
    // new property
    let percentage = RealmProperty<Float?>()
    ...
```

I tried simply setting the value in my migration block in Swift, but this leads to an error about unknown field:
```
        if (version == 54) {
            migration.enumerateObjects(ofType: "MyRealmDTO") { old, new in
                new?["percentage"] = nil
            }
            version += 1
        }
```

The new property also does not get listed in migration.**newSchema**.objectSchema during a migration inside the migration block callback.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Add a RealmProperty<Boolean?> to an existing realm object. It will not be added to the table during migration.

### Version

10.25.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Not related

### Build environment

Xcode version: Version 13.2.1 (13C100)
Dependency manager and version: cocoapods 1.10.0

**Comment by dianaafanador3** [comment]
Hi @BlueCobold you cannot mix @Persisted property declaration with the old way of property declaration `@objc` or `RealmProperty`:
You have to declare your RealmProperty like this
`@Persisted percentage: Float?`

**Comment by BlueCobold** [comment]
Aha! Thanks a lot!
Alright, then maybe update the "Manual migration" documentation, please in regards to how to handle RealProperty, @Persisted and @objc declarations. It became quite a bit messy in the meantime, I think.
