### ISSUE TITLE
RealmSwift in CocoaPods was not updated to 10.30.0

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-swift#7970]
### How frequently does the bug occur?

All the time

### Description

It is still 10.29.0. Did you forget to update?

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

[RealmSwift on CocoaPods](https://cocoapods.org/pods/RealmSwift)

### Version

10.29.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 12.6 (21G115)

### Build environment

Xcode version: 14.0.1 (14A400)
Dependency manager and version: CocoaPods 1.11.3

**Comment by MaxRandom** [comment]
Hi!
Any updates on this?

**Comment by leemaguire** [comment]
Fixed
