### ISSUE TITLE
deleteObjects 方法崩溃

### ISSUE THREAD

**Issue by TianQiLi** [realm/realm-swift#7973]
### How frequently does the bug occur?

All the time

### Description

我的代码：
RLMResults * result = [My_StagesInfoModel allobjects];// 自定义数据查询
 RLMRealm * realm = [RLMRealm defaultRealm];
    if (result.count) {
        [realm transactionWithBlock:^{
            [realm deleteObjects:result];/// 运行到这里崩溃
            [realm addObjects:array];
        }];
    } 

### Stacktrace & log output

```shell
Operating system: iOS
                  14.5.0 18E198
CPU: arm64
     8 CPUs

GPU: UNKNOWN

Crash reason:  EXC_SOFTWARE / SIGABRT
Crash address: 0x1bc264334
Process uptime: 35 seconds

Thread 0 (crashed)
 0  libsystem_kernel.dylib!__pthread_kill + 0x8
    Found by: given as instruction pointer in context
 1  libsystem_pthread.dylib!pthread_kill + 0x10c
    Found by: previous frame's frame pointer
 2  libsystem_c.dylib!abort + 0x64
    Found by: previous frame's frame pointer
 3  myapp!please_report_this_issue_in_github_realm_realm_core + 0x8
    Found by: previous frame's frame pointer
 4  myapp!realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 0x100
    Found by: previous frame's frame pointer
 5  myapp!realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 0x144
    Found by: previous frame's frame pointer
 6  myapp!void realm::util::terminate<unsigned long, unsigned long>(char const*, char const*, long, unsigned long, unsigned long) [terminate.hpp : 45 + 0x4]
    Found by: previous frame's frame pointer
 7  myapp!realm::Array::move(unsigned long, unsigned long, unsigned long) + 0x158
    Found by: previous frame's frame pointer
 8  myapp!void realm::Cluster::do_erase<realm::ArrayInteger>(unsigned long, realm::ColKey) + 0x8c
    Found by: previous frame's frame pointer
 9  myapp!realm::util::FunctionRef<bool (realm::ColKey)>::FunctionRef<realm::Cluster::erase(realm::ObjKey, realm::CascadeState&)::$_3&>(realm::Cluster::erase(realm::ObjKey, realm::CascadeState&)::$_3&)::'lambda'(void*, realm::ColKey)::__invoke(void*, realm::ColKey) + 0x328
    Found by: previous frame's frame pointer
10  myapp!realm::TableClusterTree::for_each_and_every_column(realm::util::FunctionRef<bool (realm::ColKey)>) const + 0x50
    Found by: previous frame's frame pointer
11  myapp!realm::Cluster::erase(realm::ObjKey, realm::CascadeState&) + 0x9c
    Found by: previous frame's frame pointer
12  myapp!realm::ClusterTree::erase(realm::ObjKey, realm::CascadeState&) + 0x7c
    Found by: previous frame's frame pointer
13  myapp!realm::Table::batch_erase_rows(realm::BPlusTree<realm::ObjKey> const&) + 0x46c
    Found by: previous frame's frame pointer
14  myapp!realm::TableView::clear() + 0x8c
    Found by: previous frame's frame pointer
15  myapp!realm::Results::clear() + 0xd4
    Found by: previous frame's frame pointer
16  myapp!-[RLMResults deleteObjectsFromRealm] [RLMResults.mm : 491 + 0x4]
    Found by: previous frame's frame pointer
17  myapp!-[RLMRealm deleteObjects:] [RLMRealm.mm : 1018 + 0x4]
    Found by: previous frame's frame pointer
18  myapp!__41+[My_StagesInfoModel saveToLocal:array:]_block_invoke [CSP_StagesInfoModel.m : 60 + 0x8]
    Found by: previous frame's frame pointer
19  myapp!-[RLMRealm transactionWithoutNotifying:block:error:] [RLMRealm.mm : 777 + 0x8]
    Found by: previous frame's frame pointer
20  myapp!-[RLMRealm transactionWithBlock:error:] [RLMRealm.mm : 768 + 0x8]
    Found by: previous frame's frame pointer
21  myapp!-[RLMRealm transactionWithBlock:] [RLMRealm.mm : 764 + 0xc]
    Found by: previous frame's frame pointer
```

### Can you reproduce the bug?

Yes, always

### Version

10.28.5

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

14.5

### Build environment

Xcode version: 13.4
Dependency manager and version: ...

**Comment by BlueCobold** [comment]
Do I understand correctly, that you try to delete objects from a previous query in a different realm instance you opened after the query?

**Comment by leemaguire** [comment]
Hi @TianQiLi as you can always reproduce, can you send us a sample app that demonstrates the crash?

**Comment by TianQiLi** [comment]
@leemaguire  I may not be able to describe it exactly, and I can't reproduce it on my end, but this crash is definitely happening on one of the user's devices

**Comment by TianQiLi** [comment]
> Do I understand correctly, that you try to delete objects from a previous query in a different realm instance you opened after the query?



> 

 I may not be able to describe it exactly, and I can't reproduce it on my end, but this crash is definitely happening on one of the user's devices

**Comment by TianQiLi** [comment]
> Hi @TianQiLi as you can always reproduce, can you send us a sample app that demonstrates the crash?
I may not be able to describe it exactly, and I can't reproduce it on my end, but this crash is definitely happening on one of the user's devices

**Comment by TianQiLi** [comment]
> Hi @TianQiLi as you can always reproduce, can you send us a sample app that demonstrates the crash?

@leemaguire 
I may not be able to describe it exactly, and I can't reproduce it on my end, but this crash is definitely happening on one of the user's devices

**Comment by TianQiLi** [comment]
> 
// query the saved data 
RLMResults * result = [My_StagesInfoModel allobjects];
RLMRealm * realm = [RLMRealm defaultRealm];
if (result.count) {
[realm transactionWithBlock:^{
//delete the query data 
[realm deleteObjects:result];/// crash in here
// save the new data
[realm addObjects:array];
}];

**Comment by TianQiLi** [comment]
> Do I understand correctly, that you try to delete objects from a previous query in a different realm instance you opened after the query?

@BlueCobold  yes ,I want to delete all the data saved last time and store the new data

// query the saved data
RLMResults * result = [My_StagesInfoModel allobjects];
RLMRealm * realm = [RLMRealm defaultRealm];
if (result.count) {
[realm transactionWithBlock:^{
//delete the query data
[realm deleteObjects:result];/// crash in here
// save the new data
[realm addObjects:array];
}];

**Comment by BlueCobold** [comment]
Is this actually intended to work?

**Comment by leemaguire** [comment]
@TianQiLi can you give us more stacktraces for this issue? Can you also update to the latest version of Realm and see if that helps the problem.

**Comment by dianaafanador3** [comment]
Closing this as there is no response from the user.
