### ISSUE TITLE
App won't finish launching on "My Mac (Designed for iPad)" target when the realm file is open in realm studio

### ISSUE THREAD

**Issue by eegrok** [realm/realm-swift#7982]
### How frequently does the bug occur?

All the time

### Description

This appears to be very similar to bug #6743.

I frequently debug while leaving the realm studio open on my realm file, and launching my xcode app multiple times.

This works fine with iOS Simulator apps, as well as Mac apps, but hangs when I try to launch xcode using a "My Mac (Designed for iPad)" target.

I tried this on realm studio 11.2.1 using cocoa version 10.25.0 and coreversion 11.13.0
I also then updated to the latest, studio 12.0.0 using cocoa 10.30.0 and coreversion 12.7.0

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

open a Swift apps Realm file in Realm Studio, then run the Swift app using the target "My Mac (Designed for iPad)", and call:

let realm = try! Realm()

### Version

10.25.0, 10.30.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS 12.6

### Build environment

I'm running on an M1 Macbook Pro

Replicated using 10.25.0 with core 11.13.0
also with
10.30.0 and core 12.7.0

script output for build environment below:

ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115

/Applications/Xcode.app/Contents/Developer
Xcode 14.0.1
Build version 14A400

pod not found
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

carthage not found
(not in use here)

/usr/bin/git
git version 2.37.0 (Apple Git-136)

**Comment by eegrok** [comment]
have noticed it's not just a startup bug either -- if I launch realm studio after I have launched my app, it will lock up database operations in my app.

**Comment by dianaafanador3** [comment]
Hi @eegrok you should be able to do this using latest Realm Studio version and our latest version of the SDK. Please let us know if this working on your side.
