### ISSUE TITLE
SPM : Missing required modules: 'Realm.Private', 'Realm'

### ISSUE THREAD

**Issue by pitoneux** [realm/realm-swift#7992]
### How frequently does the bug occur?

All the time

### Description

When including Realm version 10.30 and above, using xcode 14.x SPM, it produced an error at link time: 
<img width="402" alt="Screen Shot 2022-10-14 at 6 24 55 PM" src="https://user-images.githubusercontent.com/1493686/195962881-982f381f-8c1d-45d2-9ea4-d35604d7ebac.png">

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Simply include in yout project Realm using Swift package manager from xcode.  When installing ream by downloading the pre-compiled version it works.

### Version

10.3x.x

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

ios 14.5 

### Build environment

Xcode version: 14.0.1 and 14.1 beta 3
Dependency manager and version: none. using spm within xcode

**Comment by ericjordanmossman** [comment]
@pitoneux Please try [this](https://github.com/realm/realm-swift/issues/6301#issuecomment-614225989) or [this](https://github.com/realm/realm-swift/issues/6301#issuecomment-1165208194) (with the latest version), and be sure to clean the build folder. This has sporadically popped over the [years](https://github.com/realm/realm-swift/issues/2135) and appears it can happen to swift modules in general, not just Realm or SPM ones.

**Comment by pitoneux** [comment]
yes. I don't this issue using 10.32 anymore (with xcode 14.0.1).

**Comment by ssup1** [comment]
Still reproduced in Xcode 14.1 and Realm 10.33.0
