### ISSUE TITLE
Realm file is currently open in another process which cannot share access with this process

### ISSUE THREAD

**Issue by Kernelzero** [realm/realm-swift#7994]
### How frequently does the bug occur?

All the time

### Description

access realm db file when while open db file with RealmDB Studio, then occurred app crash 
I use 64-bit simulator iPhone 12Pro (sdk ios 16)

see the log belows 
 
` let realm = try! Realm()`

### Stacktrace & log output

```shell
Thread 51: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=8 "Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. For sharing files between the Realm Browser and an iOS simulator, this means that you must use a 64-bit simulator. Path: /Users/hunet/Library/Developer/CoreSimulator/Devices/11AC0343-BBA0-43DF-8989-B2830D3DF761/data/Containers/Data/Application/02F26083-AD85-48
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. realm studio open the db and keep open
2. any access db file from simulator

### Version

10.32.0 (recentest)

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS Monterey 12.6

### Build environment

xcode 14.0.1(14A400), simulator 14.0.1(986.3)

**Comment by Kernelzero** [comment]
I have been install 12.0.0, this issue fixed

**Comment by robertmylne** [comment]
I have the same issue on latest versions of realm swift and realm studio on new Mac.

**Comment by AkashBelekar2428** [comment]
I have been install 14.0.1, this issue fixed
