### ISSUE TITLE
Archive with Xcode 14.1 RC fails

### ISSUE THREAD

**Issue by Eirias** [realm/realm-swift#7995]
### How frequently does the bug occur?

All the time

### Description

Archive fails with:

<img width="364" alt="realm issue" src="https://user-images.githubusercontent.com/12933083/196730687-d641b3c2-42dc-47cf-a573-52ff82ea9144.png">

`xcrun swift-demangle s10RealmSwift0A14CollectionImplPAAE12makeIteratorAA11RLMIteratorVy7ElementQzGyF`

returns:
`$s10RealmSwift0A14CollectionImplPAAE12makeIteratorAA11RLMIteratorVy7ElementQzGyF ---> (extension in RealmSwift):RealmSwift.RealmCollectionImpl.makeIterator() -> RealmSwift.RLMIterator<A.Element>`

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

- Start Xcode
- Wait for dependency resolving and indexing
- Select Any iOS Device (arm64) (optional if already selected)
- Try to Archive the app

### Version

10.31.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 16 (Build Target is iOS 14)

### Build environment

Xcode version: 14.1 RC (released on 18.10.2022) [Link](https://developer.apple.com/download/applications/)
Dependency manager and version: 14.1 RC

**Comment by pitoneux** [comment]
Same issue but one more undefined: 
<img width="429" alt="Screen Shot 2022-10-19 at 2 36 15 PM" src="https://user-images.githubusercontent.com/1493686/196809373-6741d966-02be-4efb-87dd-61e9cca84801.png">

**Comment by prekieta** [comment]
Same for me. Rolling back to Xcode 14.0.1 works fine.

**Comment by da-mian** [comment]
Same for me
<img width="1337" alt="Screenshot 2022-10-18 at 12 45 07" src="https://user-images.githubusercontent.com/446207/196897186-f1498124-6b9a-4603-a8ff-237004cbb927.png">

**Comment by da-mian** [comment]
Same for me
<img width="649" alt="Screenshot 2022-10-20 at 10 27 34" src="https://user-images.githubusercontent.com/446207/196897267-9a9fb87a-d745-4c21-9f5a-4a427489392f.png">

**Comment by kachalo** [comment]
Same story here. Everything works fine in Debug configuration, but fails to archive the Release.

**Comment by AndresCanella** [comment]
Same issues running Realm `10.32.0`

A potential temporary workaround, I was able to build using `10.20.0`

**Comment by da-mian** [comment]
Same issue with **Xcode 14.1 RC 2**

**Comment by ericjordanmossman** [comment]
FYI team is aware of issue and trying to pinpoint issue.

> Dependency manager and version: 14.1 RC

I take this to mean SPM. Is everyone else seeing this with SPM or another dependency manager?

**Comment by prekieta** [comment]
I use SPM. I rolled back to Xcode 14.0.1 for store submissions.

**Comment by iamstephenbrown** [comment]
Can confirm SPM and the 14.1 RC 2 is causing the issue.

We are seeing similar on debug builds as well.

![Screenshot 2022-10-26 at 09 33 13](https://user-images.githubusercontent.com/57794733/197976302-c2e82d37-17c6-41ee-864a-2b7104f3452c.png)

**Comment by kachalo** [comment]
I can reproduce the issue with SPM and Xcode 14.1 RC.

**Comment by cliftonlabrum** [comment]
Same issue here using:
- Xcode 14.1 RC2
- Realm 10.32.1
- RealmDatabase 12.11.0
- Swift Package Manager
- macOS Ventura 13.0

**Comment by omerturhan** [comment]
Now I can reproduce this with CocoaPods

**Comment by Thongpak21** [comment]
10.32.1 still have issue with Carthage
![Screen Shot 2565-11-02 at 10 50 08](https://user-images.githubusercontent.com/14158501/199391175-2752c511-fb87-4c9e-bade-9a67c31321b3.png)

**Comment by tgoyne** [comment]
10.32.1 does not include the fix for this.

**Comment by eyildirimdev** [comment]
I am able to reproduce with `CocoaPods 1.11.3` on `xCode 14.1` with IOS deployment target `11.0`

Any update on this?

**Comment by eyildirimdev** [comment]
I am also able to build successfully using Realm `10.32.0` as mentioned [here](https://github.com/realm/realm-swift/issues/7995#issuecomment-1287438648)

**Comment by schroederh** [comment]
Still having this issue with `Xcode 14.1 (aka. RC2)` and `Realm 10.32.1`

Additional info:
`MacBook Pro (13-inch, M1, 2020`
`MacOS Ventura 13.0`
`SPM`
`Deployment Target 14.0`

**Comment by markusfi** [comment]
Same issue here after update (through AppStore on M1 Macbook) to Xcode 14.1 (14B47b) today and Realm 10.32.1
Did not have this problem before upgrade to the 14B47b version.

**Comment by allanweir** [comment]
As a very temporary workaround until the next release, in SPM I've updated my dependency to be tgoyne's fix as it's the only commit since Realm 10.32.1
` .package(name: "Realm", url: "https://github.com/realm/realm-swift", revision: "cedc1c8b0b2ab8506dd15703c36f8c0660774b18"),`

I've tested it from a dev build and it works. My TestFlight build from fastlane is uploading ok now but un-tested at the minute.

**Comment by mstralka** [comment]
This is also a problem with Cocoapods, so it's not just Swift Package Manager:

XCode Version 14.1 (14B47b)
Realm 10.30.0, 10.32.0, and 10.32.1
Cocoapods 1.11.2 and 1.11.3

<img width="420" alt="image" src="https://user-images.githubusercontent.com/439680/199598600-37daa81f-f5da-4b58-860d-73f6151bf1d2.png">

It archives successfully if I use tgoyne's specific commit:
~~~
pod 'RealmSwift',  git: 'https://github.com/realm/realm-swift.git', commit: 'cedc1c8b0b2ab8506dd15703c36f8c0660774b18'
~~~

**Comment by jln19** [comment]
I tried your pod update solution @mstralka, unfortunately I get a new error:

`Undefined symbol: _OBJC_CLASS_$_RLMSectionedResults
`

**Comment by mixdesign** [comment]
@jln19 Just FYI, I tried the commit above, it works for me with Xcode 14.1. You may have issues related to usage in your code.

**Comment by eyildirimdev** [comment]
> I am also able to build successfully using Realm `10.20.0` as mentioned [here](https://github.com/realm/realm-swift/issues/7995#issuecomment-1287438648)

We decided to roll back to `xCode 14.0` from `14.1` to be able to use `Realm 10.32.1`

**Comment by cloverdaniel** [comment]
Seeing this in Debug, trying to run to an attached test iPhone X.  
- Xcode 14.1
- Realm 10.32.2 (manual release download > unzip > copy 14.1 xcframework into project)

**Comment by eyildirimdev** [comment]
Realm 10.32.3 fixed the issue for me. I can build xCode Version 14.1 (14B47b) without issues

**Comment by kachalo** [comment]
I can confirm that 10.32.3 fixes issue for me.

**Comment by shadow-boy** [comment]
I can confirm that 10.32.3 fixes issue for me.

**Comment by faizaan123** [comment]
The issue still persists when I try to archive my project with the master code of realm that is 10.37.3(master code) in xcode v14.2. Can anybody help me regarding this. I have no issues while building the project. But when it comes to archiving it gets stuck at the last (1794 /1821 always at this step for some reason). Any help would be appreciated. Thanks in advance.

**Comment by leemaguire** [comment]
@faizaan123 can you attach a sample app that reproduces the issue?

**Comment by faizaan123** [comment]
@leemaguire raised the issue as instructed. #8200
