### ISSUE TITLE
Relationship/Embedded Object Between Multiple Database

### ISSUE THREAD

**Issue by dwirandytlvk** [realm/realm-swift#7996]
### Problem

Hallo Realm team, i have an idea that i want to decentralized our database, that means some feature in my app will have dedicated database instead of only use one database in an application.

I have read and try that it's possible to have multiple database in 1 application, but how to manage relationship between object from different realm file

For example i have 3 RealmObject:
- Booking.h in Booking module/framework 
- Guest.h in User module/framework
- Hotel.h in Hotel modele/framework

```
// Booking.h
--
@interface Booking : RLMObject
@property NSString *bookingID;
@property Guest *guest;
@property RLMArray<HotelRoom *><HotelRoom> *hotelRooms;
@end
 
// Define an RLMArray<HotelRoom> type
RLM_COLLECTION_TYPE(HotelRoom)
 
// Guest.h
@interface Guest : RLMObject
@property NSString *name;
@end

// HotelRoom.h
@interface Hotel : RLMObject
@property NSString *roomID;
@property NSString *price;
@end
 

// Booking.m
@implementation Booking
@end
 
// Guest.m
@implementation Guest
@end

// Hotel.m
@implementation Hotel
@end
```
My question is:
- It's possible that every module has dedicated realm database? 
- How to manage the relationship because HotelRoom & Person in in different Realm file?
- How to manage data migration process , since the application already in production that use 1 realm database?

Note
- I only use realm to store data locally

### How important is this improvement for you?

Would be a major improvement

**Comment by ericjordanmossman** [comment]
You can have multiple realm files with different object types in your application. However you wouldn't be able to have objects in realm file 1 have a relationship with objects in realm file 2, for example. Relationships would have to be within the same file.

**Comment by dwirandytlvk** [comment]
HI @ericjordanmossman thanks for your answer,
I decided to refactor my realm object structure, and put `Booking`, `Guest`, `HotelRoom` into dedicated realm file, 
May i know how to migrate the data from `default realm` to `dedicated realm` file (that contain Booking, Guest, HotelRoom)? since my app already in production and i want to exclude those files from `default realm` `objectClasses`

Should i upgrade my realm scheme version twice?
First, to migrate data from `default realm` to `dedicated realm`
Then, remove Booking, Guest, HotelRoom from `default realm` `objectClasses`

or any better solution?

Note: `Booking`, `Guest`, `HotelRoom` have no relationship/embeded object to other realm object inside `default realm`

**Comment by otso** [comment]
I understand you are moving data between two local only realms. All of our migration examples are towards migrations inside one realm.

The approach you are proposing for moving data between two local realms sounds plausible with deletions only after a successful data migration between the two local realms.

Many apps successfully employ multiple realm files. But keep in mind object relationships and migrations are designed to be used within a single file.
