### ISSUE TITLE
When integrate the realm-swift that build with xcframework, there will be have many errors

### ISSUE THREAD

**Issue by edison0951** [realm/realm-swift#8014]
### How frequently does the bug occur?

All the time

### Description

I have build the real-swift with xcframework and I integrate it in the xcode project. But there will have an error that is "Failed to build module  for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug". This is a bug in Swift [SR-14195](https://github.com/apple/swift/issues/56573). Because the real-swift have the public method Realm that is conflict with Realm module. so how can I fix this bug? 

### Stacktrace & log output

```shell
SwiftRealm.framework/Modules/SwiftRealm.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface:99:17: error: 'RLMApp' is not a member type of struct 'Realm'

SwiftRealm.framework/Modules/SwiftRealm.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface:2462:23: note: 'Realm' declared here
@frozen public struct Realm {
                      ^
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

step1: build the realmswift in xcframework

step2: integrate in xcode project

step3: import xcframework

### Version

10.32.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

iOS

### Build environment

Xcode version: 14
Dependency manager and version: OSX 12.6

**Comment by tgoyne** [comment]
While https://github.com/realm/realm-swift/pull/8016 fixes this build failure, I don't recommend trying to build Realm Swift in library evolution mode. It is something which is very focused on Apple's specific requirements and tends to be buggy for third-party usage. We have not extensively tested it to verify that everything actually works.

**Comment by edison0951** [comment]
I change the Realm to RealSwift locally, and it works. I hope to solve it officially.

**Comment by SyedTayyab99** [comment]
@edison0951 Can you please elaborate or provide an example I'm facing same issue. Thanks
