### ISSUE TITLE
Xcode 14.1 not building due to undefined symbols

### ISSUE THREAD

**Issue by NZQN23** [realm/realm-swift#8015]
### How frequently does the bug occur?
All the time

### Description
I cannot build my project any more with Xcode 14.1 (14B47b). 

I have updated all pods and cleaned my build folder. Still doesn't work.

### Stacktrace & log output
```shell
Undefined symbol: _$s10RealmSwift0A14CollectionImplPAAE12makeIteratorAA11RLMIteratorVy7ElementQzGyF
Undefined symbol: _$s10RealmSwift7ResultsVyxGAA0A14CollectionImplAAMc
```

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
Archive for Any iOS Device (arm64)

### Version
10.32.1

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
Xcode / MacOS

### Build environment
Xcode version: 14.1 (14B47b)
Dependency manager and version: Cocoapods 1.11.3

**Comment by XicoBaiao** [comment]
Same thing for me, any help ?

**Comment by tgoyne** [comment]
Duplicate of #7995.

**Comment by Mokshsuthar** [comment]
<img width="727" alt="Screenshot 2022-11-06 at 11 46 46 PM" src="https://user-images.githubusercontent.com/70541825/200187954-118a9799-85a7-469e-a480-7e561418dbae.png">
i'm also facing same issue anyone found solution 
please help fast

**Comment by kravtsovguy** [comment]
@Mokshsuthar just check that you are using the latest version of the realm, currently it is **v10.32.2**

**Comment by shreesols** [comment]
I am getting this 
![image](https://user-images.githubusercontent.com/34943366/201025993-3eda7649-9bd8-4307-aeb3-2d10b7d20e0d.png)

**Comment by MatHeartGaming** [comment]
I've just stubled upon the same issue and, in case you're using pod, running "pod deintegrate", "pod install", and "pod update" (or "arch -x86_64 pod update" if you're using ARM based Macs) did the trick for me!

**Comment by bero1975** [comment]
Undefined symbol: _$s10RealmSwift0A14CollectionImplPAAE12makeIteratorAA11RLMIteratorVy7ElementQzGyF
Undefined symbol: _$s10RealmSwift4ListCyxGAA0A14CollectionImplAAMc

Getting this when trying to Archive to send app to app store for test flight

**Comment by NZQN23** [comment]
> Undefined symbol: _$s10RealmSwift0A14CollectionImplPAAE12makeIteratorAA11RLMIteratorVy7ElementQzGyF Undefined symbol: _$s10RealmSwift4ListCyxGAA0A14CollectionImplAAMc
> 
> Getting this when trying to Archive to send app to app store for test flight

- update pods
- clean build folder
- build

**Comment by bero1975** [comment]
That was exactly it. Managed to Update the Packages, Clean the build Folder and then follow through with what I was trying to do. Thanks ever so much for the prompt reply.

**Comment by Kernelzero** [comment]
If you use RxRealm, firstly, remove RxRealm pod and update realmSwift. after then, install RxRealm.

**Comment by NeboLej** [comment]
i changed the way to create the stored model and the error is gone

there is an error:
    static func initModel(model: Model) -> [String: Any] {
        ["name": model.name, "color": model.color]
    }
    
    no error: 
        convenience init(name: String, color: String) {
        self.init()
        self.name = name
        self.color = color
    }

**Comment by dongbach69** [comment]
> 

@shreesols  do you resolved it?

**Comment by bartushak007** [comment]
macbook m2 pro "react-native": "0.65.1"
I had the exact same problem

I was able to run my react-native project without rosetta after doing these steps:

delete: podfile.lock
run: pod deintegrate
run: pod install

> > 
> 
> @shreesols do you resolved it?



> I am getting this ![image](https://user-images.githubusercontent.com/34943366/201025993-3eda7649-9bd8-4307-aeb3-2d10b7d20e0d.png)

@dongbach69 @shreesols
