### ISSUE TITLE
failed archive Xcode14 with Enable bitcode

### ISSUE THREAD

**Issue by k-teshima0901** [realm/realm-swift#8019]
### How frequently does the bug occur?

All the time

### Description

When I tried to archive with "Enable bitcode" set to "Yes" to generate dSYM, an error occurred and archiving failed!

Looking at the error, I assume it is because Realm.o" does not support bitcode.
Is it possible to create an archive with "Enable bitcode" set to "Yes"?

### Stacktrace & log output

```shell
error build: '/Users/userName/Library/Developer/Xcode/DerivedData/appName-esdaglqddwymhcallajrvdjazggq/Build/Intermediates.noindex/ArchiveIntermediates/Release/BuildProductsPath/Release-iphoneos/Realm.o' does not contain bitcode.

You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE),
obtain an updated library from the vendor,
or disable bitcode for this target.

file '/Users/userName/Library/Developer/Xcode/DerivedData/appName-esdaglqddwymhcallajrvdjazggq/Build/Intermediates.noindex/ArchiveIntermediates/Release/BuildProductsPath/Release-iphoneos/Realm.o' for architecture arm64
```

### Can you reproduce the bug?

Not yet

### Version

10.31.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

mac OS: Monterey, Xcode 14.0

### Build environment

Xcode version: 14.0.1
Dependency manager and version: SPM - realm-cocoa = 10.31.0

**Comment by tgoyne** [comment]
Apple has deprecated bitcode and you should disable it when using Xcode 14.

**Comment by k-teshima0901** [comment]
@tgoyne 
Thank you for your answer.

So, does this mean that it is impossible to build with "Enable Bitcode" set to "Yes" with Realm installed?

**Comment by k-teshima0901** [comment]
I need to generate dSYM with UUID to fix missing dSYM in Firebase Crashlytics
The intention is to enable bitcode for this purpose

**Comment by tgoyne** [comment]
Xcode 14 does not support bitcode regardless of if you are using Realm or not.

**Comment by k-teshima0901** [comment]
@tgoyne 

I understood that it is not possible to build with Bitcode enabled.

Thank you.
