### ISSUE TITLE
Getting warning for private method access when uploading build to AppStore

### ISSUE THREAD

**Issue by ayush-ttn** [realm/realm-swift#8041]
### How frequently does the bug occur?

All the time

### Description

I am getting this warning every time I upload the build on AppStore:
`The app references non-public selectors in Payload/<app-name>.app/Frameworks/Realm.framework/Realm: authenticationDidCompleteWithError`
I am using RealmSwift v10.25.2 via Cocoapods. Any resolution to this issue will be appreciated. 

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

- Add RealmSwift via Cocoapods to the project. 
- Archive and upload the ipa to the Store.
- The warning will appear after the build is uploaded.

### Version

10.25.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 16, 15,14

### Build environment

Xcode version: 14
Dependency manager and version: Cocoapods 1.11.3

**Comment by shimastripe** [comment]
@ayush-ttn  https://github.com/realm/realm-swift/releases/tag/v10.30.0 https://github.com/realm/realm-swift/issues/7945 This bug is resolved.

**Comment by ayush-ttn** [comment]
Thanks for responding @shimastripe

**Comment by dianaafanador3** [comment]
Closing as this is a duplicate from a previous issue and was fixed in version [v10.30.0](https://github.com/realm/realm-swift/releases/tag/v10.30.0)
