### ISSUE TITLE
Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-swift#8042]
### How frequently does the bug occur?

All the time

### Description

macOS 13.0.1
Xcode 14.1
RealmSwift 10.32.2
Synced Realm (MongoDB Realm App)

Can anyone explain why I would be getting this warning - I have not seen this on prior versions of macOS/Xcode/RealmSwift.

### Stacktrace & log output

```shell
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
PID: 40019, TID: 4270065
Backtrace
=================================================================
3   Realm                               0x00000001050b3288 _ZN5realm2DB14do_begin_writeEv + 60
4   Realm                               0x00000001050b5f0c _ZN5realm2DB17AsyncCommitHelper20blocking_begin_writeEv + 104
5   Realm                               0x00000001051cf9ec _ZN5realm11Transaction18acquire_write_lockEv + 92
6   Realm                               0x00000001052ee218 _ZN5realm5_impl11transaction5beginERKNSt3__110shared_ptrINS_11TransactionEEEPNS_14BindingContextEONS0_15NotifierPackageE + 404
7   Realm                               0x00000001052e6144 _ZN5realm5_impl16RealmCoordinator16promote_to_writeERNS_5RealmE + 176
8   Realm                               0x000000010536eff4 _ZN5realm5Realm20do_begin_transactionEv + 44
9   Realm                               0x0000000105370338 _ZN5realm5Realm17begin_transactionEv + 132
10  Realm                               0x000000010504af78 -[RLMRealm beginWriteTransactionWithError:] + 24
11  MakeSpace2                          0x00000001010f2c64 $s10MakeSpace27AppUserC12startSessionAA05LoginF0CyF + 264
12  MakeSpace2                          0x0000000100ef0a54 $s10MakeSpace210GlobalVarsC7appUserAA03AppF0CSgvW + 388
13  MakeSpace2                          0x0000000100ef0e80 $s10MakeSpace210GlobalVarsC7appUserAA03AppF0CSgvs + 200
14  MakeSpace2                          0x00000001017c2754 $s10MakeSpace211DataManagerC9userLogin8username8password10completionySS_SSySbctF + 1216
15  MakeSpace2                          0x00000001013b6f54 $s10MakeSpace210LoginSheetC5loginyySS_SStF + 332
16  MakeSpace2                          0x00000001013b6c28 $s10MakeSpace210LoginSheetC11loginActionyyypF + 1332
17  MakeSpace2                          0x00000001013b6c94 $s10MakeSpace210LoginSheetC11loginActionyyypFTo + 68
18  AppKit                              0x00000001894e52f0 -[NSApplication(NSResponder) sendAction:to:from:] + 440
19  AppKit                              0x00000001894e5108 -[NSControl sendAction:to:] + 72
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Occurs every time the call is made.  Only occurs in one location in the Realm App Login callback using the User object that gets returned.

### Version

10.32.2

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 13.0.1

### Build environment

Xcode version: 14.1
Dependency manager and version: ...

**Comment by hesamr76** [comment]
![Screen Shot 2022-11-24 at 12 43 44 PM](https://user-images.githubusercontent.com/31796812/203787744-cfebc6d3-2a0c-45b8-a49e-57da796ea4f6.png)

same

Xcode: 14.0.1
react-native: 0.67.1


Even though the development build is ok, the archive has the
**Thread running** issue.

**Comment by dianaafanador3** [comment]
@duncangroenewald can you please create a repro project so we can take a look at this.

**Comment by duncangroenewald** [comment]
@dianaafanador3 - I will see what I can do later this week

**Comment by aejimmi** [comment]
We are also seeing this issue

https://stackoverflow.com/questions/72533064/after-switching-to-xcode-14-beta-i-got-this-error-qos-class-user-initiated-wait
https://developer.apple.com/documentation/xcode/diagnosing-performance-issues-early

**Comment by Sonisan** [comment]
Looks similar to an issue I opened a while ago: https://github.com/realm/realm-swift/issues/7902
