### ISSUE TITLE
Crash due to duplicate primary key of an object that should have been deleted

### ISSUE THREAD

**Issue by taise-hikawa** [realm/realm-swift#8044]
### How frequently does the bug occur?

Sometimes

### premise
- person has an array of dog
- dog has already been added to the realm
- dog has a primary key

Delete and then add.
```
try realm.write {
   realm.delete(dog)
}

try realm.write {
   person.dogs.append(dog)
}
```
Sometimes crashes when adding.
The actual code is more complex.
What I want to know is not so much the solution, but why it crashes.
Since it takes time to delete an object, we expected that it had not yet been deleted when we added it.
But I'm not sure, because I think I saw somewhere that it should be fast enough that you don't have to take processing time into account.

### Stacktrace & log output

```shell
Attempting to create an object of type 'XXX' with an existing primary key value 'XXX'.
```

### Can you reproduce the bug?

Yes, sometimes

### Version

10.25.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14-16

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by dianaafanador3** [comment]
What you mentioned is weird, delete should happen within the first write block, and this error should not appear at any time. Do you happen to do this operations during an overload write, or in a background thread?.
Also, try to update to our latest version of realm, we continue to improve performance so this kind of issues don't happen. 
Please inform us if you keep seeing this after the update and attach the stack trace from the crash.

**Comment by taise-hikawa** [comment]
@dianaafanador3 Thanks for your reply!!
`realm.write` block is always called in asynchronously in series in the following queue.
```
let queue = DispatchQueue(label: "jp.co.labelname", qos: .utility)
```
Is this the answer to your question?
And  I don't know the criteria to determine if it is an overload write.

**Comment by taise-hikawa** [comment]
@leemaguire 
Please, reopen this issue.
instance
```
let  config = Realm.Configuration(fileURL: url, schemaVersion: Self.schemaVersion, migrationBlock: migrationBlock)
Realm(configuration: config)
```

**Comment by dianaafanador3** [comment]
@taise-hikawa can you please attach a sample project if you are able to repro this, or some sample code for the operation causing the issue (how you open the realm, and how you do the write and delete) please attach every little detail (queue, where are you using autoreleasepool). Also will be very nice to have the complete stackstrace so we can track from where the issue is triggered.
