### ISSUE TITLE
Missing required modules: 'Realm.Private', 'Realm'

### ISSUE THREAD

**Issue by DanPavelNan** [realm/realm-swift#8047]
### How frequently does the bug occur?

All the time

### Description

Unable to use RealmSwift as a SPM dependency in a private ( local ) package. 
SetUp:
1. Create a package (SPM) that contains 2 RealmObjects. This package has a dependency on RealmSwift. 
2. Add the local package as a dependency to a SampleApp (iOS application )
3. Inside the SampleApp, for the main target, add the package framework as a linked dependency 
4. Inside the SampleApp, for the test target, don't add any dependency . 
5. Add test on the test target, which will attempt to create the realm object from the local package 
6. Build the app / run . No problems found 
7. Attempt to build the test => "Missing required modules: 'Realm.Private', 'Realm'" 😞

Link to sample Project 
https://github.com/DanPavelNan/TestRealmWhitSPM

### Stacktrace & log output

```shell
SwiftEmitModule normal arm64 Emitting\ module\ for\ NewReamTestTests (in target 'NewReamTestTests' from project 'NewReamTest')
    cd /Users/nanda1/ios/DanRepos/TestRealmWhitSPM/NewReamTest
    builtin-swiftTaskExecution -- /Users/nanda1/Downloads/Xcode14.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -emit-module -experimental-skip-non-inlinable-function-bodies-without-types /Users/nanda1/ios/DanRepos/TestRealmWhitSPM/NewReamTest/NewReamTestTests/NewReamTestTests.swift -target arm64-apple-ios16.1-simulator -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Users/nanda1/Downloads/Xcode14.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk -I /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Products/Debug-iphonesimulator -I /Users/nanda1/Downloads/Xcode14.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib -F /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Products/Debug-iphonesimulator -F /Users/nanda1/Downloads/Xcode14.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -F /Users/nanda1/Downloads/Xcode14.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/nanda1/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG -serialize-debugging-options -serialize-debugging-options -enable-bare-slash-regex -empty-abi-descriptor -Xcc -working-directory -Xcc /Users/nanda1/ios/DanRepos/TestRealmWhitSPM/NewReamTest -resource-dir /Users/nanda1/Downloads/Xcode14.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/NewReamTestTests-generated-files.hmap -Xcc -I/Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/NewReamTestTests-own-target-headers.hmap -Xcc -I/Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/NewReamTestTests-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/NewReamTestTests-project-headers.hmap -Xcc -I/Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/DerivedSources-normal/arm64 -Xcc -I/Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/DerivedSources/arm64 -Xcc -I/Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/DerivedSources -Xcc -DDEBUG\=1 -module-name NewReamTestTests -disable-clang-spi -target-sdk-version 16.1 -emit-module-doc-path /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/Objects-normal/arm64/NewReamTestTests.swiftdoc -emit-module-source-info-path /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/Objects-normal/arm64/NewReamTestTests.swiftsourceinfo -emit-objc-header-path /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/Objects-normal/arm64/NewReamTestTests-Swift.h -serialize-diagnostics-path /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/Objects-normal/arm64/NewReamTestTests-master-emit-module.dia -emit-dependencies-path /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/Objects-normal/arm64/NewReamTestTests-master-emit-module.d -parse-as-library -o /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/Objects-normal/arm64/NewReamTestTests.swiftmodule -emit-abi-descriptor-path /Users/nanda1/Library/Developer/Xcode/DerivedData/NewReamTest-clynihkvwaxluhdndgunmpexywit/Build/Intermediates.noindex/NewReamTest.build/Debug-iphonesimulator/NewReamTestTests.build/Objects-normal/arm64/NewReamTestTests.abi.json

<unknown>:0: error: missing required modules: 'Realm.Private', 'Realm'
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Link to sample Project 
https://github.com/DanPavelNan/TestRealmWhitSPM

or zip
[TestRealmWhitSPM.zip](https://github.com/realm/realm-swift/files/10116260/TestRealmWhitSPM.zip)

### Version

10.32.3

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS  16.1

### Build environment

Xcode version:  14.1
Dependency manager and version: SPM

**Comment by cliftonlabrum** [comment]
I believe I'm having this same issue. I'm using `Realm 10.32.3` and see a `No such Module 'RealmSwift'` whenever I have an `import RealmSwift` statement in my app. I'm using Swift Package Manager in Xcode 14.1.

**Comment by pitoneux** [comment]
Same here. Haven't been able to use SPM either with Realm ever because of issues like this one.

**Comment by cliftonlabrum** [comment]
I deleted derived data, re-added all my Swift Packages, and now I can get my app to build for iOS. But it still fails on my macOS app. Maybe I just need to add Realm with Carthage.

**Comment by leemaguire** [comment]
@DanPavelNan the solution is to add your custom package to the 'Link Binary with Libraries' section under your test target:

![Screenshot 2022-11-30 at 13 41 05](https://user-images.githubusercontent.com/17234962/204811823-d6b58bea-2546-40c8-b53a-67e37f8b501e.png)

**Comment by DanPavelNan** [comment]
> I believe I'm having this same issue. I'm using `Realm 10.32.3` and see a `No such Module 'RealmSwift'` whenever I have an `import RealmSwift` statement in my app. I'm using Swift Package Manager in Xcode 14.1.

I don't think we are facing the same problem. Don't know if you had the chance to look at the sample project I added, but the idea is that Realm is used as a dependency in a private ( local) package , and then this package is used as a dependency on the sampleApp. 
Note that for me the app works as expected, the problem is with the test target

**Comment by DanPavelNan** [comment]
> @DanPavelNan the solution is to add your custom package to the 'Link Binary with Libraries' section under your test target:
> 

@leemaguire , I did try that to , but 
1. I don't think I should do that , since the test target already has a dependency on the sampleApp which depends on the package.
2. Yes, the build pass, but if you try to run the test you will notice that xcoce is complaining of duplicate implementation of classes "ABC is implemented in both .../NewReamTest.app/NewReamTest (0x10558d648) and ../NewReamTest.app/PlugIns/NewReamTestTests.xctest/NewReamTestTests (0x11efa4158). One of the two will be used. Which one is undefined."
3. Tests crash with `Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)` as soon as you try to instantiate a Realm instance

**Comment by leemaguire** [comment]
@DanPavelNan I discussed this with the team, the approach I mentioned earlier was incorrect. What needs to be done is the library needs to be linked in a way that Xcode sees it as a dynamic library. the above approach links it as a static library and that is why you are seeing warnings like `duplicate implementation of classes`. I'll try find some time to dig into finding the correct approach.

**Comment by DanPavelNan** [comment]
Hi @leemaguire ,
Happy new year.
I just want to check if any progress was done in solving this issue. No pressure 😛, but I have to tell my team what are our options. 
Thanks

**Comment by leemaguire** [comment]
Hi @DanPavelNan Happy new year to you too! I took a look and declaring your library as dynamic in the package.swift file:

```swift
    products: [
        .library(
            name: "MyPackageForRealm",
            type: .dynamic,
            targets: ["MyPackageForRealm"]),
    ],
```

Combined with embedding the library in the test target seems to work without getting any weird warnings in the logs. (Tested in Xcode 14.1 and 14.2)
<img width="1147" alt="Screenshot 2023-01-04 at 20 53 28" src="https://user-images.githubusercontent.com/17234962/210648039-4586719b-f05f-46b9-8605-679f4dd60d66.png">

<img width="1150" alt="Screenshot 2023-01-04 at 20 55 29" src="https://user-images.githubusercontent.com/17234962/210648220-ebc6c7bb-5f57-42c8-a60e-6a9b20b4a9aa.png">

**Comment by DanPavelNan** [comment]
@leemaguire , thank you very much for taking the time to look into this. 
Yes , this fix works . I think I tried this before but probably I used embedded library for both the main target as for the test target and something was not working right .
However my main project still does not like something, no idea what right now, but I can say that it does not seam to be a "Realm" problem.
Thank you again for your help, much appreciated.

**Comment by Jaafar92** [comment]
Hi @leemaguire 
I am having similar issues with Realm/SPM. It's a new and simple project. I am trying to unit test some database/Realm code. 
First, if I don't "Link Binary with Libraries" and add "Realm", "RealmSwift" or both, I get this "Missing required modules: 'Realm.Private', 'Realm'" issue. If I link the binaries, then I get a lot of "Class X is implemented in both Z and Y. One of the two will be used. Which one is undefined.

If I ignore that message and write some unit tests anyway, then I get "Thread 1: EXC_BAD_ACCESS" on List properties. 

It sounds a lot like the issue @DanPavelNan has been seeing, however I am not embedding a package. Do I need to embed a package to avoid this issue?

I am using v. 10.34.0

Hope you can help, and thanks in advance.

**Comment by ding-stephen** [comment]
@Jaafar92 Hi
I faced the same issue for unit test as you mentioned, have you solved this conflict with the main project?

**Comment by serdarshenol** [comment]
@Jaafar92 , I was struggling with the same issue. I solved the issue with making a wrapper on top of RealmSwift and used realm through it. Check the SPM in the following link:
[https://github.com/serdarshenol/PersistentDataCore](PersistentDataCore)

**Comment by Jaafar92** [comment]
@ding-stephen I did something similar to @serdarshenol.
