### ISSUE TITLE
ObservedRealmObject throws No exact matches in call to initializer 

### ISSUE THREAD

**Issue by patrickmenendez29** [realm/realm-swift#8048]
### How frequently does the bug occur?

All the time

### Description

Hello,
when I try to declare a specific ```ObservedRealmObject```, Xcode throws No exact matches in call to initializer error. This only happens with one specific class and I do not know what coudl be causing it.
Here is the code:

```
struct WelcomeNamespace: View {
        @ObservedRealmObject var db: Database
         var body: some View {
                ....
    }
}
```

and the class in question is the following:

```

class Database: Object {
    @Persisted var accounts: List<Account> = List()
    @Persisted private var eventList: List<Event> = List()
    @Persisted var accountToken: Account? = nil
    var events: [Event] {
        get {
            return Array(eventList)
        }
        set {
            eventList.append(objectsIn: newValue)
        }
    }
}
```

where ```Account``` and ```Event``` are Objects themselves. However, when I reproduce the same declaration with ```Account``` and ```Event```, it does not happen

### Can you reproduce the bug?

Yes, always

### Version

10.32.3

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by leemaguire** [comment]
Your `Object`'s need to be `ObjectKeyIdentifiable`. Also you do not need to initialise `List` when using `@persisted` doing `@Persisted private var eventList: List<Event>` is the correct approach.
