### ISSUE TITLE
Compatibility Question related to crash #7741

### ISSUE THREAD

**Issue by bb-git** [realm/realm-swift#8056]
### How frequently does the bug occur?

Sometimes

### Description

The app crashes for some iOS 14 users. I tried to downgrade on my test device from version 10.33.0 to version 10.11.0, the version we were using before and were we didn't see the crash happening. It was working, but I want to be sure, that I can do the downgrade and I'm sure, as only API compatibility is stated, but no core compatibility. Can you please confirm?

### Can you reproduce the bug?

Not yet

### Version

10.33.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

14.0-14.8.1

### Build environment

Xcode version: 14.1
Dependency manager and version: cocoapods 11.3.1

**Comment by tgoyne** [comment]
In general downgrading should be safe if it appears to work in testing. Whenever we make a change which would result in older versions of Realm being unable to read a file we bump an internal file format version, and on open we check the version and throw an exception if it's newer than the version of Realm you're using recognized (or upgrade the file if it's older).

**Comment by bb-git** [comment]
Ok, thanks for letting me know. Will there be any investigation on the issue #7741 ? It seems there is enough information, but the reporter probably went through the crashes and doesn't care anymore. Also reproduction seems in debug enviroment.

**Comment by dianaafanador3** [comment]
@bb-git Closing this as it was already solved by the comment above. We'll take a look to https://github.com/realm/realm-swift/issues/7741 as well
