### ISSUE TITLE
Generic Model using type.classname() depends on target name (iOS) 

### ISSUE THREAD

**Issue by don-hue** [realm/realm-swift#8067]
### How frequently does the bug occur?

All the time

### Description

We found that there is an unexpected behaviour when using a generic model type with realmDB via Swift on iOS. Using this generic model class across two targets fails in unexpected ways seemingly because realm does not correctly recognize the class across targets. 
Our code is using` realm.objects(Model.self)` to access all objects of one type. Internally that method calls `RLMGetObjects(rlmRealm, type.className(), nil)` and here `type.className()` seems to be the cause of the issue. 

For non-generic types its just the human readable type name: For `class Model` it'd be `Model`. But for generic types like `Model<GenericType>` .className() yield something similar to: `_TeZJ6TargetName8ModelCS_13GenericType_` and realmDB fails to fetch the data saved with a different target name as this target name is part of the stringified className.

### Can you reproduce the bug?

Yes, always

### Version

10.29.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

RealmSwift 10.29.0

### Build environment

Xcode 14.1,

**Comment by dianaafanador3** [comment]
Hi @don-hue I'm changing the tag to a feature enhancement. We'll discuss it with the team if this viable. 
Also Can we know the specific use case for this?, maybe there is another feature that can be used in your case.

**Comment by don-hue** [comment]
Hi @dianaafanador3 , 
thanks for the response. 
We encountered this behaviour as we wanted to upgrade our current app, but still wanted to use the stored data. 

The upgraded version has two different targets but the same bundle id.

**Comment by dianaafanador3** [comment]
I think this has more to do with the class been generic that been in different targets. We support shared realm between extension and different Apps, so different targets should not be an issue.

**Comment by don-hue** [comment]
well, i guess it is a special usecase to have generic types as well as the need to access the data from different targets with the same bundle id.

**Comment by dianaafanador3** [comment]
Closing this as there is already an open request for this feature. https://github.com/realm/realm-swift/issues/3635
