### ISSUE TITLE
@AutoOpen / @AsyncOpen doesn't correctly handle multiple user login/logout

### ISSUE THREAD

**Issue by fromdj** [realm/realm-swift#8069]
### How frequently does the bug occur?

All the time whenever I switch users

### Description

When first user logout followed by 2nd user log in, RealmSWift reopens the first user's Realm sync then open 2nd user. This end up causing realm to have two open sync for both users. Later logout from 2nd user and log back into 1st use causes issue since realm file is already open. 

I think there is a race. When 2nd user login, user is still pointing to 1st user which caused the issue. 
I am on 10.33.0 

### Stacktrace & log output

```shell
* thread #1, queue = 'com.apple.main-thread', stop reason = step over
    frame #0: 0x0000000102f63720 OverBnb`ObservableAsyncOpenStorage.asyncOpenForUser(user=0x0000600000fb9780, self=0x0000000123a27000) at SwiftUI.swift:1510:33
    frame #1: 0x0000000102f63524 OverBnb`ObservableAsyncOpenStorage.asyncOpen(self=0x0000000123a27000) at SwiftUI.swift:1501:13
  * frame #2: 0x0000000102f634b0 OverBnb`ObservableAsyncOpenStorage.update(partitionValue=nil, configuration=RealmSwift.Realm.Configuration @ 0x000000016d4db0a0, self=0x0000000123a27000) at SwiftUI.swift:1495:18
    frame #3: 0x0000000102f66694 OverBnb`AutoOpen.update(self=RealmSwift.AutoOpen @ 0x000000016d4db828) at SwiftUI.swift:1834:17
    frame #4: 0x0000000102f66704 OverBnb`protocol witness for DynamicProperty.update() in conformance AutoOpen at <compiler-generated>:0
    frame #5: 0x000000010c626fb4 SwiftUI`___lldb_unnamed_symbol171206 + 32
    frame #6: 0x000000010ca557b8 SwiftUI`___lldb_unnamed_symbol206541 + 248
    frame #7: 0x000000010ca54cec SwiftUI`___lldb_unnamed_symbol206520 + 88
    frame #8: 0x000000010c6280b4 SwiftUI`___lldb_unnamed_symbol171248 + 384
    frame #9: 0x000000010bda9254 SwiftUI`___lldb_unnamed_symbol100786 + 28
    frame #10: 0x000000019bc9e6f8 AttributeGraph`AG::Graph::UpdateStack::update() + 512
    frame #11: 0x000000019bc9edd4 AttributeGraph`AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428
    frame #12: 0x000000019bca6b20 AttributeGraph`AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 416
    frame #13: 0x000000019bcbc8ec AttributeGraph`AGGraphGetValue + 216
    frame #14: 0x000000010c6c0a3c SwiftUI`___lldb_unnamed_symbol175729 + 64
    frame #15: 0x000000010c6c0c0c SwiftUI`___lldb_unnamed_symbol175737 + 292
    frame #16: 0x000000010bda9254 SwiftUI`___lldb_unnamed_symbol100786 + 28
    frame #17: 0x000000019bc9e6f8 AttributeGraph`AG::Graph::UpdateStack::update() + 512
    frame #18: 0x000000019bc9edd4 AttributeGraph`AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428
    frame #19: 0x000000019bca6b20 AttributeGraph`AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 416
    frame #20: 0x000000019bcbc8ec AttributeGraph`AGGraphGetValue + 216
    frame #21: 0x000000010c6c1960 SwiftUI`___lldb_unnamed_symbol175741 + 104
    frame #22: 0x000000010c6c0f18 SwiftUI`___lldb_unnamed_symbol175737 + 1072
    frame #23: 0x000000010bda9254 SwiftUI`___lldb_unnamed_symbol100786 + 28
    frame #24: 0x000000019bc9e6f8 AttributeGraph`AG::Graph::UpdateStack::update() + 512
    frame #25: 0x000000019bc9edd4 AttributeGraph`AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428
    frame #26: 0x000000019bcabe2c AttributeGraph`AG::Subgraph::update(unsigned int) + 824
    frame #27: 0x000000010c153144 SwiftUI`___lldb_unnamed_symbol133375 + 216
    frame #28: 0x000000010c8f9b90 SwiftUI`___lldb_unnamed_symbol195065 + 2120
    frame #29: 0x000000010c8f75d8 SwiftUI`___lldb_unnamed_symbol194946 + 348
    frame #30: 0x000000010cc0bc0c SwiftUI`___lldb_unnamed_symbol221604 + 260
    frame #31: 0x000000010cc0bc50 SwiftUI`___lldb_unnamed_symbol221605 + 28
    frame #32: 0x0000000114bd214c UIKitCore`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1920
    frame #33: 0x0000000187ed749c QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 440
    frame #34: 0x0000000187ee1f54 QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 128
    frame #35: 0x0000000187e117d0 QuartzCore`CA::Context::commit_transaction(CA::Transaction*, double, double*) + 452
    frame #36: 0x0000000187e3d47c QuartzCore`CA::Transaction::commit() + 652
    frame #37: 0x0000000187e3e8b0 QuartzCore`CA::Transaction::flush_as_runloop_observer(bool) + 68
    frame #38: 0x00000001803700e4 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
    frame #39: 0x000000018036aa84 CoreFoundation`__CFRunLoopDoObservers + 512
    frame #40: 0x000000018036af3c CoreFoundation`__CFRunLoopRun + 968
    frame #41: 0x000000018036a75c CoreFoundation`CFRunLoopRunSpecific + 584
    frame #42: 0x0000000188f60c98 GraphicsServices`GSEventRunModal + 160
    frame #43: 0x000000011473cb74 UIKitCore`-[UIApplication _run] + 868
    frame #44: 0x0000000114740b1c UIKitCore`UIApplicationMain + 124
    frame #45: 0x000000010c962130 SwiftUI`___lldb_unnamed_symbol197918 + 164
    frame #46: 0x000000010c961fd8 SwiftUI`___lldb_unnamed_symbol197916 + 140
    frame #47: 0x000000010c145894 SwiftUI`static SwiftUI.App.main() -> () + 80
    frame #48: 0x0000000102ad2ef8 OverBnb`static BnbMedicApp.$main(self=OverBnb.BnbMedicApp) at BnbMedicApp.swift:21:1
    frame #49: 0x0000000102ad342c OverBnb`main at BnbMedicApp.swift:0
    frame #50: 0x0000000106ff9fa0 dyld_sim`start_sim + 20
    frame #51: 0x00000001070ede50 dyld`start + 2544




(lldb) po user.id
"6393d705bd50574bc2855d85"   <---------- 1st user. not newly logged in user!
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

use todo sample app from Realm Atlas. 
Login using user A
do something
Log out user A
Login using user B
Logout user B
Login user A again. It will crash. 

### Version

10.33.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 16 both simulator and iPhone 13 device. 

### Build environment

Xcode version: ...
Dependency manager and version: ...

RealmSwift 10.33.0 
XCode Version 14.0.1 (14A400)

**Comment by dianaafanador3** [comment]
Hi @fromdj can you please attach the stack trace from the crash, I see you attached a stacktrace from a breakpoint but it is not showing the real crash. @AutoOpen and @AsyncOpen are prepared to handle multiple users, and indeed login to a new user will open a new realm but we should not held a lock to the realms from the user.

**Comment by dianaafanador3** [comment]
You can also attach the code for the login and the async view (view using @AsyncOpen and @AutoOpen). and how are you injecting the environment values and initialising the property wrappers.

**Comment by davidcockburngithub** [comment]
I also have this issue - I have downloaded the 'Template App' available from App Services (Realm) for Swift/SwiftUI - Todo. This app (which is entirely written by Realm/MongoDB) re-creates the exact behaviour above, straight out of the box. Login User 1 is successful, then User 1 logout is successful. User 2 login then displays an error on screen 'Automatic Client Reset Failed' [User mismatch for client file identifier (IDENT)] and the log shows a Client File Ident Error (Multiple Sync Agents)? Can anyone from MongoDB assist or explain this? There don't appear to be any errors in the code? I suspect that this is either a session error, or that User 1 is not being fully 'dropped' prior to User 2 trying to login?

ContentView [initial]:

`import SwiftUI
import RealmSwift

struct ContentView: View {
    @ObservedObject var app: RealmSwift.App
    @EnvironmentObject var errorHandler: ErrorHandler

    var body: some View {
        if let user = app.currentUser {
            // Setup configuraton so user initially subscribes to their own tasks
            let config = user.flexibleSyncConfiguration(initialSubscriptions: { subs in
                subs.remove(named: Constants.allItems)
                if let _ = subs.first(named: Constants.myItems) {
                    // Existing subscription found - do nothing
                    return
                } else {
                    // No subscription - create it
                    subs.append(QuerySubscription<Item>(name: Constants.myItems) {
                        $0.owner_id == user.id
                    })
                }
            })
            OpenRealmView(user: user)
                // Store configuration in the environment to be opened in next view
                .environment(\.realmConfiguration, config)
        } else {
            // If there is no user logged in, show the login view.
            LoginView()
        }
    }
}
`

OpenRealmView [subsequent view]:

`import SwiftUI
import RealmSwift

/// Called when login completes. Opens the realm asynchronously and navigates to the Items screen.
struct OpenRealmView: View {
    @AsyncOpen(appId: theAppConfig.appId, timeout: 2000) var asyncOpen
    // We must pass the user, so we can set the user.id when we create Item objects
    @State var user: User
    @State var showMyItems = true
    @State var isInOfflineMode = false
    // Configuration used to open the realm.
    @Environment(\.realmConfiguration) private var config

    var body: some View {

        switch asyncOpen {
        case .connecting:
            // Starting the Realm.asyncOpen process.
            // Show a progress view.
            ProgressView()
        case .waitingForUser:
            // Waiting for a user to be logged in before executing
            // Realm.asyncOpen.
            ProgressView("Waiting for user to log in...")
        case .open(let realm):
            // The realm has been opened and is ready for use.
            // Show the Items view.
            ItemsView(leadingBarButton: AnyView(LogoutButton()), user: user, showMyItems: $showMyItems, isInOfflineMode: $isInOfflineMode)
                // showMyItems toggles the creation of a subscription
                // When it's toggled on, only the original subscription is shown -- "my_items".
                // When it's toggled off, *all* items are downloaded to the
                // client, including from other users.
                .onChange(of: showMyItems) { newValue in
                    let subs = realm.subscriptions
                    subs.update {
                        if newValue {
                            subs.remove(named: Constants.allItems)
                        } else {
                            if subs.first(named: Constants.allItems) == nil {
                                subs.append(QuerySubscription<Item>(name: Constants.allItems))
                            }
                        }
                    }
                }
                // isInOfflineMode simulates a situation with no internet connection.
                // While sync is not available, items can still be written and queried.
                // When sync is resumed, items created or updated offline will upload to
                // the server and changes from the server or other devices will be downloaded to the client.
                .onChange(of: isInOfflineMode) { newValue in
                    let syncSession = realm.syncSession!
                    newValue ? syncSession.suspend() : syncSession.resume()
                }
                .onAppear {
                    if let _ = realm.subscriptions.first(named: Constants.allItems) {
                        // The client was subscribed to all items from a previous
                        // session, so set UI toggle accordingly
                        showMyItems = false
                    }
                }
        case .progress(let progress):
            // The realm is currently being downloaded from the server.
            // Show a progress view.
            ProgressView(progress)
        case .error(let error):
            // Opening the Realm failed.
            // Show an error view.
            ErrorView(error: error)
        }
    }
}
`
