### ISSUE TITLE
PersistableEnum comparison fails in different contexts

### ISSUE THREAD

**Issue by Ahmed-Ali** [realm/realm-swift#8076]
I want to start by saying thank you everyone who got Realm that far! I played around with it like 6 years ago, and started to get around with it again today and it is fascinating how far things went. Thank you!

If you have any filed of an enum that conforms to the `PersistableEnum` protocol, you can't successfully use the `==` operator to compare this field. It always fail for some reason.

Adding
```
extension PersistableEnum {
    static func ==(lhs: Self, rhs: Self) -> Bool {
        return lhs.rawValue == rhs.rawValue
    }
}
```

Seems to fix the problem, but not sure if this impacts any underlying implementation in Realm
However, it doesn't fix the whole problem.
Assuming you have a field of type `Map<SomeEnumConformsToPersistableEnum, ValueType>`
you will always get `nil` when trying to fetch the value for any key even if the key does exist.

Any ideas?

**Comment by dianaafanador3** [comment]
HI @Ahmed-Ali Can you please let us know which version of Realm SDK are you using?. 
There should not having any issue comparing two `PersistableEnum`, our protocol conforms to Comparable which ensures any comparable operation can be done between two values of the enum.
`Map<SomeEnumConformsToPersistableEnum, ValueType>`, cannot be used with our `Map` data type, we only support a `String` as a key in a Map.

Everything is working fine for the following test
```
enum ModelEnum: Int, PersistableEnum {
    case one
    case two
}

enum ModelEnumString: String, PersistableEnum {
    case one
    case two
}

class ModelTest: Object {
    @Persisted var type: ModelEnum
    @Persisted var type2: ModelEnumString
}

func test() {
        let model = ModelTest()
        model.type = .two
        model.type2 = .two

        let model2 = ModelTest()
        model2.type = .two
        model2.type2 = .two

        XCTAssertEqual(model.type, model2.type)
        XCTAssertEqual(model.type2, model2.type2)

        if model.type == model2.type {
            XCTAssertTrue(true)
        }

        if model.type2 == model2.type2 {
            XCTAssertTrue(true)
        }
    }
```
I don't know if this answer your question or your use case is completely different to the one in the tests.

**Comment by Ahmed-Ali** [comment]
Thanks @dianaafanador3 that does help!
I figured out the comparison issue in my case and it was indeed user error and not Realm itself.
For the map not supporting anything other than a string for the key type, I did not know this one either. Might be helpful to make this a compile time error rather for the map type

**Comment by tgoyne** [comment]
Using a PersistableEnum as a map key isn't something we test or intended to work, but I suspect it does happen to work and if it doesn't then it'd _probably_ be easy to make it work.

**Comment by Ahmed-Ali** [comment]
I agree it shouldn't be that hard. Specially for enums whose raw value is actually string.
In my specific case I already wrap the maps/lists into dictionary/arrays for protocol conformance. So I had to just add a specified implementation where the dictionary key is Enum

for reference (in case it helps anyone, and also in case anyone has better suggestion)

```
final MyRealmType: Object {
  @Persisted var myFieldMap<String: ValueType>
}
extension MyRealmType: MyProtocol {
  var myField: [EnumType: ValueType] {
      get { getDictionary(fromMap: myFieldMap) }
      set { setValues(forMap: myFieldMap fromDictionary: newValue) }
  }
}

func getDictionary<Key: _Persistable & _MapKey & PersistableEnum, Value: _Persistable & RealmCollectionValue>(fromMap map: Map<Key.RawValue, Value>) -> [Key: Value] {
    var dict = [Key: Value]()
    for key in map.keys {
        dict[Key(rawValue: key)!] = map[key]
    }
    return dict
}

func setValues<Key: _Persistable & _MapKey & PersistableEnum, Value: _Persistable & RealmCollectionValue>(forMap map: Map<Key.RawValue, Value>, fromDictionary dict: [Key: Value]) {
    map.removeAll()
    dict.forEach { key, value in
        map[key.rawValue] = value
    }
}
```

**Comment by dianaafanador3** [comment]
@Ahmed-Ali I'll close this as there is no issue on our side, also there should be compile error if you have a Map with a PersistableEnum as a key for example `@Persisted var myFieldMap<SampleEnum, ValueType>`. I'll also open a new enhancement for supporting PersistableEnum as key in a `Map` https://github.com/realm/realm-swift/issues/8097.

**Comment by marchy** [comment]
As of Realm 10.38.2 the above mapping doesn't seem to work.

``` Swift
typealias ID = String

class MyType : Object {
	@Persisted var providerIdentifiers_:RealmSwift.Map</*Provider*/String, /*ID:*/String>
	var providerIdentifiers:[Provider: ID] {
		get { RealmUtils.getDictionary( fromMap: providerIdentifiers_ )}
		set { RealmUtils.setValues( forMap: providerIdentifiers_, fromDictionary: newValue )}
	}
}

public enum Provider : String, PersistableEnum {
	case One
	case Two
	case Three
}
```
where `RealmUtils` contains the exact two `getDictionary` and `setValues` methods from above.

Getting the following error: `Type 'Place.Provider' does not conform to protocol '_MapKey'`

@Ahmed-Ali Any idea why this is the case? Seems like it should work the same as your example. Is your `EnumType` defined the same way as `Provider` above?
