### ISSUE TITLE
Realm crash on on Unsigned .ipa/.app package

### ISSUE THREAD

**Issue by amirsaam** [realm/realm-swift#8079]
### How frequently does the bug occur?

All the time

### Description

Howdy,

While I was searching through issues here to find an answer to my own I saw that Mac Catalyst requirement is to have Keychain Sharing entitlement to don't crash (as I have been told before), while I had that enabled in my project to let other co-developers be able to work on the project and run Mac Catalyst version (iOS simulator was fine) but we have a specific requirement on that.

Our app is not to meant to be released on App Store and it will be distributed through Sideloading protocol into macOS and no matter what it will crash on it after we implemented Realm into it.

So, how can we avoid this to happen since there is no specific reason to not let me do it and is against developers will to use how they want to use Realm.

I have attached my own app crash log and SwiftUI Todo example project crash log.

[DecryptKit.ips.zip](https://github.com/realm/realm-swift/files/10284071/DecryptKit.ips.zip)

[SwiftUI TODO Peoject.ips.zip](https://github.com/realm/realm-swift/files/10284075/SwiftUI.TODO.Peoject.ips.zip)

Let me know if you need more details about it.

Regards.

### Can you reproduce the bug?

Yes, always

### Version

Realm 10.33.0, Realm Database 12.13.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

macOS 13.1

### Build environment

Xcode version: 14.2 (14C18)

**Comment by amirsaam** [comment]
Can I use something like https://github.com/kishikawakatsumi/KeychainAccess to do workaround for it?

**Comment by amirsaam** [comment]
In fact I am building package unsigned using:
```swift
xcodebuild archive -project <XCODEPROJ> -scheme <SCHEME> -archivePath unsigned.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
```

**Comment by tgoyne** [comment]
We should be trying to handle this case automatically, but you can work around this by setting the `REALM_DISABLE_METADATA_ENCRYPTION` environment variable to any non-empty value before opening a Realm. Note that this will result in the user's access token being stored in plain text.

**Comment by amirsaam** [comment]
@tgoyne thank you for the answer!
Unfortunately I am not finding any data about `REALM_DISABLE_METADATA_ENCRYPTION`, can you please elaborate how should it be done?

**Comment by amirsaam** [comment]
Note that I am using sync to Atlas not local Realm

**Comment by dianaafanador3** [comment]
Hi @amirsaam a production app should never have metadata encryption disable, that's why we don't include this in our App Configuration.
You should add REALM_DISABLE_METADATA_ENCRYPTION=1 to your Environment Variables in your schema run Arguments.
<img width="937" alt="Screenshot 2023-01-03 at 13 31 45" src="https://user-images.githubusercontent.com/5484247/210357934-b9cf51e1-fe84-4106-b6f4-80e335c995f9.png">

**Comment by tgoyne** [comment]
Setting it in the scheme only effects launching it from Xcode. Prior to opening a Realm, you'll need to call `setenv("REALM_DISABLE_METADATA_ENCRYPTION", "1", 1)`.

**Comment by amirsaam** [comment]
since we couldn't just add `setenv` before `@main, I have added it in `loadRealmAppConfig()` function before its `return` and it got fixed!
Thanks for your helps.

**Comment by amirsaam** [comment]
Did anything changed since before and Realm handles this now automatically?
I tested again w/o setenv and the app didn't crash.
Is it just a coincidence?
