### ISSUE TITLE
[BUG] CRASH StringIndex alloc.hpp

### ISSUE THREAD

**Issue by phanducthang** [realm/realm-swift#8082]
### How frequently does the bug occur?

Sometimes

### Description

Got a report of the following crash from Firebase Crashlytic. It seems to occur every time for this user when trying to get data from the database and it's happened frequently times on specific users. . Unfortunately, I don't have the realm database file.

### Stacktrace & log output

```shell
Crashed: rx.global_dispatch_queue.serial
0      0xc0ca68 StringIndex + 562 (alloc.hpp:562)
1     0xdee878 refresh_index_accessors + 1572 (vector:1572)
2     0xbfa144 create_table_accessor + 1572 (vector:1572)
3     0xbf9dd0 do_get_table + 666 (group.cpp:666)
4     0xe097f0 check_consistency + 958 (group.hpp:958)
5     0xbe3be8 open + 958 (shared_ptr.h:958)
6     0xbe5f3c open + 485 (vector:485)
7     0xbe9c4c create + 485 (vector:485)
8     0xc76d88 open_db + 869 (shared_ptr.h:869)
9     0xc77bfc do_get_realm + 282 (realm_coordinator.cpp:282)
10    0xc77a8c get_realm + 93 (shared_realm.hpp:93)
11    0xcdabf4 get_shared_realm + 93 (shared_realm.hpp:93)
12    0xb7a3d8 +[RLMRealm realmWithConfiguration:queue:error:] + 869 (shared_ptr.h:869)
13    0xec1a58 init + 834732 (<compiler-generated>:834732)
14    0x4d42b0 <name omitted> + 29 (RealmRepository.swift:29)
15    0x724c9c <name omitted> + 4304440476 (<compiler-generated>:4304440476)
16    0x724ed8 run + 36 (Deferred.swift:36)
17    0x72525c run + 73 (Deferred.swift:73)
18    0x751aa8 <name omitted> + 26 (Producer.swift:26)
19    0x751194 schedule + 18 (CurrentThreadScheduler.swift:18)
20    0x751094 subscribe + 24 (Producer.swift:24)
21    0x746990 subscribe + 4304578960 (<compiler-generated>:4304578960)
22    0x76c04c <name omitted> + 79 (SubscribeOn.swift:79)
23    0x72a560 <name omitted> + 27 (DispatchQueueConfiguration.swift:27)
24   0x71f95c <name omitted> + 4304419164 (<compiler-generated>:4304419164)
25 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
26 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
27 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
28 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
29 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
30 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
31 libsystem_pthread.dylib        0xe5c start_wqthread + 8
```

### Can you reproduce the bug?

Not yet

### Version

10.30.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Model:iPad (8th generation) Orientation: Landscape RAM free: 452.47 MB Disk free: 18.68 GB Operating System Version:15.6.1

### Build environment

Xcode version: Version 14.0.1 (14A400)
Dependency manager and version:  Realm: 10.30.0

**Comment by dianaafanador3** [comment]
Hi @phanducthang It seems there is a data corruption in the file and looking up the index is just one of the first things that happens which is throwing the error. 
It is really hard to determine how the file got into that state without taking a look a the realm file, if you can get a user to send you the file after this issue, that will be very helpful.
Some corruption issues has been fixed in our latest releases, updating to the most recent version may fix some of this issues, as well.
This may be related to this https://github.com/realm/realm-swift/issues/7286.

**Comment by dianaafanador3** [comment]
Hi @phanducthang we solved some corrupted issue in our latest releases, please update to our latest version and let us know if you're still getting experiencing this issue.

**Comment by leemaguire** [comment]
Closing as the latest version of Realm should solve this issue. If the problem persists on the latest version please open a new issue.
