### ISSUE TITLE
$sort order for BSON RealmSwift document

### ISSUE THREAD

**Issue by davidkessler-ch** [realm/realm-swift#8083]
### How frequently does the bug occur?

All the time

### Description

I stumbled across very strange behaviour in my aggregate query that I am running in Swift (using RealmSwift package) through:

```swift
db.collection(withName: "Example")..aggregate(pipeline: aggregatePipeline) { ... }
```

This is the stage that is behaving very strangely:

```swift
let aggregatePipeline: [Document] = [
                [
                    "$sort": [ "seen": 1 , "score": -1, "_id": -1 ]
                ]
]
```

The results I get are sorted by these three keys, but in seemingly arbitrary sorting order each time I run the query. So sometimes the "seen" sorting is prioritised (as it should be) but sometimes it sorts first by "_id", or "score". When I print the stage right after defining it by running:

```swift
print(aggregatePipeline[0])
```

I do see a the probable reason for those odd results... first run prints:

```swift
["$sort": Optional(RealmSwift.AnyBSON.document(["_id": Optional(RealmSwift.AnyBSON.int64(-1)), "seen": Optional(RealmSwift.AnyBSON.int64(1)), "score": Optional(RealmSwift.AnyBSON.int64(-1))]))]
```

second run prints:

```swift
["$sort": Optional(RealmSwift.AnyBSON.document(["seen": Optional(RealmSwift.AnyBSON.int64(1)), "score": Optional(RealmSwift.AnyBSON.int64(-1)), "_id": Optional(RealmSwift.AnyBSON.int64(-1))]))]
```

In the relevant [docs](https://www.mongodb.com/docs/manual/reference/operator/aggregation/sort/) or especially [this](https://www.mongodb.com/docs/realm/sdk/swift/app-services/mongodb-remote-access/) it is stated that sorting should be done like this. Am I missing something or is this a bug?

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```swift

let aggregatePipeline: [Document] = [
                [
                    "$sort": [ "seen": 1 , "score": -1, "_id": -1 ]
                ]
]

print(aggregatePipeline[0])
```

### Version

10.33

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

MacOS

### Build environment

Xcode version: 14.1

**Comment by dianaafanador3** [comment]
Hi @davidkessler-ch thanks for opening the issue. Closing this as there is already an issue where we discuss this https://github.com/realm/realm-swift/issues/7188. Unfortunately our current API uses a dictionary `Dictionary<String, AnyBSON?>` (which is unorganised), to set up the sort order. Because  changing this API will be a breaking change, we are waiting for a major release to change this.
