### ISSUE TITLE
mac catalyst error when archive: could not build Objective-C module 'Realm'

### ISSUE THREAD

**Issue by Norwa9** [realm/realm-swift#8086]
### How frequently does the bug occur?

All the time

### Description

I create a demo project, only adding 'pod 'RealmSwift', and set this project's supported destinations including 'Mac(Mac catalyst)',
when I archive the project, error occur:
1. Could not build Objective-C module 'Realm' in Aliases.swift file
2. Umbrella header 'Realm.h' not found in module.modulemap file

### Stacktrace & log output

```shell
Could not build Objective-C module 'Realm'
Umbrella header 'Realm.h' not found
```

### Can you reproduce the bug?

Yes, always

### Version

realm:10.33.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS:12.6 (21G115), Xcode:Version 14.2 (14C18)

### Build environment

Xcode version: 14.2
Dependency manager and version: ...

**Comment by dianaafanador3** [comment]
Hi @Norwa9 can you upload or attach a reproduction project for this. I tried your reproduction steps and the issue is not happening in my sample project.

**Comment by leemaguire** [comment]
`RealmSwift` has a dependancy of `Realm` so you don't need to explicitly declare it. There also seems to be an issue with CocoaPods and Xcode 14.3. This SO comment solved the issue for me when I reproduced it https://stackoverflow.com/a/76062768
