### ISSUE TITLE
Memory not freed when Realm goes out of scope

### ISSUE THREAD

**Issue by mungbeans2** [realm/realm-swift#8090]
### How frequently does the bug occur?

Always

### Description

There is no Realm close method when using Swift, and the documentation states:

There is no need to manually close a realm in Swift or Objective-C. When a realm goes out of scope and is removed from memory due to ARC, the realm is closed.
(https://www.mongodb.com/docs/realm/sdk/swift/realm-files/configure-and-open-a-realm/)

But I am finding memory is never released in my app when it's finished using Realm. Here's a code snippet I created which reproduces and condenses the issue on iOS:

```
autoreleasepool {
    NSLog("App memory usage is 19MB at this point")
    iDontReleaseMemory()
    NSLog("Now its 34Mb")
}
NSLog("Its still 34MB")

func iDontReleaseMemory() {
    autoreleasepool {
        do {
            let theConfig = Realm.Configuration()
            let realm = try Realm(configuration: theConfig)
        } catch let error as NSError {
      }
   }
}
```

The memory usage jumps from 19MB to 34MB when the line let realm = try Realm(configuration: theConfig) is executed. It stays at 34MB forever afterwards.

The usage of Realm is confined within a function and only local variables are used within the function, for good measure its in an autorelease pool, as is its invocation.
If the Realm doesn't go out of scope when the iDontReleaseMemory() exits, and if memory doesn't get freed via the autoreleasepool, then when exactly does it go out of scope and release its memory and how can that be forced if the code above isn't doing so?

### Can you reproduce the bug?

Always

### Reproduction Steps

See code in description

### Version

10.32.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

All versions of iOS

### Build environment

Xcode version: ..14.1
Dependency manager and version: ...

**Comment by tgoyne** [comment]
There is a significant amount of lazy-loaded data which is initialized the first time you access a Realm which then stays in memory until the process terminates. The largest portion of this is just lazy-loaded dynamic frameworks; many of the system frameworks are not actually loaded until they're first used, and automatic schema discovery requires that we eagerly initialize all frameworks. We also have some internal structures such as the shared schema which we calculate once and then store forever, but these are very small in comparison.

**Comment by mungbeans2** [comment]
@tgoyne This is causing a real problem for my app. 
I'm using Realm in a notification service extension and doing that is taking up 15KB of memory which isn't being freed. That leaves insufficient memory for the extension to do other processing and the result in the extension crashes as it runs out of memory. 

What I would like to be able to do is open Realm, use it, then close it and any resources it used freed.

The fact that memory is never being freed by Realm makes it next to useless for use in extensions if whatever else the extensions are doing takes up several MG of memory.

**Comment by tgoyne** [comment]
In an extension you will want to explicitly set `objectTypes` in your Realm configuration rather than relying on automatic schema discovery, as this avoids eagerly loading all of the linked frameworks.

**Comment by mungbeans2** [comment]
@leemaguire it helps with reducing the amount of memory Realm uses
