### ISSUE TITLE
static.realm.io certificate has expired

### ISSUE THREAD

**Issue by zacwest** [realm/realm-swift#8092]
### How frequently does the bug occur?

Always

### Description

```bash
> curl https://static.realm.io -v
*   Trying [2600:9000:21c4:1400:c:c7f8:96c0:93a1]:443...
* Connected to static.realm.io (2600:9000:21c4:1400:c:c7f8:96c0:93a1) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### Stacktrace & log output

```
 Installing Realm (10.33.0)
[!] /bin/bash -c 
set -e
sh scripts/setup-cocoapods.sh

Downloading dependency: 12.13.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.13.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v12.13.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Attempt to install Realm via Cocoapods

### Version

12.13.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 13

### Build environment

Xcode version: Xcode 14.1
Dependency manager and version: Cocoapods 1.11.3

**Comment by sst-tim** [comment]
I can confirm facing same issue at the moment

**Comment by NobodyButMe-Haiya** [comment]
confirm  also

**Comment by DukeLuo** [comment]
also get this issue

**Comment by septe01** [comment]
yess, I get this issue too

![Screen Shot 2023-01-09 at 10 30 00](https://user-images.githubusercontent.com/30195561/211236891-0342ff04-efff-4edd-9d23-31c63304e3ca.png)

**Comment by quangkhaidam93** [comment]
I am the same

**Comment by DukeLuo** [comment]
If you get error like this in React Native project, you can use `export NODE_TLS_REJECT_UNAUTHORIZED=0` to disabling certificate verification in Node.

![image](https://user-images.githubusercontent.com/26000789/211252974-2e8ee001-a4ca-4793-a8cc-57e7a585dfda.png)

**Comment by chatarveer** [comment]
Happening to my project too. 


`Downloading dependency: 11.1.1 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.1.1.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.1.1.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
##[error]The process '/usr/local/lib/ruby/gems/3.0.0/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/pod' failed with exit code 1
`

**Comment by Netacom-NetAlo** [comment]
also get this issue

Installing Realm (10.12.0)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

Downloading dependency: 11.2.0 from https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.2.0.tar.xz
Downloading core failed:
	https://static.realm.io/downloads/core/realm-monorepo-xcframework-v11.2.0.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by PigHeroT** [comment]
also get this issue

![Screenshot 2023-01-09 at 2 29 50 PM](https://user-images.githubusercontent.com/13663410/211258896-c97985a5-8fcd-4d69-8532-384648798f37.png)

**Comment by chatarveer** [comment]
Seems same thing happened in past -- 

[Realm SSL Issue] (https://github.com/realm/realm-swift/issues/7825)

**Comment by malgee012** [comment]
I had the same problem

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/17418390/211274469-41027734-c563-49ae-9ecc-3f8bce31fcb5.png">

**Comment by mehul2013** [comment]
I also facing `CERT_HAS_EXPIRED` issue from Realm. Please provide quick solution as soon as possible.
![Screenshot 2023-01-09 at 2 44 05 PM](https://user-images.githubusercontent.com/4091807/211274776-c364dacd-d6db-4f44-a2aa-a6d015d1abf6.png)

**Comment by VscDnl** [comment]
same problem here

<img width="859" alt="Screenshot 2023-01-09 at 10 22 28" src="https://user-images.githubusercontent.com/56850664/211275824-2c34ac0a-9537-4a09-88d8-e607b72076ba.png">

**Comment by kanji-dubizzle** [comment]
![Screenshot 2023-01-09 at 1 57 29 PM](https://user-images.githubusercontent.com/81670605/211282198-acd81020-3832-42bd-b199-cf206dda6649.png)

**Comment by mehul2013** [comment]
Hello All,
I found a temporary solution for **React Native developers**. 
**Please Follow the below steps:**

- Copy and replace `node_modules/realm` from another git branch or backup(which has an older app installed and **didn't had done pod install for the last 2 days**.) or copy from your colleague's system.
- Then do `pod install` and run the app.

I hope it might be helpful to native iOS developers also.
Thank you

**Comment by drmas** [comment]
Another workaround for React Native apps is to disable node certificate check using:
`NODE_TLS_REJECT_UNAUTHORIZED=0 yarn` or `NODE_TLS_REJECT_UNAUTHORIZED=0 npm install`

**Comment by dianaafanador3** [comment]
static.realm.io certificate has expired. We are working to fix this and we hope to have a resolution by the end of the day.

**Comment by ilyasemenow90** [comment]
Workaround
You can add insecure option to your `$HOME/.curlrc` file:
`vi $HOME/.curlrc`

Append the following:

`insecure`

Save and close the file. However, I do not recommend disabling SSL checks for all connections by default for security reasons.

More details here https://www.cyberciti.biz/faq/how-to-curl-ignore-ssl-certificate-warnings-command-option/

**Comment by geragray** [comment]
Downloading of binaries from static.realm.io has been fixed. Please accept our apologies for the inconvenience.
