### ISSUE TITLE
Unable to install realm pod 

### ISSUE THREAD

**Issue by sumit-vts** [realm/realm-swift#8093]
### How frequently does the bug occur?

Always

### Description

When i hit command Pod Install in terminal
I'm getting below error

[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 4.7.11 from https://static.realm.io/downloads/sync/realm-sync-cocoa-4.7.11.tar.xz
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-4.7.11.tar.xz
	curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Realm Pod is not able to install in my project.
I'm able to run other pods as well.

### Can you reproduce the bug?

Always

### Version

3.20.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by michalnowak061** [comment]
the same

**Comment by pahanius** [comment]
Use SwiftPM instead of Pods.

**Comment by visdyn** [comment]
Can you include your Podfile and version of Cocoapods?

**Comment by bmunkholm** [comment]
You are using an ancient version, so I would suggest to upgrade to a newer and let us know if that still causes issues. Thanks!
