### ISSUE TITLE
Adding .searchable to a SwiftUI List populated with ObservedResults makes List not updated with new result

### ISSUE THREAD

**Issue by piersonleo** [realm/realm-swift#8096]
### How frequently does the bug occur?

Always

### Description

I have a SwiftUI list that I populate using ObservedResults. So everytime there's a change to the database my list would be updated.

Since I want to be able to filter my list, I added .searchable to the list. But after adding .searchable to the list, it doesn't get updated anymore when I added a new result to my list. To make the list update I have to search for it first from the search bar.

If I remove the searchable my list is updated with new result as expected after adding. 

### Can you reproduce the bug?

Always

### Reproduction Steps

Here's the code of my view

```
import SwiftUI
import RealmSwift

struct AccountList: View {

    @ObservedResults(
        AccountEntity.self,
        sortDescriptor: SortDescriptor(keyPath: "name", ascending: true)
    ) var accounts
    
    @State private var searchFilter = ""
    
    var body: some View {

        NavigationStack {
            List(accounts) { account in
                NavigationLink{
                    AccountDetail(account: account)
                } label: {
                    AccountRow(account: account)
                }
            }
            .searchable(text: $searchFilter,
                        collection: $accounts,
                        keyPath: \.name) {
                ForEach(accounts) { accountsFiltered in
                    
                }
            }
        }
        .navigationTitle("Accounts")
    }
}
```

And my add function is simple like this, which I call from another view

```
func addAccount(account: AccountEntity){
        let defaultRealm = try! Realm()
        
        try! defaultRealm.write{
            defaultRealm.add(account)
        }
}

```

### Version

12.13

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Monterey 12.6.1

### Build environment

Xcode version: 14.1
Dependency manager and version: ...

**Comment by leemaguire** [comment]
Hi @piersonleo I cannot reproduce your issue with the given steps. Could you create a small app that reproduces this issue?

**Comment by piersonleo** [comment]
Hi @leemaguire here's the sample app that reproduces this issue

https://github.com/piersonleo/RealmSearchable

**Comment by leemaguire** [comment]
@piersonleo Thanks for this we will investigate.

**Comment by leemaguire** [comment]
I've found the cause of this. I'll get a PR up shortly.

**Comment by piersonleo** [comment]
Great! Hope it gets merged soon!
