### ISSUE TITLE
SSL handshake failed: invalid certificate chain

### ISSUE THREAD

**Issue by labelcoin** [realm/realm-swift#8099]
### How frequently does the bug occur?

Always

### Description

User is successfully logging in but I get a SSL handshake failed: invalid certificate chain when trying to Open a Realm with flexibleSyncConfiguration.

I get the same error when I try using partitions

### Stacktrace & log output

```shell
2023-01-13 13:47:18.768111+0000 -------[1882:354976] Sync: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, client reset = false
2023-01-13 13:47:19.915756+0000 -------[1882:354976] Sync: Connected to endpoint ':443' (from ':55204')
2023-01-13 13:47:21.496084+0000 -------[1882:354976] Sync: Connection[1]: SSL handshake failed: invalid certificate chain
2023-01-13 13:47:21.496270+0000 -------[1882:354976] Sync: Connection[1]: Connection closed due to error
```

### Can you reproduce the bug?

Always

### Reproduction Steps

```swift
func initialize() async throws {
        //auth
        realmUser = try await app.login(credentials: .anonymous)
        self.configuration = realmUser?.flexibleSyncConfiguration(initialSubscriptions: { subs in
            if subs.first(named: "events") == nil {
                subs.append(QuerySubscription<Event>(name: "events"))
            }
            return
            
        }, rerunOnOpen: true)
        if let configuration = configuration {
            realm = try? await Realm(configuration: configuration, downloadBeforeOpen: .never)
        }
    }
```

### Version

12.13.0

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

16.1

### Build environment

Xcode version: Version 14.1
Dependency manager and version: Package Manager
MacOS Version: 12.5 M1 MacBook Pro

**Comment by leemaguire** [comment]
Hi @labelcoin Are you using a VPN, proxy etc? Is the date & time on your device correct?
