### ISSUE TITLE
Database has an unsupported version (23) and cannot be upgraded Exception backtrace:

### ISSUE THREAD

**Issue by claudeios** [realm/realm-swift#8101]
### How frequently does the bug occur?

Always

### Description

RealmSwift ~>10
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=6 "Opening Realm files of format version 23 is not supported by this version of Realm" UserInfo={Error Code=6

### Can you reproduce the bug?

No

### Version

~>10

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

16.1

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by leemaguire** [comment]
You need to update to the latest version of Realm.

**Comment by claudeios** [comment]
@leemaguire I found out that realm browser is generating v23 whenever i am opening it when my xcode project is only ready v22.

**Comment by NickKhachtryan** [comment]
hello! how did you solve this problem? Cause i have the same problem, please help

**Comment by claudeios** [comment]
@NickKhachtryan you have to check app realm folder if the version of default.realm is being changed when you are opening it in realm browser

**Comment by NickKhachtryan** [comment]
i just solved it by deleting my default.realm file
