### ISSUE TITLE
No exact matches in reference to subscript on Date

### ISSUE THREAD

**Issue by Nerkyator** [realm/realm-swift#8102]
### How frequently does the bug occur?

Always

### Description

This is my model

```
class Event: Object, ObjectKeyIdentifiable {
    @Persisted(primaryKey: true) var _id: ObjectId
    @Persisted var _partitionValue: String = Constants.realmPartition.rawValue
    @Persisted var date: Date
    @Persisted var kind: EventKind?
    @Persisted var times: Int
    }
```
    
In a class I need to filter events by date, this is the code

`self.filteredEvents = realm.objects(Event.self).where { $0.date.isToday }`

(`filteredEvents` is declared as `var filteredEvents: Results<Event>`)

but this cannot even compile because Xcode says _No exact matches in reference to subscript_ 

The error appears also with other properties you try to use on `$0.date,` like `isLeapYear`, `isInFuture`, `isInPast` etc

### Can you reproduce the bug?

Always

### Version

10.34.0

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.3

### Build environment

Xcode version: 14.2
Dependency manager and version: SPM

**Comment by leemaguire** [comment]
These Date extensions would need to be extended from our `Query` struct. An example of how to do this would be:
```swift
extension Date {
    var startOfDay: Date {
        return Calendar.current.startOfDay(for: self)
    }

    var endOfDay: Date {
        var components = DateComponents()
        components.day = 1
        components.second = -1
        return Calendar.current.date(byAdding: components, to: startOfDay)!
    }
}

extension Query where T == Date {
    var isToday: Query<Bool> {
        let date = Date()
        return self.contains(date.startOfDay..<date.endOfDay)
    }
}
```
