### ISSUE TITLE
RealmSwift 10.34.0 install with SPM, compiling error about @Sendable

### ISSUE THREAD

**Issue by ACFancy** [realm/realm-swift#8104]
- RealmSwift 10.34.0 install with SPM, building compiling error:
     - Converting non-sendable function value to ‘@Sendable (UInt, UInt) → Bool’ may introduce data races
     - ![image](https://user-images.githubusercontent.com/10044815/213386143-7f2ee4aa-492b-4725-b480-22480395a490.png)
     - swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx13.0
     - Xcode Version 14.0.1 (14A400)

**Comment by ACFancy** [comment]
@tonyarnold

**Comment by ACFancy** [comment]
@tgoyne

**Comment by DouweBos** [comment]
Getting the same when validating a cocoapod podspec, so this is not a SPM unique issue.

**Comment by tgoyne** [comment]
I think this is specific to non-macOS Xcode 14.0. I disabled the sendability annotations when building with Xcode 14.0 because too many of the platform SDK types were missing sendable annotations, but in retrospect that was probably because I was testing for macOS and thus still using the macOS 12 SDK.

**Comment by ACFancy** [comment]
@tgoyne  Have some solutions, plan or ideas to solve that compiling error?

**Comment by danieljoska** [comment]
Ran into the same issue on MacOS Monterey 12.5 (M2 Apple Silicon) and XCode 14.0.1 when attempting to install and build RealmSwift 10.34.0 with SPM. In my case, the error was fixed by updating XCode to version 14.2 and recompiling.
