### ISSUE TITLE
Realm Custom-Token Login failed. [When switched to partition based sync to Flexible sync]

### ISSUE THREAD

**Issue by Kathiravan001** [realm/realm-swift#8108]
### How frequently does the bug occur?

Always

### Description

Hi
We have released the app with  change of Partition based sync to flexible sync configuration with new appId in the new release. User can able to login with JWT token credentials for Realm login. But when the user did not use the app for 3 or more then 3 days, after open the app all the user facing realm Custom token Auth Error, with error of
 "'"appid"' not found in 'aud' claim" & and user can't able to have any access any features in through the app. When i checked with the jwt generated token in online decode platform the payload contains the old appId. How it was possible?.
 Can anyone help me out this......?
 The realm swift version was used is 10.28.2
 
<img width="435" alt="Screenshot 2023-01-21 at 10 25 23 PM" src="https://user-images.githubusercontent.com/123259892/213877883-5be720e3-63dd-4d6c-8586-1c7a2cf616e5.png">

### Can you reproduce the bug?

No

### Version

10.28.2

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

-- select --

### Platform OS and version(s)

iOS

### Build environment

Xcode version: ...14.2

**Comment by leemaguire** [comment]
Hi @Kathiravan001 Can you show us how you are generating the custom token on the client side?

**Comment by bmunkholm** [comment]
@Kathiravan001 We can't help without your input. Have you resolved the issue?
