### ISSUE TITLE
Git Clone Issue

### ISSUE THREAD

**Issue by Brett-Best** [realm/realm-swift#8116]
### How frequently does the bug occur?

Always

### Description

When cloning the project, a warning about colliding file paths is printed.
While the clone does succeed this causes the checkout to be dirty and when a dependency manager e.g. Carthage, attempts to checkout another branch or tag it fails because of changes in the `.github/workflows/Issue-Needs-Attention.yml`.

### Stacktrace & log output

```shell
brettbest@Bretts-iMac ~/Downloads> git clone git@github.com:realm/realm-swift.git
Cloning into 'realm-swift'...
remote: Enumerating objects: 91975, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 91975 (delta 26), reused 32 (delta 15), pack-reused 91907
Receiving objects: 100% (91975/91975), 66.28 MiB | 2.13 MiB/s, done.
Resolving deltas: 100% (66142/66142), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  '.github/workflows/Issue-Needs-Attention.yml'
  '.github/workflows/issue-needs-attention.yml'
```

### Can you reproduce the bug?

Always

### Reproduction Steps

In terminal run `git clone git@github.com:realm/realm-swift.git`.

### Version

N/A

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 12.6.3 (21G419)

### Build environment

Xcode version: 14.2 (14C18)
git version 2.39.1
Dependency manager and version: N/A

**Comment by bmunkholm** [comment]
Thanks for reporting @Brett-Best - It's ben fixed now.
