### ISSUE TITLE
Unable to Receive 100 push notifications on a single device from Realm Function

### ISSUE THREAD

**Issue by neelchheda** [realm/realm-swift#8121]
`exports = function(changeEvent) {
    let enteredTime = new Date();
    let ehours = enteredTime.getHours();
    let eminutes = enteredTime.getMinutes();
    let eseconds = enteredTime.getSeconds();
    let emilliseconds = enteredTime.getMilliseconds();

    console.log(`Entered date and time: ${enteredTime.toLocaleDateString()} ${ehours}:${eminutes}:${eseconds}:${emilliseconds}`);

    console.log(JSON.stringify(changeEvent.fullDocument));
    let body = {};
    let alert = {};
    let payload = {};
    let aps = {};
    let triggerData = {};
    let token = "";

        var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
        const xhr = new XMLHttpRequest();
        var url = "http://4.227.137.1:5000/api/trigger";
        xhr.open('POST', url, true);
        xhr.timeout = 5000; 
        const fullDocument = changeEvent.fullDocument;
        alert = fullDocument.alertObj;
        payload = fullDocument.payload;
        body.alert = alert;
        body.payload = payload;
        body.sound = "chime.aiff";
        console.log("Body Data", JSON.stringify(body));
        triggerData.aps = body;
        token = fullDocument.token;
        triggerData.token = token;
        console.log("Trigger Data", JSON.stringify(triggerData));

        xhr.onreadystatechange = function() {
                console.log("Final State :", JSON.stringify(xhr.readyState));
            };
        xhr.send(JSON.stringify(triggerData));
        console.log(xhr.readyState);   
    let exitTime = new Date();
    let xhours = exitTime.getHours();
    let xminutes = exitTime.getMinutes();
    let xseconds = exitTime.getSeconds();
    let xmilliseconds = exitTime.getMilliseconds();

    console.log(`Exited date and time: ${exitTime.toLocaleDateString()} ${xhours}:${xminutes}:${xseconds}:${xmilliseconds}`);
};`

This is the code which send 1 push notification, but when this is looped 100 times, the Realm function can only send 25 notifications ta once.

**Comment by dianaafanador3** [comment]
Hi @neelchheda can you check on the App services logs if you are getting all the functions request, and if you see them, if there is any error?. If everything is correct you'll have to check your push notifications services logs to find out what is the issue.

**Comment by dianaafanador3** [comment]
Hi @neelchheda did you follow the above instructions?, we need more information to be able to diagnose this.
