### ISSUE TITLE
Realm Transactions, Read Inside or Outside

### ISSUE THREAD

**Issue by mgrms** [realm/realm-swift#8122]
### How frequently does the bug occur?

Sometimes

### Description

Hello,

We use Realm very actively, that is, we have a very large number of creates/updates/deletes, several every second.

Sometimes we see a crash that an object has been deleted or invalidated.

We noticed the following thing, that when we change code from this:

```
if let task = realm.object(ofType: Task.self, forPrimaryKey: taskId) {
   try realm.write {
      task.priority = 5
      task.title = "Task title"
   }
}
```

to this:
```
try realm.write {
  if let task = realm.object(ofType: Task.self, forPrimaryKey: taskId) {
      task.priority = 5
      task.title = "Task title"
   }
}
```

Then it seems we can no longer reproduce this crash. 

Can you please tell if there is a difference whether we read the object **inside** the transaction or **outside**? How to do better/correct and what is the difference? We could not find the information in the documentation.

I also wanted to note that we do all these transactions on a separate serial queue, maybe this matters.

Thank you.

### Can you reproduce the bug?

Sometimes

### Version

10.34.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 15,16

### Build environment

Xcode version: 14.2
Dependency manager and version: CocoaPods

**Comment by tgoyne** [comment]
Beginning a write transaction refreshes the Realm. If you're using Realm on multiple threads, each Realm instance will have a stale view of the data between when the write is committed and when the Realm is next refreshed, and inside a write transaction is the only time you can be guaranteed to see the latest data (as no other threads can be writing).

**Comment by mgrms** [comment]
@tgoyne 

Thanks for your answer.

That is, is it normal practice to read an object inside a transaction? In the documentation, all examples are when an object is read outside a transaction and only updated inside a transaction, and this confused me a little.

**Comment by tgoyne** [comment]
Yes, you should perform any validation checks you need inside the write transaction. Depending on how performance sensitive this is you may wish to check both before beginning the write and inside the write:

```
if let task = realm.object(ofType: Task.self, forPrimaryKey: taskId) {
   try realm.write {
      guard !task.isInvalidated else {
          realm.cancelWrite()
          return
      }
      task.priority = 5
      task.title = "Task title"
   }
}
```

This would avoid starting the write if the object already doesn't exist, and then cancels the write if it's been deleted simultaneously by someone else, which is marginally faster than committing an empty transaction.

**Comment by mgrms** [comment]
@tgoyne 

Wow, didn't know this trick with `cancelWrite()`! Amazing!

Thank you so much for your help, really appreciate it! I'll close the ticket now.

Have a nice day!

**Comment by mgrms** [comment]
@tgoyne 

One more thing to clarify to completely understand how it works:

1)
```
if let task = realm.object(ofType: Task.self, forPrimaryKey: taskId) {
   try realm.write {
      guard !task.isInvalidated else {
          realm.cancelWrite()
          return
      }
      task.priority = 5
      task.title = "Task title"
   }
}
```

2)
```
try realm.write {
  guard let task = realm.object(ofType: Task.self, forPrimaryKey: taskId) else {
    realm.cancelWrite()
    return
  }
  task.priority = 5
  task.title = "Task title"
}
```

As far as I understand these 2 approaches are doing the same, because in 2) case we don't need to check **`.isInvalidated`** since we are already inside a transaction and Realm should be already up to date. Am I right? Or it still better to read an object outside a transaction for some reason? Does these 2 cases have any difference? Is it safe to **read** from Realm inside a **write {...}** transaction?

Sorry for bothering.

**Comment by tgoyne** [comment]
You don't want to do _too_ much work inside a write transaction, but that's more of that you shouldn't do a synchronous network request or something. Just looking up an object in the Realm is much faster than even a very simple modification. The only reason to do the check before starting the write is to avoid waiting for the write lock if you don't need to, which doesn't really matter if you're writing on a background thread, but does if you're writing on the main thread (which is generally a bad idea).

**Comment by mgrms** [comment]
We have a dedicated background queue (DispatchQueue) for Realm transactions **only** , we don't have any logic (networking, calculations etc) there except Realm read/writes, so as I understand, option 2 will work normally for us and is good option to go with?

**Comment by tgoyne** [comment]
Yeah, probably no benefit from checking before the write in that scenario.

**Comment by mgrms** [comment]
@tgoyne 

Thanks again for your help.

When migrating to this new approach, another question came up:

What about Results? After some googling I see that Results used to have **`isInvalidated`** property, but it seems like it does not exist in latest Realm SDK.

As an example following code:

```
let tasks = realm.objects(Tast.self).filter("type == 1")
try realm.write {
   realm.delete(tasks)
}
```

Should we do something like this? :

```
let tasks = realm.objects(Tast.self).filter("type == 1")
try realm.write {
   let validTasts = tasks.filter { !$0.isInvalidated }
   realm.delete(validTasts)
}
```

Or to move the read inside a transaction to be sure that all the objects in `**tasks**` are valid:

```
try realm.write {
   let tasks = realm.objects(Tast.self).filter("type == 1")
   realm.delete(taks)
}
```

Or Realm will check it internally during deletion of this objects? And the same thing is actual for Lists I think.

Thank you.
