### ISSUE TITLE
Please implement `.caseAndDiacriticInsensitive` string filtering in Realm Swift Query

### ISSUE THREAD

**Issue by vladavasek** [realm/realm-swift#8128]
### Problem

While using NS predicates we can specify `CONTAINS[cd]` to perform both case and diacritic insensitive string filtering at the same time.
However, while using Realm Swift Query we can only specify `.caseInsensitive` or `diacriticInsensitive` but not a combination of both.

### Solution

Please implement the `.caseAndDiacriticInsensitive` option for Realm Swift Query that works exactly the same as `CONTAINS[cd]` of NS predicate.

### Alternatives

There is a clumsy workaround:

`results!.where {$0.property.contains(string, options: .caseInsensitive) || $0.property.contains(string, options: .diacriticInsensitive)}`

but it doesn't find all relevant strings.

For example, let's say we have four strings: "Á", "A", "á", "a". 
The workaround will only find three of them – if we search for "a" it will only find "á", "a", "A" but not "Á".
NS predicate, on the other hand, will find all of them correctly.

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by horatiu1921** [comment]
What if you group the options? Something like this:

```
results!.where { $0.property.contains(string, options: [.caseInsensitive, .diacriticInsensitive]) }
```

**Comment by vladavasek** [comment]
How simple, thank you, your solution works. It just didn't occur to me to use a set of options, my bad.

**Comment by horatiu1921** [comment]
Excellent! Glad I could help.

**Comment by vladavasek** [comment]
This is solved using a set of options, no action needed. I hope this will at least help someone else who hit the same obstacle:-)
Thanks for horatiu1921's help.
