### ISSUE TITLE
Realm Version 10.36 hangs when an Object class has no fields

### ISSUE THREAD

**Issue by YellowFlash3454** [realm/realm-swift#8141]
### How frequently does the bug occur?

Always

### Description

Upgraded from version 3.21 to 10.36 and whenever I tried creating a new Realm the program would hang. Changing the class type from Object to NSObject fixed this issue. 

### Stacktrace & log output

```shell
No stack traces, program hangs. There is no error being thrown so the issue is unclear.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Create a class of type Object with no defined properties. Try instantiating a new realm. 

`
// Open the local-only default realm                                                                        
let realm = try!  Realm()`

`// Note this class should only contain methods                                                                 
class TestClass: Object {...}`

### Version

10.36

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

MacOS Montery version 12.6

### Build environment

Xcode version: 14.2
Dependency manager and version:  cocaopods 11.3.1

**Comment by dianaafanador3** [comment]
Hi @YellowFlash3454 it is not allowed to have a class inherit from Object without a property. You're probably getting this error, are you sure you are not seeing it?
`Terminating app due to uncaught exception 'RLMException', reason: 'No properties are defined for 'TestClass'.`
Also, I don't see any reason to have this, any specific use case for this?.

**Comment by YellowFlash3454** [comment]
Yes, I am sure that there is no error being thrown. The program is running but does not do anything, it just hangs.

**Comment by dianaafanador3** [comment]
Hi @YellowFlash3454 can you please create a sample repo where I can check that this error is not showing. I'm testing v10.36.0 through Cocoapods and I'm seeing the exception. 
Even though this is not showing an error what you are trying to do is not allowed, so please change the Object to have at least one property.

**Comment by YellowFlash3454** [comment]
@dianaafanador3 my code is fixed, I have already resolved the issue. I left this issue to inform you of a hang in the program when upgrading and left all the info I do see. I will, unfortunately, not be creating a repo as I would have to change a lot of propriety code in order to do so, and I do not have the time.

**Comment by dianaafanador3** [comment]
I tested this in both Cocoapods and SPM and I can see the error. This is probably caused by something particular to your project, that's why it's very hard to reproduce on our side.

**Comment by YellowFlash3454** [comment]
I had the realm being created after setting configurations, this all happens prior to any logic from my project happens. The only time I saw an error is when my tests failed with a similar output to what you described. However, this did not happen at all during the app running. I couldn't even get to a place where I could interact with the new Realm objects I create, my app hangs during class initializations when trying to create a new Realm.

**Comment by YellowFlash3454** [comment]
Here's an example of what the project structure looks like: 
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/47014027/220703344-c3b7710e-83c1-4c5d-88ac-153d4579700d.png">

**Comment by YellowFlash3454** [comment]
Closing since I will NOT be reproducing this issue.
