### ISSUE TITLE
Realm Transactions - Errors Handling

### ISSUE THREAD

**Issue by mgrms** [realm/realm-swift#8145]
### Problem

Hello,

I've been using Realm for a long time and it works very well when used correctly. Thank you for such a wonderful product.

But to be honest, some things are not clear to me. For example the following case:

```
class TestRObj: Object {
    @Persisted(primaryKey: true) var id: String
    @Persisted var field1: Int
}

do {
     let realm = try Realm(configuration: realmConfiguration)
     try realm.write {
         let data = ["id": "someId", "field1": "sfads"]
         realm.create(TestRObj.self, value: data, update: .modified)
     }
} catch {
   //Never be executed
}
```

The code above will crash the app with `"Invalid value 'sfads' of type 'NSTaggedPointerString' for 'int' property 'TestRObj.field1'."	0x00006000014edd50"`, and the `catch {}` block will never be executed.

Wouldn't it be better in this situation to just cancel the transaction and throw the error to the catch block? As for me, this would be a more logical and expected result.

In practice, I encountered this problem when I started receiving not always valid data from the API, where a string instead of Integer began to come in one of the fields.

Perhaps I do not understand something, then I will be grateful if you can explain. But in my opinion, it would be possible to think about how to improve such cases.

Thank you

### Solution

Cancel a transaction and throw an error to a catch block

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by tgoyne** [comment]
Conceptually we consider it a precondition that the data you pass us be valid. Our general assumption is that either you're giving us data in a known format and if that format is invalid then it's just a bug in your code which should be fixed, or if you're receiving data from an external source you're validating that data before inserting it in the database. Since we don't support defining validation rules beyond "can the input be coerced to the expected type", trying to insert data and seeing if it fails isn't a very good way to validate it.

Historically the simple reason why we decided on this approach was that Swift didn't have a good way to report non-fatal errors. It still sort of doesn't; `realm.create()` could throw an error but property setters and subscript operators and such can't. It also avoids a lot of complex problems around what happens if you catch the error and try to continue with the write afterwards. If you pass a nested dictionary or complex object graph to `realm.create()` we currently don't try to validate up-front that the entire operation will succeed, but instead just start setting properties and throw an exception if any of them fail. If you catch the exception via obj-c things, this leaves your data in a very weird state.

**Comment by dianaafanador3** [comment]
Hi @mgrms, the `create(:value)` API is not designed to detect API errors and we consider that a value with a different type that the one defined in the schema is no-op and we throw and exception
You should verify the type passed to this API before using itI if you want to handle the error.
For example
```
guard let intValue = Int("sfads") else {
   // Throw/Handle error
}
```

**Comment by mgrms** [comment]
Hi @tgoyne , @dianaafanador3 

Thank you for your explanations.

@dianaafanador3 yeah, it is possible to do a check you suggested, but it become more complicated in case of models with a lot of fields.

Of course it is possible to decode from Json/Dictionary to custom Decodable `Object` model, and create/update it via: `realm.add(...)`, but it's not optimal for all cases.

As an example following model:

```
class Note: Object, Decodable {
  //Fields we receive from API
  @Persisted(primaryKey: true) var title: String
  @Persisted var text: String

  //This one we manage locally on device
  @Persisted var isViewed: Bool

  init(fromDecoder ...) {
     //decode and validate all the fields
  }
}
```

Fields `title` and `text` being received from API, `isViewed` is managed locally.

And image that we receive data from API with following format:
`[{  title: "a", text: "a" }, {  title: "b", text: "b" }]`

In case of using `realm.create(...)` with this data it will update **only** the fields we are passing to create (like a partial update), but in case of decoding to a new Note object and `realm.add(...)` all the fields including local ones will be overwritten.

So the solution can be to add :

```
class Note: Object, Decodable {
  //Fields we receive from API
  @Persisted(primaryKey: true) var title: String
  @Persisted var text: String

  //This one we manage locally on device
  @Persisted var isViewed: Bool

   init(fromDecoder ...) {
       //decode and validate all the fields
    }

  var fieldsToUpdate: [String: Any] { 
       return ["title": title, "text": text] 
  }
}

let obj = try JSONDecoder().decode(json, as: Note.self)
realm.create(Note.self, value: obj.fieldsToUpdate, update: .modified)
```

It will work, but will require additional decoding step to validate the json data.

But this seems to be the most optimal solution in this situation, and in the absence of exact confidence that the data will always be valid (for external data sources in 100% cases), decoding is indispensable.

**Comment by dianaafanador3** [comment]
Hi @mgrms 
When you mean "local fields", you mean properties data that you don't want to persist on realm?
On that case you don't mark that property with the `@Persisted` annotation, so it will not get persisted on the realm, even if it belongs to the object.
```
class Note: Object, Decodable {
  //Fields we receive from API
  @Persisted(primaryKey: true) var title: String
  @Persisted var text: String

  //This one we manage locally on device
  var isViewed: Bool

  init(fromDecoder ...) {
       //decode and validate all the fields
  }
}
```
If you mean you don't want to update the value of that property on each external API update, I don't think there is an issue if you persist the value of the local managed property each time.

**Comment by mgrms** [comment]
Hi @dianaafanador3 ,

As a "local field" I meant that we still need to store it in Realm, but we do not receive it from external API, but manage it locally.

Since we can not specify what fields exactly to update when using `realm.add(...)`, we need to use `realm.create(...)` to pass a dictionary of values we actually need to update (the ones we received from API in that case).

The other option will be to check every time if the object with same primary key is already in Realm, fetch it and update each field we need separately. Which does not sound like a good solution.

**Comment by dianaafanador3** [comment]
You can use 
`realm.add(object, update: .modified)` https://github.com/realm/realm-swift/blob/5d0f055bfaecc9eb133b75f0b5585dfabdb67e54/RealmSwift/Realm.swift#L534
which in case of a new object it will add it to the database and in cases of updates it will only update the properties that have changed 
https://github.com/realm/realm-swift/blob/5d0f055bfaecc9eb133b75f0b5585dfabdb67e54/RealmSwift/Realm.swift#L495
