### ISSUE TITLE
Multiple crashes observed while deleting the records

### ISSUE THREAD

**Issue by NAVEENRAJ3692** [realm/realm-swift#8147]
### How frequently does the bug occur?

Sometimes

### Description

For several versions we have been experiencing different crashes related to the Realm library and we have not been able to obtain any type of information or what could be failing. We are not able to reproduce it, it only happens to some users in production. this is a rare crash.

### Stacktrace & log output

```shell
Crashed: com.appname.Entity
 0 libsystem_kernel.dylib 0x7200 __pthread_kill + 8 
1 libsystem_pthread.dylib 0x71ac pthread_kill + 268 
2 libsystem_c.dylib 0x20c8c abort + 180 
3 appname 0xb4810c realm::util::terminate(char const*, char const*, long, std::initializer_listrealm::util::Printable&&) + 128 (terminate.cpp:128)
 4 appname 0xb4844c realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 123 (terminate.cpp:123) 
5 appname 0xb481c8 realm::util::terminate(char const*, char const*, long, std::initializer_listrealm::util::Printable&&) + 133 (terminate.cpp:133) 
6 appname 0x94f890 realm::StringIndex::do_delete(realm::ObjKey, realm::StringData, unsigned long) + 590 (alloc.hpp:590)
 7 appname 0x94f398 realm::StringIndex::do_delete(realm::ObjKey, realm::StringData, unsigned long) + 1658 (memory:1658)
 8 appname 0x94fa58 realm::StringIndex::erase(realm::ObjKey) + 1658 (memory:1658)
 9 appname 0xb0861c realm::Table::erase_from_search_indexes(realm::ObjKey) + 1496 (iterator:1496) 10 appname 0x91e9f0 realm::ClusterTree::erase(realm::ObjKey, realm::CascadeState&) + 956 (cluster_tree.cpp:956)
 11 appname 0xb0ecd8 realm::Table::batch_erase_rows(realm::BPlusTreerealm::ObjKey const&) + 1496 (iterator:1496) 
12 appname 0xb20960 realm::TableView::clear() + 499 (table_view.cpp:499) 
13 appname 0x9d03b8 realm::Results::clear() + 885 (results.cpp:885) 
14 appname 0x8c93a0 -[RLMResults deleteObjectsFromRealm] + 492 (RLMResults.mm:492) 
15 appname 0x8c0a1c -[RLMRealm deleteObjects:] + 881 (RLMRealm.mm:881) 
16 appname 0x4cbd9c Classname.deleteRecordsBefore<A>(entityClass:realm:earliestToKeepUTC:) + 23 (Classname.swift:23) 
17 appname 0x395360 closure #2 in DataBase.deleteOldRecords(completion:) + 307 (Database.swift:307) 
18 appname 0x39d5c4 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply + 4314502596 (<compiler-generated>:4314502596) 
19 appname 0xca5200 Realm.write<A>(withoutNotifying::) + 255 (Realm.swift:255) 
20 appname 0x397d7c closure #1 in Realm.safeWrite(:) + 349 (Database.swift:349)
 21 appname 0x39d588 partial apply for closure #1 in Realm.safeWrite(:) + 4314502536 (<compiler-generated>:4314502536) 
22 appname 0x39d5a4 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply + 4314502564 (<compiler-generated>:4314502564) 
23 libswiftObjectiveC.dylib 0x1308 autoreleasepool<A>(invoking:) + 64 
24 appname 0x39d530 partial apply for closure #1 in Realm.safeWrite(type::) + 345 (Database.swift:345) 
25 appname 0x39d568 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply + 4314502504 (<compiler-generated>:4314502504) 
26 libswiftDispatch.dylib 0x1900 partial apply for thunk for @callee_guaranteed () -> (@out A, @error @owned Error) + 28 
27 libswiftDispatch.dylib 0x8c88 thunk for @callee_guaranteed () -> (@out A, @error @owned Error)partial apply + 16 
28 libswiftDispatch.dylib 0x2c08 closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 188 
29 libswiftDispatch.dylib 0x2d1c partial apply for thunk for @callee_guaranteed () -> () + 28 
30 libswiftDispatch.dylib 0x26e8 thunk for @escaping @callee_guaranteed () -> () + 28 
31 libdispatch.dylib 0x3fdc _dispatch_client_callout + 20
 32 libdispatch.dylib 0x13574 dispatch_lane_barrier_sync_invoke_and_complete + 56 
33 libswiftDispatch.dylib 0x2040 implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 180 
34 libswiftDispatch.dylib 0x1060 partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 56 
35 libswiftDispatch.dylib 0x1d50 OS_dispatch_queue.syncHelper<A>(fn:execute:rescue:) + 396 
36 libswiftDispatch.dylib 0x110c OS_dispatch_queue.sync<A>(execute:) + 164
```

### Can you reproduce the bug?

No

### Version

10.25.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

All iPhone devices

### Build environment

Xcode version: 13.4
Dependency manager and version: SPM 5.3

**Comment by dianaafanador3** [comment]
Hi @NAVEENRAJ3692 thanks for reporting this. I think to be able to reproduce this we need more information. 
Can you please attach the code in `Classname.swift` where you make the call to `deleteObjects`, and the model declaration of the object you are trying to delete. This is very specific to deleting objects that have an index, so we could be lucky and maybe reproduce this.
One last question, are you using our Objective-C API from Swift?, Any reason for this? Or maybe I'm reading some incorrectly from the stack trace.

**Comment by NAVEENRAJ3692** [comment]
> Hi @NAVEENRAJ3692 thanks for reporting this. I think to be able to reproduce this we need more information. Can you please attach the code in `Classname.swift` where you make the call to `deleteObjects`, and the model declaration of the object you are trying to delete. This is very specific to deleting objects that have an index, so we could be lucky and maybe reproduce this. One last question, are you using our Objective-C API from Swift?, Any reason for this? Or maybe I'm reading some incorrectly from the stack trace.

Hi @dianaafanador3 
We are using the following method for deleting the objects.
`realm.delete(realm
            .objects(entityClass)
            .filter("_timestampUTC<%@", timeStampUTC))`

Please find the entity class with variables and types being used. While deleting the object of this entity the crash is being observed(Based on the crash report).

`
import Foundation
import RealmSwift

class Entity: Object {
    
    static let var1: Int32 = Int32.max
    static let var2: Int32 = 0
    
    @objc private dynamic var _id: Int32 = 0
    @objc private dynamic var _var3: Int64 = 0
    @objc private dynamic var _var4: String = ""`

The Entity is extended with the following type

`public typealias Object = RealmSwiftObject`

> Hi @NAVEENRAJ3692 thanks for reporting this. I think to be able to reproduce this we need more information. Can you please attach the code in `Classname.swift` where you make the call to `deleteObjects`, and the model declaration of the object you are trying to delete. This is very specific to deleting objects that have an index, so we could be lucky and maybe reproduce this. One last question, are you using our Objective-C API from Swift?, Any reason for this? Or maybe I'm reading some incorrectly from the stack trace.

**Comment by dianaafanador3** [comment]
@NAVEENRAJ3692 did you update yo our latest version?, any updates on this issue
