### ISSUE TITLE
Realm deletes objects in a wrong way

### ISSUE THREAD

**Issue by zhaojiewen** [realm/realm-swift#8149]
### How frequently does the bug occur?

Always

### Description

When I use Realm to add a set of data, this data is regularly identified, he added it correctly, but when I query a part of this set of data and print this set of data, everything is displayed according to my specific representation, Then when I want to delete this set of data, the database deletes other data, and it is deleted regularly. This rule is to skip one data and then delete it.

### Can you reproduce the bug?

Always

### Reproduction Steps

1.  Delete All Data and  Insert 999 Index Data: 0,1,2,3,4...999
2. Delete First 100 index Data: 0,1,2,3,4...99
3. read first 200 index respected data: 100,101,102...999
4. but first 200 index data is: 1,3,5,7,9...191,193,195,197,199

### Version

10.35.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Simulator

### Build environment

Xcode version: 14.2 (14C18)
Dependency manager and version: .

**Comment by zhaojiewen** [comment]
public func deleteFirst(_ k: Int = 1) -> Bool {
        let block: () -> Bool = {
            guard let realm = self.realm else {
                return false
            }
            let records = realm.objects(FabricEventRecord.self)
            guard 1..<(records.count + 1) ~= k else { return  false }
            let deleteRecords = records[0..<k]
            
            do {
                try realm.write {
                    realm.delete(deleteRecords)
                }
            } catch {
                fabricInternalLogError("【Fabric Analytics】checkAfterInsert Error: \(error)")
                return false
            }
            return true
        }
        
        return fabricBlockQueue(queue: self.serialQueue, block: block)
    }

public func fabricIsSameQueue(queue: DispatchQueue) -> Bool {
    queue.label == String(cString: __dispatch_queue_get_label(nil))
}

public func fabricBlockQueue<T>(queue: DispatchQueue, block: () -> T) -> T {
    if fabricIsSameQueue(queue: queue) {
        return block()
    } else {
        var value: T!
        queue.sync {
            value = block()
        }
        return value
    }
}

**Comment by zhaojiewen** [comment]
public func deleteFirst(_ k: Int = 1) -> Bool {
        let block: () -> Bool = {
            guard let realm = self.realm else {
                return false
            }
            let records = realm.objects(FabricEventRecord.self)
            guard 1..<(records.count + 1) ~= k else { return  false }
            let deleteRecords = records[0..<k]
            
            for deleteRecord in deleteRecords {
                do {
                    try realm.write {
                        realm.delete(deleteRecord)
                    }
                } catch {
                    fabricInternalLogError("【Fabric Analytics】checkAfterInsert Error: \(error)")
                    return false
                }
            }

            return true
        }
        
        return fabricBlockQueue(queue: self.serialQueue, block: block)
    }

public func fabricIsSameQueue(queue: DispatchQueue) -> Bool {
    queue.label == String(cString: __dispatch_queue_get_label(nil))
}

public func fabricBlockQueue<T>(queue: DispatchQueue, block: () -> T) -> T {
    if fabricIsSameQueue(queue: queue) {
        return block()
    } else {
        var value: T!
        queue.sync {
            value = block()
        }
        return value
    }
}

**Comment by zhaojiewen** [comment]
``` 
public func deleteFirst(_ k: Int = 1) -> Bool {
        let block: () -> Bool = {
            guard let realm = self.realm else {
                return false
            }
            let records = realm.objects(FabricEventRecord.self)
            guard 1..<(records.count + 1) ~= k else { return  false }
            let deleteRecords = records[0..<k]
            
            do {
                try realm.write {
                    realm.delete(deleteRecords)
                }
            } catch {
                fabricInternalLogError("【Fabric Analytics】checkAfterInsert Error: \(error)")
                return false
            }
            return true
        }
        
        return fabricBlockQueue(queue: self.serialQueue, block: block)
    }

public func fabricIsSameQueue(queue: DispatchQueue) -> Bool {
    queue.label == String(cString: __dispatch_queue_get_label(nil))
}

public func fabricBlockQueue<T>(queue: DispatchQueue, block: () -> T) -> T {
    if fabricIsSameQueue(queue: queue) {
        return block()
    } else {
        var value: T!
        queue.sync {
            value = block()
        }
        return value
    }
}
```

**Comment by dianaafanador3** [comment]
@zhaojiewen `Results` doesn't guarantee to return the objects in the order they were created or added to the database, and when you do this  `let deleteRecords = records[0..<k]` we create a [Subsequence](https://developer.apple.com/documentation/swift/array/subsequence) from the Results collection which may not always be the same order.
I'll recommend for your case to use a query, which is more efficient, to get the objects to delete
Something like this
`let deleteRecords = realm.objects(FabricEventRecord.self).where { $0.index.contains(1...200) }`
where index is the property that stores the index.
For a ordered list you may also want to check List<Type>
