### ISSUE TITLE
Unable to access readonly local Realm

### ISSUE THREAD

**Issue by Jerry-Carter** [realm/realm-swift#8151]
### How frequently does the bug occur?

Always

### Description

**MacOS**
- Create Realm database on MacOS using version 10.36.0.
- Write out a compacted version of the database
`realm.writeCopy(toFile:myURL, encryptionKey: myKey)`
- Read from the compacted version as a sanity check.
`try await Realm(configuration: .init(fileURL:myURL, encryptionKey: myKey, readOnly: true), downloadBeforeOpen: .never)`

**Xcode iOS Project**
- Add the compacted database to the project and ensure that it is copied during 'Copy Bundle Resources'

**iOS Application**
- On the view, pass in the realm configuration
`MyView().environment(\.realmConfiguration, Realm.Configuration(fileURL:Bundle.main.url(forResource:"MyRealm", withExtension:"realm"), encryptionKey: myKey, readOnly: true))`
- Inside the view, attempt to access the realm using library version 10.36.0
`@ObservedResult(MyClass.self) var myData`

This generates an exception, "Unable to open a realm at path '/private/var/containers/Bundle/Application/&lt;
UUID>/&lt;APPNAME>/MyRealm.realm.lock': open() failed".  This is not surprising as the Bundle directory is read only.  However, it does contradict the [online documentation](https://www.mongodb.com/docs/realm/sdk/swift/realm-files/bundle-a-realm/) which claims "You can open the realm at the bundle path directly if the readOnly property is set to true on the Realm.Configuration."

### What is the desired resolution?

Realm should create the lock file in a different and writeable location.

Why?  The bundled Realm file may grow to be rather large.  The application can copy the data using `seedFilePath` but this nearly doubles the application footprint on the device for large Realms.

### Can you reproduce the bug?

Always

### Version

10.36.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 16.2

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by dianaafanador3** [comment]
Hi @Jerry-Carter following your reproduction steps I'm not able to reproduce this. Can you please create a sample repo where this is reproducible.

**Comment by leemaguire** [comment]
@Jerry-Carter can you send us a sample app the reproduces the issue?
