### ISSUE TITLE
Feedback on weak encryption: "SHA1" and insecure creation mode: "malloc"

### ISSUE THREAD

**Issue by fridayyue** [realm/realm-swift#8160]
### Problem

Dear developers：
  I am honored to use the software you developed. Recently, our company strengthened the security aspect of our APP. While scanning the Realm library, we found two issues. One was about weak HASH algorithms (weak HASH algorithms include SHA1 and MD5. When a program uses a weak HASH algorithm, the HASH algorithm may be attacked by hackers and the HASH verification method may become invalid. If the HASH verification method fails, private data on the client may be leaked, files may be tampered, and transmitted data may be obtained. As a result, sensitive user information may be stolen. The other uses the malloc method. (The underlying iOS system is Unix. Due to the signal processing mechanism of Unix, there is no way to tell where the process is executing when the signal is captured. If the process is executing malloc, additional storage is allocated in its heap, and malloc is called in the signal handler inserted to execute the signal because it caught the signal. If this happens, one of two things will happen:
1. The process deadlocks in the signal handler because malloc will not be able to acquire the heap lock.
2. Some global information of malloc internal maintenance is damaged, causing the application to crash inexplicably. . 

Can I change the HASH algorithm to HASH256 or HASH128? My company will not let me use Realm library unless I can improve it, which will be a huge workload for me (sad).Thank you very much!
<img width="697" alt="Xnip2023-03-08_17-57-29" src="https://user-images.githubusercontent.com/12948542/223682298-919001bd-20df-4314-91ee-e00bf36695dd.png">

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by tgoyne** [comment]
The only place where we use sha-1 is to validate the [Sec-WebSocket-Accept](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-WebSocket-Accept) header in websocket connections, where it is a mandated part of the protocol and not something under our control. We use SHA-2 everywhere else.
