### ISSUE TITLE
Making non-breaking changes to Device Sync sometimes triggers clientUserError

### ISSUE THREAD

**Issue by Kalzem** [realm/realm-swift#8162]
### How frequently does the bug occur?

Sometimes

### Description

A few days ago, we added a new object (model) which, according to the [documentation](https://www.mongodb.com/docs/atlas/app-services/sync/data-model/update-schema/#breaking-vs.-non-breaking-change-quick-reference), is a non-breaking change.

However, we have noticed a few users (~10% so far) triggering the sync manager's error handler with a `clientUserError`.
This can become an annoying behavior as we follow up with a logout and users have to re-login.

We also believe there is another related bug where the clientUserError isn't triggered instantaneously. I'll explain the flow :

1. User opens the app
2. App does a `Realm.asyncOpen(configuration: config)` (with config = partition-based and using recoverOrDiscardUnsyncedChanges) so that we are sure to be 100% sync every time. User is stuck on a loading screen meanwhile.
3. Upon success, user can finally continue with the app, and we set up one Realm listener on a specific object.
4. Client User Error is now triggered <- _Why only now and not at step 2?_

Unfortunately, we can't reproduce the bug on our side (+ it is too complex to set up the same conditions as our users who are crashing).

By the way, is there a way to manually trigger a clientUserError? How does the Realm team simulate this error in their unit test?

### Can you reproduce the bug?

No

### Version

10.33.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 15.x and 16.x

### Build environment

Xcode version: 14.2
Dependency manager and version: SPM

**Comment by dianaafanador3** [comment]
Hi @Kalzem do you happen to have a stack trace of the error, having the exact error code will help us diagnose the issue.
This surely shouldn't be happening on any way, after a client reset the realm should be in a usable condition and the data should be recover or discarded (depending if it is meant to recover data or the state of the data.
Also, do you happen to have recovery mode enable in the Device Sync Platform.
Regarding the sync client reset tests, what we actually do is create a server history inconsistency between the synced data and the local realm, we do this by suspending the sync session on the local realm and adding data offline, next time the realm is opened the client reset will trigger.

**Comment by Kalzem** [comment]
Hi @dianaafanador3 
I can show you the stack track but I don't think it will be very helpful because the crash isn't from Realm SDK per se but from my side.

After a **successful** Realm.asyncOpen, I set up a listener on a Realm object in DB, then I get a crash as Realm has already triggered a clientReset before I could even set up the listener. It feels like there is a race condition somewhere or Realm.asyncOpen returns a false positive.

I have added 0.5 sec of delay after the initial Realm.asyncOpen hoping that if a clientReset has to happen, it will be enough and my app won't proceed with setting up the listener. So far, this hack seems to have fixed the issue.

> Also, do you happen to have recovery mode enable in the Device Sync Platform?

Yes I have "Enable Client Recovery".

And thanks for the client reset test tip, I'll try it out.

```
Fatal Exception: RLMException
Only objects which are managed by a Realm support change notifications

0  CoreFoundation                 0x9e88 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  Pyra                           0x4980c0 RLMObjectBaseAddNotificationBlock + 727 (RLMObjectBase.mm:727)
3  Pyra                           0x595614 RLMObjectBase._observe<A>(keyPaths:on:_:) + 144 (Aliases.swift:144)
4  Pyra                           0x3d5460 one-time initialization function for shared + 43 (EnergyManager.swift:43)
5  libdispatch.dylib              0x3fdc _dispatch_client_callout
6  libdispatch.dylib              0x5828 _dispatch_once_callout
7  Pyra                           0x171a18 AppCoordinator.logout() + 33 (EnergyManager.swift:33)
8  Pyra                           0x34d8c closure #3 in closure #1 in RealmManager.setupClientReset() + 142 (RealmManager.swift:142)
9  Pyra                           0x34b0c RealmManager.logout(completion:) + 312 (RealmManager.swift:312)
10 Pyra                           0x33f3c closure #1 in RealmManager.setupClientReset() (<compiler-generated>)
11 Pyra                           0x34e70 thunk for @escaping @callee_guaranteed (@guaranteed Error, @guaranteed RLMSyncSession?) -> () (<compiler-generated>)
12 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release
13 libdispatch.dylib              0x3fdc _dispatch_client_callout
14 libdispatch.dylib              0x127f4 _dispatch_main_queue_drain
15 libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF
16 CoreFoundation                 0x9a6f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
17 CoreFoundation                 0x7c058 __CFRunLoopRun
18 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific
19 GraphicsServices               0x1368 GSEventRunModal
20 UIKitCore                      0x3a23d0 -[UIApplication _run]
21 UIKitCore                      0x3a2034 UIApplicationMain
22 libswiftUIKit.dylib            0x35308 UIApplicationMain(_:_:_:_:)
23 Pyra                           0x774c main (PurchaseManager+PurchaserInfo.swift)
24 ???                            0x1b57d8960 (Manquant)
```

**Comment by leemaguire** [comment]
@Kalzem does this crash only happen on the logout? I wonder if this is related to the user being logged out an the observed object being related to a specific user if so?

**Comment by dianaafanador3** [comment]
@Kalzem The crash above shows that the object doesn't is not managed by the realm at the moment of adding the observer. Are you sure this object is added to the realm?, the weird thing is that after setting the delay the exception doesn't throw. Can you please attach the code where you do the log out and add the observation to the object.

**Comment by ericjordanmossman** [comment]
@Kalzem Are you able to provide what Diana asked?

**Comment by Kalzem** [comment]
Sorry for the delay.

I tried to reproduce the problem in order to have better logs to share. Unfortunately, I am no longer part of the project which had this bug :/

What I can assure is that by adding a delay (0.5+ second) after the Realm.asyncOpen and before plugging any listener, the bug was never triggered.

Another point is that I *believe* (not confirmed) that some of those client errors, which happen after logging in, are about SSH broken pipe. Not sure if it's important or not.

> does this crash only happen on the logout?

Yes, only on the logout. And as leemaguire says, it might have to do with "the user being logged out an the observed object".

FYI, I had this code:

```swift
// Realm Manager logic, just after app init.
private func setupClientReset() {
    self.app.syncManager.errorHandler = { [weak self] error, session in
        guard let self = self, let syncError = error as? SyncError else { return }
        switch syncError.code {
        case .clientResetError:
            guard let (_, clientResetToken) = syncError.clientResetInfo() else { return }
            // Notify all observers to invalidate their NotificationToken
            NotificationCenter.default.post(name: .gameClientWillReset, object: nil)
            // Invalidate Realm
            self.userSyncRealm?.invalidate()
            // Send user back to login screen...
        }
    }
}
```

Now about the flow of the listener:

1. When you start the app, there is a login screen with Apple Sign In that calls Realm.asyncOpen.
2. On success, it opens a new screen which has a top bar with the quantity of "energy". It's a mobile game with an energy bar.
3. The code for the energy listener is the following:

```swift
// Energy Bar View, init after successful Realm login, never before
self.energyNotificationToken = EnergyManager.shared.energyContent().observe(keyPaths: ["energy"]) { [weak self] change in
    guard let self = self else { return }
    switch change {
    case .change(_, let properties):
        properties.forEach({
            if $0.name == "energy" {
                self.updateUI()
            }
        })
    case .deleted: break
    case .error(let error): Log.warning(error)
    }
}

NotificationCenter.default.addObserver(forName: .gameClientWillReset, object: nil, queue: nil) { [weak self] _ in
    self.energyNotificationToken?.invalidate()
    self.energyNotificationToken = nil
}
```

And finally, the energyContent() function

```swift
// Energy Manager
func energyContent() -> EnergyContent {
    if let content = self.realm()?.objects(EnergyContent.self).first {
        return content
    }
    let newContent = EnergyContent()
    newContent.wonEnergy = Constant.firstTimeEnergy
    self.saveRealm(newContent) // It's just a do try realm.write { realm.add(newContent, update: .all) }
    return newContent
}
```

**Comment by dianaafanador3** [comment]
Hi @Kalzem thanks for getting back to use and give us some more context about this issue. I have my doubts this error you are getting are associated to a client reset (which should not be happening in this case, because is a non-breaking change), but to an SSL issue.
We have fixed several issues associated to SSL in the past several release which should decrease the number of errors you are getting. It would be pretty nice to check this with someone that's working currently on the project.
