### ISSUE TITLE
vuf

### ISSUE THREAD

**Issue by matejzvikl712** [realm/realm-swift#8170]
### How frequently does the bug occur?

Sometimes

### Description

ugg

### Stacktrace & log output

```shell
urud
```

### Can you reproduce the bug?

Sometimes

### Reproduction Steps

mcckf

### Version

fkj

### What Atlas Services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

Yes

### Platform OS and version(s)

mmvk

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by dianaafanador3** [comment]
@matejzvikl712 closing this as there is no enough information of the issue.
