### ISSUE TITLE
Could not find module 'RealmSwift' for target 'arm64-apple-ios-simulator'

### ISSUE THREAD

**Issue by ankitpoplify** [realm/realm-swift#8174]
### How frequently does the bug occur?

Always

### Description

Hello, I am using Xcode 14.2 in my m1 macbook air. Everything was working fine but suddenly I starts getting this error
`Could not find module 'RealmSwift' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/poplify/Library/Developer/Xcode/DerivedData/HowNow3.1-bfpxedwvqjetxzgaohwamxopkaiy/Build/Products/Debug-iphonesimulator/RealmSwift/RealmSwift.framework/Modules/RealmSwift.swiftmodule`
when I try to run my project on simulator. I'm using 'RealmSwift', '~> 5.5.0' pod. I tried all the solution but nothing is working for me. 

### Can you reproduce the bug?

Always

### Reproduction Steps

To reproduce build the app on simulator.

### Version

5.5.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16

### Build environment

Xcode version: 14.2
Dependency manager and version: ...

**Comment by leemaguire** [comment]
@ankitpoplify you'll either need to use SPM or update to the latest version of Realm.

**Comment by muhammadsulaiman789** [comment]
Swift Compiler Error (Xcode): Could not find module 'PusherSwiftWithEncryption' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: /Users/bwa-it/StudioProjects/hallaw-client/build/ios/Debug-iphonesimulator/PusherSwiftWithEncryption/PusherSwiftWithEncryption.framework/Modules/PusherSwiftWithEncryption.swiftmodule
/Users/bwa-it/.pub-cache/hosted/pub.dev/pusher_client-2.0.0/ios/Classes/AuthRequestBuilder.swift:7:7

can you help me to fix it ?

**Comment by LawrenceBi** [comment]
same issue here : (
