### ISSUE TITLE
Compilation error on RealmSwift 10.37.0

### ISSUE THREAD

**Issue by vishal-frosting** [realm/realm-swift#8176]
### How frequently does the bug occur?

Always

### Description

I recently updated RealmSwift, I have the following in my Podfile.lock:
`  - Realm (10.37.0):
    - Realm/Headers (= 10.37.0)
  - Realm/Headers (10.37.0)
  - RealmSwift (10.37.0):
    - Realm (= 10.37.0)
...
  - Unrealm (1.9.4):
    - Realm
    - RealmSwift
    - Runtime
`
**Now I get compilation error:** 
`Declaration of 'RealmSwiftObject' must be imported from module 'Realm.Swift' before it is required`

File: Object_Unrealm.m
Line: 13
Code: `@implementation RealmSwiftObject (Unrealm)`

### Can you reproduce the bug?

Always

### Version

10.37.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Macbook Air M1, MacOS Ventura 13.0.1

### Build environment

Xcode version: 14.2 (14C18)
Dependency manager and version: pod --version: 1.11.2

**Comment by tgoyne** [comment]
`RealmSwiftObject` is an implementation detail and not part of the public API. As the error says, you can import the module which it is now defined by.

**Comment by vishal-frosting** [comment]
Correct, this is part of the 'Unrealm' Pod. Not relevant here, thanks for your response.
