### ISSUE TITLE
Iterating through a List in an @ObservedRealmObject always returns new objects

### ISSUE THREAD

**Issue by aarku** [realm/realm-swift#8179]
### How frequently does the bug occur?

Always

### Description

If you take the [Realm SwiftUI quickstart code](https://www.mongodb.com/docs/realm/sdk/swift/swiftui-tutorial/#complete-code) and set a breakpoint inside the ```ForEach``` that renders each ItemRow view, you will see that the memory address changes each time, even though the data did not change at all.

You can trigger rerendering just by adding some counter state. Here is the modified code.

```swift
struct ItemsView: View {
    @ObservedRealmObject var itemGroup: ItemGroup
    @State var counter = 0
    /// The button to be displayed on the top left.
    var leadingBarButton: AnyView?

    var body: some View {
        let _ = Self._printChanges()
        let user = app?.currentUser
        NavigationView {
            VStack {
                // The list shows the items in the realm.
                List {
                    ForEach(itemGroup.items) { item in
                        if item.name == "keen lace" {
                            let _ = print(item.name)
                        // call 1: item    Realm_SwiftUI_Quickstart.Item    0x0000000280f7f200
                        // call 2: item    Realm_SwiftUI_Quickstart.Item    0x0000000280f7eb00
                        }
                        ItemRow(item: item)
                    }.onDelete(perform: $itemGroup.items.remove)
                        .onMove(perform: $itemGroup.items.move)
                }
                .listStyle(GroupedListStyle())
                .navigationBarTitle("Items", displayMode: .large)
                .navigationBarBackButtonHidden(true)
                .navigationBarItems(
                    leading: self.leadingBarButton,
                    // Edit button on the right to enable rearranging items
                    trailing: EditButton()
                )
                // Action bar at bottom contains Add button.
                HStack {
                    Spacer()
                    Button(action: {
                        // The bound collection automatically
                        // handles write transactions, so we can
                        // append directly to it.
                        // Because we are using Flexible Sync, we must set
                        // the item's ownerId to the current user.id when we create it.
                        $itemGroup.items.append(Item(value: ["ownerId": user?.id ?? "local"]))
                    }) { Image(systemName: "plus") }
                }.padding()
            }
        }
        .safeAreaInset(edge: .bottom) {
            Button("Rerender ItemsView (\(counter))") {
                counter += 1
            }
        }
    }
}
```

This behavior breaks SwiftUI's normal checks to decide whether or not to invoke the view body of ```ItemRow```, and causes it to always run. This quickly destroys the performance of your app.

You can work around it by making ItemRow an ```EquatableView``` and adding your own equals function manually. (In case anyone reading this isn't familiar, with that process, it's [described here](https://swiftwithmajid.com/2020/01/22/optimizing-views-in-swiftui-using-equatableview/) well.

I think this "copying" behavior happens because the ```@ObservedRealmObject``` property wrapper is implicitly calling ```itemGroup.items.freeze()``` behind the scenes, and that always makes a new copy.

Perhaps to fix this Realm should maintain a cache of frozen objects and only return a newly copied one when the object actually changes?

Thanks,
-Jon

### Can you reproduce the bug?

Always

### Version

10.37.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 16.3.1

### Build environment

Xcode version: Version 14.2 (14C18)
Dependency manager and version: built in Swift package manager

**Comment by tgoyne** [comment]
Reading from a managed `List` always allocates a new object regardless of whether or not it's frozen. To work with `ForEach`'s diffing objects must conform to `Identifiable`, which in the case of the quick start example is done by conforming to `ObjectKeyIdentifiable`, which defines an id using Realm's internal object key.

**Comment by tgoyne** [comment]
Identifiable exists specifically for that purpose. SwiftUI falls back to the memory address as an identity for objects which don't conform to Identifiable, but doesn't otherwise use it.

Replacing `@ObservedRealmObject var itemGroup: ItemGroup` with `@State var items = [Item]()` and adjusting everything to use the array instead of the `ItemGroup` results in the exact same behavior of `ForEach()` invoking the body for each ItemRow whenever the counter is incremented even though it is reusing the same objects.

**Comment by aarku** [comment]
Good idea to test that. I guess that's not it.

I did some more testing. If ```Item``` is a similar simple struct, it correctly skips rerendering. If it's a simple (non-Realm) class, it does rerender until you implement the ```Equatable```, but Realm has that of course does.

Next I thought maybe the Equatable implementation might not be working, but I tested that on objects across different ```ForEach```s, and it seems to work fine.

I have no idea why SwiftUI always rerenders views that take Realm Objects,

**Comment by aarku** [comment]
By making a bunch of views conform to Equatable, by making use of the fact that Realm objects are equatable, makes it pretty easy to fix in the end. I tried more complicated fixes like converting to structs, but this is the only thing that really worked consistently.

**Comment by aarku** [comment]
Sorry, I wrote too soon, bad habit. It prevented needed rerenders too. I didn't test nearly enough obviously. It seems like equality is always true at the point the view equality function gets called. I tested that by printing out the objects in the view's static equality function, and also inspecting them in the debugger. Both sides of the equality seem to always have the new data.

Maybe this rerendering behavior has something to do with the fact that a Realm Object is an ObservableObject that keeps getting recreated.

Next I'm thinking of trying to make all the data CustomPersistable structs some how and not use any of the SwiftUI integration, and manage a repository/subscriptions manually. The docs say a CustomPersistable must be an EmbeddedObject, but it seems to work as a regular Object too in a modified SwiftUI quickstart. Bad idea? I just don't know what to do.

I'm not exactly sure how realm-managed lists are going to work with this idea, either, but I'm going to experiment. Thanks for reading.

**Comment by dejiapps** [comment]
@aarku What ended up being the solution you came up with? I am having similar performance issues.

**Comment by aarku** [comment]
@dejiapps It wasn't simple, and wouldn't be great for every app. I'm all ears for a better solution. What I did:

1. Don't use any of the Realm SwiftUI stuff. It'd be cool if it worked, but I think the Realm team needs to "dog food" it to see how unstable it is.
2. Never pass a Realm Object to a SwiftUI View. Convert the data to value types.
3. Do not subscribe to Realm Objects at performance sensitive times, like scrolling. Cache the data you need separately. There seems to be a significant fixed cost to subscribing to anything. It's almost like it's starting a new thread for each subscription, but I'm not sure.
4. Make sure you're only rendering a View as much as you need to. Use `Self._printChanges()` and some visual counters overlaid on your views.
5. Pre-iOS 17 and family, use EnvironmentObjects very carefully. Any published change triggers every view body referencing it to be ran again, which can cause a ton of unneeded renders. I switched to using the wonderful [Factory](https://github.com/hmlongco/Factory) library, but am not sure what I'm going to do as iOS 17 and family fixes the problem.

**Comment by dejiapps** [comment]
> @dejiapps It wasn't simple, and wouldn't be great for every app. I'm all ears for a better solution. What I did:
> 
>     1. Don't use any of the Realm SwiftUI stuff. It'd be cool if it worked, but I think the Realm team needs to "dog food" it to see how unstable it is.
> 
>     2. Never pass a Realm Object to a SwiftUI View. Convert the data to value types.
> 
>     3. Do not subscribe to Realm Objects at performance sensitive times, like scrolling. Cache the data you need separately. There seems to be a significant fixed cost to subscribing to anything. It's almost like it's starting a new thread for each subscription, but I'm not sure.
> 
>     4. Make sure you're only rendering a View as much as you need to. Use `Self._printChanges()` and some visual counters overlaid on your views.
> 
>     5. Pre-iOS 17 and family, use EnvironmentObjects very carefully. Any published change triggers every view body referencing it to be ran again, which can cause a ton of unneeded renders. I switched to using the wonderful [Factory](https://github.com/hmlongco/Factory) library, but am not sure what I'm going to do as iOS 17 and family fixes the problem.

Thanks for the quick and detailed reply. I'm going to give them a try.

**Comment by aehlke** [comment]
Thanks for the detailed explanations. I realized this is why non-persisted Published properties on a realm object used via ObservedRealmObject don't work.
