### ISSUE TITLE
Compiler error 'Expected unqualified-id'

### ISSUE THREAD

**Issue by cellgit** [realm/realm-swift#8184]
### How frequently does the bug occur?

Always

### Description

<img width="1356" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/24635226/227417732-dedc1269-1f75-4d0d-beec-24d8673637e0.png">

MacOS: 12.6.3
Xcode: Version 13.1 (13A1030d)
Swift:5.5

### Can you reproduce the bug?

Always

### Reproduction Steps

1.pod install
2.Compile

### Version

10.37.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

MacOS: 12.6.3

### Build environment

Xcode version: 13.1 (13A1030d)
Dependency manager and version: CocoaPods 1.11.2

**Comment by tgoyne** [comment]
10.33.0 was the final version which supports Xcode 13.1. Xcode 13.3 is now the minimum supported version.

**Comment by cellgit** [comment]
The same project, The Intel compile with error, the M1 max is success

**Comment by cellgit** [comment]
@tgoyne Xcode 13.1, RealmSwift 10.33.0 build succeeded, Thanks
