### ISSUE TITLE
Migrating from 10.33.0 to 10.34.0 can no longer cast to `MigrationObject`.

### ISSUE THREAD

**Issue by dlbuckley** [realm/realm-swift#8190]
### How frequently does the bug occur?

Always

### Description

# Overview

We are looking to migrate from version 10.33.0 to the latest version (10.37.1 at the time of writing) but our tests flagged up an issue affecting migration. It appears we can no longer cast to `MigrationObject/DynamicObject` which worked previously. Here is the migration code with added `print` statements to illustrate what is going wrong:

``` swift
m.enumerateObjects(ofType: Subscription.className()) { (old, new) in

    guard let old, let new else { return }

    if let oldAccount = old["account"] as? DynamicObject {
        print("Old account: \(oldAccount)")
        if let accountId = oldAccount["id"] as? String {
            print("Account ID: \(accountId)")
            new["accountID"] = accountId // 10.33.0 successfully migrates the value
        } else {
            print("Failed to get account ID")
        }
    } else {
         print("Failed to get old account") // 10.34.0+ fails at this point instead of casting correctly
    }
}
```
In 10.33.0 we are able to cast `old["account"]` to a `DynamicObject` or `MigrationObject` and access it's subscript properties without issue. But as of 10.34.0 (I've tested all versions up to the latest and 10.34.0 was where the issue was introduced) the cast fails. I can't see anything within the release notes which would indicate a change in this behaviour.

# Details

What seems to have worked (on 10.34.0+) is casting to `RLMDynamicObject` in the console. At this point I can then access the subscript properties with no issue. Unfortunately this is only possible in the console due to `RLMDynamicObject` being private. 

<img width="353" alt="Screenshot 2023-03-28 at 17 36 05" src="https://user-images.githubusercontent.com/349373/228308437-9592bd2e-bec0-491f-9b97-3ac0eec6bb44.png">
<img width="417" alt="Screenshot 2023-03-28 at 17 36 57" src="https://user-images.githubusercontent.com/349373/228308640-6d8ad543-7a1a-4532-a88b-6d6eadafca5e.png">

But if I try to cast to either `DynamicObject` or `MigrationObject` I get `nil`.

<img width="352" alt="Screenshot 2023-03-28 at 17 38 27" src="https://user-images.githubusercontent.com/349373/228308997-91044df1-a49f-4eea-b91f-f6ae22465059.png">

The `Subscription` object is quite large, but you can see that `account` is clearly associated to it in this small snippet.

<img width="342" alt="Screenshot 2023-03-28 at 17 42 38" src="https://user-images.githubusercontent.com/349373/228310009-6681f8a4-f968-40c2-8c79-56df5283585e.png">

### Can you reproduce the bug?

Always

### Reproduction Steps

The actual code this relates to is sensitive so I've shared what I can publicly for now.

### Version

10.34.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

All

### Build environment

Xcode version: 14.2
Dependency manager and version: SPM

**Comment by tgoyne** [comment]
How are you initializing your Realm instance that's performing the migration? The type of the objects passed to the migration callbacks is an internal configuration parameter set to `MigrationObject` when we convert a `Realm.Configuration` to the underlying `RLMRealmConfiguration` and to `RLMMigrationObject` when a `RLMRealmConfiguration` is created directly. It's possible that maybe one of our initialization paths is failing to propagate that value to the correct place?

**Comment by dlbuckley** [comment]
```swift
let config = Realm.Configuration(
    fileURL: containerURL,
    schemaVersion: schemaVersion,
    migrationBlock: realmMigration
)
Realm.Configuration.defaultConfiguration = config
```
I should note that the above migration is one of many migration steps over a number of different versions. They all pass their tests except for this one. (`realmMigration` is a closure thats declared elsewhere and passed in)

**Comment by tgoyne** [comment]
And then you're just doing `try Realm()` to trigger the migration?

**Comment by tgoyne** [comment]
Oh, I think I see what the problem is. `-[RLMRealmConfiguration copy]` isn't copying the `migrationObjectClass` property and opening via the default configuration involves a copy.

**Comment by dlbuckley** [comment]
Thanks for looking in to this for us, it sounds like there is a possible avenue to explore here? If you need us to test anything our side then please let us know and we would be happy to accommodate. 

Just to note we are on GMT+1 so likely wont be able to look at any suggestions until tomorrow.

**Comment by dlbuckley** [comment]
@tgoyne I just pointed to the branch with the fix and it seems to have resolved our issue with the test which was failing 🎉 I'm just pushing it though our CI to make sure nothing else is broken and then will report back.

**Comment by dlbuckley** [comment]
It looks like the branch fixes the issues we were seeing and hasn't introduced anything which were caught by our tests. Is it possible this can make it into a patch release or will we have to wait for the next minor release?
