### ISSUE TITLE
Archiving with Xcode 14.2 takes forever

### ISSUE THREAD

**Issue by faizaan123** [realm/realm-swift#8200]
### How frequently does the bug occur?

Always

### Description

Archiving is just stuck on a particular step for hours and hours at the below given step.
<img width="519" alt="Screenshot 2023-04-04 at 9 29 02 PM" src="https://user-images.githubusercontent.com/37843872/229885172-b727211f-9e03-41a8-9565-4f177a28a40e.png">

I have installed realm swift through the swift package manager. Attaching file for reference
<img width="243" alt="Screenshot 2023-04-04 at 9 33 46 PM" src="https://user-images.githubusercontent.com/37843872/229886507-27d50a6d-7e2f-4fff-b3f2-5091682a013f.png">

<img width="734" alt="Screenshot 2023-04-04 at 9 35 46 PM" src="https://user-images.githubusercontent.com/37843872/229886908-ce935a9f-8d93-4aee-9cd8-d6700863000e.png">

### Stacktrace & log output

```shell
No response
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Start Xcode
Wait for dependency resolving and indexing
Select Any iOS Device (arm64) (optional if already selected)
Try to Archive the app

### Version

1.Realm Database: 13.8.0    2. Realm : 10.37.2

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

Build Target (ios 12 and above)

### Build environment

Xcode version: 14.2 (updated from app store)
Dependency manager and version: 
1. Realm Database : 13.8.0
2. Realm : 10.37.2

Other Info:
Xcode 14.2 (Updated from app store)
Realm 10.37.2(master)
RealmDatabase 13.8.0
Swift Package Manager
macOS Ventura 13.0

**Comment by faizaan123** [comment]
@leemaguire for you reference. Thanks in advance

**Comment by dianaafanador3** [comment]
Hi @faizaan123 I tested archiving using Xcode 14.2 and version 10.37.2 and everything seems to be working fine, this must be something particular to your project or setup. If you go to the report navigator you get a detailed description of what is happening during the archiving?. You can export this report as a `.txt`and attach it to the issue, so we can check what is happening
