### ISSUE TITLE
Type safe query syntax crashes when checking bool value implicitly

### ISSUE THREAD

**Issue by Ogerets** [realm/realm-swift#8212]
### How frequently does the bug occur?

Always

### Description

Type safe query syntax crashes when checking bool value implicitly

Crash Example
```
realm.objects(RealmEntity.self).where { $0.someBooleanProperty }
```

No crash Example
```
realm.objects(RealmEntity.self).where { $0.someBooleanProperty == true }
```

### Stacktrace & log output

```shell
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unable to parse the format string "someBooleanProperty"'
```

### Can you reproduce the bug?

Always

### Reproduction Steps

[Here's a sample](https://github.com/Ogerets/realm-bug-sample) which reproduces bug on every launch

### Version

v10.38.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Tested in iOS 16.4.1, pretty sure it occurs on anything

### Build environment

Xcode version: 14.3
Dependency manager and version: SPM

**Comment by dianaafanador3** [comment]
@Ogerets this is something that we shouldn't allow, but that happens to pass our compilation validation and that we haven't implemented for our type safe swift query engine. I have a pic which should fix this https://github.com/realm/realm-swift/tree/dp/implicit-equal-bool
