### ISSUE TITLE
Initializing Realm from background thread causes data race warnings

### ISSUE THREAD

**Issue by TomasLinhart** [realm/realm-swift#8222]
### How frequently does the bug occur?

Always

### Description

`Object._getProperties()` and `EmbeddedObject._getProperties()` are annotated with `@MainActor`, but if you initialize Realm from a background thread. For example, using `DispatchQueue.global().async`. These methods will be called from the same thread that was used to initialize Realm.

It happens only if you build Realm as a debug build via Carthage, because you set `SWIFT_STRICT_CONCURRENCY` to `complete`.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/28642/235416988-34add86f-df4b-47ac-9e13-50c6885b45ac.png">

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/28642/235417483-2a99c30f-0c0a-49a7-808e-6c5e77ecaf96.png">

I would either expect `Realm.init` to be on the main actor too or the methods not requiring the main actor.

### Can you reproduce the bug?

Always

### Version

v10.38.3

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.4

### Build environment

Xcode version: 14.3
Dependency manager and version: Carthage - Locally built Debug build

**Comment by tgoyne** [comment]
Ah, those annotations are just incorrect.
