### ISSUE TITLE
Environment realm instance is different from the one initially injected

### ISSUE THREAD

**Issue by horatiu1921** [realm/realm-swift#8228]
### How frequently does the bug occur?
Always

### Description
Since 10.39.0, SwiftUI Environment realm instance is different from the one that was initially injected into environment.

When app starts, I open the realm and query a User object which maps to current logged in user. Then later, on ContentView the realm and user are injected into the environment:

```
.environment(\.appUser, user)
.environment(\.realm, realm)
```

Then in my SwiftUI views:

```
@Environment(\.realm) var realm
@Environment(\.appUser) var appUser
```

When objects are retrieved from realm and queried against ```user``` properties, the app crashes with error:

```
Object must be from the Realm being queried
```

Printing realm and user.realm retrieved from environment confirms that they are different instances.

Last working version: 10.38.0.

### Can you reproduce the bug?
Always

### Reproduction Steps
Open realm:

```
let realmUser = /*get app.currentUser or authenticate it.*/
let realm = try await Realm(configuration: realmUser.flexibleConfiguration, downloadBeforeOpen: downloadMode)
```

Getting User.object

```
let user = realm.objects(User.self).first(where: { $0._id == realmUser.id })
```

Injecting both into environment:

```
MainContentView()
.environment(\.appUser, user)
.environment(\.realm, realm)
```

Child SwiftUI view:

```
@Environment(\.realm) var realm
@Environment(\.appUser) var appUser

let results = realm.objects(SomeObject.self).where({ $0.someProperty == appUser.someProperty })
```

And then it crashes with:

```
Object must be from the Realm being queried
```

### Version
10.39.0

### What Atlas Services are you using?
Both Atlas Device Sync and Atlas App Services

### Are you using encryption?
Yes

### Platform OS and version(s)
macOS 13.3.1, iOS 16.4.1

### Build environment
Xcode version: 14.3

**Comment by ericjordanmossman** [comment]
@horatiu1921 Do you see the problem if you inject just the realm, then access app.currentUser within the child view? Do you have multiple users and realms in this app? Do you have any more reproduction steps or a sample reproduction proj?

**Comment by horatiu1921** [comment]
@ericjordanmossman The user I mentioned is not a RealmUser but a custom User realm object created by an Atlas function when someone creates an account on my app. After the realm is open, I check if this user object exists and then the realm and user are injected into environment.

```
let realm = try await Realm(configuration: realmUser.flexibleConfiguration, downloadBeforeOpen: downloadMode)
let user = realm.objects(User.self).first(where: { $0._id == realmUser.id })

MainContentView()
.environment(\.appUser, user)
.environment(\.realm, realm)
```

Then, from a SwiftUI view, using ```@Environment(\.realm) var realm``` fetch some objects and try to filter them ```let results = realm.objects(SomeObject.self).where({ $0.someProperty == user.someProperty })```, the app crashes.

I have a single realm and a single app user in the app.

What happens in my case is that this realm
```
let realm = try await Realm(configuration: realmUser.flexibleConfiguration, downloadBeforeOpen: downloadMode)
```
injected into environment
```
MainContentView()
.environment(\.realm, realm)
```
 and then get back ```@Environment(\.realm) var realm``` are different instances. Which was not happening on Realm 10.38.0.

**Comment by dianaafanador3** [comment]
@horatiu1921 every time you access a view and use `@Environment(\.realm) var realm` a new instance of the realm is created, this doesn't mean that this realm has different configuration or is associated to a different realm file, it's just initialised on every screen. This is because we don't actually store the realm instance but the realm configuration when you use `.environment(\.realm, realm)`.

In the other hand, from the error `Object must be from the Realm being queried`, it seems like the schema for the realm you are using to query the `User` object does not include the property you are querying, I would suggest.
* To verify that the configuration from the realm is the same one that you injected.
* Verify that the schema associated to the realm includes the `User` object and the `_id` property.

**Comment by horatiu1921** [comment]
@dianaafanador3 thank you for the update! I will investigate further to see what is happening but the thing is the same code works just fine on Realm 10.38.0 and it crashes on v 10.39.1.

**Comment by leemaguire** [comment]
Hi @horatiu1921 did you manage to solve your issue?

**Comment by horatiu1921** [comment]
Hi @leemaguire,

No, the original issue is still there. What I did, as a workaround, is to get the user from ```@Environment(\.realm) var realm``` and further inject it into environment ```.environment(\.user, user)```.

I guess we can close this issue even if I still don't know what is causing it. It worked just fine on Realm 10.38.0.
