### ISSUE TITLE
.searchable bar on a SwiftUI List disappears when NavigationLink returns to the list view

### ISSUE THREAD

**Issue by piersonleo** [realm/realm-swift#8229]
### How frequently does the bug occur?

Always

### Description

I have a SwiftUI List that's populated with ObservedResults data. Inside this list I have a navigation link that leads to another view. The issue is that the .searchable bar seems to be hidden when NavigationLink returns to the view that has the list.

I needed to drag down the list to make the search bar appears again.

### Can you reproduce the bug?

Always

### Reproduction Steps

This is the code of the view

```
import SwiftUI
import RealmSwift

struct AccountList: View {

    @ObservedResults(
        AccountEntity.self,
        sortDescriptor: SortDescriptor(keyPath: "name", ascending: true)
    ) var accounts

    @State private var searchFilter = ""
    
    var body: some View {

        NavigationStack {
            List(accounts) { account in
                NavigationLink{
                    AccountDetail()
                } label: {
                    AccountRow(account: account)
                }
            }
            .searchable(text: $searchFilter,
                        collection: $accounts,
                        keyPath: \.name) {
                ForEach(accounts) { accountsFiltered in
                    
                }
            }
        }
        .navigationTitle("Accounts")
    }
}

struct AccountDetail: View {
    var body: some View {
        Text("Hello, World!")
    }
}
```

Here's the sample project that reproduces this issue:
https://github.com/piersonleo/RealmSearchable

### Version

13.10.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Monterey 12.6.1

### Build environment

Xcode version: 14.1
Dependency manager and version: ...

**Comment by leemaguire** [comment]
You need to set the `placement` attribute like so:

```swift
 .searchable(text: $searchFilter,
                        collection: $accounts,
                        keyPath: \.name,
                        placement: .navigationBarDrawer(displayMode: .always))
```

**Comment by Akomea** [comment]
Move this line .navigationTitle("Accounts") up to modify the List, before .searchable
