### ISSUE TITLE
request for module stability

### ISSUE THREAD

**Issue by koykw** [realm/realm-swift#8231]
### Problem

I got Xcframework from Assets realm-swift-x.x.x.zip.

after unzip that zip file, I got Realm.xcframework, RealmSwift.xcframework each version of Xcode & Swift.

Eeach Version has not module stability.

For Example, i get & apply 13.4.1 Realm.xcframework & RealmSwift.xcframework in Xcode 13.4.1. it would be nice.
But it cannot use in Xcode 14.0 and over version.

When you build, set BUILD_LIBRARIES_FOR_DISTRIBUTION = YES, then swiftmodule & swiftmoduleinterface will be made.

if there were swiftmoduleinterface, it will be moudle stability.

### Solution

When you build, set BUILD_LIBRARIES_FOR_DISTRIBUTION = YES

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas App Services: Auth or Functions etc

**Comment by ericjordanmossman** [comment]
Thanks for the submission. We've discussed using the distribution mode before, but found that it would it likely cause more problems and instability than resolving it.
