### ISSUE TITLE
RLMSyncLogLevel is deprecated

### ISSUE THREAD

**Issue by krissbennett** [realm/realm-swift#8251]
### Problem

Im still getting these deprecation warnings come up, (RLMSyncLogLevel is not used in any of my code so much be internal to the packages) so is there a way a future release can address these to get rid of these warnings?

### Solution

Resolve deprecations internal to package

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by dianaafanador3** [comment]
Hi @krissbennett this APIs are gonna be deprecated in the near future, but on the meantime this warnings may appear for some release. I'll take a look and check if I can remove them completely.

**Comment by mywristbands** [comment]
@dianaafanador3 Thanks for looking into this--I reached out to MongoDB Support with basically the same issue. As [krissbennett](https://github.com/krissbennett) said, there is probably something wrong within the realm-swift package that is leading to this deprecation warning. Deprecation warnings should only appear if you actually try to use the deprecated code in your codebase; a package shouldn't just warn you about any deprecated code you could theoretically use from the package.

**Comment by robsontenorio** [comment]
Same for Xcode 15 beta.
