### ISSUE TITLE
Cannot find 'assumeOnActorExecutor' in scope (Xcode 15 Beta)

### ISSUE THREAD

**Issue by marticztn** [realm/realm-swift#8254]
### How frequently does the bug occur?

Always

### Description

Cannot build my project, currently running Xcode 15 Beta with macOS 14 Sonoma Beta.

### Can you reproduce the bug?

Always

### Version

10.40.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 14 Sonoma Beta

### Build environment

Xcode version: Xcode 15 Beta

**Comment by tgoyne** [comment]
Already fixed by https://github.com/realm/realm-swift/pull/8253.

**Comment by mohpor** [comment]
That open PR is not the fix. @tgoyne lease update your comment.

**Comment by adbdehghan** [comment]
We also faced this problem is there any fix or update on this?

**Comment by kachalo** [comment]
Same issue here.

**Comment by TripwireNL** [comment]
Please approve the PR that fixes this issue :)

**Comment by dianaafanador3** [comment]
This has been released on release [v10.40.1](https://github.com/realm/realm-swift/releases/tag/v10.40.1)
