### ISSUE TITLE
Crash in verifier method when using `preconditionIsolated` with iOS 17

### ISSUE THREAD

**Issue by khambir** [realm/realm-swift#8267]
### How frequently does the bug occur?

Always

### Description

I am encountering a crash when using the latest version of Realm and attempting to fetch objects from DB. This issue arises specifically on iOS 17.

To provide some context, I have implemented a Realm actor called RealmActor. Below is an example of the code structure:
```
actor RealmActor {
    var realm: Realm!
    
    init() async throws {
        realm = try await Realm(actor: self)
    }
    
    var count: Int {
        realm.objects(Todo.self).count
    }
}
```

The crash occurs within the verifier method, which is associated with the preconditionIsolated call.
```
#if swift(>=5.9)
        // When possible use the official API for actor checking
        if #available(macOS 14.0, iOS 17.0, tvOS 17.0, watchOS 10.0, *) {
            return {
                self.preconditionIsolated()
            }
        }
#endif
```

I would greatly appreciate it if this issue could be investigated and addressed in a future release. If any additional information is needed to assist with debugging or reproducing the issue, please let me know.

Thank you for your attention to this matter, and I look forward to a resolution.

### Stacktrace & log output

```shell
RealmSwift/Realm.swift:1469: Precondition failed: Incorrect actor executor assumption; Expected 'UnownedSerialExecutor(executor: (Opaque Value))' executor.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Fetch objects from the DB, using Actor

### Version

10.40.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17

### Build environment

Xcode version: 15.0 beta (15A5160n)
Dependency manager and version: SPM

**Comment by tgoyne** [comment]
I can't reproduce this. The given code works for me in both the iOS 17 simulator (on macOS 13) and on a device running iOS 17 beta.

**Comment by buildnewmac** [comment]
@khambir @tcollins590 I am facing the same issue on iOS when using an actor-isolated realm. 

```
RealmSwift/Realm.swift:1469: Precondition failed: Incorrect actor executor assumption; Expected 'UnownedSerialExecutor(executor: (Opaque Value))' executor. 
2023-09-16 09:42:47.762209+0800 xctest[10556:186244] RealmSwift/Realm.swift:1469: Precondition failed: Incorrect actor executor assumption; Expected 'UnownedSerialExecutor(executor: (Opaque Value))' executor.
```

![2023-09-16-0947-12](https://github.com/realm/realm-swift/assets/141930960/a7c57189-f4d0-492c-9de1-52360736f801)

**Comment by sssuourabh** [comment]
> @buildnewmac It took me a long time to solve this because the crash didn't have a great trace. I ended up going call by call everywhere I was accessing realm. There was one place that I was calling it from a different TaskGroup, or DistpatchQueue. I have no clue why this worked in iOS 16, but in iOS 17 it was crashing. My suggestions is to very closely look at each call you make to each of your realms and make sure they're calling on the exact same thread

what mesure have you taken?

**Comment by sssuourabh** [comment]
@tcollins590 i have accessed data from Realm but as soon as i am trying to use that accessed objects then it crashes and says `RealmSwift/Realm.swift:1469: Precondition failed: Incorrect actor executor assumption; Expected 'UnownedSerialExecutor(executor: (Opaque Value))' executor. `

**Comment by aehlke** [comment]
I'm seeing this issue in iOS 16 after updating to latest RealmSwift and Xcode 15.

**Comment by kakhaberikiknadze** [comment]
Realm 10.42.4, Xcode 15, iOS 17 and I'm experiencing the same issue.

**Comment by tgoyne** [comment]
This is reporting a bug in your application where you are using a Realm outside of the actor which is it isolated to.

**Comment by sssuourabh** [comment]
Yes, correct. I followed every code where i am using Realm and made it to adhere my global actor then it worked. @aehlke @kakhaberikiknadze

**Comment by davidkessler-ch** [comment]
This also happens for us, even when only accessing realm from MainActor

**Comment by BenjaminAlbrectsen** [comment]
This happens for me as well, but only on iOS 17 (Swift 5.9)

**Comment by marcoboerner** [comment]
I noticed two things. On the one hand, I didn't mark the functions that were somehow calling my Realm actor methods with my `globalActor` wrapper `@RealmActor`.
But also there were a few places where I had a Realm `Object`, and I tried to change a value of that object.

Once I ran this also inside my realm actor, this error disappeared. It showed me, consequently another error, that I cannot modify the object outside a write transaction. Which I didn't know was possible.

So I recommend to check not only where you might access methods of your actor, but also if you might be trying to modify any Realm object.

**Comment by marcoboerner** [comment]
After trying a few more things, noticing very similar problems popping up here and there, I had another look at the documentation, and realized, there were a few more things I wasn't aware of. I can only recommend: [https://www.mongodb.com/docs/realm/sdk/swift/use-realm-with-actors/](https://www.mongodb.com/docs/realm/sdk/swift/use-realm-with-actors/) 😃

**Comment by kakhaberikiknadze** [comment]
Guess I forgot to post the reply. I've also fixed it by marking the function from where I call the method with global actor @RealmActor.

**Comment by aehlke** [comment]
> This also happens for us. Whenever an unmanaged object is passed between actors.

I've resolved this issue via ThreadSafeReference for manages objects. But how are unmanaged objects to be passed across actors..?

**Comment by nirinchev** [comment]
Can you post a stacktrace for the error that you get when using unmanaged objects?
