### ISSUE TITLE
Class Projection Notifications on sub objects

### ISSUE THREAD

**Issue by alexjameslittle** [realm/realm-swift#8276]
### How frequently does the bug occur?

Always

### Description

We are unable to observe a projection and successfully get it to fire when a deeply nested property changes.  Is this expected behaviour?

### Can you reproduce the bug?

Always

### Reproduction Steps

Models:
```swift
class TestObject: Object {
    @Persisted(primaryKey: true) var id: String
    @Persisted var sub: TestSub?
}

class TestSub: Object {
    @Persisted var sub: TestSubSub?
}

class TestSubSub: Object {
    @Persisted var name: String = "test"
}

class TestProjection: Projection<TestObject> {
    @Projected(\TestObject.sub?.sub?.name) var name
}
```

Observer:
```swift 
let token = await projection.observe(on: MainActor.shared) { _, _ in
            expectation.fulfill()
        }
```

Using the above objects and observation block, if you write to the "name" property, the observation on `TestProjection` is not notified.

### Version

10.40.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16

### Build environment

Xcode version: 14.3.1
Dependency manager and version: SPM

**Comment by dianaafanador3** [comment]
Hi @alexjameslittle thanks for taking the time to open an issue. I tested your sample code and like you mentioned this doesn't seem to be working correctly. On the meantime I'll recommend using key paths for observing properties within a Projection that links to an object with nested properties. We'll take a look at the issue and let you know of any updates.

**Comment by dianaafanador3** [comment]
Hi @alexjameslittle I was finally found the issue and and working on a PR which solves this issue https://github.com/realm/realm-swift/pull/8244
