### ISSUE TITLE
How to store coordinates as GeoJSON for upcoming support

### ISSUE THREAD

**Issue by robertmiles3** [realm/realm-swift#8277]
I understand that support for geo queries [are coming](https://github.com/realm/realm-js/issues/5737) to Realm but are not ready yet. I'm just starting an app (Swift, Realm, Device Sync) and will need to store GPS coordinates for images inside the database so that I can filter/query the images based on their GPS location. @papafe was very helpful [in his response](https://github.com/realm/realm-js/issues/5737#issuecomment-1594569446), but it's based on the JS SDK and not Swift.

Knowing that the full support is still on the way, I'm wondering what is the suggested way of storing this in Swift such that it will (a) properly sync via Device Sync and (b) be queryable via the upcoming support. I want to make sure that what I start with will be the best way long-term as the support rolls out.

**Comment by nirinchev** [comment]
This should work with device sync, yes. On the server you can issue geospatial queries and add a geo index on `location` - the format on the client matches what the server expects. When geospatial support comes to the Swift SDK, you'll be able to run geospatial queries on the client against that same data. The initial version we're planning to ship will not have support for geo indexes on the client, but that is planned as a future improvement.

**Comment by robertmiles3** [comment]
Thanks so much for the hard work. Looking forward to the full support in the SDK.

**Comment by realmtai** [comment]
Did this make it into the offical swift realm SDK? I don't see this in the release notes.

https://github.com/realm/realm-swift/releases?page=1

**Comment by dianaafanador3** [comment]
Feature has been merged but not released yet.

**Comment by realmtai** [comment]
Wooo!! speedy rely! Thank you! Any chance you can share the timeline for the upcoming release?

**Comment by realmtai** [comment]
https://github.com/realm/realm-swift/releases/tag/v10.47.0

Found it ✅
