### ISSUE TITLE
Very slow build/compile time in pipeline (Azure DevOps)

### ISSUE THREAD

**Issue by Mittchel** [realm/realm-swift#8281]
### How frequently does the bug occur?
  * select --

### Description
We are experiencing very slow build times with the use of Realm. Our build increases from 20 minutes to around 1h30min at the moment. We've noticed especially compiling takes a while when using Swift Package Manager. We've used some form of caching using the Package.resolved and managed to get the build back to around 60minutes.

I am not sure where to post this question, so I hope it's in the right category. We were wondering if other people experience this issue as well? Or is this the reason why you should use carthage?

### Can you reproduce the bug?
Always

### Version
v10.40.2

### What Atlas Services are you using?
Local Database only

### Are you using encryption?
Yes

### Platform OS and version(s)
iOS 16.5

### Build environment
Xcode version: 14.3.1
Dependency manager and version: Swift Package Manager (latest, v2 I believe)

**Comment by leemaguire** [comment]
Hi @Mittchel As well as Carthage, you could also resolve this by creating your own `package.swift` file that points to a precompiled binary of Realm, and reference that in your app instead of our `package.swift`. The issue of slow build times is on our radar and we do try to tackle it incrementally.

**Comment by Mittchel** [comment]
@leemaguire thank you for your reply. Good to hear that it's being worked on. So for my clarification, the slow build times also happen on other ci/cd tools, like BitRise? 

Do you have any idea how far up the backlog this fix is positioned on? Is it something we might be able to expect in the coming 6 months? 

Thanks again.

**Comment by leemaguire** [comment]
Build times really depend on the resources allocated to the VM's running these CI tools. We do not see build times as slow as 1hr on our own setup.

I cannot give a solid timeline on the issue but we always look for ways to incrementally improve build time.

**Comment by dianaafanador3** [comment]
@Mittchel do you have any update on this issue?, did you try using a precompiled binary of Realm on your CI?

**Comment by Mittchel** [comment]
> @Mittchel do you have any update on this issue?, did you try using a precompiled binary of Realm on your CI?

Our team set it a side for a short while since we are in talks of moving to a different CI/CD and exploring our options. It's on the backlog and hopefully soon will be picked up. We've tried to embed the precompiled library and the build time went down by a lot. Personally I would try to use carthage since that seems to help.
