### ISSUE TITLE
Spurious Warnings in Xcode 15

### ISSUE THREAD

**Issue by bdkjones** [realm/realm-swift#8301]
### How frequently does the bug occur?

Always

### Description

This may be related to #8251, but I recently added Realm to a project that I'm compiling with Xcode 15 beta 3 and I get 37 gobbledegook warnings about debug notes:

<img width="862" alt="Screenshot 2023-07-13 at 00 02 15" src="https://github.com/realm/realm-swift/assets/926566/f3cadda5-ddc4-4f55-b40b-fee522bd3e86">

And I get a warning about duplicating the `lc++` library:

<img width="875" alt="Screenshot 2023-07-13 at 00 02 25" src="https://github.com/realm/realm-swift/assets/926566/e9db0b5e-ca13-46bc-b326-cf64185ed08d">

(Nothing in this app uses C++ other than Realm.)

### Stacktrace & log output

```shell
N/A
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Include Realm in an app, then build it with Xcode 15 beta 3.

### Version

10.40.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 13.4.1

### Build environment

Xcode version: 15 beta 3
Dependency manager and version: SPM via Xcode

**Comment by dianaafanador3** [comment]
@bdkjones thanks for letting us know about this. 
This issue appears since Xcode 15 beta and it's still happening on Xcode 15 beta 4, and by the looks of it seems like it is an Apple Bug. By the looks of it, looks like the linker is finding multiple occurrence of the same library, in concrete c++, and may be related to the introduction of C++ interoperability, but I'm not completely sure. 
We'll keep this issue open so we can track any changes on future releases.

**Comment by dianaafanador3** [comment]
Some of this warnings have dissapeared  on Xcode 15 Beta 5, the only one remaining is
`Ignoring duplicate library '-lc++'`.

**Comment by bdkjones** [comment]
@dianaafanador3 The remaining warning about duplicate C++ libraries still exists in Xcode 15 Beta 8. 

The consensus is that since Apple added C++ interoperability (and therefore now link the C++ library by default) they forgot to handle all the many libraries that explicitly included the C++ libraries: https://github.com/getsentry/sentry-cocoa/issues/3122#issuecomment-1651461769

I think this spurious warning is going to remain until Apple either gets their act together or Realm explicitly removes the C++ libraries when the build is done with Xcode 15+

**Comment by vg-identance** [comment]
bump (Xcode 15 released and issue still exists)

**Comment by bdkjones** [comment]
This discussion explains the cause and a way for users to address it via a build flag:

https://indiestack.com/2023/10/xcode-15-duplicate-library-linker-warnings/

**Comment by bdkjones** [comment]
Closed the issue because the bug is Apple's and Realm can't solve it.
