### ISSUE TITLE
warning: Swift error in scratch context: error: compiled module was created by a different version of the compiler; rebuild 'RealmSwift' and try again: RealmSwift

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-swift#8310]
### How frequently does the bug occur?

always

### Description

I am suddenly getting the following error - the application is working fine except for execution of a specific function where this error appears.  There doesn't seem to be any exception being thrown.

What is the cause of this - RealmSwift and the application have both been compiled with Xcode 14.3.1 ?

```
warning: Swift error in scratch context: error: compiled module was created by a different version of the compiler; rebuild 'RealmSwift' and try again: RealmSwift
.
Shared Swift state for MakeSpace2 has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.
```

### Stacktrace & log output

```shell
warning: Swift error in scratch context: error: compiled module was created by a different version of the compiler; rebuild 'RealmSwift' and try again: RealmSwift
.
Shared Swift state for MakeSpace2 has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.
```
```


### Can you reproduce the bug?

Always

### Reproduction Steps

It appears to be happening consistently with a specific area of code suddenly.

### Version

10.32.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 13.4.1

### Build environment

Xcode version: 14.3.1
Dependency manager and version: None


NOTE: I will try using the SPM version

**Comment by duncangroenewald** [comment]
Anyone ?

**Comment by dianaafanador3** [comment]
Hi @duncangroenewald How do you link RealmSwift to your project?, It looks like you are using a different version to compile RealmSwift and your project. Can you build again your RealmSwift framework and link it to your project, making sure you are using the same Xcode Version. 
If you use SPM this will be handle by them and you would need to worry about this.

**Comment by duncangroenewald** [comment]
I only have one version of Xcode installed so it's not clear how this could happen.  

The problem with SPM is that debug performance is pretty bad.

**Comment by duncangroenewald** [comment]
I am going to assume it must have been user error mixing up the built version of the library.  After cleaning everything out and using SPM and then reverting to a rebuilt library the error seems to have gone.
