### ISSUE TITLE
Xcode 15 beta 5 build failure

### ISSUE THREAD

**Issue by dabaicaifen** [realm/realm-swift#8317]
### How frequently does the bug occur?

Always

### Description

<img width="673" alt="Screenshot 2023-07-26 at 9 08 34 AM" src="https://github.com/realm/realm-swift/assets/25300313/194a55ff-2050-44de-8722-76feb39bd96b">

can be easily reproduced by the demo project: https://github.com/dabaicaifen/RealmDemo

### Stacktrace & log output

```shell
See the screenshot
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Reproduced 100% in the demo project

### Version

10.41.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16

### Build environment

Xcode version: Xcode 15 beta 5
Dependency manager and version: SPM

**Comment by dianaafanador3** [comment]
We are working to fix this, you can follow this [PR](https://github.com/realm/realm-swift/pull/8312) for any updates.

**Comment by dianaafanador3** [comment]
Closing this as duplicated of this https://github.com/realm/realm-swift/issues/8308
