### ISSUE TITLE
v10.42.0 Carthage.xcframework was built using old swift

### ISSUE THREAD

**Issue by Ogerets** [realm/realm-swift#8326]
### How frequently does the bug occur?

Always

### Description

v10.42.0 release contains Carthage.xcframework, which was built with 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51).
However the previous v10.41.1 was built using Swift 5.8.1

If I try to build it from sources using latest Swift I get `CocoaPodsDynamicExample.xcodeproj cannot be opened because it is missing its project.pbxproj file.`

Something is wrong with this release

### Can you reproduce the bug?

Always

### Reproduction Steps

- Create Cartfile with `github "realm/realm-swift" "v10.42.0"`
- Run `carthage update --use-xcframeworks`

### Version

v10.42.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

MacOS Ventura 13.5

### Build environment

Xcode version: 14.3.1
Swift: 5.8.1
Dependency manager and version: Carthage 0.39.0

**Comment by tgoyne** [comment]
Carthage is such a nightmare. It looks like if there's multiple zips on a github release with xcframework in the name it just downloads a pseudorandom one, so sometimes it coincidentally picks the first one and sometimes it doesn't. Because the correct one is the first one, it *usually* happens to use that one.

**Comment by Ogerets** [comment]
@tgoyne Oh, I had the same issue once.
According to Carthage [documentation](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification), there is a way to specify binary project specification file with links to proper xcframework archive.
I think this is the proper way to do it, when there's multiple xcframeworks attached to a release.

**Comment by Ogerets** [comment]
I will look into the problem tomorrow again. Maybe I will come up with the draft PR with fix
