### ISSUE TITLE
Significant performance decrease between `@objc dynamic` and `@Persisted`

### ISSUE THREAD

**Issue by lukaskollmer** [realm/realm-swift#8330]
### How frequently does the bug occur?

Always

### Description

I'm currently in the process of (potentially) migrating an iOS app using Realm from the legacy `@objc dynamic` property syntax to the new `@Persisted` syntax.

According to the release notes at the time, the new syntax should be faster.
However, I'm observing the opposite.

The small example program below demonstrates/reproduces this.
On my machine, running this program in a Release configuration (via Xcode) takes ~1.7 seconds when using the `@objc dynamic` syntax, and ~2.8 seconds when using the new `@Persisted` syntax.

The program creates a realm and fills it with 1000 objects which have a String property with a UUID value, and then tries to fetch these objects based on the value of that property.

Simply changing the `#if` condition between `true` and `false` causes the run-time of the measured fetch operation at the end to decrease/increase by one whole second.

Am I missing something obvious here?

### Can you reproduce the bug?

Always

### Reproduction Steps

- Run this in Xcode (eg as a macOS command line program), with RealmSwift added as an SPM dependency.
- Run as a Release build, since it's even slower otherwise.

```swift
import Foundation
import RealmSwift
import func QuartzCore.CACurrentMediaTime


func measure(_ label: String, _ block: () -> Void) {
    let startTS = CACurrentMediaTime()
    block()
    let endTS = CACurrentMediaTime()
    print("[\(label)] took \(endTS - startTS) sec")
}



class Entry: RealmSwift.Object {
#if true // <-- Toggle this between true/false to switch between the old and new property syntax.
    @Persisted(primaryKey: true) var id: UUID
    @Persisted(indexed: true) var internalTitle: String
#else
    @objc dynamic var id: UUID = UUID()
    @objc dynamic var internalTitle: String = ""
    
    override class func primaryKey() -> String? {
        return "id"
    }
    override class func indexedProperties() -> [String] {
        return ["internalTitle"]
    }
#endif
}



let realm = try Realm()

var uuidsToCheck: Set<String> = []

try realm.write {
    realm.deleteAll()
    for _ in 0..<1000 {
        let entry = Entry()
        entry.internalTitle = UUID().uuidString
        uuidsToCheck.insert(entry.internalTitle)
        realm.add(entry)
    }
}



// Add some additional IDs so that we also have some misses
for _ in 0..<250_000 {
    uuidsToCheck.insert(UUID().uuidString)
}


// Try to fetch the objects
measure("fetch objects") {
    for uuid in uuidsToCheck {
        let entries = realm.objects(Entry.self).where { $0.internalTitle == uuid }
        precondition(entries.count <= 1)
    }
}
```

### Version

Realm 10.42.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 13.4.1 (22F82)

### Build environment

Xcode version: 14.3 (14E222b)
Dependency manager: SPM (Xcode builtin)

Hardware: MacBook Pro 14" (Late 2021), with an M1 Pro and 32GB of memory

**Comment by mixdesign** [comment]
Interesting investigation. 
Realm team, is it true?

**Comment by leemaguire** [comment]
@lukaskollmer the `.where` type safe query API is not supported with the old object syntax. For a more direct speed comparison I used the NSPredicate API which resulted in 1.24 seconds for both syntax types, although the syntax declaration wouldn't matter here is this case. Another test I done was to test the actual speed of the write like so:

```swift
measure("write objects") {
    try! realm.write {
        realm.deleteAll()
        for _ in 0..<1000 {
            let entry = Entry()
            entry.internalTitle = UUID().uuidString
            realm.add(entry)
        }
    }
}
```

This resulted in 0.015 for the `@Persisted`  syntax and 0.018 for the `@objc` syntax

**Comment by tgoyne** [comment]
```swift
measure("fetch objects") {
    for uuid in uuidsToCheck {
        let entries = realm.objects(Entry.self).where { $0.internalTitle == uuid }
        precondition(entries.count <= 1)
    }
}
```

The code being measured here doesn't actually instantiate any `Entry` objects, so it's just measuring the performance of building the query. With `@objc dynamic` we turn the keypath into a string with `_kvcKeyPathString` (which only works for KVC-compatible property types), while with `@Persisted` we have to do much more complicated things and that's probably unavoidably slower. In situations like this where the query construction is a meaningful portion of the runtime, using `.filter()` with a query string instead will be faster with both types of property declarations.

**Comment by AlaghbariKamel** [comment]
Hello ,
I test both of your codes

@lukaskollmer 
[fetch objects] took 7.2836009900001955 sec @objc dynamic
[fetch objects] took 13.34427892199983 sec @persisted


[@leemaguire 
write objects] took 0.046405838999817206 sec  @persisted
[write objects] took 0.06406051700014359 sec @objc dynamic
