### ISSUE TITLE
RLMException - mmap() failed: Cannot allocate memory size: 67108864 offset: 2348810240

### ISSUE THREAD

**Issue by linwear** [realm/realm-swift#8337]
### How frequently does the bug occur?

Sometimes

### Description

When I write data, occasionally the write fails, this error is reported and the program crashes, but it does not happen 100%

### Stacktrace & log output

```shell
no detailed stack info
```

### Can you reproduce the bug?

Sometimes

### Reproduction Steps

[RLMRealm.defaultRealm transactionWithBlock:^{
            [RLMRealm.defaultRealm addOrUpdateObject:model];
        }];

### Version

10.10.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iPhone SE (2nd generation)、iPhone 12 Pro  、iPhone 8  、iOS 15.5.0、iOS 16.6.0 ...more...

### Build environment

Xcode version: Version 14.1 (14B47b)
Dependency manager and version: pod ~> 10.10.0

**Comment by ianpward** [comment]
@linwear Are you able to set this entitlement and see if this fixes your issue?
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_extended-virtual-addressing

**Comment by linwear** [comment]
Thanks for your reply, I'll check it out.




lw
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "realm/realm-swift"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月7日(星期四) 晚上11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [realm/realm-swift] RLMException - mmap() failed: Cannot allocate memory size: 67108864 offset: 2348810240 (Issue #8337)





 
@linwear Are you able to set this entitlement and see if this fixes your issue?
 https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_extended-virtual-addressing

**Comment by wsrGitHub** [comment]
> @linwear Are you able to set this entitlement and see if this fixes your issue? https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_extended-virtual-addressing

Thanks. This greatly reduces the crash rate

**Comment by mohameditani** [comment]
Thank you @linwear , I enabled the entitlement and this had a great impact of the crash rate!
