### ISSUE TITLE
user.Logout caused app crash due to `libc++abi: terminating due to uncaught exception of type std::logic_error: Cannot start a sync session for user '' because this user has been removed.

### ISSUE THREAD

**Issue by fuermosi777** [realm/realm-swift#8342]
### How frequently does the bug occur?
Always

### Description
Followed in SwiftUI quick start guide but user.logout always crashes the app due to the error mentioned in the title.

### Stacktrace & log output
```shell
libc++abi: terminating due to uncaught exception of type std::logic_error: Cannot start a sync session for user '64eacfbc24629d791762efd7' because this user has been removed.
```

### Can you reproduce the bug?
Always

### Reproduction Steps
1. Created a app following [SwiftUI quick start](https://www.mongodb.com/docs/realm/sdk/swift/swiftui-tutorial/#integrate-atlas-device-sync).
1. Login anonymously
1. Logout

In the `ContentView`, I have the following code:

```
if let user = realmApp.currentUser, user.state != .removed {
  let config = user.flexibleSyncConfiguration(...)
  RealmSyncView()
        .environment(\.realmConfiguration, config)
} else {
  LoginView()
}
```

The `LoginView()` didn't show up when `user.logout()` is tapped. The app crashes.

### Version
v10.42.0

### What Atlas Services are you using?
Atlas Device Sync

### Are you using encryption?
No

### Platform OS and version(s)
iOS 16.4

### Build environment
Xcode version: Version 14.3.1 (14E300c)
Dependency manager and version: ...

**Comment by fuermosi777** [comment]
And the error is also not thrown in `app.syncManager.errorHandler`, not sure if this is intended.

**Comment by nirinchev** [comment]
The error message could be improved, but you can't create a sync session for a logged-out user either. So the `user.state` check should instead look like `user.state == .loggedIn`.
