### ISSUE TITLE
Version 10.42.0 crashing when launching for iOS 12.4.1

### ISSUE THREAD

**Issue by JoaoPinho** [realm/realm-swift#8343]
### How frequently does the bug occur?
Always

### Summary
Hey
I have updated my project from version 10.38.0 to the latest version available 10.42.0 since i currently have Realm and realmSwift installed through Framework and i wanted to support Xcode 15 (more specifically Beta 5 since is the one supported by the framework).

Before testing the RealmSwift Framework for 15.0 Xcode, i first tested only updating the version to see if using Xcode 14.1 with most updated version everything was ok and noticed that on iOS 12.4.1 version i get a crash as soon as the app starts.
Also noticed if it was using other iOS version like 12.5.1 it was everything fine.

After all of this, simply tried to have it using pod and by using Xcode 14.1 everything was fine but as soon as i tested it on Xcode 15.0 beta 5 i also got a crash on start using only iOS 12.4.1.

### Details
Note that for every test done i always perform a clean build, then delete Derived Data folder and restart Xcode.

Framework used on for Xcode 14.1:
![002](https://user-images.githubusercontent.com/16039087/263651819-4250f6a8-f416-46c8-a2cc-b496e7b1c386.png)

Crash when using Realm and RealmSwift as Framework with Xcode 14.1 on iOS 12.4.1:
![001](https://user-images.githubusercontent.com/16039087/263651952-1e839e92-b6d0-4cc1-80bd-593496e12ebe.png)

Crash when using Cocoapods with Xcode 15.0 Beta 5 on iOS 12.4.1:
![003](https://user-images.githubusercontent.com/16039087/263653468-37c25f2d-f76b-45db-9dba-2f61e694d64f.png)

### Impact
Users using iPhone with iOS 12.4.1.

### Can you reproduce the bug?
Always

### Version
10.42.0

### What Atlas Services are you using?
Local Database only

### Are you using encryption?
Yes

### Platform OS and version(s)
iOS 12.4.1

### Build environment
Xcode version: 14.1 and 15.0 Beta 5

**Comment by nirinchev** [comment]
This was fixed in Xcode 15.1.
