### ISSUE TITLE
SwiftWASM support for realm-js for cross-platform RealmSwift

### ISSUE THREAD

**Issue by aehlke** [realm/realm-swift#8345]
### Problem
I have a lot of Swift code that uses RealmSwift but is otherwise quite portable code that could run in the browser via SwiftWASM. Now that you have RealmCore ported to the web via emscripten / the new realm-js alpha, it would be an absolute game-changer to have SwiftWASM support for wrapping RealmCore in the browser so that I can reuse my code cross-platform (including on non-browser platforms like Windows, Android where I can also run WASM in webviews).

### How important is this improvement for you?
Would be a major improvement

### Feature would mainly be used with
Local Database only

**Comment by aehlke** [comment]
Small update - Tokamak https://github.com/TokamakUI/Tokamak has work in progress for adding Android support via SDL to their SwiftUI-compatible SwiftUI-for-WASM library. That's in addition to their web target support of course. 

I just want to emphasize the breadth of realm-swift picking up the realm-js work in combination with SwiftWASM - someone would be able to easily put together a demo that runs identical Swift code across iOS, Mac, cross-plat web, Android, likely Windows as well, all using realm-js for the core with realm-swift wrapping it, with the optional ability to also use identical SwiftUI across all plats (with plat-specific parts as usual).

**Comment by nirinchev** [comment]
We don't have plans to bring WASM support to the Swift SDK for the time being. The Swift SDK is still very much intertwined with Obj C and Apple platforms and our WASM support is in its very early stages.
