### ISSUE TITLE
Expedited update to latest `realm-core`

### ISSUE THREAD

**Issue by dlbuckley** [realm/realm-swift#8358]
### Problem

We have been seeing a steady rise in crashes since we upgraded to Realm 10.38.0 which we have lovingly referred to as the `terminate.cpp` crash internally (even though this is a catch all for a whole magnitude of issues). We originally filed a report [back in April](https://github.com/realm/realm-core/issues/6593) and have been trying to investigate/mitigate the crash ever since with little success. We have found it near impossible to reproduce, and when it has happened it's been in unrelated places and always happening with writes.

In some kind of unfortunate fluke with timings we saw the crashes increase by ~5x this past week after we passed some threshold with additional writes in our latest release. We then saw that a [potential fix](https://github.com/realm/realm-core/pull/6962) to address the core of this issue was merged by @jedelbo in `realm-core` only hours ago. To give some scale about how much this effects us we are now seeing 10s of thousands of crashes a day related to this issue.

We are now in a predicament where we would like to start testing this fix ASAP instead of continuing to spend our time trying to mitigate the issue (we have spent a lot over the past few months) and get the fix released to our users. We could fork ream-core and realm-swift and get the fix quicker that way but we don't want to add even more fuel to the fire if we can help it by bypassing any internal checks/QA before an 'official' release.

We are therefore requesting an expedited bug fix patch release of `realm-core` and `swift-realm` to include the fix. If this works you will make a lot of developers on our team (and our users) extremely happy.

### Solution

A new release of realm which includes [this](https://github.com/realm/realm-core/pull/6962) fix.

### Alternatives

We have considered forking to get the fix quicker, but we don't want to add fuel to the fire and make things worse. We have also tried all sorts of mitigations in and around write threading synchronisation over the past few months to no avail.

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by tgoyne** [comment]
Cutting a release with a new core version the same day as the core release happens is our normal flow, and if it doesn't happen it's because we've discovered problems while integrating it.

**Comment by dlbuckley** [comment]
@tgoyne apologies, I'm not intimately familiar with the release process, but it sounds as if a new `relam-swift` release is imminent since a `realm-core` [release](https://github.com/realm/realm-core/releases/tag/v13.20.1) with the fix has just been released. If thats the case then that would be wonderful!
