### ISSUE TITLE
[Xcode 15] Issue to build documentation 

### ISSUE THREAD

**Issue by MarinB69** [realm/realm-swift#8365]
### How frequently does the bug occur?

Always

### Description

Hello, 

I'm currently working on a project using Swift Package Manager to obtain different packages, including Realm-Swift (currently 10.42.2).
The project can build and archive correctly.
I'm trying to add some documentations but when I try to build the documentation with Xcode 15 I get this kind of error:

`
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So26RLMFindOneAndModifyOptionsC10RealmSwiftE10projection4sort6upsert23shouldReturnNewDocumentABSDySSAC7AnyBSONOSgGSg_ALS2btcfc' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:e:s:So26RLMFindOneAndModifyOptionsC10RealmSwiftE10projectionSDySSAC7AnyBSONOSgGSgvp' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 'c:@CM@RealmSwift@@objc(cs)RealmSwiftEmbeddedObject(cm)ignoredProperties' has no reference. A symbol will always have at least one reference.
Command CompileDocumentation failed with a nonzero exit code
`

At first I thought it was my project that had a bad configuration because it has many local packages also using Realm-Swift.

But we get this error just by creating an empty project:
- Create an empty project (iOS)
- Add Realm-Swift with SPM
- And try to build the documentation

Are you experiencing this problem? If yes, do you know how to fix this problem?

Thanks in advance

### Stacktrace & log output

```shell
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So26RLMFindOneAndModifyOptionsC10RealmSwiftE10projection4sort6upsert23shouldReturnNewDocumentABSDySSAC7AnyBSONOSgGSg_ALS2btcfc' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:e:s:So26RLMFindOneAndModifyOptionsC10RealmSwiftE10projectionSDySSAC7AnyBSONOSgGSgvp' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 'c:@CM@RealmSwift@@objc(cs)RealmSwiftEmbeddedObject(cm)ignoredProperties' has no reference. A symbol will always have at least one reference.
Command CompileDocumentation failed with a nonzero exit code
```

### Can you reproduce the bug?

Always

### Reproduction Steps

- Create an empty project (iOS)
- Add Realm-Swift with Swift Package Manager
- And try to build the documentation

### Version

10.42.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16~17

### Build environment

Xcode version: 15
Dependency manager and version: Swift package manager

**Comment by JuliusHuizing** [comment]
Same problem here.

**Comment by JuliusHuizing** [comment]
Unfortunately, problem seems to persist, also in new release RealmSwift release 10.43.0. 
As of now, it looks like it is impossible to use Realm in combination with Xcode 15 if you want to build documentation for your projects?

**Comment by marcinax** [comment]
The same here.

**Comment by Cheezzhead** [comment]
Has anybody found any workarounds for this? Or does anybody know which previous xcode/realm version doesn't have this issue?

**Comment by amaurydavid** [comment]
I have the same issue with Realm 10.43.0, Cocoapods 1.13 and Xcode 15:
```
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So20RLMEmailPasswordAuthC10RealmSwiftE09callResetB8Function5email8password4args7Combine6FutureCyyts5Error_pGSS_SSSayAC7AnyBSONOGtF' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So7RLMUserC10RealmSwiftE9functionsAC9FunctionsVvp' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:STsE3mapySayqd__Gqd__7ElementQzKXEKlF::SYNTHESIZED::c:objc(cs)RLMResults' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So20RLMEmailPasswordAuthC10RealmSwiftE23resendConfirmationEmail5email7Combine6FutureCyyts5Error_pGSS_tF' has no reference. A symbol will always have at least one reference.
```

**Comment by Sangsom** [comment]
Same here, tested on empty project as well and as soon as Realm is added to project, documention can't be built anymore.
Realm 10.43.0,
Xcode 15.0

```
** BUILD DOCUMENTATION FAILED **


The following build commands failed:
	CompileDocumentation (in target 'RealmSwift' from project 'Realm')
(1 failure)
```

**Comment by JuliusHuizing** [comment]
> Has anybody found any workarounds for this? Or does anybody know which previous xcode/realm version doesn't have this issue?

Unfortunately not.
Moving back to Xcode 14 seems to work if that's an option for you. 
But that's of course far from ideal in any situation.

**Comment by MarinB69** [comment]
Issue still present with 10.44.0 ...

**Comment by AdamDia** [comment]
Same here with 10.44.0

**Comment by pinalpsspl** [comment]
Same issue with 10.44.0

CompileDocumentation (in target 'RealmSwift' from project 'Realm')
    cd /Users/UserName/Library/Developer/Xcode/DerivedData/ProjectName-cmhnsjuckdubbtaubfagmkcawuak/SourcePackages/checkouts/realm-swift
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc convert --index --fallback-display-name RealmSwift --fallback-bundle-identifier RealmSwift --fallback-bundle-version 0 --output-dir /Users/UserName/Library/Developer/Xcode/DerivedData/ProjectName-cmhnsjuckdubbtaubfagmkcawuak/Build/Products/Debug-iphoneos/RealmSwift.doccarchive --ide-console-output --diagnostics-file /Users/UserName/Library/Developer/Xcode/DerivedData/ProjectName-cmhnsjuckdubbtaubfagmkcawuak/Build/Intermediates.noindex/Realm.build/Debug-iphoneos/RealmSwift.build/RealmSwift-diagnostics.json --additional-symbol-graph-dir /Users/UserName/Library/Developer/Xcode/DerivedData/ProjectName-cmhnsjuckdubbtaubfagmkcawuak/Build/Intermediates.noindex/Realm.build/Debug-iphoneos/RealmSwift.build/symbol-graph

SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So18RLMMongoCollectionC10RealmSwiftE12changeEvents6onOpen7Combine22AsyncThrowingPublisherVyAF10PublishersOACE05WatchL0VGyyYbc_tF' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So26RealmSwiftAsymmetricObjectC0aB0E12objectSchemaAC0dF0Vvp' has no reference. A symbol will always have at least one reference.
Command CompileDocumentation failed with a nonzero exit code

**Comment by JuliusHuizing** [comment]
So this is starting to become increasingly problematic in my opinion. Seems like anyone using Xcode 15 together with RealmSwift has not been able to build documentation now for > 2 months? Or are we some unlucky subset of users?

Hope this issue gets picked up soon by someone from the Realm-swift team...! Cheers in advance.

**Comment by vcalfa** [comment]
Try to set DOCC_EXTRACT_EXTENSION_SYMBOLS = NO for the targets Realm and RealmSwift in the "Documentation Compiler - Option" within the Build Settings tab. Hopefully, this adjustment will fix the issue for you as well.

**Comment by Tabonx** [comment]
__10.45.0__ still the same issue. Did anyone find a workaround? Setting _DOCC_EXTRACT_EXTENSION_SYMBOLS = NO_ didn't work for me.
```
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 'c:@CM@RealmSwift@@objc(cs)RealmSwiftEmbeddedObject(py)invalidated' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So18RLMMongoCollectionC10RealmSwiftE9insertOneyySDySSAC7AnyBSONOSgG_ys6ResultOyAFs5Error_pGctF' has no reference. A symbol will always have at least one reference.
SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So24RealmSwiftEmbeddedObjectC0aB0E11dynamicListyAC0F0CyAC07DynamicD0CGSSF' has no reference. A symbol will always have at least one reference.
```

**Comment by JuliusHuizing** [comment]
> **10.45.0** still the same issue. Did anyone find a workaround? Setting _DOCC_EXTRACT_EXTENSION_SYMBOLS = NO_ didn't work for me.
> 
> ```
> SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 'c:@CM@RealmSwift@@objc(cs)RealmSwiftEmbeddedObject(py)invalidated' has no reference. A symbol will always have at least one reference.
> SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So18RLMMongoCollectionC10RealmSwiftE9insertOneyySDySSAC7AnyBSONOSgG_ys6ResultOyAFs5Error_pGctF' has no reference. A symbol will always have at least one reference.
> SwiftDocC/DocumentationContext.swift:1206: Fatal error: Symbol with identifier 's:So24RealmSwiftEmbeddedObjectC0aB0E11dynamicListyAC0F0CyAC07DynamicD0CGSSF' has no reference. A symbol will always have at least one reference.
> ```

Unfortunately not, still waiting for a fix.

**Comment by vcalfa** [comment]
> @vcalfa Thanks for the suggestion! Can you specify how to do that exactly? I have managed to disable it for my project that uses Realm as a dependency, but I don't yet see how I can change it for The Realm packages themselves. As far as I understand, you cannot change that for packages (as explicitly stated here: https://developer.apple.com/documentation/xcode/documenting-apps-frameworks-and-packages)?
> 
> Disabling it for my project that does not seem to fix the issue unfortunately.

In my setup, I've integrated Realm into my project using CocoaPods, where I can change the build settings for the targets in the Pods project. However, when I was attempting to integrate the Realm with SPM, I wasn't able to find a suitable workaround. It appears that this issue might be related to the documentation compiler https://github.com/apple/swift-docc/pull/715.

**Comment by sanzaru** [comment]
Same here. This issue is very annoying. We can't build the documentation for any app with realm. Would be really nice if someone would prioritize the issue.

**Comment by nacho4d** [comment]
> It appears that this issue might be related to the documentation compiler https://github.com/apple/swift-docc/pull/715.

@vcalfa 
Thank you for the info!. 

That bug was fixed merged into Swift5.10 (https://github.com/apple/swift-docc/pull/725) which is shipped in Xcode15.3. As of today Xcode15.3 is still in beta1 so we need to wait a bit more for the official release but I was able to build the documentation of my entire app which uses realm with SPM.

**Comment by nirinchev** [comment]
Apologies for the delayed response here - as this should now be fixed upstream, I'll close this issue.

**Comment by kakhaberikiknadze** [comment]
> Apologies for the delayed response here - as this should now be fixed upstream, I'll close this issue.

I have the same exact issue right now Realm 10.47.0

**Comment by nirinchev** [comment]
Did you upgrade to Xcode 15.3?

**Comment by kakhaberikiknadze** [comment]
> Did you upgrade to Xcode 15.3?

Haven't yet. I see there's 15.3 RC and will download when I get a chance. Currently on 15.2 version. Have you tried it on 15.3 RC and did it work?
