### ISSUE TITLE
[Xcode 15] Compiling for iOS 11.0, but module 'RealmSwift' has a minimum deployment target of iOS 12.0

### ISSUE THREAD

**Issue by Rylaa** [realm/realm-swift#8368]
### How frequently does the bug occur?

Always

### Description

I'm using Realm version '10.42.2,' but when I switched to Xcode 15, I encountered this error. How can I resolve it

### Can you reproduce the bug?

Always

### Version

10.42.2

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

Xcode 15 minimum deployment target v11

### Build environment

Xcode version: 15

**Comment by tgoyne** [comment]
Xcode 15 has dropped support for iOS 11 and has a minimum deployment target of iOS 12.

**Comment by Nabeel-Shehzad** [comment]
What's the solution ?

**Comment by FilipBodnar** [comment]
Has anyone found solution to this ? I cannot run Xcode14 on Sonoma as suggested.

**Comment by ntaworking** [comment]
@tgoyne 
Is this mandatory?
If I still would like support iOS 11 when using XCode 15, can I do it?

**Comment by tgoyne** [comment]
Xcode 15 does not support iOS 11.
