### ISSUE TITLE
Xcode 15 Carthage release built with beta Xcode version

### ISSUE THREAD

**Issue by mikhailmulyar** [realm/realm-swift#8370]
### How frequently does the bug occur?

Always

### Description

Carthage release for 10.42.3 built with Swift 5.9 (5.9.0.128.106) which is swift version from Xcode 15 beta release. Current Swift version is Swift 5.9 (5.9.0.128.108).

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Run Carthage `carthage build --no-skip-current --use-xcframeworks --platform iOS`

Output
```
***  Skipped installing realm-swift binary due to the error:
	"Incompatible Swift version - framework was built with 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1) and the local version is 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)."

    Falling back to building from the source
```

### Version

10.42.3

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 17.0

**Comment by kawacho** [comment]
The same problem occurs with `v10.42.4`.
```
*** Downloading realm-swift binary at "v10.42.4"
***  Skipped installing realm-swift binary due to the error:
	"Incompatible Swift version - framework was built with 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1) and the local version is 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)."

    Falling back to building from the source
```

- swiftlang-5.9.0.128.**106** clang-1500.0.40.1
- swiftlang-5.9.0.128.**108** clang-1500.0.40.1

**Comment by tgoyne** [comment]
It looks like Carthage does not approve of our xcframework having slices built with mixed compiler versions, so we'll need to drop the visionOS build until there's a non-beta Xcode version which supports it.

**Comment by kawacho** [comment]
@tgoyne 

still occurs with `v10.43.0`

```
*** Downloading realm-swift binary at "v10.43.0"
***  Skipped installing realm-swift binary due to the error:
	"Incompatible Swift version - framework was built with 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1) and the local version is 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)."

    Falling back to building from the source
```

**Comment by mikhailmulyar** [comment]
@tgoyne yep, issue is not fixed in latest version

**Comment by aehlke** [comment]
still broken
