### ISSUE TITLE
Unmanaged objects cannot be thawed 

### ISSUE THREAD

**Issue by chinaTLJ** [realm/realm-swift#8372]
### How frequently does the bug occur?

Sometimes

### Description

There are two tabs at the bottom of my app, the first tab has the operation of the database, the second does not, normal is no problem, but I click the switch operation in the two tabs, it is possible to crash to report this error。
When I click the first tab, I execute the following code：

```
        let items = DbUtils.getRealm().objects(ItemNoteBean.self)
        for (index,item) in items.enumerated().reversed(){
            if (item.title.replacingOccurrences(of: " ", with: "").isEmpty){
                if let attributedString = try? NSKeyedUnarchiver.unarchiveTopLevelObjectWithData(item.contentData) as? NSAttributedString {
                    if !attributedString.string.replacingOccurrences(of: " ", with: "").isEmpty{
                    } else {
                        try! DbUtils.getRealm().write{
                            DbUtils.getRealm().delete(item)
                        }
                    }
                }else {
                    try! DbUtils.getRealm().write{
                        DbUtils.getRealm().delete(item)
                    }
                }
            }
        }

class DbUtils {
    static var realm: Realm?
    
    static func getRealm() -> Realm {
        if realm == nil {
           
            do {
                realm = try Realm()
            } catch {
                fatalError("error: \(error)")
            }
        } else {
           
            print("has initdb")
            
        }
        return realm!
    }
}
```

### Can you reproduce the bug?

Always

### Version

10.39.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iphone 16.6

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by chinaTLJ** [comment]
Sometimes this error is also reported here：
 @StateRealmObject var item: ItemNoteBean
 try! DbUtils.getRealm().write {
                item.thaw()?.time = Date().timeIntervalSince1970
            }
            
   The above code this sentence report error:  try! DbUtils.getRealm().write

**Comment by nirinchev** [comment]
Per the error message, it looks like you're trying to thaw an object that is unmanaged (i.e. not persisted in the database). This is by design, as those objects cannot be frozen or thawed. From the snippets you've provided, it's not clear where the source of the issue originates from, but if you attach a debugger and walk down the stacktrace, you should be able to identify where these unmanaged objects are coming from and restructure your app not to call thaw on them.
