### ISSUE TITLE
[Xcode 15] Compiling for iOS 13.0, but module 'RealmSwift' has a minimum deployment target of iOS 17.0

### ISSUE THREAD

**Issue by djtyranix** [realm/realm-swift#8373]
### How frequently does the bug occur?

Always

### Description

I am using the latest version of Realm through CocoaPods. (`pod 'RealmSwift', '~>10'`). Whenever I do a pod install, it always shows this error message and causes an error on a clean install too. The suspect (which is a bit weird) is on the Minimum Deployment version when I see it through the Pods' project. 

It looks like this: `$(IPHONEOS_DEPLOYMENT_TARGET_$(XCODE_VERSION_MAJOR))` on both Realm and RealmSwift.
![Screenshot 2023-09-23 at 21 33 39](https://github.com/realm/realm-swift/assets/37214301/e664d78d-21e4-469e-9215-1086ba1dc070)

I already set my platform version in the Podfile (13.0) but seems like it doesn't matter.

### Can you reproduce the bug?

Always

### Reproduction Steps

`pod install`

### Version

10.42.3

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS / 17.0

### Build environment

Xcode version: 15
Dependency manager and version: CocoaPods 1.13.0

**Comment by TooComplicatedBye** [comment]
I have the same issue, please fix this!

**Comment by djtyranix** [comment]
@dianaafanador3 hello! Unfortunately i cannot share the project because it was a company project. But i did set the minimum version on Pods, i set it to iOS 13. My expectation is that whenever i redo pod install, Realm should automatically target the number on the Podfile, yes? If yes, then it doesn't happen.

**Comment by TooComplicatedBye** [comment]
> Can you please reinstall your pods,` pod deintegrate`, remove Podfile.lock and rerun `pod install`?

I tried this on my own project and it hadn't helped.

**Comment by MartinMoizard** [comment]
I'm facing the same issue with SPM and another dependency. This is not related to RealmSwift.

**Comment by roman-sundurov** [comment]
I have the same issue.

**Comment by nguyendai0208** [comment]
resolved after upgrade to version "v10.43.1"
with Carthage, Xcode 15

**Comment by nirinchev** [comment]
If anyone is facing this issue with the latest version of Realm on a clean project (i.e. one that can be shared with us to debug), please let us know. Otherwise, we'll consider this as resolved upstream.

**Comment by pzanitti** [comment]
Can confirm it's resolved after updating

```
Installing Realm 10.47.0 (was 10.38.0)
Installing RealmSwift 10.47.0 (was 10.38.0)
```
