### ISSUE TITLE
[Xcode 15] iOS 14.7.1 crashing with Realm 10.42.4

### ISSUE THREAD

**Issue by GodLikeCode** [realm/realm-swift#8376]
### How frequently does the bug occur?

Always

### Description

Crash when connecting Xcode debug

![image](https://github.com/realm/realm-swift/assets/15194686/3deae541-c683-42d7-b348-87311bd59116)

### Can you reproduce the bug?

Always

### Version

10.42.4

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

14.7.1

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by GordonLJY** [comment]
Seems to be similar to the issue #8369 which affects all project that supports iOS 14 variants and earlier.
Try adding the `-Wl,-ld_classic` options to the `OTHER_LDFLAGS` build in the project settings.

**Comment by GodLikeCode** [comment]
not work

**Comment by GodLikeCode** [comment]
also crash at 10.43.0

**Comment by GodLikeCode** [comment]
It does not crash when the application is running, but crashes when Xcode is debugging

**Comment by GodLikeCode** [comment]
The -Wl and -ld_classic options have been added to the OTHER_LDFLAGS build in the project Settings

**Comment by nirinchev** [comment]
Do you have a minimum repro project that you can share with us?
