### ISSUE TITLE
Store Raw JSON in Realm

### ISSUE THREAD

**Issue by davidgodzsak** [realm/realm-swift#8381]
### Problem

1. Realm does not support polymorphism. When I want to model a complex data model with polymorphism I cannot use Realm or have to use super complex measures.
2. Sometimes I want to define dynamic types (resolved in runtime) based on some configuration etc.

Because of these I am either forced into model my data in a weird way just to store them as a string and then deserialize in my app into an object. This is weird if I connect other apps to my mongodb database and suddenly have mixed string and json objects and have do deserialize some parts of my objects.

A ticket has been open for years to fix it, but I understand this is hard and will take some more time.

### Solution

Allow storing JSON nodes (objects, arrays, primitives) in Realm. This would allow me to store a meaningful json in mongodb with no hacks.

In swift it would allow me to model my data with polymorphism, still need to write my own decoder but it would allow me much more flexibility in writing my data models.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
Storing arbitrary structures in Realm will be enabled when this issue is resolved: https://github.com/realm/realm-swift/issues/8457. I know it's not 1:1 to what is described here, but the core request will be addressed.
