### ISSUE TITLE
Could not build Objective-C module 'Realm'

### ISSUE THREAD

**Issue by medabida** [realm/realm-swift#8392]
### How frequently does the bug occur?

Always

### Description

When building realm (10.43.0) with Carthage and then importing it into my project, i am getting the error 
```
Could not build Objective-C module 'Realm'

..../Debug-iphonesimulator/Realm.framework/Headers/Realm.h:64:1: Umbrella header for module 'Realm' does not include header 'RLMSyncUtil.h'
.../Debug-iphonesimulator/Realm.framework/Headers/Realm.h:64:1: Umbrella header for module 'Realm' does not include header 'RLMPlatform.h'
```

This issue only happens with 10.43.0 and above

### Can you reproduce the bug?

Always

### Reproduction Steps

- Build realm 10.43.0 with Carthage
- include it in any iOS project
- see the error

### Version

10.43.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by nirinchev** [comment]
RLMSyncUtil.h was removed in https://github.com/realm/realm-swift/pull/8002 and RLMPlatform.h was removed in https://github.com/realm/realm-swift/pull/8309. Not sure why Carthage is looking for these files, but it's possible you have some leftover files in your project - does this happen in a new project?
