### ISSUE TITLE
Stop randomly changing error codes!!

### ISSUE THREAD

**Issue by jeanbaptistebeau** [realm/realm-swift#8400]
### How frequently does the bug occur?

Always

### Description

A recent upgrade of the library broke my app's registration flow, simply because you guys decided, once again, to change error codes.

That happened in the past, I mentioned this issue [here](https://www.mongodb.com/community/forums/t/did-atlas-app-service-error-codes-change-recently/205041) (and got no answer at all).

The error code for the "confirmation required" error changed from 47 to 24 to 5. The other errors changed as well.

As far as I know, this is not documented anywhere. So, do you guys plan to correct this repeating issue somehow, or will every library update be a gamble that may break vital components of my app?

I'm very disappointed in Realm/MongoDB on that. You guys do a great job, but things like that makes me want to move away from the whole system.

Note: I've heard before that the error description should be used instead of the code, but that's not possible because of localization —and should not be the official solution, as the name "description" suggests.

### Can you reproduce the bug?

Always

### Reproduction Steps

- Write a code that relies on error code
- Update the library
- Notice that things don't work anymore

### Version

10.42.2

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS, all versions

### Build environment

Xcode version: 15.0

**Comment by tgoyne** [comment]
The constants defined in RLMError.h are the stable API, not the specific error codes. That said, I'm not aware of any changes to error codes since v10.0.0 and we've put a nontrivial amount of effort into ensuring that they stay the same.

**Comment by jeanbaptistebeau** [comment]
I can guarantee that the numerical values changed (confirmed by your colleague [here](https://www.mongodb.com/community/forums/t/did-atlas-app-service-error-codes-change-recently/205041/6?u=jean-baptiste_beau)).

That said, the suggestion of using the constants sounds interesting, but again, I think some constants are wrong. Based on observation, the codes for the following errors in v10.42.2 are the following:
- email confirmation required -> 5
- email already used -> 25
- invalid credentials -> 26

I believe the part of RLMError.h that is of interest is the following:

```
/// An error which occurred when making a request to Atlas App Services.
typedef RLM_ERROR_ENUM(NSInteger, RLMAppError, RLMAppErrorDomain) {
    /// An unknown error has occurred
    RLMAppErrorUnknown = -1,

    /// A HTTP request completed with an error status code. The failing status
    /// code can be found in the ``RLMHTTPStatusCodeKey`` key of the userInfo
    /// dictionary.
    RLMAppErrorHttpRequestFailed = 1,

    /// A user's session is in an invalid state. Logging out and back in may rectify this.
    RLMAppErrorInvalidSession,
    /// A request sent to the server was malformed in some way.
    RLMAppErrorBadRequest,
    /// A request was made using a nonexistent user.
    RLMAppErrorUserNotFound,
    /// A request was made against an App using a User which does not belong to that App.
    RLMAppErrorUserAppDomainMismatch,
    /// The auth provider has limited the domain names which can be used for email addresses, and the given one is not allowed.
    RLMAppErrorDomainNotAllowed,
    /// The request body size exceeded a server-configured limit.
    RLMAppErrorReadSizeLimitExceeded,
    /// A request had an invalid parameter.
    RLMAppErrorInvalidParameter,
    /// A request was missing a required parameter.
    RLMAppErrorMissingParameter,
    /// Executing the requested server function failed with an error.
    RLMAppErrorFunctionExecutionError,
    /// The server encountered an internal error.
    RLMAppErrorInternalServerError,
    /// Authentication failed due to the request auth provider not existing.
    RLMAppErrorAuthProviderNotFound,
    /// The requested value does not exist.
    RLMAppErrorValueNotFound,
    /// The value being created already exists.
    RLMAppErrorValueAlreadyExists,
    /// A value with the same name as the value being created already exists.
    RLMAppErrorValueDuplicateName,
    /// The called server function does not exist.
    RLMAppErrorFunctionNotFound,
    /// The called server function has a syntax error.
    RLMAppErrorFunctionSyntaxError,
    /// The called server function is invalid in some way.
    RLMAppErrorFunctionInvalid,
    /// Registering an API key with the auth provider failed due to it already existing.
    RLMAppErrorAPIKeyAlreadyExists,
    /// The operation failed due to exceeding the server-configured time limit.
    RLMAppErrorExecutionTimeLimitExceeded,
    /// The body of the called function does not define a callable thing.
    RLMAppErrorNotCallable,
    /// Email confirmation failed for a user because the user has already confirmed their email.
    RLMAppErrorUserAlreadyConfirmed,
    /// The user cannot be used because it has been disabled.
    RLMAppErrorUserDisabled,
    /// An auth error occurred which does not have a more specific error code.
    RLMAppErrorAuthError,
    /// Account registration failed due to the user name already being taken.
    RLMAppErrorAccountNameInUse,
    /// A login request failed due to an invalid password.
    RLMAppErrorInvalidPassword,
    /// Operation failed due to server-side maintenance.
    RLMAppErrorMaintenanceInProgress,
    /// Operation failed due to an error reported by MongoDB.
    RLMAppErrorMongoDBError,
};
```

By counting from the top, this seems to match for _email confirmation required_ (`RLMAppErrorAccountNameInUse`) and _invalid credentials_ (`RLMAppErrorInvalidPassword`).

However, the constant associated to _email confirmation required_, 5, is `RLMAppErrorUserAppDomainMismatch`. I'm not sure how I'm supposed to deduct that. Can I rely on that constant to always be matched to the _email confirmation required_ error?

**Comment by tgoyne** [comment]
The error codes in realm-core have changed significantly, but there's a translation layer between those and the error codes exposed in the swift SDK. The only changes in the latter from the internal rework should have been changing some errors previously reported as Unknown to specific error codes.

AppDomainMismatch is indeed a pretty confusing error for confirmation required, but it appears to be correct. The server sets a user's auth domain when it is confirmed, so using an unconfirmed user hits the check to see if the user and app go together and reports that they don't. I'm not sure how you could know that without looking at the server source, so it's definitely something the docs need to mention.

**Comment by jeanbaptistebeau** [comment]
Ok, then we'll use those codes and hope that they'll always be associated with the same error. I strongly suggest an improvement of the doc on that. 

Thanks for the quick answer; closing this issue.
