### ISSUE TITLE
Crash many times: "Fatal error: Incorrect actor executor assumption; Expected same executor as MainActor." 

### ISSUE THREAD

**Issue by EddieSwift** [realm/realm-swift#8419]
### How frequently does the bug occur?

Sometimes

### Description

Sometimes I see this crash:  "Fatal error: Incorrect actor executor assumption; Expected same executor as MainActor." 

### Stacktrace & log output

```shell
RealmSwift/Util.swift:169: Fatal error: Incorrect actor executor assumption; Expected same executor as MainActor.
```

### Can you reproduce the bug?

Sometimes

### Reproduction Steps

Just start an app
<img width="1395" alt="Screenshot 2023-11-10 at 15 41 52" src="https://github.com/realm/realm-swift/assets/37484195/f74a143a-7c15-4947-95b5-f393bc71d832">

### Version

10.42.4

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17

### Build environment

Xcode version: 15.0.1
Dependency manager and version: Pods 1.12.1

**Comment by Jaycyn** [comment]
Since you have a point where you know it's crashing, can you also include your/the code that leads up to the crash? That would be most helpful to understand the situation around the crash

**Comment by aehlke** [comment]
I'm also facing this

**Comment by nirinchev** [comment]
@aehlke do you have a minimal project that reproduces the issue that we can run locally and debug?

**Comment by aehlke** [comment]
It happens very rarely for me and is happening in a LARGE project so I'm not sure I can trim it down and know that whatever combination of things is still causing it remains in my sample. However my app is now stable now that I've removed all usage of ObservedResults where I also had other frequent writes to that data elsewhere in the app...

**Comment by nirinchev** [comment]
Thanks! We'll probably need to allocate some time to look into ObservedResults/ObservedSectionedResults as I've seen a handful of bug reports around those. In case we're unable to get to the bottom of it, we'll reach out to you to see if we can look into your large project (under NDA, of course).

**Comment by nirinchev** [comment]
This appears to be caused by `update` being invoked from a non-main-thread actor. Since this is called by the framework itself, the expectation is that it should happen on the main actor, but it's possible there is some condition where this expectation doesn't hold, though it's unclear how it comes to be. If someone who can repro this problem can share a stacktrace, that would help us make progress on the investigation.
