### ISSUE TITLE
xcframework for Carthage seems to be built with Xcode 15.1 (beta). Shouldn't it be built with non-beta version of Xcode?

### ISSUE THREAD

**Issue by kainosk** [realm/realm-swift#8422]
### How frequently does the bug occur?

Always

### Description

When I use carthage to fetch RealmSwift in Xcode 15.0.1 environment, log says `Incompatible Swift version`. I think xcframework should be built with non-beta version of Xcode. Is this situation is intentional? 

Thank you.

### Stacktrace & log output

```shell
*** Fetching realm-swift
*** Checking out realm-swift at "v10.44.0"
*** xcodebuild output can be found in /var/folders/lj/28bcryw51c11f68srg3_fz3m0000gn/T/carthage-xcodebuild.XqxPAe.log
*** Downloading realm-swift binary at "v10.44.0"
***  Skipped installing realm-swift binary due to the error:
	"Incompatible Swift version - framework was built with 5.9.2 (swiftlang-5.9.2.2.51 clang-1500.1.0.2.2) and the local version is 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)."

    Falling back to building from the source
*** Building scheme "RealmSwift" in Realm.xcworkspace
*** Building scheme "Realm" in Realm.xcworkspace
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. set local Xcode version to `15.0.1` (current latest stable release of Xcode)
2. confirm local Xcode version with `xcodebuild -version` then output should be `Xcode 15.0.1 Build version 15A507`
3. Create Cartfile. The content is `github "realm/realm-swift" "v10.44.0"`
4. Do carthage with `carthage update --platform iOS --use-xcframeworks`

Then carthage says `Incompatible Swift version ` like the log I attached.

### Version

v10.44.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS17

### Build environment

Xcode version: 15.0.1
Dependency manager and version: Carthage 0.39.1

**Comment by tgoyne** [comment]
10.45.0 was built without any beta Xcodes installed on the build machines at all, so whatever's going wrong with the packaging script shouldn't apply to it.
