### ISSUE TITLE
Can I filter a `PersistableEnum` with predicate?

### ISSUE THREAD

**Issue by cuongtv51** [realm/realm-swift#8423]
### How frequently does the bug occur?

Always

### Description

Can I filter a `PersistableEnum` with predicate?
I search document, but not found solution

### Can you reproduce the bug?

Always

### Version

all

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by Jaycyn** [comment]
Can you clarify the question? Including some code that demonstrates what's being attempted and your models. 

If you're asking about filtering on a Realm Object property that's set to a PersistableEnum value, the answer is yes. But if not, what's the use case for filtering on an enum since it's essentially static data (a fixed set of related values)?

**Comment by cuongtv51** [comment]
Hi, great thanks your feedback?
we have models:
`enum MSPlaylistType: String, PersistableEnum {
    case systemMedia
    case systemLastPlay
    case systemFavorite
    case systemHistory
    case userCreated
    case artist
    case genre
    case album
}

class MSPlaylist: Object, Identifiable {
    @Persisted(primaryKey: true) public var playlistId      : String!
    @Persisted public var title           : String?
    @Persisted(indexed: true) var playlistType: MSPlaylistType = .userCreated
}
`
How can I filter `MSPlaylist` with `playlistType` is `album`? I don't know write that filter with predicate? I search on google but not found any solution.

**Comment by Jaycyn** [comment]
You're going to love this!

Here are your original enum and object, noting I changed how the primaryKey is instantiated - nothing to do with the solution.

```
enum MSPlaylistType: String, PersistableEnum {
    case systemMedia
    case systemLastPlay
    case systemFavorite
    case systemHistory
    case userCreated
    case artist
    case genre
    case album
}

class MSPlaylist: Object, Identifiable {
    @Persisted(primaryKey: true) var _id: ObjectId
    @Persisted public var title : String?
    @Persisted(indexed: true) var playlistType: MSPlaylistType = .userCreated
}
```



And then some code to write an artist and genre and then query for them

```
let p0 = MSPlaylist()
p0.playlistType = .artist

let p1 = MSPlaylist()
p1.playlistType = .genre

try! realm.write {
    realm.add(p0)
    realm.add(p1)
}
```

and then query

```
let artistResults = realm.objects(MSPlaylist.self).where { $0.playlistType == .artist}
print(artistResults)

let genreResults = realm.objects(MSPlaylist.self).where { $0.playlistType == .genre}
print(genreResults)
```

There you go!

Try to implement some of the new styles of doing queries that are more type safe than Predicates. See here [.where](https://www.mongodb.com/docs/realm/sdk/swift/crud/read/#filter-queries-based-on-object-properties)

Going forward try to ask general programming questions in the forums or on StackOverflow - leave git for more bug-level reporting issues.

**Comment by cuongtv51** [comment]
Great thank your support.
