### ISSUE TITLE
[Duplicate] Importing RealmSwift within Xcode 15 causes Documentation Builds to fail.

### ISSUE THREAD

**Issue by JuliusHuizing** [realm/realm-swift#8431]
### How frequently does the bug occur?

Always

### Description

Reposting the issue below, because that one does not seem to have gotten any traction since the issue was first raised.
https://github.com/realm/realm-swift/issues/8365

### Stacktrace & log output

```shell
https://github.com/realm/realm-swift/issues/8365
```

### Can you reproduce the bug?

Always

### Reproduction Steps

https://github.com/realm/realm-swift/issues/8365#issuecomment-1842276331

### Version

10.44

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Xcode 15, ios17

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by nirinchev** [comment]
Apologies for the delayed response here and in the other issue. Per the last comment there, the fix was applied upstream and will ship with Xcode 15.3.
