### ISSUE TITLE
Will it support Xcode15.1   

### ISSUE THREAD

**Issue by tikamsingh** [realm/realm-swift#8434]
### Problem

We are not able to compile this framework in updated  Xcode 15.1 and Mac OS Sonoma through Carthage, 

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by Jaycyn** [comment]
See v10.45.0

https://github.com/realm/realm-swift/releases

**Update release packaging for Xcode 15.1.**
**Carthage release for Swift is built with Xcode 15.1.0.**

**Comment by nirinchev** [comment]
Per @Jaycyn's comment, we do support Xcode 15.1 now.
