### ISSUE TITLE
We are unable to fetch the lib in carthage

### ISSUE THREAD

**Issue by tikamsingh** [realm/realm-swift#8442]
### How frequently does the bug occur?
Always

### Description
When we are using Carthage script to download

Incompatible Swift version - framework was built with 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5) and the local version is 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)

### Can you reproduce the bug?
Always

### Reproduction Steps
When we are using Carthage script to download

### Version
10.45.1

### What Atlas Services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
iOS

### Build environment
Xcode version 15.1

**Comment by tgoyne** [comment]
The error indicates that you are using Xcode 14, not 15.1.

**Comment by tikamsingh** [comment]
No, I am using Xcode 15.1 , I am sure.

**Comment by tgoyne** [comment]
"the local version is 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)" is explicitly saying that Carthage is using Xcode 14.2.

**Comment by tikamsingh** [comment]
How we can update local swift version to xcode15.1

**Comment by nirinchev** [comment]
You need to update your Xcode version. Feel free to reopen if you still see the problem with Xcode 15.1.
