### ISSUE TITLE
Migration from old version to latest version

### ISSUE THREAD

**Issue by hyoromo** [realm/realm-swift#8448]
### Problem

I wrote the below but did not receive any response from anyone, so I am posting the same content here as a feature request.
https://www.mongodb.com/community/forums/t/the-app-crashes-when-updating-from-an-older-version/250898

I tried updating existing apps from v0.98.3 to v10.43.1.
There were no issues with new installs, but updating from v0.98.3 resulted in the following error:

`Terminating app due to uncaught exception 'RLMException', reason: 'Database has an unsupported version (3) and cannot be upgraded'
`

### Alternatives

I would like the ability to update from old DB versions to the latest version.
If that feature is not implemented, please let me know what incremental update path I can take from v0.98.3 to catch up to the latest version.

### How important is this improvement for you?

Fairly niche but nice to have anyway

### Feature would mainly be used with

Local Database only

**Comment by Jaycyn** [comment]
Sorry we missed your post of the forums!

Are you sure you're going from **v0.98.3** to v10.43.1?

v0.98.3 was back in 2016 - 8 years ago.

If so, I believe that's going to require an intermediate step. It's been a few years but an older version of Realm *Browser* needs to be used to open the database, which will then update it. Then Realm Studio can be used to make it more 'modern'. I also could be totally wrong as it's been years.

**Comment by hyoromo** [comment]
Thank you for your response.

Since there were no particular issues occurring, I had missed updating Realm.
Sorry for the inconvenience.

Could you provide me with detailed information on the intermediate steps? Or is there any information available somewhere?

Realm Browser and Realm Studio are tools for PCs, right?

For iOS app users currently using the **v0.98.3** DB, I want to update Realm so that the app can launch properly.
To do this, my understanding is that I need to "use an old version that can be updated from v0.98.3, wait for that version to penetrate, then use an even older version" repeatedly. Is my understanding correct?

**Comment by Jaycyn** [comment]
Ok. So. 100% guesswork here but *may* be helpful

See my SO answer to [this question](https://stackoverflow.com/questions/62314788/app-using-new-version-of-realm-cant-open-db-created-with-app-using-older-versio/62327662#62327662)

and then see the notes on the [5.0.0 release notes](https://github.com/realm/realm-swift/releases/tag/v5.0.0)

**Comment by hyoromo** [comment]
Thank you very much.

I see that v5.0.0 upgrades the "Realm file format to version 10", automatically updating DBs up to ver9.
I have time next week to work on this, so I will first try updating to v5.0.0 then. If that doesn't work, I will try gradually lowering the major version.

As noted in the Release Notes, is the range of "automatic updates" something that I can only know by trying it?
The Release Notes for v10.0.0 describe something similar, and neither specifies the DB versions that can be read.
https://github.com/realm/realm-swift/releases/tag/v10.0.0

**Comment by hyoromo** [comment]
The update from Realm v0.98.3 to v5.0.0 failed with the following error:
`Opening Realm files of format version 3 is not supported by this version of Realm`

However, it was able to launch without issues on v4.4.1.
Thank you for the support.
