### ISSUE TITLE
No such module 'RealmSwift' - Error on Sonoma (14.2.1) - Xcode 15.1

### ISSUE THREAD

**Issue by Madhivanan** [realm/realm-swift#8449]
### How frequently does the bug occur?

Always

### Description

I added dependencies using the package manager for RealmSwift. then, when I import "RealmSwift," a compiler error message such as "No such module 'RealmSwift'" appears.

Xcode version - 15.1
Mac - 14.2.1

### Can you reproduce the bug?

Always

### Version

10.45.2

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

Xcode version: 15.1
Dependency manager and version: ...

**Comment by Jaycyn** [comment]
I am running the exact same configuration and it worked for me with no issues. 

Don't forget then when using SPM, there are two libraries  that need to be added: Realm and RealmSwift which will be found at this repository https://github.com/realm/realm-swift.git when you are searching for packages

Also be sure to set the Dependency Rules to Up to Next Major Version and in the first field use the current version 10.45.2

**Comment by Madhivanan** [comment]
But my end this problem is occur 
<img width="1111" alt="Screenshot 2024-01-05 at 3 00 55 PM" src="https://github.com/realm/realm-swift/assets/2713977/ccc46204-acf5-4a2d-be1c-0fd9597a044a">

**Comment by Jaycyn** [comment]
@bahrulhalimi

I just now created a new iOS Project, selected Swift and Storyboard and then followed the exact instructions here  [Install the SDK for iOS, macOS, tvOS, and watchOS](https://www.mongodb.com/docs/realm/sdk/swift/install/#install-the-sdk-for-ios--macos--tvos--and-watchos). Then built the project (Command-B)

It worked perfectly. I am on macOS Sonoma 14.2.1 and XCode 15.2

The only difference I see in your setup is the packages shown in your screen shot are older. (10.45 vs my 10.47). That may indicate you didn't do this part

> Specify Options
> In the options for the realm-swift package, we recommend setting the Dependency Rule to Up to Next Major Version, and enter the  [current Realm Swift SDK version](https://github.com/realm/realm-swift/releases). Then, click Add Package.

![Realm_Install](https://github.com/realm/realm-swift/assets/19558530/168c243e-c654-450e-ae35-d002f081bd4b)
