### ISSUE TITLE
Sort results is different between realm sort and Swift sort

### ISSUE THREAD

**Issue by yzm347404** [realm/realm-swift#8451]
i am using realmSwift, to cater the requirement, i will sort this result for display,  when i sort  it using sorted(by:) in realm and sorted() in swift,  found that the results is different. The sort keyword is a property of the object type String.

func sortInventories(inventories: Results<Inventory>, by preference: SortingPreference)  {
        var sortDescriptors = [RealmSwift.SortDescriptor]()
        sortDescriptors.append(.init(keyPath: \Inventory.brandName))
        var arr = Array(inventories).sorted { s, ss in
            return s.brandName < ss.brandName
        }
        var xx = inventories.sorted(by: sortDescriptors)
    }

![image](https://github.com/realm/realm-swift/assets/15798109/844295a6-7274-4442-aa26-f082b8197679)

**Comment by Jaycyn** [comment]
There are a number of reasons those sorts will be different and I don't believe this line of code is valid as-is

`var sortDescriptors = RealmSwift.SortDescriptor`

But... there's no need to leverage high level Swift functions - and doing that defeats the purpose of the memory friendly lazy-loading feature of Realm.

Why not just use a one liner?

`let sortedInventory = realm.objects(Inventory.self).sorted(by: \.brandName)`
