### ISSUE TITLE
Need realm-swift-10.46.0/15.0 (xcode 15.0)

### ISSUE THREAD

**Issue by juntec** [realm/realm-swift#8477]
### Problem

v10.46.0 does not include xcode 15.0 binaries.
Can you please include the xcode 15 binaries in the release?
(Currently only 14.2, 14.3.1, 15.1, 15.2 are included.)

Background:
My app is built on Xcode 15.0 and uses the Realm library.
However, there is a limitation that I cannot use SPM, so I am copying the binary into the app and importing Realm.
Currently only 14.2, 14.3.1, 15.1, and 15.2 binaries are released, and if I use those binaries, Build will fail due to different Build versions.

Is there a better way or can you release binaries for xcode 15.0?

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
Creating prebuilt binaries with multiple versions of Xcode complicates our CI infrastructure and is an ongoing maintenance burden. Is there a particular reason why you're not able to update your Xcode version?

**Comment by juntec** [comment]
We have a lot of framework dependencies in our application and need to wait until all frameworks support 15.1 or 15.2.
(And there is a limitation that our app cannot use SPM)

> Creating prebuilt binaries with multiple versions of Xcode complicates our CI infrastructure and is an ongoing maintenance burden.

Yes, I agree with you on the above issue. Managing multiple versions of XCode can be complicated.

Is it possible to generate the realmSwift.xcframework myself in my local environment from 10.46.0 Source code?

**Comment by nirinchev** [comment]
You can run `./build.sh package ios` to generate an xcframework with your current version of Xcode.

**Comment by juntec** [comment]
```./build.sh package ios```

I was able to solve the CompilerVersion problem by the method you suggested.

This Issue has been resolved.
