### ISSUE TITLE
Crash in app launch ios 14 and earlier 

### ISSUE THREAD

**Issue by DrWaleedNour** [realm/realm-swift#8487]
### How frequently does the bug occur?

Always

### Description

in my app when run it in ios 14 and earlier, the app not run and crash on launch, the crash occur before appdelgate and this is reason
 Thread 1: EXC_BAD_ACCESS (code=1, address=0x3c4000)

realm::util::FunctionRef<unsigned long (realm::BPlusTreeNode*, unsigned long)>::FunctionRef<realm::BPlusTree<long long>::insert(unsigned long, long long)::'lambda'(realm::BPlusTreeNode*, unsigned long)&>(realm::BPlusTree<long long>::insert(unsigned long, long long)::'lambda'(realm::BPlusTreeNode*, unsigned long)&)::'lambda'(void*, realm::BPlusTreeNode*, unsigned long)::__invoke(void*, realm::BPlusTreeNode*, unsigned long):

### Can you reproduce the bug?

Always

### Reproduction Steps

run on ios 14 and earlier

### Version

10.46

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

14

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by nirinchev** [comment]
Does this happen on simulator or a real device? Also, does it happen in a brand new project or only in your real project? This is the first time we've received such a report, indicating that it's likely not a widespread issue and there's something unusual about your setup that is causing the crash.

**Comment by DrWaleedNour** [comment]
> Does this happen on simulator or a real device? Also, does it happen in a brand new project or only in your real project? This is the first time we've received such a report, indicating that it's likely not a widespread issue and there's something unusual about your setup that is causing the crash.


real device
real project

**Comment by nirinchev** [comment]
Unfortunately, this is not enough information for us to investigate. If you're able to reproduce it and get a complete stacktrace or give us a project we can debug locally, we would be happy to work on it.
