### ISSUE TITLE
Crash when launch

### ISSUE THREAD

**Issue by DrWaleedNour** [realm/realm-swift#8493]
### How frequently does the bug occur?

Always

### Description

we added realm sdk as static to my app, and we add all requirements, but when run my app i receive this crash:
 dyld: symbol not found: _objc_class_$_rlmap

### Can you reproduce the bug?

Always

### Reproduction Steps

- Add realm sdk as a static framework  to project
- Under Link Binary with Libraries, click + and add libc++.tbd, libz.tbd, and libcompression.tbd.
-  Run app > crash

### Version

10.47.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

All

### Build environment

Xcode version: ...
15.2..

**Comment by DrWaleedNour** [comment]
Yes

**Comment by nirinchev** [comment]
Do you have a minimal project that demonstrates the issue?

**Comment by DrWaleedNour** [comment]
No

**Comment by nirinchev** [comment]
We can't help in that case.

**Comment by DrWaleedNour** [comment]
could send to me steps to add realm sdk?

**Comment by DrWaleedNour** [comment]
May be crash because static library?

**Comment by nirinchev** [comment]
I'm sorry, but we can't provide support like this. Our documentation is up to date and creating a brand new project, linking the static xcframework from [10.47.0](https://github.com/realm/realm-swift/releases/tag/v10.47.0) works just fine. If it doesn't for you, then there's something special in your project/environment and unless you're able to give us something that reproduces the problem, there's no way for me to guess what that is.
