### ISSUE TITLE
Possible perf regression between 10.42.3 and 10.47.0

### ISSUE THREAD

**Issue by macdrevx** [realm/realm-swift#8513]
### How frequently does the bug occur?

Always

### Description

We recently tried upgrading from v10.42.3 to v10.47.0, but a few of our users with larger Realm databases (e.g. 4.6 GB) started seeing the app crash on launch. Via BugSnag, we saw that the crash was occurring due to taking too long to launch (see stacktrace).

Without changing the size of the Realm, the issue went away when we reverted to v10.42.3.

The stacktrace shows that the realm was being compacted at the point of termination, but it's not possible to say for sure whether compaction itself is the culprit here since the stacktrace only shows a moment in time.

Given Apple's upcoming privacy manifest requirements, it's critical that we be able to upgrade soon, so resolving this perf regression is high-priority for us. Please let us know what other information we can provide to help debug.

Additionally, we're aware that a 4.6 GB Realm is not ideal — we're working to resolve this, but also want to explore this potential perf regression.

### Stacktrace & log output

```shell
App Hang: The app was terminated while unresponsive

0  realm::Array::init_from_mem(realm::MemRef)
1  realm::Array::do_write_deep(realm::_impl::ArrayWriterBase&, bool) const
2  realm::Array::do_write_deep(realm::_impl::ArrayWriterBase&, bool) const
3  realm::Array::do_write_deep(realm::_impl::ArrayWriterBase&, bool) const
4  realm::Array::do_write_deep(realm::_impl::ArrayWriterBase&, bool) const
5  realm::Array::do_write_deep(realm::_impl::ArrayWriterBase&, bool) const
6  realm::Array::do_write_deep(realm::_impl::ArrayWriterBase&, bool) const
7  realm::Group::write(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, realm::Group::TableWriter&, bool, bool, unsigned long long)
8  realm::Group::write(realm::util::File&, char const*, unsigned long long, realm::Group::TableWriter&) const
9  realm::DB::compact(bool, std::__1::optional<char const*>)
10 realm::_impl::RealmCoordinator::open_db()
11 realm::_impl::RealmCoordinator::do_get_realm(realm::RealmConfig&&, std::__1::shared_ptr<realm::Realm>&, std::__1::optional<realm::VersionID>, realm::util::CheckedUniqueLock&, bool)
12 realm::_impl::RealmCoordinator::get_realm(realm::RealmConfig, std::__1::optional<realm::VersionID>)
13 realm::Realm::get_shared_realm(realm::RealmConfig)
14 +[RLMRealm realmWithConfiguration:confinedTo:error:] (RLMRealm.mm:430:25)
15 +[RLMRealm realmWithConfiguration:queue:error:] (RLMRealm.mm:395:24)
16 @nonobjc RLMRealm.__allocating_init(configuration:queue:) (<compiler-generated>)
17 Realm.init(configuration:queue:) (Realm.swift:95:28)
...
19 AppDelegate.application(_:didFinishLaunchingWithOptions:)
...
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Strictly speaking, one of our users was able to repro consistently (by opening the app, which opened the realm), but at the moment, we don't actually have a database file that demonstrates the issue.

### Version

10.47.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17.3.1, iPhone 15 Pro

### Build environment

Xcode version: 15.2 (15C500b)
Dependency manager and version: CocoaPods 1.14.3

**Comment by nirinchev** [comment]
Do you think you can get the Realm file that reproduces the issue and either share it with us or get a profile to help us understand where the app is spending time? As a temporary workaround you could try shipping a version that doesn't compact the Realm file at launch.

@finnschiermer this is updating from Core 13.20.1 to 13.26.0 - I tried skimming through the changelog entries and there was nothing that jumped at me as having potentially large performance impact.

**Comment by macdrevx** [comment]
> As a temporary workaround you could try shipping a version that doesn't compact the Realm file at launch.

How do you do this? Will the realm never be compacted, or just not while it's being opened?

> Do you think you can get the Realm file that reproduces the issue and either share it with us or get a profile to help us understand where the app is spending time?

I won't be able to get the exact realm file. We'll likely need to see whether we can create one artificially.

**Comment by nirinchev** [comment]
You can return `false` in the `shouldCompactOnLaunch` callback skipping compaction for the Realm file. You can also use a heuristic where it returns `true` for smaller files, but not for those large ones, which take a long time.

In terms of whether the file it'll compact, the answer is yes-ish. By that, I mean, that we now have automatic compaction enabled on every commit where we'll do certain cheap storage optimizations continuously. This is not as effective as running a compact on launch but it gets close in a lot of scenarios.

Alternatively, you could restructure your app so that it doesn't open the Realm file as part of the `AppDelegate.application` call and instead do it after that the app has loaded (possibly adding a loading indicator in case the file size is beyond a certain threshold).
