### ISSUE TITLE
Crash when user sessions are revoked

### ISSUE THREAD

**Issue by movic-wj** [realm/realm-swift#8519]
### How frequently does the bug occur?

Always

### Description

<img width="1207" alt="Screenshot 2024-03-14 at 13 36 04" src="https://github.com/realm/realm-swift/assets/101322534/17e2c548-0877-4c5c-974d-065f0cb97376">

The issue occurs when the session is revoked for that user and next time you launch the app it will crash. Since the delegate invokes the didCompleteWithError, this time the NSError is nil: "attempt to insert nil object from objects[3]"

### Stacktrace & log output

```shell
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]'
*** First throw call stack:
(0x19881eb28 0x190692f78 0x198788898 0x1987881b4 0x10106c044 0x19987f98c 0x105c8cb98 0x105c8e7bc 0x105c9666c 0x105c9743c 0x105ca4404 0x105ca3a38 0x1f471cf20 0x1f471cfc0)
libc++abi: terminating due to uncaught exception of type NSException
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Login the user with anonymously and then revoke the sessions. Re-launch the app and it will crash

### Version

10.48.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by nirinchev** [comment]
Hey, thanks for this report. Can you check what the status code is when you hit this code?

**Comment by movic-wj** [comment]
Hi,
Its 401.

Regards
