### ISSUE TITLE
Package manifest at '/Package.swift' cannot be accessed (/Package.swift doesn't exist in file system)

### ISSUE THREAD

**Issue by andgordio** [realm/realm-swift#8527]
### How frequently does the bug occur?

Always

### Description

• Create a new project in Xcode
• Follow the documentation, SwiftPM tab: https://www.mongodb.com/docs/realm/sdk/swift/install/
• See error when attempting to add the package: Package manifest at '/Package.swift' cannot be accessed (/Package.swift doesn't exist in file system)

Can be fixed by changing Dependency rule from “Up to latest major” to “exact: 10.48.1”

### Can you reproduce the bug?

Always

### Version

latest

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

14.2.1 

### Build environment

Xcode version: Version 15.1
Dependency manager and version: SPM

**Comment by Jaycyn** [comment]
I did these exact steps and did not encounter any issues

• Create a new project in Xcode
• Follow the documentation, SwiftPM tab: https://www.mongodb.com/docs/realm/sdk/swift/install/

I tried it with both a macOS app and iOS as well.

Running macOS 14.2.1, XCode 15.3 and the current Realm release v10.49.1. Here's a screenshot of what I entered.

<img width="451" alt="Package" src="https://github.com/realm/realm-swift/assets/19558530/6aff8459-aa46-4944-9aa1-97550a7dec1a">

I built a project a couple of months ago with XCode 15.1 and didnt have any issues then.

Can you try upgrading your XCode? Perhaps there's a permissions issue - try Disk First Aid or even a reboot.

**Comment by andgordio** [comment]
Double-checked my settings and noticed that the version was set to 1.0.0<2.0.0. I guess I got so used to the first field being pre-filled with the latest minor version that I didn’t pay attention to the input. Apologies for the confusion.

**Comment by Jaycyn** [comment]
Sooooo...... does that mean it can be closed or is there still an issue we're overlooking?

**Comment by andgordio** [comment]
No issue. Please close. Thanks.
