### ISSUE TITLE
v10.49.1 not compatible with Realm Studio 14.1.2

### ISSUE THREAD

**Issue by krissbennett** [realm/realm-swift#8529]
### How frequently does the bug occur?

Always

### Description

unable to open realm database created with v10.49.1, 
"database has an unsupported version (24) and cannot be upgraded

### Can you reproduce the bug?

Always

### Version

v10.49.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

macOS Sonoma 14.3.1

**Comment by nirinchev** [comment]
Realm Studio 15.0 was released with support for opening Realm files created or upgraded by Realm Swift 10.49.1.

**Comment by krissbennett** [comment]
Thanks, might be worth updating release notes on min studio version.
