### ISSUE TITLE
Database has an unsupported version (9) and cannot be upgraded

### ISSUE THREAD

**Issue by dj00122222222** [realm/realm-swift#8532]
### How frequently does the bug occur?

Always

### Description

Our project is currently using sdk version 4.4.1, when I upgrade to the latest version, there is an error, is there a solution to solve this problem

### Stacktrace & log output

```shell
*** Terminating app due to uncaught exception 'RLMException', reason: 'Database has an unsupported version (9) and cannot be upgraded'
*** First throw call stack:
(0x180f73c60 0x19879fee4 0x109353be0 0x1092d8898 0x1092da434 0x1092d9df0 0x1092d8ecc 0x10516f464 0x104f80c5c 0x104f80904 0x1080a1fc8 0x1080a3934 0x104f80840 0x10516ac0c 0x183525574 0x1836f9d98 0x1836e34bc 0x183551284 0x1833b7fa8 0x1834da9dc 0x1835f0008 0x183818434 0x1837a8174 0x1833b8cf4 0x1834748e4 0x1833baa84 0x18349f134 0x1838f4f38 0x1833e872c 0x18342a4cc 0x183555cec 0x18349d550 0x1920ffc50 0x192121f98 0x1920e2bdc 0x1920e3fd4 0x1080a1fc8 0x1080a54cc 0x1920e42ac 0x1920e37c0 0x1920e7960 0x180f94448 0x180fa4578 0x180ee6790 0x180eebe08 0x180eff174 0x1a1a1a988 0x183701a88 0x18349af78 0x105222ed4 0x10665c4d0)
```

### Can you reproduce the bug?

Always

### Version

4.4.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17.4

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by Jaycyn** [comment]
In a nutshell, your Realm *core* version is too old to directly upgrade it. I believe you will have to take a couple of incremental steps to get it current.

SDK v4.x used file format version 9.

Using SDK < v5.4 bumps the version to 10, then 5.4 to 11. It can then be read by modern SDK's

So - stretching my memory a bit, if you upgrade to 5.0 and then let it update your database, and then 5.4 which will increase the file version to 11, you should be good to go after that.

Maybe an employee will have a better upgrade path option.

**Comment by tgoyne** [comment]
10.48.0 is the final version to support upgrading from pre-v5.0.0 databases.

**Comment by dj00122222222** [comment]
@Jaycyn Thank you for your solution, but v5 is not compatible with Apple's Privacy Checklist policy, and there is no PrivacyInfo.xcprivacy file to upgrade gradually

**Comment by dj00122222222** [comment]
@tgoyne Thank you for your solution, it solved my problem very well
