### ISSUE TITLE
SwiftPackageManger print "skipping cache due to an error" warning for realm-swift

### ISSUE THREAD

**Issue by VictorVlakh** [realm/realm-swift#8534]
### How frequently does the bug occur?

Always

### Description

When add https://github.com/realm/realm-swift repository via SwiftPackageManager, in the logs I see the following warning:

`skipping cache due to an error: https://github.com/realm/realm-swift: The repository could not be found. Make sure a valid repository exists at the specified location and try again.`

<img width="1089" alt="Screenshot 2024-04-02 at 09 38 05" src="https://github.com/realm/realm-swift/assets/105867610/f6f09b8f-efc5-4f35-bc83-9dd578e499ce">

Realm: **10.49.1**

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Create new project 
2. Add realm-swift via SwiftPackageManager
3. Reset package caches

### Version

10.49.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

mac os (14.1)

### Build environment

Xcode version: 15.3
Dependency manager and version: SwiftPackageManager

**Comment by Jaycyn** [comment]
Maybe just a typo but by the screenshot, the path is not correct. The repository that should be added has a `.git` extension on the end:

https://github.com/realm/realm-swift.git

not

 https://github.com/realm/realm-swift

see

[Realm Installation](https://www.mongodb.com/docs/realm/sdk/swift/install/#installation)

I just tried it with yours and got the same error. Adding .git make it work correctly without the error.

**Comment by VictorVlakh** [comment]
@Jaycyn  Thank you very match, it was really typo that for some reason still download real but with this warning :)

**Comment by nerzh** [comment]
@Jaycyn thanks 👍
