### ISSUE TITLE
与GTSDK同时用pod导入之后，Realm启动崩溃    在xcode15.3

### ISSUE THREAD

**Issue by lizp-peng** [realm/realm-swift#8541]
### How frequently does the bug occur?

Always

### Description

与GTSDK同时用pod导入之后，Realm启动崩溃    
在xcode15.3 ios系统17以下不管真机还是模拟器都会崩溃，17系统以上则不会崩溃

在xcode14.3.1则不会崩溃

### Can you reproduce the bug?

Always

### Version

10.48

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macbook air m2 14.4.1 (23E224) 

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by lizp-peng** [comment]
![Xnip2024-04-10_15-44-58](https://github.com/realm/realm-swift/assets/79796126/e63ef71d-fcd0-44d1-ac01-ba2bb0212b6d)
![Xnip2024-04-10_15-45-05](https://github.com/realm/realm-swift/assets/79796126/3c7dbd7e-f66f-421a-aecb-6656671d3935)

**Comment by lizp-peng** [comment]
[Uploading MyTest.zip…]()

**Comment by lizp-peng** [comment]
[MyTest.zip](https://github.com/realm/realm-swift/files/14929262/MyTest.zip)

**Comment by nirinchev** [comment]
I'm sorry, but we can only provide support in English. That being said, the stacktrace appears similar to the one in https://github.com/realm/realm-swift/issues/8397, so you could try applying the workaround proposed in this comment: https://github.com/realm/realm-swift/issues/8397#issuecomment-2024047065.
