### ISSUE TITLE
update sdk version

### ISSUE THREAD

**Issue by ml2720101** [realm/realm-swift#8545]
### Problem

I want tp update sdk version 4.1.1 to 10.46.0 , need  migrate ?

### How important is this improvement for you?

-- select --

### Feature would mainly be used with

-- select --

**Comment by nirinchev** [comment]
I'm not sure what you're asking here, but yes - upgrading from 4.1.1 to 10.46.0 will involve migrating the file format in a non-backwards-compatible way - that is, once you upgrade a file, you won't be able to open it with an old Realm version. It will also involve addressing any breaking changes, which you can find the in the changelog.
