### ISSUE TITLE
Add Apple Privacy Manifests to a 10.48.2 Release

### ISSUE THREAD

**Issue by laideybug** [realm/realm-swift#8558]
### Problem

The most recent fixes to Realm's privacy manifests were made in the 10.49.2 release. However, 10.49.0 contains breaking changes that drop support for opening pre-v5.0.0 Realm files. As we are on an older version of the SDK there simply isn't enough time between now and the May 1st deadline to upgrade to 10.48.1, release to all users, and then upgrade to 10.49.2. 

### Solution

Please release a patch to 10.48.1 that includes the privacy manifest fixes that were shipped in 10.49.2.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by tgoyne** [comment]
I'm currently under the impression that the privacy manifest in 10.48.1 is valid for everything except SPM, and I was hoping to get some sort of confirmation that the changes in 10.49.2 have actually fixed it before backporting.

**Comment by tgoyne** [comment]
v10.48.2 is now tagged with the changes to Package.swift that were required to get a test app to stop producing privacy manifest warnings. Note that it'll also require changes in your app configuration - you'll have to set RealmSwift to "Embed & Sign" so that it's built as a dynamic framework, as it turned out that how Xcode builds static SPM targets is incompatible with bundled privacy manifests.

**Comment by SESA762550** [comment]
@tgoyne  I am trying to install versions 10.48.2 through Cocoapods but getting below error
[!] CocoaPods could not find compatible versions for pod "RealmSwift":
In Podfile:
RealmSwift (= 10.48.2)

None of your spec sources contain a spec satisfying the dependency: RealmSwift (= 10.48.2).

You have either:
mistyped the name or version.
not added the source repo that hosts the Podspec to your Podfile.

Please help me out here as i am really struggling to update the Realm with the latest Privacy Manifest Changes. I can't use version 10.49 as i have a production app which is using older Realm DB version (Realm version - 3.21)

**Comment by nirinchev** [comment]
@SESA762550 please refrain from commenting on multiple closed issues as that's generating work on our end that we could instead spend trying to solve your problem. I've responded in the other thread, but for visibility, 10.48.2 was tagged for SPM users, while our understanding is that 10.48.1 should work just fine for Cocoapods/Carthage users.

**Comment by SESA762550** [comment]
@nirinchev Thanks for the quick support, will stick to v 10.48.1 for now and will raise a new ticket if the App is rejected by Apple.
