### ISSUE TITLE
Realm Corruption Following Client Resets Due to Permission/Role Changes on Server

### ISSUE THREAD

**Issue by divan84** [realm/realm-swift#8559]
### How frequently does the bug occur?

Sometimes

### Description

We are experiencing corruptions of Realm databases following client resets triggered by permission/role changes on the server. This issue is not reliably reproducible, and unfortunately, we do not have logs to provide more insight. We only have the incorrect Realm files, which we have examined using Realm Studio.

It is suspected that this issue may arise when the client undergoes multiple client resets in quick succession.

It appears there may be flaws in the client reset logic that need to be addressed!

### Can you reproduce the bug?

No

### Reproduction Steps

Roughly speaking, our scenario is as follows
-  We manage SyncPermissions via CustomUser data. Any change in this data typically triggers a client reset.
-  We handle projects. When a project is added, a Server-Trigger adds a Managed-Team object to the project. This change also modificats our Permission-Properties to the CustomUser data.
-  A client reset occurs, and usually, everything on the client side appears as it should. However, when a project is deleted, another trigger modifies the CustomUser data changing permissions again, leading to another client reset.

Due to the above workflow, situations may arise where multiple client resets occur in quick succession due to permission/role changes on the server.

However, in some cases, the following issues have been observed:
-  The ManagedTeam object, which should be added to the Project object by the server trigger, is missing after the client reset.
- Lists containing the Project object, or Lists that are included in the project, display incorrect behavior: contents appear duplicated and incorrectly structured (In Realm Studio the List-Elements are duplicated but share the same index(!)) When the Realm is opened in Realm Studio, it seems that identical objects appear duplicated. (Screenshot from RealmStudio attached)

<img width="493" alt="Realm-Studio1" src="https://github.com/realm/realm-swift/assets/97874917/82e4afdf-2c13-4f19-869b-8612f256ede9">
<img width="924" alt="Realm-Studio2" src="https://github.com/realm/realm-swift/assets/97874917/7d0cf56d-6268-4541-8713-6e1fcd9da9f5">
<img width="1065" alt="Realm-Studio3" src="https://github.com/realm/realm-swift/assets/97874917/65724593-7024-40be-9a54-d1f9345fc7ca">

### Version

<= 10.49.1

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

macOS

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by Jaycyn** [comment]
That's certainly an odd issue. Two questions

When you examine the data on the server using the Console, is it also duplicated?

Have you examined the data with something other than Realm Studio? e.g. craft up a quick app to read in the local data and output to console?  Then compare that to what's shown in Realm Studio. It would eliminate something funky going on with Realm Studio (which I doubt)

**Comment by divan84** [comment]
The problem was also synced and could therefore also be seen on the server.

We also saw the problems in our Realm Swift App - that's when we realized that something must be wrong.

**Comment by nirinchev** [comment]
Hey @divan84, since this is a sync issue that may require that the team investigates the sync history as well as analyze the server logs, can you please file a support ticket here: http://support.mongodb.com/? The realm-swift repo is primarily used to track bugs with the Realm Swift SDK and engineers working on this project don't have the access necessary to debug server-side problems.

**Comment by divan84** [comment]
We will contact the support! Thanks!
