### ISSUE TITLE
Updating RealmSwift to latest version doesn't update realm-core to the latest

### ISSUE THREAD

**Issue by StanleyLubrick** [realm/realm-swift#8568]
### How frequently does the bug occur?

Always

### Description

I'm using RealmSwift 10.49.3 but the version of realm-core is 14.5.2 and doesn't update to the latest.
Do you know by anychance how to do it ? I'm using SPM.

Otherwise I'm still having this bug (which seem to have been fixed in realm-core 14.6.0) :
 
Optional(file:///Users/XXXXXX/Library/Developer/CoreSimulator/Devices/09732132-EB09-4347-A768-B9BD4B3BD218/data/Containers/Data/Application/8DB767D0-69F9-41DE-AD37-2C1894C358F2/Documents/default.realm)
file:///Users/XXXXXX/Library/Developer/CoreSimulator/Devices/09732132-EB09-4347-A768-B9BD4B3BD218/data/Containers/Data/Application/8DB767D0-69F9-41DE-AD37-2C1894C358F2/Documents/
/Users/XXXXXX/Library/Developer/Xcode/DerivedData/DroneApp-athxujldxmwwvqecqojsddtdpqhw/SourcePackages/checkouts/realm-core/src/realm/util/encrypted_file_mapping.cpp:1028: [realm-core-14.5.2] Assertion failed: new_size % (1ULL << m_page_shift) == 0
0 RealmSwift 0x0000000107fd59f4 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1 RealmSwift 0x0000000107fd59d4 _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 308
2 RealmSwift 0x0000000107fd58a0 _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 0
3 RealmSwift 0x0000000107f85c60 _ZN5realm4util20EncryptedFileMapping9extend_toEmm + 120
4 RealmSwift 0x0000000107f9d370 _ZN5realm4util24extend_encrypted_mappingEPNS0_20EncryptedFileMappingEPvmmm + 192
5 RealmSwift 0x0000000107f9a84c _ZN5realm4util4File7MapBase13try_extend_toEm + 324
6 RealmSwift 0x0000000107732b80 _ZN5realm4util4File3MapIcE13try_extend_toEm + 40
7 RealmSwift 0x0000000107730cfc _ZN5realm9SlabAlloc18update_reader_viewEm + 1384
8 RealmSwift 0x000000010772f824 _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigEPNS_4util13WriteObserverE + 2904
9 RealmSwift 0x00000001078487f4 _ZN5realm2DB4openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_9DBOptionsE + 436
10 RealmSwift 0x0000000107854818 _ZN5realm2DB6createERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_9DBOptionsE + 80
11 RealmSwift 0x0000000107a4963c _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1456
12 RealmSwift 0x0000000107a4a858 _ZN5realm5_impl16RealmCoordinator12do_get_realmEONS_11RealmConfigERNSt3__110shared_ptrINS_5RealmEEENS4_8optionalINS_9VersionIDEEERNS_4util17CheckedUniqueLockEb + 84
13 RealmSwift 0x0000000107a4a724 _ZN5realm5_impl16RealmCoordinator9get_realmENS_11RealmConfigENSt3__18optionalINS_9VersionIDEEE + 760
14 RealmSwift 0x0000000107b00f5c ZN5realm5Realm16get_shared_realmENS_11RealmConfigE + 144
15 RealmSwift 0x000000010823ef58 +[RLMRealm realmWithConfiguration:confinedTo:error:] + 940
16 RealmSwift 0x000000010823eac8 +[RLMRealm realmWithConfiguration:queue:error:] + 156
17 RealmSwift 0x000000010750037c $sSo8RLMRealmC13configuration5queueABSo0A13ConfigurationC_So012OS_dispatch_C0CSgtKcfCTO + 144
18 RealmSwift 0x00000001075b904c $s10RealmSwift0A0V13configuration5queueA2C13ConfigurationV_So012OS_dispatch_D0CSgtKcfC + 192
19 DroneApp 0x0000000100b1b780 $s8DroneApp12RealmServiceC010setupLocalC09encryptedySb_tFyyXEfU + 2588
20 DroneApp 0x0000000100b1f0ac $s8DroneApp12RealmServiceC010setupLocalC09encryptedySb_tFyyXEfU_TA + 32
21 libswiftObjectiveC.dylib 0x00000001c5040c18 $s10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 56
22 DroneApp 0x0000000100b1ad34 $s8DroneApp12RealmServiceC010setupLocalC09encryptedySb_tF + 136
23 DroneApp 0x0000000100cecc00 $s8DroneApp0B8DelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtF + 464
24 DroneApp 0x0000000100ced314 $s8DroneApp0B8DelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFTo + 196
25 UIKitCore 0x00000001853e4a40 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 312
26 UIKitCore 0x00000001853e5ea0 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 2788
27 UIKitCore 0x00000001853ea9e8 -[UIApplication _runWithMainScene:transitionContext:completion:] + 856
28 UIKitCore 0x0000000184a8a8ec -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 148
29 UIKitCore 0x00000001853e7ccc -[UIApplication _compellApplicationLaunchToCompleteUnconditionally] + 44
30 UIKitCore 0x00000001853e801c -[UIApplication _run] + 832
31 UIKitCore 0x00000001853ebcc8 UIApplicationMain + 124
32 DroneApp 0x0000000100ced7bc main + 64
33 dyld 0x0000000102605544 start_sim + 20
34 ??? 0x0000000101ff60e0 0x0 + 4328480992
35 ??? 0xd027800000000000 0x0 + 14999097821469081600
!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose
/Users/XXXXXX/Library/Developer/Xcode/DerivedData/DroneApp-athxujldxmwwvqecqojsddtdpqhw/SourcePackages/checkouts/realm-core/src/realm/util/encrypted_file_mapping.cpp:1028: [realm-core-14.5.2] Assertion failed: new_size % (1ULL << m_page_shift) == 0
0 RealmSwift 0x0000000107fd59f4 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1 RealmSwift 0x0000000107fd59d4 _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 308
2 RealmSwift 0x0000000107fd58a0 _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 0
3 RealmSwift 0x0000000107f85c60 _ZN5realm4util20EncryptedFileMapping9extend_toEmm + 120
4 RealmSwift 0x0000000107f9d370 _ZN5realm4util24extend_encrypted_mappingEPNS0_20EncryptedFileMappingEPvmmm + 192
5 RealmSwift 0x0000000107f9a84c _ZN5realm4util4File7MapBase13try_extend_toEm + 324
6 RealmSwift 0x0000000107732b80 _ZN5realm4util4File3MapIcE13try_extend_toEm + 40
7 RealmSwift 0x0000000107730cfc _ZN5realm9SlabAlloc18update_reader_viewEm + 1384
8 RealmSwift 0x000000010772f824 _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigEPNS_4util13WriteObserverE + 2904
9 RealmSwift 0x00000001078487f4 _ZN5realm2DB4openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_9DBOptionsE + 436
10 RealmSwift 0x0000000107854818 _ZN5realm2DB6createERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_9DBOptionsE + 80
11 RealmSwift 0x0000000107a4963c _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1456
12 RealmSwift 0x0000000107a4a858 _ZN5realm5_impl16RealmCoordinator12do_get_realmEONS_11RealmConfigERNSt3__110shared_ptrINS_5RealmEEENS4_8optionalINS_9VersionIDEEERNS_4util17CheckedUniqueLockEb + 84
13 RealmSwift 0x0000000107a4a724 _ZN5realm5_impl16RealmCoordinator9get_realmENS_11RealmConfigENSt3__18optionalINS_9VersionIDEEE + 760
14 RealmSwift 0x0000000107b00f5c ZN5realm5Realm16get_shared_realmENS_11RealmConfigE + 144
15 RealmSwift 0x000000010823ef58 +[RLMRealm realmWithConfiguration:confinedTo:error:] + 940
16 RealmSwift 0x000000010823eac8 +[RLMRealm realmWithConfiguration:queue:error:] + 156
17 RealmSwift 0x000000010750037c $sSo8RLMRealmC13configuration5queueABSo0A13ConfigurationC_So012OS_dispatch_C0CSgtKcfCTO + 144
18 RealmSwift 0x00000001075b904c $s10RealmSwift0A0V13configuration5queueA2C13ConfigurationV_So012OS_dispatch_D0CSgtKcfC + 192
19 DroneApp 0x0000000100b1b780 $s8DroneApp12RealmServiceC010setupLocalC09encryptedySb_tFyyXEfU + 2588
20 DroneApp 0x0000000100b1f0ac $s8DroneApp12RealmServiceC010setupLocalC09encryptedySb_tFyyXEfU_TA + 32
21 libswiftObjectiveC.dylib 0x00000001c5040c18 $s10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 56
22 DroneApp 0x0000000100b1ad34 $s8DroneApp12RealmServiceC010setupLocalC09encryptedySb_tF + 136
23 DroneApp 0x0000000100cecc00 $s8DroneApp0B8DelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtF + 464
24 DroneApp 0x0000000100ced314 $s8DroneApp0B8DelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFTo + 196
25 UIKitCore 0x00000001853e4a40 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 312
26 UIKitCore 0x00000001853e5ea0 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 2788
27 UIKitCore 0x00000001853ea9e8 -[UIApplication _runWithMainScene:transitionContext:completion:] + 856
28 UIKitCore 0x0000000184a8a8ec -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 148
29 UIKitCore 0x00000001853e7ccc -[UIApplication _compellApplicationLaunchToCompleteUnconditionally] + 44
30 UIKitCore 0x00000001853e801c -[UIApplication _run] + 832
31 UIKitCore 0x00000001853ebcc8 UIApplicationMain + 124
32 DroneApp 0x0000000100ced7bc main + 64
33 dyld 0x0000000102605544 start_sim + 20
34 ??? 0x0000000101ff60e0 0x0 + 4328480992
35 ??? 0xd027800000000000 0x0 + 14999097821469081600
!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose

### Can you reproduce the bug?

Always

### Version

15.3

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

MacOs 14.4.1

### Build environment

Xcode version: 15.3
Dependency manager and version: ...
Realm 10.49.3
RealmDatabase : 14.5.2

**Comment by nirinchev** [comment]
Realm Swift 10.49.3 hasn't updated to the latest version of Core. We have another release planned that will pull that in.
