### ISSUE TITLE
skipping cache due to an error: https://github.com/realm/realm-swift: The repository could not be found. Make sure a valid repository exists at the specified location and try again.

### ISSUE THREAD

**Issue by itamargilvybe** [realm/realm-swift#8574]
### How frequently does the bug occur?

-- select --

### Description

After adding the Realm Swift package in XCode's Package Manager - I get a warning skipping cache due to an error: https://github.com/realm/realm-swift: The repository could not be found. Make sure a valid repository exists at the specified location and try again.

### Stacktrace & log output

```shell
skipping cache due to an error: https://github.com/realm/realm-swift: The repository could not be found. Make sure a valid repository exists at the specified location and try again.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Remove Realm package
2. Add the package again
3. The error will show up in the Issue Navigator

### Version

c04db3248711a67cbc7eb0b242a3454cdac57261

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.0

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by nirinchev** [comment]
This repository clearly exists as evidenced by us discussing this here 😄 Joking aside, is it possible you're rewriting https to ssh in your .gitconfig? [Here's an answer on SO](https://stackoverflow.com/questions/58816416/swift-package-manager-error-the-repository-could-not-be-found) that describes a similar symptom as well as a few solutions for fixing it.
