### ISSUE TITLE
Error loading RealmSwift dynamic framework in macOS app

### ISSUE THREAD

**Issue by x-creates** [realm/realm-swift#8575]
**💡 UPDATE**: 2024-06-10 Try the workaround provided by @zhanswift below https://github.com/realm/realm-swift/issues/8575#issuecomment-2157044853 

### How frequently does the bug occur?

Always

### Description

I'm encountering an issue loading the RealmSwift framework in my macOS app, and I'm hoping someone can provide some guidance.

I'm using Xcode 15.3 and have the RealmSwift 10.50.0 framework installed as a dependency in my project. The error suggests that the framework is not being correctly referenced or found during runtime. Build can be done successfully, though.

The error complains that the file '/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/RealmSwift.framework/Versions/A/RealmSwift' does not exist. It also states that the code signature for 'RealmSwift.framework/Versions/A/RealmSwift' (with the identifier <68E4E55B-1392-3E7B-B51C-B2FE88455CD8>) is not valid for use in the process, as the mapping process and the mapped file have different Team IDs.

**I have ensured that I only included RealmSwift and made it an embedded and signed option.**

Has anyone else encountered this issue before? If so, what steps did you take to resolve it? Any guidance would be greatly appreciated.

I have attached the sample project `Foo.zip`. You can download it from this link: [Foo.zip(https://github.com/realm/realm-swift/files/15208298/Foo.zip). I can confirm that downgrading the library to version 10.49.2 solved the issue.

### Stacktrace & log output

```shell
dyld[11169]: Library not loaded: @rpath/RealmSwift.framework/Versions/A/RealmSwift
  Referenced from: <59A4BF84-B08D-338E-8F6D-83EDC110D43D> /Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/Foo
  Reason: 
    tried: '/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/RealmSwift.framework/Versions/A/RealmSwift' (no such file),
    '/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/PackageFrameworks/RealmSwift.framework/Versions/A/RealmSwift' (code signature in <68E4E55B-1392-3E7B-B51C-B2FE88455CD8> '/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/PackageFrameworks/RealmSwift.framework/Versions/A/RealmSwift' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs),
    '/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/PackageFrameworks/RealmSwift.framework/Versions/A/RealmSwift' (code signature in <68E4E55B-1392-3E7B-B51C-B2FE88455CD8> '/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/PackageFrameworks/RealmSwift.framework/Versions/A/RealmSwift' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs),
    '/System/Volumes/Preboot/Cryptexes/OS/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/PackageFrameworks/RealmSwift.framework/Versions/A/RealmSwift' (no such file),
    '/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/PackageFrameworks/RealmSwift.framework/Versions/A/RealmSwift' (code signature in <68E4E55B-1392-3E7B-B51C-B2FE88455CD8> '/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/PackageFrameworks/RealmSwift.framework/Versions/A/RealmSwift' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs),
    '/System/Volumes/Preboot/Cryptexes/OS/Users/*/Library/Developer/Xcode/DerivedData/Foo-*/Build/Products/Debug/PackageFrameworks/RealmSwift.framework/Versions/A/RealmSwift' (no such file)

Logging Error: 
  Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
```

The issue at https://github.com/realm/realm-swift/issues/8571 appears to be a similar problem.

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Create a new macOS command-line project.
2. Follow the instructions at https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/install/ to install Realm.
3. Enable Realm as a dynamic framework, embed it, and sign it.
4. Import RealmSwift in the main.swift file.
5. Run the app.

### Version

10.50.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

14.4

### Build environment

Xcode version: 15.3
Dependency manager and version: ...

![2024050407042Ibok6jk](https://github.com/realm/realm-swift/assets/64649350/64842357-107e-4413-9686-3a09d6529fb4)
![202405040704xXdBXUt5](https://github.com/realm/realm-swift/assets/64649350/fa658c55-55ac-4ef0-a09f-a907dbe5bac9)

**Comment by anton-plebanovich** [comment]
I have the same issue. Though my dependency graph might be more complex the problem is the same. I also tried to use `Archive` but it did not help.

**Comment by anton-plebanovich** [comment]
This answer was helpful https://stackoverflow.com/a/73844861/4124265

I had to manually sign all frameworks in the `PackageFrameworks` directory to be able to run the executable successfully. This looks like an Xcode issue or I may be missing a proper build configuration to resign frameworks automatically. I faced the issue initially using `None` team and `Sign to Run Locally` option but even with other team and options it does not seem to work

**Comment by anton-plebanovich** [comment]
I had to add post-build action as a workaround fix with this script:
```
# Resigning as a workaround for https://github.com/realm/realm-swift/issues/8575

# Framework resign
for framework_path in "${BUILT_PRODUCTS_DIR}/PackageFrameworks/"*/; do
  framework_dir=$(basename "${framework_path}")
  framework_name="${framework_dir%.*}"
  framework_binary_path=`find "${framework_path}" -type f -name "${framework_name}"`
  echo "Fixing code sign issue for '${framework_name}' framework: ${framework_binary_path}"
  codesign -f -s - "${framework_binary_path}"
done

# Executable resign
codesign -f -s - "${CODESIGNING_FOLDER_PATH}"
```

**Comment by ukushu** [comment]
Downgrade to 10.49.0 resolved issue.

So this is not XCode related issue. This is issue of RealmSwift library.

**Comment by anton-plebanovich** [comment]
Well, they switched to library `type: .dynamic` in the SPM which was not used previously. This mode might be buggy from the Apple side but in any case, it has to be investigated on the RealmSwift side first. There could be a workaround or a solution.

**Comment by zhanswift** [comment]
I've cleaned the DerivedData folder and noticed that the RealmSwift was not embedded. 
After I switched to **Embed & Sign** it is working now.
<img width="605" alt="Screenshot_Realm" src="https://github.com/realm/realm-swift/assets/16617536/9703b90d-ea9c-40b0-ad8b-98d2c2f077d7">

**Comment by zhanswift** [comment]
Sure.
Go to the **Your Project file -> Your app target -> General - > Frameworks, Libraries, and Embedded Content** and review this list.
<img width="1200" alt="Screenshot_Realm2" src="https://github.com/realm/realm-swift/assets/16617536/d759bdf7-781c-4100-b3d4-cc1101fc8132">

**Comment by Jeanno** [comment]
> Well, they switched to library type: .dynamic in the SPM which was not used previously.

Is the option to statically link the library gone? Many "solutions" have the instruction to "embed and sign" RealmSwift but it's not what I want.
