### ISSUE TITLE
terminating due to uncaught exception of type realm::util::DecryptionFailed: Decryption failed: 'unable to decrypt after 0 seconds (retry_count=2, from=iv1 == 0, size=16384)

### ISSUE THREAD

**Issue by sanjeevi-mobileteam** [realm/realm-swift#8578]
### How frequently does the bug occur?

Always

### Description

I have used local realm database for my swift iOS application. For the very first time i create the realm database after execute the code then, copy the empty database and i did the upload data using CSV for reduce the loading of bulk data. Then i insert the default.realm file into xcode project. After i execute the project, i copy the local bundle realm database data into runtime created db. so that i can easy to do bulk insertion. Then i sync the latest data only from backend. Before that it works well. but after update the xcode and realm studio. it will show the error i mentioned in title. every time when new data try to insert into the db i got the error. And the code works without any issue in iOS Simulator only error happens in actual device.

### Stacktrace & log output

```shell
libc++abi: terminating due to uncaught exception of type realm::util::DecryptionFailed: Decryption failed: 'unable to decrypt after 0 seconds (retry_count=2, from=iv1 == 0, size=16384)'
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Follow the steps we provide in the description
<img width="845" alt="Screenshot 2024-05-07 at 11 18 10 AM" src="https://github.com/realm/realm-swift/assets/149563275/dc584f22-57b1-4ff3-9523-1837c40ae445">

And the code works without any issue in iOS Simulator only error happens in actual device.

### Version

10.41.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 17

### Build environment

Xcode version: 15.0.1
Realm Studio Versions: 15.0.1

**Comment by nirinchev** [comment]
This was fixed with the latest version of the SDK. If you still experience the issue once you upgrade, feel free to reopen this ticket.
