### ISSUE TITLE
Realm Swift 10.50.0 fails to build

### ISSUE THREAD

**Issue by nrbrook** [realm/realm-swift#8580]
### How frequently does the bug occur?

Always

### Description

Targeting an iPad (arm64) running iOS 17.4.
Realm 10.49.2: Builds fine
Realm 10.50.0: 
```
Undefined symbol: ___ubsan_handle_add_overflow

Undefined symbol: ___ubsan_handle_alignment_assumption

Undefined symbol: ___ubsan_handle_builtin_unreachable

Undefined symbol: ___ubsan_handle_divrem_overflow

Undefined symbol: ___ubsan_handle_float_cast_overflow

Undefined symbol: ___ubsan_handle_load_invalid_value

Undefined symbol: ___ubsan_handle_mul_overflow

Undefined symbol: ___ubsan_handle_negate_overflow

Undefined symbol: ___ubsan_handle_nonnull_arg

Undefined symbol: ___ubsan_handle_nonnull_return_v1

Undefined symbol: ___ubsan_handle_out_of_bounds

Undefined symbol: ___ubsan_handle_pointer_overflow

Undefined symbol: ___ubsan_handle_shift_out_of_bounds

Undefined symbol: ___ubsan_handle_sub_overflow

Undefined symbol: ___ubsan_handle_type_mismatch_v1
```
<img width="551" alt="Screenshot 2024-05-07 at 15 42 07" src="https://github.com/realm/realm-swift/assets/1141167/5ad22982-6bf7-443a-a465-acb6faaed2df">

### Can you reproduce the bug?

Always

### Version

10.50.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Xcode 15.3, iPad, iOS 17.4

### Build environment

Xcode version: Xcode 15.3
Dependency manager and version: SwiftPM

**Comment by nrbrook** [comment]
It isn't possible:
<img width="430" alt="Screenshot 2024-05-07 at 16 18 10" src="https://github.com/realm/realm-swift/assets/1141167/cb83d862-6f34-4bd0-96f5-f342a2dfb9aa">

**Comment by nirinchev** [comment]
Based on [this SO answer](https://stackoverflow.com/questions/74226342/build-error-after-disabling-the-address-sanitizer-in-xcode) you can do that by editing the .xcscheme file in your .xcodeproj.
