### ISSUE TITLE
Realm 10.50.0 Cocoapods compile warning

### ISSUE THREAD

**Issue by bb-git** [realm/realm-swift#8582]
### How frequently does the bug occur?

Always

### Description

I don't know if this is something crucial, but we see this warning when using cocoapods, but it's not appearing when using SPM. Any idea, why this is happening?

Showing Recent Issues
/Pods/RealmSwift/RealmSwift/Realm.swift:1351:23: Passing argument of non-sendable type 'RLMRealm' outside of actor-isolated context may introduce data races

### Can you reproduce the bug?

Always

### Version

10.50.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 17.4

### Build environment

Xcode version: 15.3
Dependency manager and version: Cocoapods 1.15.2

**Comment by Jaycyn** [comment]
I built a clean Realm project, following [installation guide for Cocoapods](https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/install/#installation) exactly and received the exact same message

![non-sendable](https://github.com/realm/realm-swift/assets/19558530/16322216-dac2-49b2-a552-0875eae97f7c)

I also noted a another issue with this clean podfile install. While tracking it down, things suddenly started working and the `non-sendable type 'RLMRealm' outside of actor-isolated context may introduce data races` error went away. They appeared to be unrelated but adding this just in case

Sandboxing: Sandbox: rsync.samba(code) deny(1) file-read-data... some path

![Sandboxing](https://github.com/realm/realm-swift/assets/19558530/31060b26-c550-47f6-bec1-e794b25fa8f5)

To fix: in Build Settings, had to set User Script Sandboxing to NO

![UserScriptSandboxing](https://github.com/realm/realm-swift/assets/19558530/3d180626-b744-4f09-8d32-11a0b591e436)

then in Signing and Capabilities, had to check Incoming and Outgoing in the Network settings. I usually just removed that entirely but that didn't work, but this did.

![Network](https://github.com/realm/realm-swift/assets/19558530/e5fa0e22-c3f5-41b7-912c-cb991b171ba2)

Once I made those changes, all of the errors went away.

Again - a 100% totally clean brand new Realm Test project with no other code, following the installation guide.

Realm 10.50
XCode 15.3
Cocoapods 1.15.2

and my podfile

```
project 'Realm Test'
target 'Realm Test' do
  use_frameworks!
  platform :osx, '14.0'
  pod 'RealmSwift', '~>10'
end
```

I have no idea what the relationship is between the error but at least I am back to coding.

**Comment by tgoyne** [comment]
This is an expected warning when building Realm with sendability checking enabled which we should be able to fix in Swift 6 but cannot in Swift 5.

**Comment by Jaycyn** [comment]
@tgoyne Cool. Thanks for the update.

Any idea why the project I just created, which exhibited the same issue, suddenly stopped flagging with the error after I made the changes noted above?

**Comment by bb-git** [comment]
@tgoyne so just to be clear, it's all fine to use it like this?
or are any changes necessary?
Thanks

**Comment by nirinchev** [comment]
it's fine to use it like this.
