### ISSUE TITLE
Xcode15 Realm crash

### ISSUE THREAD

**Issue by MaQun666** [realm/realm-swift#8583]
### How frequently does the bug occur?

Always

### Description

Xcode15 crashes, but Xcode14 does not

Realm version：4.3.2

### Stacktrace & log output

```shell
Crashed: History
0  libobjc.A.dylib                0x1a0a0 class_getSuperclass + 4
1  Realm                          0x73c4c RLMIsObjectSubclass + 250 (RLMObject.mm:250)
2  Realm                          0xe6d10 RLMRegisterClassLocalNames(objc_class**, unsigned long) + 105 (RLMSchema.mm:105)
3  Realm                          0xe73e8 +[RLMSchema sharedSchema] + 506 (unique_ptr.h:506)
4  Realm                          0xdc218 +[RLMRealm realmWithConfiguration:error:] + 492 (RLMRealm.mm:492)
5  RealmSwift                     0x15cc8 @nonobjc RLMRealm.__allocating_init(configuration:) + 84 (<compiler-generated>:84)
6  RealmSwift                     0x15c68 Realm.init() + 67 (Realm.swift:67)
```

### Can you reproduce the bug?

No

### Reproduction Steps

do {
            let realm = try getRealm()
            let results:Results<RouteItem> =
                realm.objects(RouteItem.self)
                    .filter(// do something);

            if results.isEmpty {
                Logger.debug(" --> no data to delete")
                return
            }

            Logger.debug("unmanaged route data")
            try realm.write {
                realm.delete(results)
            }

        } catch {
            Logger.error("failed to delete unmanaged device data => Error: \(error)")
        }

### Version

4.3.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Xcode:15.3  Realm:4.3.2 iPhone 12pro OS:iOS17.4.1

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by nirinchev** [comment]
4.3.2 is 4 years old and we no longer support it. That being said, it looks similar to https://github.com/realm/realm-swift/issues/7275 where the workaround is to explicitly set the `objectClasses` on the Realm configuration to avoid having Realm inspect all classes in your application.

**Comment by MaQun666** [comment]
@nirinchev  But some people don't happen。Add  the “-Wl,-ld_classic” in OTHER_LDFLAGS？or Realm is fixed when upgraded to the latest version？
What should I do？
