### ISSUE TITLE
Partition based Sync not supported in new Apps

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-swift#8592]
### How frequently does the bug occur?

Always

### Description

I am trying to create a new cluster and App to load data from an existing realm database but it seems it is no longer possible to create a partition based sync app.

Can someone explain how to load a local realm database that is a backup from an existing partition based sync app into one of the new flexible sync apps.

There seems to be a very long explanation for how to migrate and existing app from partition based to flexible sync but that doesn't help because I need to load the new app from a javascript client code that reads the old database and then uses that data to load the new flexible sync database.

Presumably it should just be a matter of connecting to the new App by opening the Realm() with flexible sync.  Does that mean that all the existing clients will need to be upgraded to open the app with flexible sync and not partition based sync ?

Pretty confusing the explanations in documentation particularly because it says that no client side code change is required.

### Can you reproduce the bug?

Always

### Reproduction Steps

Existing javascript client code opens the realm and loads data but sync fails.  No errors appear on the client side code.

Assuming the database can be loaded into the new flexible sync realm what if any Swift client side code changes need to be made to connect to and sync with the flexible sync app.

Documentation seems to indicate that no client side code changes are required.

You assistance will be much appreciated - thanks

### Version

JS 11.10.2 Swift 10.42.4

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

macOS Sonoma

### Build environment

Xcode version: 15.4
Dependency manager and version: SPM

**Comment by duncangroenewald** [comment]
@tgoyne - Thomas not sure if you see these tagged comments - but if you do I would appreciate it if you could help solve loading a local realm file into a flexible sync realm.  The javascript program supplied originally by yourselves appears to fail with an error and it seems it might be related to needing to create subscriptions before writing to the realm.  

Given we sync the entire database we presumably need to create subscriptions for all objects - but when doing so the javascript program throws an exception 

`Error, objectType must be of type 'string', got ([object Object])`

**Comment by nirinchev** [comment]
@duncangroenewald can you file a support ticket at http://support.mongodb.com and the team will assist you there. They could enable creation of partition-sync apps for your account or offer other alternatives for a seamless migration.

**Comment by duncangroenewald** [comment]
I have raised a ticket with them but my experience is they end up referring to some of the realm folks here who seem to have the detailed technical expertise.

We need to do a schema update so may as well migrate to flexible sync - but we sync the entire database to all clients so flexible sync seems overkill.  Presumably our clients would just need to subscribe to all objects and things would function much like partitioned sync.

**Comment by duncangroenewald** [comment]
OK - my bad. I was not using a string to define the class/object in the subs.add() function !!!
