### ISSUE TITLE
Update packaging for Xcode 15.4

### ISSUE THREAD

**Issue by ilendemli** [realm/realm-swift#8593]
### How frequently does the bug occur?

Always

### Description

Xcode 15.4 has been released but realm-swift has not been updated to use it yet. We are using the [RealmBinary](https://github.com/RomanEsin/RealmBinary/tree/v10.45.2) package to improve build times. This causes the builds to fail with the following error: `cannot load module 'RealmSwift' built with SDK 'iphoneos17.4' when using SDK 'iphoneos17.5'`

### Can you reproduce the bug?

Always

### Version

10.50.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

Xcode 15.4

**Comment by mhty19891833** [comment]
Is there a solution?

**Comment by imamat0ff** [comment]
I have also faced same issue, are there any updates ?, I am using Realm.xcframework, on custom framework to avoid crashes mentioned [7989](https://github.com/realm/realm-swift/issues/7989) and [8218](https://github.com/realm/realm-swift/issues/8218).

**Comment by nirinchev** [comment]
This is fixed in https://github.com/realm/realm-swift/pull/8598
