### ISSUE TITLE
AsyncOpen progress does not reflect the bootstrap change sets 

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-swift#8595]
### How frequently does the bug occur?

-- select --

### Description

   The function below has been used successfully on partition based synced realms and correctly shows the sync progress when the client is bootstrapped.

However when used with a flexible synced realm this code more or less immediately returns 100% but then the bootstrap change sets haven't yet been downloaded and integrated.

How can we get the progress notifications for the bootstrap process to correctly show the initialisation progress to the app users ?

```
    func asyncRealmI(completion: @escaping (Realm?, Error?)->Void)->Realm.AsyncOpenTask {
        
        self.setSyncErrorHandler()
        
        let task = Realm.asyncOpen(configuration: self.realmSyncConfig, callbackQueue: .main) { result in
            
            switch result {
            case .failure(let error):
                DebugLog("MongoRealm asyncOpen failed: \(error.localizedDescription)")
                completion(nil, error)
                
            case .success(let realm):
                DebugLog("MongoRealm asyncOpen successfull")
                completion(realm, nil)
                return
                
            }
        }
        
        task.addProgressNotification(block: { syncProgress in
            DispatchQueue.main.async {
                let prog = syncProgress.fractionTransferred * 100.0
                DebugLog("Sync: \(prog.formatted0)%")
                GlobalVars.shared.downloadSyncProgress = prog
            }
        })
        
        return task
    }
```

### Can you reproduce the bug?

Always

### Reproduction Steps

See above function to asyncOpen a flexible synced realm.

### Version

10.42.4

### What Atlas Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

macOS Sonoma

### Build environment

Xcode version: 15.4
Dependency manager and version: Realm/RealmSwift frameworks built from source

**Comment by nirinchev** [comment]
You need to upgrade to latest Realm Swift to get correct progress notifications when using flexible sync.
