### ISSUE TITLE
Opening Realm files of format version 23 is not supported by this version of Realm (10.25.2)

### ISSUE THREAD

**Issue by syquandev** [realm/realm-swift#8596]
### How frequently does the bug occur?

Sometimes

### Description

I'm encountering an issue with my iOS app that uses Realm for local data storage. Recently, my app started throwing the following error: "Opening Realm files of format version 23 is not supported by this version of Realm"

Here are some details about my setup: Realm Swift version: 10.25.2 iOS version: 84%iOS 17 ; 12% iOS 16; 3% iOS 15 and Other (2) Xcode version: 15.0 image description: https://i.sstatic.net/bZYBEn0U.png

Context: I have not updated the Realm Swift library recently. The app has been using version 10.25.2 for a while. After updating my app to a new version (but without changing the Realm library), some users reported this issue. I verified that The database has no changes and I didn't open the Realm files with any other tools like Realm Studio that might have upgraded the file format.

**My Questions:** How could the Realm file format version have been upgraded to 23 without updating the Realm library? Are there any known issues or scenarios where this could happen? Any insights or suggestions would be greatly appreciated. Thank you!

### Can you reproduce the bug?

Sometimes

### Version

10.25.2

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

XCode 15.0

### Build environment

Xcode version: 15.0
Dependency manager and version: Realm-swift: 10.25.2

**Comment by ChauVietThach** [comment]
Can someone help me?
Is it possible that the error message from Realm is being used for a different issue? I can't find any reason why my app would automatically upgrade the file to version 23.

**Comment by nirinchev** [comment]
It's not possible for the Realm file to accidentally have been updated. There are 3 ways I can see this happening:
1. You released an app update that uses a newer Realm version, then downgraded.
2. The user opened the Realm file using Studio or a different tool that upgraded it.
3. You bundled a Realm file that was created with a newer version of Realm in your app.
