### ISSUE TITLE
Crash on Notification Service Extension (RESOURCE_TYPE_MEMORY)

### ISSUE THREAD

**Issue by devssun** [realm/realm-swift#8606]
### How frequently does the bug occur?

Always

### Description

My Test Information
iPhone 11, iOS 17.5.1

In our application, we save push information at notification service extension(NSE).
I made project using Tuist. After apply Tuist, RealmSwift occured error when I called `tryRealm()` from NSE.

the error is
`Thread 2: EXC_RESOURCE (RESOURCE_TYPE_MEMORY: high watermark memory limit exceeded) (limit=24 MB)`
![스크린샷 2024-05-27 오후 5 55 57](https://github.com/realm/realm-swift/assets/16014607/0535ab6d-9922-4865-b3c7-1507ea32cb70)

stacktrace
![스크린샷 2024-05-27 오후 5 56 02](https://github.com/realm/realm-swift/assets/16014607/55a7fde7-5246-4f6d-855a-86c127cac7c4)

I don't understand what happened. please help me.

### Stacktrace & log output

```shell
Thread 2 Queue : com.apple.NSXPCConnection.user.endpoint (serial)
#5	0x0000000107a8b07c in +[RLMSchema sharedSchema] at /Library/Developer/Xcode/DerivedData/efygztealpifkhargabzepbdapti/SourcePackages/checkouts/realm-cocoa/Realm/RLMSchema.mm:262
#6	0x0000000107a64b28 in +[RLMRealm realmWithConfiguration:queue:error:] at /Library/Developer/Xcode/DerivedData/efygztealpifkhargabzepbdapti/SourcePackages/checkouts/realm-cocoa/Realm/RLMRealm.mm:465
#8	0x0000000107b2a3c4 in Realm.init(configuration:queue:) at /Library/Developer/Xcode/DerivedData/efygztealpifkhargabzepbdapti/SourcePackages/checkouts/realm-cocoa/RealmSwift/Realm.swift:92
#9	0x0000000107b2a600 in Realm.init(fileURL:) at /Library/Developer/Xcode/DerivedData/efygztealpifkhargabzepbdapti/SourcePackages/checkouts/realm-cocoa/RealmSwift/Realm.swift:106


---
Thread 2: EXC_RESOURCE (RESOURCE_TYPE_MEMORY: high watermark memory limit exceeded) (limit=24 MB)
```

### Can you reproduce the bug?

Always

### Version

10.7.4

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 17.5.1

### Build environment

Xcode version: 15.2
Dependency manager and version: SPM

**Comment by nirinchev** [comment]
Can you try to explicitly specify the `objectTypes` in your realm config? That way you can avoid the costly reflection that's needed to build the default schema.

**Comment by devssun** [comment]
I already defined. This error does not occur in projects where Tuist is not applied. Could settings in the **build settings** possibly affect this?

```
public class History: Object {
    @objc public dynamic var _id = ObjectId.generate()
    @objc public dynamic var id: String?
    @objc public dynamic var date: Date = Date()
    @objc public dynamic var read: Bool = false
    @objc public dynamic var dataString: String?
}
```

**Comment by devssun** [comment]
oops I'm sorry. I fix this issue. thank you.
