### ISSUE TITLE
Doesn't work with cocoapods

### ISSUE THREAD

**Issue by gerchicov-vg** [realm/realm-swift#8619]
### How frequently does the bug occur?

Always

### Description

Project contains RealmSwift cocoapods dependency but I can't download it.

### Can you reproduce the bug?

Always

### Reproduction Steps

Podfile:
`pod 'RealmSwift', '~>10'`
Console:
```
pod update FBSDKCoreKit
Updating local specs repositories
Analyzing dependencies
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/9/4/5/RealmSwift/10.51.0/RealmSwift.podspec.json Response: Failure when receiving data from the peer
```

### Version

10.x

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS Sonoma 14.3.1

### Build environment

Xcode version: 15.x (but it doesn't matter)
Dependency manager and version: cocoapods 1.15.2

**Comment by nirinchev** [comment]
This appears to be a CocoaPods issue - Realm doesn't have control over the CocoaPods CDNs. That url is working for me, so it could either have been a temporary glitch that's fixed now or you may have an issue with your networking setup.

**Comment by gerchicov-vg** [comment]
@nirinchev I manage multiple projects with RealmSwift and other cocoapods and this problem happened with this project only. Solved by adding into podfile:
`source 'https://cdn.cocoapods.org/'`
But again other projects don't require it.
