### ISSUE TITLE
Realm 10.51.0 not available in SPM

### ISSUE THREAD

**Issue by AF-cgi** [realm/realm-swift#8622]
### How frequently does the bug occur?

Always

### Description

It's not possible to integrate Realm 10.51.0 with SPM. The error is the following one:
`Couldn’t check out revision ‘4c4413abd0cd2221f59318f800960fe5bddc1494’`

### Can you reproduce the bug?

Always

### Reproduction Steps

Add RealmSwift via SPM and set the minimum version to 10.51.0.

### Version

10.51.0

### What Atlas Services are you using?

-- select --

### Are you using encryption?

-- select --

### Platform OS and version(s)

iOS

### Build environment

Xcode version: 15.4
Dependency manager and version: SPM / Swift 5.10

**Comment by AF-cgi** [comment]
Some update: This issue occurs if you try to update the package from 10.50.0 to 10.51.0.
I found a workaround. If you remove the package and add it again with the latest version 10.51.0 then it works fine.

**Comment by nirinchev** [comment]
Revision [4c4413abd0cd2221f59318f800960fe5bddc1494](https://github.com/realm/realm-swift/commit/4c4413abd0cd2221f59318f800960fe5bddc1494) exists in the repo and there's no obvious reason for SPM to fail to check it out. Closing this as it's likely a transient issue.
