### ISSUE TITLE
Crashing 100% when using @available(..., *) for a dynamic library in ObjC

### ISSUE THREAD

**Issue by nightfall708** [realm/realm-swift#8626]
### How frequently does the bug occur?

All the time.

### Description

My app is built from ObjC and Swift I'm supporting iOS 15.0. 
I have a class which includes WeatherKit which is only available in iOS 16.
So it looks like:

```
@available(iOS 16.0, *)
@objcMembers
class Example {
    @Published var weather: Weather?
}
```

by replacing the @Published property with a non iOS 16.0 only property, the crash is solved. So I'm stuck on how to keep my app compatible with iOS 15.0.

### Stacktrace & log output

This will 100% cause a crash when trying to initialize realm. Crashing on `RLMSchema`:
```
unsigned int numClasses;
using malloc_ptr = std::unique_ptr<__unsafe_unretained Class[], decltype(&free)>;
malloc_ptr classes(objc_copyClassList(&numClasses), &free); <<< CRASH
RLMRegisterClassLocalNames(classes.get(), numClasses);
```

I've create a repo that reproduces this: https://github.com/nightfall708/realm_crash
Make sure to run on an iOS 15.0 simulator.

### Can you reproduce the bug?

Yes, always.

### Reproduction Steps

See repo bellow

### Version

14.9.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 15.0

### Build environment

Xcode version: 15.2

**Comment by tgoyne** [comment]
You'll need to explicitly set `objectTypes` on your `Realm.Configuration` rather than relying on automatic class discovery. The obj-c runtime unfortunately does not support `@available` so using it on an obj-c type breaks objc_copyClassList.

**Comment by nightfall708** [comment]
Thank you!
