### ISSUE TITLE
After upgrading to 10.52.0 our app crashes on launch when we attempt to observe a collection

### ISSUE THREAD

**Issue by dmorgereth** [realm/realm-swift#8636]
### How frequently does the bug occur?

Always

### Description

Other than upgrading to v 10.52.0 there have been no changes to the app.  The app works fine with version 10.51.0.  In version 10.52.0 the app crashes the first time we try to observe a Realm collection (for changes)
<img width="1530" alt="Screenshot 2024-06-18 at 5 10 47 PM" src="https://github.com/realm/realm-swift/assets/91491422/eea97ba4-5126-422c-9056-bd1d1ad7ad57">

### Stacktrace & log output

```shell
See attached screen shot
```

### Can you reproduce the bug?

Always

### Version

10.52.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17.4,  Realm 10.52.0

### Build environment

Xcode version: xCode 15.3
Dependency manager and version:  Swift Package Manager

**Comment by tgoyne** [comment]
It looks like #8295 made it so that we're now exposing a frozen SectionedResults from `@ObservedSectionedResults`. You can work around this by explicitly calling `thaw()`, but we should maybe see if we can avoid this.

**Comment by MatteoGgl** [comment]
I am currently experiencing the same issue, but downgrading to `10.51.0` unfortunately does not help.
Using `@ObservedSectionedResults` works correctly; @tgoyne where and what would you `thaw()` exactly to work around the problem?

**Comment by nirinchev** [comment]
You need to call `thaw()` on the results instance before you call `.observe()` on it.
