### ISSUE TITLE
App crash for iOS 12 using 'RealmSwift', '~> 3.20.0'

### ISSUE THREAD

**Issue by rajaMusharaf** [realm/realm-swift#8638]
### How frequently does the bug occur?

Always

### Description

static void create_empty_group_when_missing(Group& group)
    {
        if (!group.m_top.is_attached())
            group.create_empty_group(); // Throws
    }
<img width="1105" alt="Screenshot 2024-06-25 at 2 51 29 PM" src="https://github.com/realm/realm-swift/assets/98593594/c20cea7c-4ffb-4011-a9a6-62c90c95a4e0">

### Stacktrace & log output

```shell
Thread 1: EXC_BAD_ACCESS (code=1, address=0x2a2d4eb968cf)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

let realm = try! Realm()

### Version

3.20.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

iOS 12.5.6

### Build environment

Xcode version: 15.0
Dependency manager and version: ...

**Comment by Jaycyn** [comment]
The bug report is a little vague as there's no Realm code involved. The crash is shown but there's no context around what that function does so that would need to be included as well. Also, based on the report, are you actually using Ream 3.20.0? Or something later? Keeping in mind that 3.20.0 will not be file compatible with later versions and you'll need to go through an upgrade/migration process to use more current versions (3.20.0 was from Oct 21 2019)

**Comment by rajaMusharaf** [comment]
@nirinchev here is the more information:
<img width="1153" alt="Screenshot 2024-06-26 at 10 50 07 AM" src="https://github.com/realm/realm-swift/assets/98593594/4fd5b251-7e89-41b5-b0d1-23b2c19e6589">
in above image i added break point. after pressing stepover in xcode it goes to 
<img width="1166" alt="Screenshot 2024-06-26 at 10 51 57 AM" src="https://github.com/realm/realm-swift/assets/98593594/397aed7e-1c33-44a3-81af-4c57c460ba0e">
with the crash.

**Comment by nirinchev** [comment]
This screenshot doesn't really give us new information - it's not obvious why creating an empty group would fail. That being said, as @Jaycyn pointed out, Realm Swift 3.20 is a very old version and we don't plan to investigate or backport fixes to it. Can you try to upgrade to the latest version and see if the issue still occurs?
