### ISSUE TITLE
Doesn't Map value type work at all?

### ISSUE THREAD

**Issue by gerchicov-vg** [realm/realm-swift#8644]
### How frequently does the bug occur?

Always

### Description

Code example
```
@objcMembers
class Obj1: Object {
    dynamic var obj2: Obj2?
}

@objcMembers
class Obj2: Object {
    dynamic var obj3: Obj3?
}

@objcMembers
class Obj3: Object {
    dynamic var val: String?
    dynamic var valMap: Map<String, String>?
}

try! realm.write {
            let obj1 = Obj1()
            obj1.obj2 = .init()
            obj1.obj2?.obj3 = .init()
            obj1.obj2?.obj3?.val = "test"
            obj1.obj2?.obj3?.valMap = .init()
            obj1.obj2?.obj3?.valMap?["testKey"] = "testValue"
            realm.add(obj1)
        }

try! RealmManager.shared.realm.write {
            let requestedObj1 = realm.objects(Obj1.self).first!
            ...
}
```

I check every value inside `requestedObj1` and see each data I've stored previously **except of** `Map` object and its values - it just becomes nil after assignment.

Possibly there are similar bugs exist but I can't found it - documentation doesn't show a concrete example of how to use `Map` and in the same time `Map` is similar to Swift's `map` for collections and sequences which make searching almost impossible.

In general are there other ways to store a dictionary in Realm?

### Can you reproduce the bug?

Always

### Version

10.46.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 15.5 (simulator)

### Build environment

Xcode version: 15.0
Dependency manager and version: cocoapods 1.15.2

**Comment by tgoyne** [comment]
`Map?` is not a supported property type, as collections must be non-optional. When using `@objc dynamic`, unsupported properties are implicitly ignored. With `@Persisted`, this would be a compilation error instead.

**Comment by gerchicov-vg** [comment]
@tgoyne when I use `@Persisted var` it crashes on start saying that I should declare this map optional. When it is optional a compiler doesn't like it:
`Generic struct 'Persisted' requires that 'Map<String, ...>' conform to '_PersistableInsideOptional'`
And I don't know how to deal with this error.

**Comment by nirinchev** [comment]
You can see an example of how map properties are defined in our tests: https://github.com/realm/realm-swift/blob/235d0034ee3b25041c708e8aa745e3eb6b334198/RealmSwift/Tests/CodableTests.swift#L252-L282.
