### ISSUE TITLE
Realm crash when accessing PersistableEnum

### ISSUE THREAD

**Issue by YoavGro** [realm/realm-swift#8651]
### How frequently does the bug occur?

Sometimes

### Description

We are seeing a huge uptick in crashes by our users. We are currently unable to replicate the issue.

```
0  Riverside                      0x16d96b0 protocol witness for static _Persistable._rlmGetProperty(_:_:) in conformance StudioRecordingSet.RecordingType + 2552184
1  Riverside                      0x16d9600 protocol witness for static _Persistable._rlmGetProperty(_:_:) in conformance StudioRecordingSet.RecordingInputType + 2552008
```

The very strange thing is that in the crashing func I see the call to get one of the `@Persisted public var` that is crashing (`recordingInputType`) but not to the other one (`recordingType`)

This is how they are defined, and the crashing func

```
    public enum RecordingType: String, PersistableEnum {
        case studioRecording
        case testRecording
    }
    public enum RecordingInputType: String, PersistableEnum {
        case screen
        case cameraAndMicrophone
        
        public var streamInputType: ParticipantInputType {
            switch self {
            case .screen: return .screen
            case .cameraAndMicrophone: return .camera
            }
        }
    }

    @Persisted public var recordingType: RecordingType = .studioRecording
    @Persisted public var recordingInputType: RecordingInputType = .cameraAndMicrophone


    public var archiveId: String { <--- here is the crash
        // editor team expects the screenshare recordings to have a specific prefix
        let prefix = self.recordingInputType == .screen ? "screenshare_" : "" 
        return "\(prefix)\(self.cleanParticipantName)-\(self.archiveNumber)"
    }
```

### Stacktrace & log output

```shell
0  Riverside                      0x16d96b0 protocol witness for static _Persistable._rlmGetProperty(_:_:) in conformance StudioRecordingSet.RecordingType + 2552184
1  Riverside                      0x16d9600 protocol witness for static _Persistable._rlmGetProperty(_:_:) in conformance StudioRecordingSet.RecordingInputType + 2552008
2  RealmSwift                     0x6090c $s10RealmSwift9PersistedV3getyxSo13RLMObjectBaseCF + 720
3  RealmSwift                     0x60614 $s10RealmSwift9PersistedV18_enclosingInstance7wrapped7storagexqd___s24ReferenceWritableKeyPathCyqd__xGAHyqd__ACyxGGtcSo13RLMObjectBaseCRbd__luigZ + 104
4  Riverside                      0x16dd7e4 StudioRecordingSet.archiveId.getter + 111 (StudioRecordingSet.swift:111)
5  Riverside                      0x16e3c7c StudioRecordingSet._getBaseRecordingObject() + 476 (StudioRecordingSet.swift:476)
6  Riverside                      0x16e4508 StudioRecordingSet.getUpdateRecordingObject() + 429 (StudioRecordingSet.swift:429)
7  Riverside                      0x16ebcd0 StudioRecordingsManager._handleRecordingEnded(_:log:) + 128 (StudioRecordingsManager.swift:128)
8  Riverside                      0x16eb488 StudioRecordingsManager._updateRecordingsOnServerDB() + 90 (StudioRecordingsManager.swift:90)
9  Riverside                      0x16ea740 closure #1 in StudioRecordingsManager._startUpdaterTimer() + 63 (StudioRecordingsManager.swift:63)
10 Riverside                      0x26c8e4 thunk for @escaping @callee_guaranteed () -> () + 4302997732 (<compiler-generated>:4302997732)
11 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
12 libdispatch.dylib              0x746c _dispatch_continuation_pop + 504
13 libdispatch.dylib              0x1aa58 _dispatch_source_invoke + 1588
14 libdispatch.dylib              0x15a6c _dispatch_root_queue_drain + 396
15 libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
16 libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
17 libsystem_pthread.dylib        0xb98 start_wqthread + 8
```

### Can you reproduce the bug?

No

### Reproduction Steps

The crash is happening a lot for our users.

### Version

Realm (10.45.3) RealmSwift (10.45.3)

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS (16.2, 17.4.1, 17.5.1)

### Build environment

Xcode version: 15.2
Dependency manager and version: Cocoapods

**Comment by Jaycyn** [comment]
Can you include what the enum models look like for additional clarity?

**Comment by YoavGro** [comment]
> Can you include what the enum models look like for additional clarity?

@Jaycyn Sure NP, added to the description

**Comment by nirinchev** [comment]
Is it possible that in the database you have a value that is not part of the possible enum values?

**Comment by YoavGro** [comment]
No, there is no option like that.
These values are given in the init function of the Object

**Comment by nirinchev** [comment]
The value stored in the database is a raw string, so even if you supply the enum value in the init function of the object, there can be a number of ways where the value on disk can be something other than what's allowed by the enum - for example, if the enum property was introduced after a migration, but existing objects were not backfilled with one of the valid values. Or if the enum cases were renamed without migrating the data on disk. Not saying this is necessarily what's happening, just making sure those cases are considered.

If you're able to get access to the Realm file from one of your crashing users or capture trace level logs from a crashing run, that should give us some clue as to what's happening.

**Comment by YoavGro** [comment]
I'll try to look for this, haven't managed to find one yet.

One question, why would realm crash trace show error on the `recordingType` value, where the crashing line does not use that property (it is using `recordingInputType` and not `recordingType`)?

The crash trace shows both of the values, why would that happen?

**Comment by nirinchev** [comment]
Yeah, that's weird but I have no theory as to why both appear in the stacktrace. @dianaafanador3 perhaps you can see something I'm not?

**Comment by YoavGro** [comment]
@nirinchev found something, but I'm not sure it has anything to do with this

the property `@Persisted public var recordingInputType: RecordingInputType = .cameraAndMicrophone` was introduced recently, And I see that I do not have a migration specifically to add it to existing models, can this be an issue?

*I'm under the impression that If I give a default value and increase the realm file's version the automatic migration will take case of it

**Comment by nirinchev** [comment]
The default value only applies when creating new objects and will not go ahead and update existing objects, so they'll have the intrinsic default for the datatype which is an empty string in the case of an enum. Since that won't match any of the enum values you have defined and the enum property is not optional, you would get an exception trying to parse the string into the enum.

**Comment by YoavGro** [comment]
Interesting, this contradicts the documentation that adding a property is automatically managed by the auto-migration (as long as the file version is increased)

**Comment by nirinchev** [comment]
In the [Automatically Update Schema](https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/model-data/change-an-object-model/#automatically-update-schema) section of the docs, there's a warning box that states:

> Realm does not automatically set values for new required properties. You must use a migration block to set default values for new required properties. For new optional properties, existing records can have null values. This means you don't need a migration block when adding optional properties.

I can see that the wording can be improved to clarify that the automatic handling will just assign the intrinsic defaults, even if you have an explicit default set in your model. Let me know if you have other suggestions for how we can make this more clear and I'll relay those to the docs team.

**Comment by YoavGro** [comment]
Yeah, maybe a more explicit example would be helpful (although when reading this with the current case we have, it is quite understandable, but maybe for new adopters)

Anyway looks like this is the reason of the issue.

Thank you so much for your help! I'll close this ticket
