### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by FlamurBeqiri** [realm/realm-swift#8669]
### How frequently does the bug occur?

Always

### Description

We have a server function that has no arguments:
`let realmResponse = try await app.currentUser?.functions.deleteAccount()`

After performing the call the app crashes on `FunctionCallable` see screenshot:
<img width="1493" alt="Screenshot 2024-08-20 at 13 35 44" src="https://github.com/user-attachments/assets/ae8394ce-b7b9-4577-a50b-85c5c695c1e3">

### Stacktrace & log output

```shell
RealmSwift/Sync.swift:1144: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

### Can you reproduce the bug?

Always

### Version

10.52.3

### Are you using encryption?

No

### Platform OS and version(s)

17.5

### Build environment

Xcode version: 15.4.0

**Comment by tgoyne** [comment]
It looks like both the type and implementation of the `async` version of `user.functions` are very incorrect.

**Comment by FlamurBeqiri** [comment]
> It looks like both the type and implementation of the `async` version of `user.functions` are very incorrect.

What exactly do you mean?
Following the [documentation](https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/app-services/call-a-function/#async-await-call-a-function) I don't see any issue.

**Comment by tgoyne** [comment]
Well yes, the documentation isn't going to say "we implemented this incorrectly".

**Comment by FlamurBeqiri** [comment]
And how should I use it correctly?
