### ISSUE TITLE
error: Swift package target 'Realm' is linked as a static library by 'AppName' and 'Realm', but cannot be built dynamically because there is a package product with the same name.

### ISSUE THREAD

**Issue by bekzodrakhmatof** [realm/realm-swift#8694]
### How frequently does the bug occur?

Always

### Description

error: Swift package target 'Realm' is linked as a static library by 'AppName' and 'Realm', but cannot be built dynamically because there is a package product with the same name.

### Stacktrace & log output

```shell
error: Swift package target 'Realm' is linked as a static library by 'AppName' and 'Realm', but cannot be built dynamically because there is a package product with the same name.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

error: Swift package target 'Realm' is linked as a static library by 'AppName' and 'Realm', but cannot be built dynamically because there is a package product with the same name.

### Version

all

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 18

### Build environment

[Xcode version: ...
Dependency manager and version: ...
](error: Swift package target 'Realm' is linked as a static library by 'AppName' and 'Realm', but cannot be built dynamically because there is a package product with the same name.)

**Comment by isabsent** [comment]
Which version of Realm is affected by this bug? Only the latest or all previous ones too?

**Comment by bekzodrakhmatof** [comment]
It was on the all versions as well. But it looks like it worked after some workaround. It could be something conflicting with other packeges.
